### ISSUE TITLE
One street is not recongnized by the app

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1073]
I try to add a delivery on "rue de l'official 1 liège" and the app didn't recognized the adress while the street appears on the map
<img width="241" alt="2020-01-15 17_21_13-RAYON9" src="https://user-images.githubusercontent.com/44605344/72450957-7df76a00-37bb-11ea-8e94-08cf8edb68e1.png">

**Comment by TifaineSicklo** [comment]
It happens same with one users try to enter his adress but not recongnize by the map software. We tell him to put an adress close and comment the real. But it can be difficult and a problem with distance calculate for "magasin".

**Comment by alexsegura** [comment]
Same as #617

It is useless to report super specific address matching problems, as we just rely on Google Maps data, we can do nothing with this. 

The address is recognized when written as "Rue d'Official"

<img width="409" alt="Capture d’écran 2020-07-24 à 11 48 00" src="https://user-images.githubusercontent.com/1162230/88379756-bf3c8800-cda3-11ea-9754-6c4bf69df2d4.png">
