### ISSUE TITLE
Interval days not supported?

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1092]
If I configure a store opened 1 day a week, with 2 days interval, when I create a delivery from this store, it offers me two dates spaced a week.

<img width="959" alt="2020-01-22 11_16_46-" src="https://user-images.githubusercontent.com/44605344/72885789-e2a94c00-3d08-11ea-9aa1-b70a15122587.png">
<img width="482" alt="2020-01-22 11_17_07-RAYON9" src="https://user-images.githubusercontent.com/44605344/72885791-e2a94c00-3d08-11ea-9837-693c434108c5.png">

**Comment by alexsegura** [comment]
Fixed in 3bccea08d3f6d687ffb5d3f374e08afd9bd52793
