### ISSUE TITLE
map is not loading in the locally-run instance

### ISSUE THREAD

**Issue by vova1vova** [coopcycle/coopcycle-web#1116]
I'm trying to run the platform locally. When I run the docker containers I'm able to see the restaurants page and login, but on the admin page the map component is not loading:
<img width="1298" alt="Screenshot 2020-01-29 at 16 58 07" src="https://user-images.githubusercontent.com/1525555/73373237-a94c7f80-42b8-11ea-8956-bf125f235adf.png">

In the logs I see this error:
```
2020-01-29?nav=off:1 Uncaught (in promise) 
xd {message: "initMap is not a function", name: "InvalidValueError", stack: "Error↵    at new xd (https://maps.googleapis.com/m…sYbRcHI&libraries=places&callback=initMap:154:124"}
message: "initMap is not a function"
name: "InvalidValueError"
stack: "Error↵    at new xd (https://maps.googleapis.com/maps/api/js?key=AIzaSyDF7b3keybRcHI&libraries=places&callback=initMap:75:227)↵    at Object._.yd (https://maps.googleapis.com/maps/api/js?key=AIzaSyDF7b3keybRcHI&libraries=places&callback=initMap:75:337)↵    at aj (https://maps.googleapis.com/maps/api/js?key=AIzaSyDF7b3keybRcHI&libraries=places&callback=initMap:154:239)↵    at https://maps.googleapis.com/maps/api/js?key=AIzaSyDF7b3keybRcHI&libraries=places&callback=initMap:154:124"
__proto__: Error
constructor: ƒ (a)
__proto__: Object
```

<img width="1148" alt="Screenshot 2020-01-29 at 16 50 24" src="https://user-images.githubusercontent.com/1525555/73373340-ca14d500-42b8-11ea-9432-845f03e008b4.png">

**Comment by vova1vova** [comment]
seems to be fixed

**Comment by alexsegura** [comment]
We also see this error in production *sometimes*. 
I think it is because the Google Maps script is loaded like this:
```html
<script src="https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places&callback=initMap"
  async defer></script>
```

So, with `async` & `defer` attributes. I think that sometimes, what happens is that the script is loaded too late (or too early), and doesn't see the expected `initMap()` callback function defined.
