### ISSUE TITLE
It is possible to order in the past

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#112]
To be added to the validation of the order: it is possible to order with dates in the past. 
Discovered while testing and creating lots of orders. 
It seems there is a problem with `DatePicker` which keeps previous date stored in LocalStorage.

**Comment by Atala** [comment]
Linked to #98

**Comment by Atala** [comment]
"It seems there is a problem with DatePicker which keeps previous date stored in LocalStorage" 

This should be fixed  ([reference](https://github.com/coopcycle/coopcycle-web/blob/master/js/app/cart/index.jsx#L17)
