### ISSUE TITLE
Dashboard staying offline

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1121]
Few days sicklo's dashboard doesn't pass green mode, courriers aren't geolocalise, doesn't appear on the map even if the app is open.
![Sans titre](https://user-images.githubusercontent.com/59088580/73544133-cf009280-4438-11ea-993b-5abc2070d5fe.png)

**Comment by alexsegura** [comment]
Fixed in e22169214a5a7b70c8ffd768e3f5494ba6562488
