### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by Tiziano1175** [coopcycle/coopcycle-web#1128]
Hi,
change default language in parameters.yml:
`parameters:
    country_iso: en
    coopcycle.locale: en
`
Frontend:
![frontend](https://user-images.githubusercontent.com/8971925/73649430-0f9e1d00-4680-11ea-9801-9ebe7c6d553b.png)
there are no names of the dishes!

Admin:
![admin](https://user-images.githubusercontent.com/8971925/73649501-33f9f980-4680-11ea-9861-6a30ee89f131.png)
there are no names of the dishes!
if you try to change its name
![admin-confirm](https://user-images.githubusercontent.com/8971925/73649579-5e4bb700-4680-11ea-9c3e-1e64f3c6b27d.png)
and you confirm you get an exception
![admin-exception](https://user-images.githubusercontent.com/8971925/73649615-76bbd180-4680-11ea-961b-c35cce50256f.png)
name is empty

**Comment by ERAMANrepartos** [comment]
This is highly specific, so we are going to close due to inability to prioritize the issue
