### ISSUE TITLE
Changing date of a task should be possible without unassignment/reassignment

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1172]
When a task is assigned to a courrier, It's impossible to changing date. I must unassign the task, change the date and reassign the task. Maybe this process could be simplified

**Comment by PasLoin** [comment]
Also will be interesting to change date of multiple task in one time ; sometimes client report a round and changing date in all tasks is a boring process. 
FYI also linked to alow changing date from plugin woocommerce.

**Comment by ERAMANrepartos** [comment]
@alexsegura this can be done now, we should close the issue
