### ISSUE TITLE
Routing does not work with uploaded stops

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1173]
![grafik](https://user-images.githubusercontent.com/56302059/73738067-0d04fb80-4744-11ea-98c6-00344dce451d.png)

The route only connects the first two stops.

**Comment by alexsegura** [comment]
@GuidoHaagen it's fixed. It was broken in 0b6485853c64a42d3c6493b0060278d3d0fb2296

**Comment by GuidoHaagen** [comment]
Thank you! :)
