### ISSUE TITLE
Allow attaching data to tasks

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1178]
For deposit-refund, we need to all messengers to report how many containers were collected. 
Basically, the app needs to present the messenger with a number input, and to post this number to the backend. 

To implement this is a generic and reusable manner, we need to introduce a way to attach arbitrary data payload to tasks, as well as a way to render a form with those inputs in the app.

#### Fields definition

Each task can have a `TaskField` collection, which indicates what kind of entry it accepts

`GET /api/tasks/1`

```json
{
  "fields": [
    {
      "type": "number", 
      "name":"containers_returned",
      "label":"How many containers?"
    }
  ]
}
```

On the app, depending on the `fields` property, a dynamic form with a number input is rendered on the screen to complete a task.

#### Sending data

When completing a task, it is possible to specify a `data` payload

`PUT /api/tasks/1/done`

```json
{
  "data": [
    {"name": "containers_returned", "value": 4}
  ]
}
```

**Comment by rayon9coop** [comment]
It's a good idea. For example, for bookstores where we depose magazines, we have to enter the number of unsold items we take back

**Comment by CCCC-Jorrit** [comment]
Not sure if it belongs here but just the name of the person who takes the package. I always write it as a comment but I think it should be a separate field before the signature and with the option to make it obligatory
