### ISSUE TITLE
Champs désactivés dans le formulaire d'ajout d'une adresse

### ISSUE THREAD

**Issue by florentk** [coopcycle/coopcycle-web#118]
Lors de l'ajout d'une nouvelle adresse dans /profile/addresses/new , les champs Adresse, Code postal et ville ne sont pas accessible (attribut disabled="disabled" dans la balise input). Il m'est donc impossible d'ajouter une nouvelle adresse.
Navigateur : Chromium Version 56.0.2924.76 Built on Ubuntu

**Comment by Atala** [comment]
My fault, will fix

**Comment by florentk** [comment]
I think change field property of AddressForm builder : "required => true" insteadof  "disabled => true"

**Comment by Atala** [comment]
Actually it's because the form is used in two different places, we should have two different forms.
