### ISSUE TITLE
Bug on assignation and saving of an imported task

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1193]
After importing, I try to assign a task. The Saving button doesn't have any effect
![bug](https://user-images.githubusercontent.com/44605344/75235367-66e56800-57bc-11ea-94ea-126ed2b6a8db.gif)

**Comment by alexsegura** [comment]
Fixed in 55cb3715964dbf2cfa244b5f8baa43bee93c6475
