### ISSUE TITLE
Default address when order

### ISSUE THREAD

**Issue by florentk** [coopcycle/coopcycle-web#120]
I add one user address in my account. But  when I order, the address form is initialized with a other address. 

The bug is in RestaurantController.php:176, I not understand this code 

`
            // we need to compute the geohash, because of small differences between geodata from the back and from the front
            $address = $user->getAddresses()->filter(
                function ($address) use ($addressData, $geotools) {
                    $addressCoordinate = new Coordinate([$address->getGeo()->getLatitude(), $address->getGeo()->getLongitude()]);
                    $basketCoordinate = new Coordinate([$addressData['latitude'], $addressData['longitude']]);
                    return $geotools->geohash()->encode($addressCoordinate, 9)->getGeohash() ===
                        $geotools->geohash()->encode($basketCoordinate, 9)->getGeohash();
                }
            );
`

Why a filter is needed ? When I delete the filter, the address form is initialized with my first address.

**Comment by Atala** [comment]
`But when I order, the address form is initialized with a other address.` 

On which page?

**Comment by Atala** [comment]
A non-problem AFAIK, please reopen or comment if needed
