### ISSUE TITLE
Unable to access 'Menu' and 'Orders' in responsive

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#124]
On restaurant form page these buttons are not displayed in responsive.

![capture d ecran 2017-11-07 a 11 21 45](https://user-images.githubusercontent.com/4426585/32490116-6242f57e-c3b2-11e7-961c-4cb2d04261bb.png)

**Comment by alexsegura** [comment]
Fixed in 48f977966c7b26d402e9f99ea383e91b63a0b8e5
