### ISSUE TITLE
Send SMS and/or notification to recipient when messenger is approaching

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1241]
Needs #1194

Given the COVID-19 pandemic, it is important to minimise contact between messengers & recipients. As everybody else, we are now focusing on contactless deliveries. The best would be that the messenger drops the order in front of the building, without touching the doorbell or anything, and the customer goes down the building to grab the order. 

To make sure the customer goes down, best would be to alert him/her when the messenger is approaching. We can send him/her an SMS and/or a notification when : 
- the order has been picked
- the messenger is ~ 1km away

---

We are using [Tile38](https://tile38.com/) to monitor geofences. 

Basically, the implementation would be like: 
- When a new order is created, use the [SET](https://tile38.com/commands/set/) command to create a POINT for the customer address. 
- Also, create a channel using the [SETCHAN](https://tile38.com/commands/setchan/) command to get notified when the messenger is nearby customer address. Subscribe to this channel, of course. 
- When the channel is notified, send SMS/notification. To avoid sending notification all the time, make sure `detect = enter` (see [geofencing](https://tile38.com/topics/geofencing/))
- When the order has been delivered, make sure to cleanup the point, and stop watching for the geofence.

**Comment by joel-shiftdelivery** [comment]
One additional option could be to send the SMS when a task is started, depending on what is easiest to implement. I believe this is what Onfleet does currently. 

Also, a related note from Slack a while ago:
Did a little research, and it looks like Telnyx ( https://telnyx.com/ ) seems to the best SMS pricing across the world, and looks like a primary Twilio competitor with similar feature-set.

**Comment by alexsegura** [comment]
> One additional option could be to send the SMS when a task is started

It is like this since c9353129c7011581253639a67bf219229df75a5d, but it needs the SMS gateway configured

Since 781bd8e75a109837ab626ad0fd080d71327b21f9, it is possible to configure Twilio as a gateway.

**Comment by ERAMANrepartos** [comment]
Covid is over, and this issue is both controversial and niche. At the least, SMS is complicated given costs and current use cases (whatsapp...). Closing issue, but can be reopened if made relevant to current use cases
