### ISSUE TITLE
When making a pre-order delivery time is displayed incorrectly

### ISSUE THREAD

**Issue by Pidgeon45** [coopcycle/coopcycle-web#1247]
![77224275-f5e76500-6b5b-11ea-95b0-30404c70ef99](https://user-images.githubusercontent.com/19227348/77423527-4dd5d400-6dc7-11ea-820e-bf25b5f8adaa.jpg)
![77224273-f2ec7480-6b5b-11ea-9ffe-7785e13e3f1d](https://user-images.githubusercontent.com/19227348/77423543-53331e80-6dc7-11ea-9937-69043fbab1e6.jpg)

When making an order via the website and booking delivery for a future timeslot, the delivery time is displayed incorrectly.

**Comment by riceyrice** [comment]
Just had the Currywurst myself actually :+1:
