### ISSUE TITLE
Have a tick box to choose which tabs of a spreadsheet should be uploaded

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1255]
Would it be possible that every tab of a spreadsheet is uploaded as a separate folder/tour? This way I would not have to create a lot of files to upload them one after the other.

**Comment by Paul-Eraman-CoopCycle** [comment]
The best solution to this so far is to use google sheets instead of excels, and download the tab needed to upload

easy workaround, closing
