### ISSUE TITLE
Add visual feedback when uploading an image

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#127]
The image is only shown after the user has saved. It would be nicer to have a preview.

**Comment by couleurmate** [comment]
validation import image /admin/restaurant input file

File is uploaded but no visual animation whether the file is successfully imported 
<input type="file" id="restaurant_imageFile_file" name="restaurant[imageFile][file]">

**Comment by alexsegura** [comment]
It would be nice to integrate [DropZone.js](https://www.dropzonejs.com/)

However I'm not sure `VichUploaderBundle` works out of the box with DropZone.js (see dustin10/VichUploaderBundle#664), maybe we need to switch to [OneupUploaderBundle](https://github.com/1up-lab/OneupUploaderBundle)

**Comment by alexsegura** [comment]
Fixed in 10e2c4aec34759754fa9363a624545ff619bb807
