### ISSUE TITLE
Localized address autosuggest for the UK

### ISSUE THREAD

**Issue by georgeowell** [coopcycle/coopcycle-web#1288]
When entering an address for ordering we are often getting `This address is not precise enough` errors on valid UK addresses. 

It seems to happen inconsistently and there isn't any difference in formatting between the addresses that work and those that don't. Google is auto completing the addresses ok. 

Sometimes this is the difference between a few numbers on the same street.

**Comment by georgeowell** [comment]
According to mex, this is an issue with UK addresses. Fix will take a bit of time.

**Comment by alexsegura** [comment]
The address widget in the UK should behave slightly differently 

![postcode-postoffice](https://user-images.githubusercontent.com/1162230/80301344-e800b180-87a3-11ea-8697-b8982e222b7f.gif)

I _think_ it can be implemented like this:
1/ Ask user to enter postcode, use [postcodes.io](http://postcodes.io/) to retrieve the lat/lng of postcode
2/ Use [Google Place Search](https://developers.google.com/places/web-service/search) to retrieve a list of adresses that are in a radius of X kilometers around the postcode

**Comment by alexsegura** [comment]
Basically, all UK adresses are in the [Postal Address File (PAF)](https://www.poweredbypaf.com/), which is what providers like [getaddress.io](https://getaddress.io/) use. The PAF is proprietary data, and license is very expensive. 

- https://stackoverflow.com/questions/1900221/how-do-i-match-street-addresses-to-uk-postcodes

This is what is needed, to get all postal addresses corresponding to a postcode.

**Comment by Pidgeon45** [comment]
We could use lower resolution data, street addresses against postcodes may be accurate enough, as residence number is already entered by the customer. See this API https://developer.ordnancesurvey.co.uk/os-names-api

**Comment by agichim** [comment]
I realize we don't really need the postcode to call postal addresses. We only need the postcode to call a lon-lat area and so, in the next 'checkout' section the customer is asked to input (manually) their full address in different fields. 

By doing the above, the only restriction would be 'lon-lat' which will correspond to different postcodes, so in the first section after they input the postcode the customer will only see 'York' (the name of the city) and
it would avoid getting `This address is not precise enough` and customer can go to `order` where they input their full address.

That would mean that the `address` field should be editable and above the `address` there should be a non-editable field called `postcode` with the postcode the customer entered at first. 
![image](https://user-images.githubusercontent.com/51931067/80410621-cb0ed000-88c2-11ea-9682-793dcceffaa2.png)

I can see it's not a very practical workaround when there will be more coops in the UK, but could that work?

**Comment by alexsegura** [comment]
I think it can be achieved with Google Maps. 

From what I understand, all of this happens because people in the UK are used to enter their postcode first, and the predictions returned by Google are not street addresses.

If we change the UI/UX to enter the postcode first, then the street address, it should be ok. 
So it's a 2 step process, like in the GIF above: 
- 1/ Enter your postcode (YO24 4ND)
- 2/ Enter your street address (18 Bea...)

I found the query needed to use with [Place Autocomplete](https://developers.google.com/places/web-service/autocomplete), to limit the results so that when people type "18 Bea...", it does not return results in London

```
https://maps.googleapis.com/maps/api/place/autocomplete/json?
key=YOUR_API_KEY&
components=country:GB&
location=53.955328,-1.123139&
radius=5000&
types=address&
strictbounds&
input=18%20bea
```
