### ISSUE TITLE
Translation issue in french: changing "Noix" to "Fruits à coque" in the list of allergens

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1306]
Because in french a "noix" (nut) is not used to talk about all the nuts. 

And "Noix" does not exist in the official list of allergens. The official term to use is "Fruits à coque". "Noix" is one "Fruit à coque" but there are many others types of nuts. 

https://www.health.belgium.be/fr/alimentation/informations-aux-consommateurs/etiquetage/la-declaration-des-allergenes

**Comment by alexsegura** [comment]
This needs to be changed on the translation webapp

https://translate.coopcycle.org/translate/coopcycle/coopcycle-web/fr/?checksum=6e59f3c4a76c5164
