### ISSUE TITLE
Display delivery's price in the popup window

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1307]
One restaurant want to offer the delivery's fee to their custumers. 

He regrets this information doesn't appear before the custumer put something in the cart. Some customers may be encouraged to order if they know delivery is offered.

Maybe, the delivery's price (or the mention "Delivery fee offered") can be displayed near the minimal's amount of the cart?
 
![image](https://user-images.githubusercontent.com/44605344/78991888-42f69f80-7b3a-11ea-9db5-c706a8b51535.png)

**Comment by rayon9coop** [comment]
When something is in the cart, the delivery's price appears
![image](https://user-images.githubusercontent.com/44605344/78992190-fd86a200-7b3a-11ea-8a3d-e2c3b21def2b.png)

**Comment by ERAMANrepartos** [comment]
@alexsegura can we close this?
