### ISSUE TITLE
Stops assigned by connecting the stops on the map only show the courier after reload

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1321]
I was confused about it at the first time. 
Not urgent but I wanted to have it written someplace.

**Comment by ERAMANrepartos** [comment]
@GuidoHaagen 
can you clarify?

**Comment by GuidoHaagen** [comment]
@ERAMANrepartos , 
step 0 : in Dispo view
step 1 : assigning a stop with the mouse by connecting it to an assigned one 
step 2 : open the new assigned task (like you would change something
step 3 : it looks like there is no courier assigned
Eventhought its in the list of the driver. 

Hope that helps. :)

**Comment by Paul-Eraman-CoopCycle** [comment]
I just checked, this no longer occurs
🥳
