### ISSUE TITLE
Being able to make a difference in VAT of elements in a "menu" product

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#1326]
Restaurants ask us to make products like menus "burger+fries+beer" for 18 euros" 
In that case, a problem is that we should set things up so that the VAT of the beer be 20% (in France) and the rest 10% but being thought for being "one product", we have to chose only one VAT value"

**Comment by ERAMANrepartos** [comment]
Few people buy beer with the food, i´m going to leave this, but we could close soon
