### ISSUE TITLE
Use Redis for mail spooling

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#133]
We could use [this](https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md#swiftmailer-spooling) to enqueue mails in Redis

**Comment by Atala** [comment]
@alexsegura what do you think of this? I think it could improve our perfs significantly - however we will need a cron job to send mails stored in Redis ([ref](http://symfony.com/doc/3.3/email/spool.html#spool-using-files))

**Comment by alexsegura** [comment]
Would be cool, but we do not send lots of emails right now 😉
Before doing that I think using Mailjet to send emails would be a better improvement. 

Also, something that would actually improve performance is storing **PHP sessions** in Redis. 
Right now the file system is being hit on each page load.

**Comment by alexsegura** [comment]
Not relevant anymore since there is an async message handler to send emails (0cf692f50f2b6c657c1b957e3f0ef720d76d4372)
