### ISSUE TITLE
More information in the users' list

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#1336]
Date of registration
Number of orders
Last order

**Comment by alexsegura** [comment]
Unfortunately, we don't have the date of registration ☹️
It could be added but previous users would be unknown.

**Comment by AdrienSICKLO** [comment]
Well previous ain't that necessary. It's just to know which users registers after some advertising action. To evaluate them

**Comment by alexsegura** [comment]
Related to #1378
