### ISSUE TITLE
Assign tasks by selecting an area on the map screen

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1341]
For particular deliveries, the same product is dropped at lots of addresses (free press, prospectus or letters, ...). There are no differences between the tasks exept the adress. 

One way to dispatch theses tasks is to assign them to courriers according to their preferred neighborhoods or by separating deliveries with natural limits (river, highway, railways, ...).

It would be facilitating to select an area on the map -and the adresses inside this area- and assign it to a courier.

**Comment by alexsegura** [comment]
One of those Leaflet plugins to implement selection:

https://leafletjs.com/plugins.html#areaoverlay-selection
