### ISSUE TITLE
Create a 'Go To Today' button on Dispatch (Dashboard) 

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1347]
Button could be placed between 'Date box' and 'Export' button or on the left of 'Date box'.

![image](https://user-images.githubusercontent.com/51931067/80215397-4c046800-8634-11ea-8985-418c55ec618f.png)

**Comment by alexsegura** [comment]
There's a "Today" button in the data picker out of the box, IMHO it's sufficient

But maybe add a keyboard shortbcut? Hitting "t" would go to today

<img width="354" alt="Capture d’écran 2020-06-22 à 17 17 05" src="https://user-images.githubusercontent.com/1162230/85304629-413b4780-b4ac-11ea-98ca-c9ae424cc3a4.png">

**Comment by agichim** [comment]
Yeah, a keyboard shortcut would do fine I think. The goal was to only have to click once, instead of twice (open calendar, maybe change month and then click on the day in question). Also I use it a lot on my phone when I self dispatch, I find it easier than the app, so there a "go to today" button would be cool to use. But it's no biggy, it's not an important issue.

**Comment by alexsegura** [comment]
Closing as it's already possible
