### ISSUE TITLE
Add support for Adyen payments

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1349]
Adyen (adyen.com) support will be very helpful for Canada and US.

Stripe and Paypal charge 2.9% + $0.30/transaction in Canada/US, which is higher than Europe. Adyen works on an Interchange++ model, so the average cost will be lower (closer to 1.5-2%).

This is very important, especially for low margin shops like grocery stores.

**Comment by alexsegura** [comment]
Ok, in this case, when the country the platform is running in is CA/US, then it will de-facto use Adyen (i.e, in the platform settings, only Adyen will appear).

It makes no sense to have 2 credit cards gateways in any case.

**Comment by joel-shiftdelivery** [comment]
Sounds good!

Someone in the future may have a reason for having Stripe instead of Adyen in CA/US, but I think having only Adyen available by default is perfect :)

**Comment by joel-shiftdelivery** [comment]
@alexsegura 
Do you happen to have a rough idea of the amount of work/time needed for Adyen integration? 

Just trying to get an idea of when we can expect to begin onboarding restaurants and shops with Adyen.
Thanks for all your work!

**Comment by alexsegura** [comment]
I think it's reasonably feasible for end of May (on the web version). 
First I want to merge #664 that is beginning to be critical, check how it behaves in live conditions, and then we can begin to take a look 🙂

**Comment by joel-shiftdelivery** [comment]
@alexsegura
If end of May still an expected time for a live web implementation of Adyen (with app support coming later)?

**Comment by alexsegura** [comment]
Adyen won't enable the ["Adyen For Platform"](https://docs.adyen.com/platforms) feature for us, so closing atm.

**Comment by agichim** [comment]
Any updates on Adyen?
