### ISSUE TITLE
Why do we need two Redis clients in our Node Process

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#135]
These [lines](https://github.com/coopcycle/coopcycle-web/blob/9f28cfa08a13b059f424ee7a968c56a11611bf52/js/api/order/tracking.js#L34-L39) sound weird to me.

@alexsegura any thoughts?

**Comment by alexsegura** [comment]
This is normal: you can't use the same client for pubsub and for other things ¯\_(ツ)_/¯

**Comment by Atala** [comment]
From the docs https://redis.io/topics/pubsub
```
A client subscribed to one or more channels should not issue commands, although it can subscribe and unsubscribe to and from other channels.
```

But why? I ll find out

**Comment by alexsegura** [comment]
In any case, if I remember well, the `redis` library triggers an error if you try to use the same client for both things. Let's keep it like this 😉
