### ISSUE TITLE
Allow restaurant/shop to remove or replace items in an order

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1355]
This is helpful for grocery and other store orders where an item is out of stock, so one item can be removed without cancelling the whole order. 

Alternately, the shop could contact the customer and offer a replacement product for an equal or lower cost, and replace the out of stock item if the customer agrees.

As cards are pre-authorized when the customer clicks purchase, this should work fine, as long as the new order $ total is not more than the original $ total that was pre-authorized.

**Comment by ERAMANrepartos** [comment]
Realistically this is a UI/UX issue. Currently, in Eraman for example, we deal with this manually. Frankly, this may be the best option.

**Comment by ERAMANrepartos** [comment]
elaborated in #3630 and expanded
