### ISSUE TITLE
Notify store users by email when delivery is complete

### ISSUE THREAD

**Issue by dingusdong** [coopcycle/coopcycle-web#1358]
An email notfication to be sent to a Store User when a delivery has been completed.

**Comment by PasLoin** [comment]
Also linked to : https://github.com/coopcycle/coopcycle-web/issues/1146 

Email to store user must be configurable by store. 

Send mail : yes no and the content can depend of store configuration.

**Comment by vladimir-8** [comment]
Also looks similar to #1668
