### ISSUE TITLE
500 Error when clicking task number hyperlink in # column - Store User

### ISSUE THREAD

**Issue by dingusdong** [coopcycle/coopcycle-web#1359]
When a Store Users selects a task number in the # column of the "My Orders" page, it returns a 500 error. 

"KZ" hyperlink in image below:
![Screen_Shot_2020-04-24_at_16 17 00](https://user-images.githubusercontent.com/64378003/80317980-e6180c00-87fe-11ea-899e-76b4871d69d2.png)

Error:
![Screen Shot 2020-04-26 at 20 41 24](https://user-images.githubusercontent.com/64378003/80317955-b7019a80-87fe-11ea-8bdc-ab8bed061146.png)

**Comment by alexsegura** [comment]
Cannot reproduce
