### ISSUE TITLE
Disable Product Options - #Restaurants #Menu

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1364]
It should be possible to disable an option for a product in the same way it possible to disable a product. 

For example if a shop is out of bacon it should be possible to disable the option "extra bacon" in a Burger but at the same time it should be possible to mantain the option "extra cheese" in the set of options connected with that burger. 

I searched in the issues for "options" and I could find just this issue, that could be realted maybe: https://github.com/coopcycle/coopcycle-web/issues/540

#restaurant #menu #options

**Comment by alexsegura** [comment]
![disable_option](https://user-images.githubusercontent.com/1162230/100971831-f2eca300-3537-11eb-9c92-2e771e7a9a49.gif)
