### ISSUE TITLE
Possibility to set different times (dropoff and/or pickup) in the order-box in the column "accepted orders" in the dashboard #dispatch

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1368]
Atm the dropoff-time is shown. 

For some of the coops using the app it would be more important to have the pickup-time shown in the order box in the column "accepted orders". 

Others prefer to have the dropoff time. 

Then: it would be nice to have the possibility to switch between them or to have both shown. 

Internal Slack discussion: https://coopcycle.slack.com/archives/CQDUL440P/p1588028871031500

**Comment by Paul-Eraman-CoopCycle** [comment]
not planned currently, dropoff is working fine, though i understand the issue and we are taking it into account in future designs
