### ISSUE TITLE
Differentiation Sales tax 

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1370]
Add sales tax on values from option. Problem appear when you create a "eat formule" (10% vat) as a product with an alcool (20% vat) or a soft (5,5% vat) to choose in as an option. Need differentiation.

**Comment by 552020** [comment]
True. #restaurant #menu #option

**Comment by ERAMANrepartos** [comment]
@TifaineSicklo is this something that is still important?

**Comment by Paul-Eraman-CoopCycle** [comment]
This is a repeat issue, we have the other one in the roadmap
