### ISSUE TITLE
Additional delay before ordering Day(s) setup is different to display in restorant page

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#1371]
I have setup a restorant with 3 Additional delay before ordering Day(s) and in the page of restorant it's displayed 2. (id 21 in our instance)

**Comment by alexsegura** [comment]
Fixed in 90663bc54711935b329b3fe1c80ffd36a5394f43

**Comment by PasLoin** [comment]
I setup for 5 days and it's displayed : Order now for later. Order at least 4 days in advance. 
6 day give 5 ;-)
