### ISSUE TITLE
See multiple tasks on Dashboard Map where the adddress is the same. 

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1373]
Maybe simply click on the pin and see multiple popups. 1 per each task.
There are two tasks for the same address in this pin.

![image](https://user-images.githubusercontent.com/51931067/80482750-b1b26600-894c-11ea-9771-e68de93e6bf1.png)

**Comment by alexsegura** [comment]
Fixed in a1766f09e4dd5991b95e203a0996307206cdccba
