### ISSUE TITLE
Add Store/Restaurant name in the emails when a new order has been placed.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1380]
A new order `for [store name]` has been created

![image](https://user-images.githubusercontent.com/51931067/80592603-9f512e80-8a17-11ea-8b42-05142e34edc2.png)

**Comment by PasLoin** [comment]
Can be aslo usefull for dispatcher to have more information : 
- Name of client/customer
- Adress of delivery.
- Date and time range.

**Comment by PasLoin** [comment]
Also a prospect ask us to add the date and time in the email.

**Comment by ERAMANrepartos** [comment]
This has been implimented
