### ISSUE TITLE
Street numbers disappear when importing tasks in some streets

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1389]
I imported a file with four tasks, each time two addresses in the same street. When imported in the dashboard, the street numbers disappear. Editing the task manually to re-encode the street numbers work only on the dashboard's list (on the right of the screen). When I editing the task on the map, the street numbers disapear again. If I assign them to courriers they don't see the street numbers on the app. 

This is appenning  only on few streets

![bugadress](https://user-images.githubusercontent.com/44605344/80804443-7666a000-8bb5-11ea-98cb-e3bc45aa8e16.gif)
![index](https://user-images.githubusercontent.com/44605344/80804640-0ad10280-8bb6-11ea-8991-79de3d3888b2.jpg)

**Comment by alexsegura** [comment]
Obsolete since we don't use Google Maps anymore (2c40e532570d0ccc56d4cb7b27c5772a501dd86b)
