### ISSUE TITLE
Bug on filters

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1390]
Applying filters make disappearing the non assigned tasks.
When I have to assign a lot of tasks, it will be useful to hide assigned tasks and the see what is assigned and what should be assigned

![bugonfilters](https://user-images.githubusercontent.com/44605344/80805738-1c67d980-8bb9-11ea-9f9c-f7ab56da7749.gif)

**Comment by joel-shiftdelivery** [comment]
Duplicate/related to #772 and maybe #1354

**Comment by alexsegura** [comment]
Does it fix the problem?

<img width="429" alt="Capture d’écran 2020-06-22 à 16 40 18" src="https://user-images.githubusercontent.com/1162230/85300802-519cf380-b4a7-11ea-9a2e-10e0894b63a7.png">
