### ISSUE TITLE
Show the name and colours of couriers on assigned orders.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1399]
This would very helpful for the restaurant. Otherwise they struggle to know which order they already started cooking, unless they write it down on a paper. But every time they look at the dashboard they have to check which order they began cooking already.

The dispatcher should also be able to see this. 

![dashboard-assignedrider@2x-100](https://user-images.githubusercontent.com/51931067/81166447-90c0c500-8f8b-11ea-9feb-bc5997b5e7f8.jpg)

**Comment by alexsegura** [comment]
It's hard to retrieve the avatar color, it is [randomly picked](https://github.com/laravolt/avatar), and after that it's an image. 
At some point people will be able to upload their own avatar, so maybe it's not a good idea to base user interface on the fact that the avatar is a colored circle. 

I did this:

<img width="320" alt="Capture d’écran 2020-08-14 à 12 24 40" src="https://user-images.githubusercontent.com/1162230/90240418-7cf9ea00-de29-11ea-8f79-477e64c7ed96.png">

Can we find another solution with a color that is not dynamic?

**Comment by alexsegura** [comment]
Linked to #538 & #776

**Comment by alexsegura** [comment]
Actually fixed
