### ISSUE TITLE
Disable closing the 'New task' popup when clicking outside the popup.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1403]
If you input all the details and by mistake you click outside the popup, it closes and you lose the details you've inputed. 

![image](https://user-images.githubusercontent.com/51931067/81205938-46f3d100-8fc3-11ea-977d-8a54a6394b08.png)

**Comment by alexsegura** [comment]
What about storing the input, so that when you reopen the popup, it's still there?

**Comment by agichim** [comment]
Yeah, that sounds good.
When clicking `Save` the input disappears.
But you'd need a `Clear` button, in case you input quite a bit of info and want to input some completely different info.
