### ISSUE TITLE
Reflect Order number across the whole platform.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1404]
Show Order number `NH (#898)` on popup on pin map. ↓
E.g.: `#587 │ NH (#898)`

![image](https://user-images.githubusercontent.com/51931067/81206379-ee710380-8fc3-11ea-8ee1-4fd35fc39f2d.png)

Show Order number `NH (#898)` on Unassigned and Assigned tasks. 
E.g.: `#587 │ NH (#898) customer address, before 7:35 pm`

![image](https://user-images.githubusercontent.com/51931067/81206500-1bbdb180-8fc4-11ea-8241-6836cec35b8d.png)

It allows for easier dispatching.

**Comment by agichim** [comment]
@alexsegura hey, is this something too complicated to do?

**Comment by MathildeS** [comment]
+1 on this issue

**Comment by alexsegura** [comment]
To implement this, we first need to have this merged → #1229

**Comment by alexsegura** [comment]
Since #2524 it's possible to attach metadata to tasks:

```php
$task->setMetadata('order_number', $order->getNumber());
```
