### ISSUE TITLE
Timeline is wrong: Preparation / Pickup / Dropoff - see screenshot

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1405]
Same issue reflects on the app for the restaurant: [slack thread here](https://coopcycle.slack.com/archives/C4UT4DGQ3/p1588409976379000) 

![image](https://user-images.githubusercontent.com/51931067/81209470-7c4eed80-8fc8-11ea-8e97-8a30c4cf07b7.png)

**Comment by alexsegura** [comment]
Fixed in f0dd6b072000f179b69d9b9f220732aab363ed5d
