### ISSUE TITLE
Create a security question when Refusing an order.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1407]
A restaurant refused/cancelled an order by mistake and they didn't realize. It's good to have a popup/prompt question when hitting the Refuse button.

> "Are you sure you want to cancel this order"

**Comment by alexsegura** [comment]
Partially fixed in 0bf60b89ea995f591240e41b4db3c68c61e5c544

When cancelling an accepted order, you now need to indicate the reason.

![cancel_reason](https://user-images.githubusercontent.com/1162230/81389893-dcee3f80-911a-11ea-952c-dbc999c7d2df.gif)

**Comment by agichim** [comment]
Yes, I remember there was the 'specify reason', but twice it happened with no prompt to specify.

**Comment by alexsegura** [comment]
@agichim this is new 🙂 
I need to add it also when refusing an order
