### ISSUE TITLE
Add a make update command

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#141]
Useful when pulling changes. It should do at least: 

```
composer install
docker-compose run php bin/console doctrine:migrations:migrate
```

**Comment by Atala** [comment]
It can even `git pull --rebase` ;)

**Comment by johnnybigoode** [comment]
Can I take a shot at this? 

Besides the `make update`, I feel that a `make fresh` would be nice. Idea from this [reply](https://github.com/coopcycle/coopcycle-web/issues/436#issuecomment-437593541). Probably needs a big warning message since it will delete everything. 

Is this a bad idea?

**Comment by alexsegura** [comment]
Yes sure 🙂
