### ISSUE TITLE
Weekpicker by default instead of datepicker

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#1417]
To be discussed. For invoicing, we are doing export per week number. One needs to check an external calendar for having this info

**Comment by alexsegura** [comment]
On which page(s)?

**Comment by PasLoin** [comment]
It's for the tasks export i guess but IMHO because it's recuring you just need to see what's the last export week number is and you have the info.

**Comment by ERAMANrepartos** [comment]
Too specific use case, closing
