### ISSUE TITLE
Ability to uncheck one or more time slots and save settings.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1418]
We are using time slots like this to manage pre-orders. When we have enough pre-orders in a certain time slot, it's cool if we can disable/uncheck that time slot only and save setting, so people can't order for that time slot anymore. 

![image](https://user-images.githubusercontent.com/51931067/81546235-fb01ad00-9371-11ea-80e5-6a65d481fbbf.png)

**Comment by alexsegura** [comment]
Ok, allowing to toggle the lines of the schedules on/off is the easy way. 
But maybe it's too complicated, you have to enter into each restaurant page, don't forget to re-enable it afterwards...
IMHO this is something that should be on the orders dashboard. Not sure how to represent this in terms of user interface. Maybe the system can groups the orders by time slot, and show the count, with a button to disable it?

The "exclusion" needs to be temporary and volatile. 
It could be achieved by storing the excluded slots (as text, ex: `2020-07-03 17:00-18:00`) in Redis, and expire the keys when the slot ends. 

Here which capacity decides if a slot is full? The capacity of the restaurant? Of the messengers?

**Comment by ERAMANrepartos** [comment]
Feature implemented
