### ISSUE TITLE
Removing any time slot only removes the time slot at the bottom.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1419]
See .gif ↓

![timeslotremoval](https://user-images.githubusercontent.com/51931067/81547084-3d77b980-9373-11ea-8e7f-6b3ae2fb9d92.gif)

**Comment by alexsegura** [comment]
Actually, is was removing the corresponding row, but the UI was not reflecting changes, because of a mechanism of React.

Look, on your GIF, after removal, the first row says "between 5:00 PM and 6:00 PM", while the time pickers show 16:00 PM - 17:00 PM

**Comment by agichim** [comment]
haha! I see it! Thanks!
