### ISSUE TITLE
Proposal : create a `Contract` entity linked to `Restaurant` entity

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#142]
For contractual aspects, I propose to introduce named `Contract`. This entity will represents the deal that has been signed between the Restaurant and the platform operator.

For now on the new informations I will put in this entity : 
 - `deliveryPrice` : flat price for a delivery
 - `minCartAmount` : minimum amount for a cart

This entity will be linked one-to-one with a restaurant. Only the `admin` user can manage them.
In the future, if the platform is administrated by several orgs, we could introduce the `Organization` entity. `Contract` will then link an org and a restaurant.

@alexsegura any thoughts?  Or anyone?

**Comment by alexsegura** [comment]
Looks good to me to keep things simple at the moment.
Don't we need also the commission percentage at least?

**Comment by alexsegura** [comment]
Fixed in 8e6b4adcd67a27003d527e2137fe5f93b8803920
