### ISSUE TITLE
Unable to use "forgot password" fuction

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1428]
I tried to reset the password to one of our dummy users "tricargo_Kunden" but always got an error message: "500 Internal Server Error!"

![grafik](https://user-images.githubusercontent.com/56302059/82191453-d7e77800-98f2-11ea-9fde-b7858f101ed0.png)

**Comment by alexsegura** [comment]
Fixed in ef994e08541127e65c2a0781a2fdc624ce0396ab
