### ISSUE TITLE
Sales tax localization for Canada

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1435]
Canada tax system is very different from VAT in Europe, most significantly tax is in addition to item price, instead of being included in the item price with VAT.

Main localization features needed:

1. Items need to allow up to 2 taxes to apply. (provincial PST and federal GST tax apply separately)

2. All prices in Canada do not include tax. Tax needs to be show in the cart after an item is added.

3. All tax on goods are collected by the shop. When tax is charged on the delivery fee that the customer pays, the PST would be collected by the store, and the GST would be collected by the Co-op.

4. Specific rules around when and how GST and/or PST would apply to the delivery fee charged to the customer.

**Comment by alexsegura** [comment]
Some information here Sylius/Sylius#1882

**Comment by alexsegura** [comment]
Taxes are shown in cart in Canada

- bf02a472ef1701ca290b69b688affb754817c83b
- d951e3d7c4d475a44a62ecf1baa68e7d6e5bdf90

**Comment by alexsegura** [comment]
Also interesting Sylius/Sylius#7833

**Comment by joel-shiftdelivery** [comment]
@alexsegura 
It looks like the sales tax calculation for stores didn't change over with the shops/restaurants. Would this be easy to update stores to the Canada localization where just GST (5%) would apply for all pricing through stores?


![Screenshot from 2020-07-28 14-34-52](https://user-images.githubusercontent.com/64277836/88724793-f54d7500-d0df-11ea-95d4-fd839b3440c0.png)
