### ISSUE TITLE
Remove SAVE button on restaurant MENU page - To improve UX

### ISSUE THREAD

**Issue by dingusdong** [coopcycle/coopcycle-web#1440]
**In order to**  `achieve something`
Only have one "SAVE" button on the restaurant Menu page. 

**As a** `role`
Better User interface design for the restaurant. 

**Whereas currently** `this happens`
There is two "SAVE" buttons. One at top and one at bottom. This causes confusion for the user. We find the user always tries to save changes with the button at the top of the page. This save button does not save changes to the menu, it only saves the change to menu name.

**Additional context**
Remove this "SAVE" button.
![Screen Shot 2020-05-26 at 10 51 51](https://user-images.githubusercontent.com/64378003/82887278-b06e5c00-9f3f-11ea-993d-9dfefb0a5661.png)

Keep this one "SAVE" button.
![Screen Shot 2020-05-26 at 10 52 34](https://user-images.githubusercontent.com/64378003/82887269-ae0c0200-9f3f-11ea-9f17-90b61b955eff.png)

**Comment by alexsegura** [comment]
![menu_editor](https://user-images.githubusercontent.com/1162230/83278886-926d5980-a1d4-11ea-9bcb-81ec920765fd.gif)
