### ISSUE TITLE
Possibility to do Refunds and Credit Notes paid by the Coop

### ISSUE THREAD

**Issue by MattiaKolyma2** [coopcycle/coopcycle-web#1447]
It would be quite fundamental to have the possibility to do refunds and create credit notes paid by the co-op and not only by the restaurant.

At the moment there is no way that we, as coop, can refund a customer for a mistake we (and not the restaurant) made. Refunded money is taken from Restaurant stripe, and Credit Notes not restricted to a single restaurant result in money not paid to the next Restaurant where that customer will order.

It would be amazing to be able to choose if Refunds and Credit Notes would contain a multiple choice option like: Refund paid by ...(name of the coop)/ Refund paid by (name of the customer)
In the same way, there should be such an option for Credit notes.

**Comment by alexsegura** [comment]
It is impossible technically. It is the restaurant who creates the original transaction, thus the refund can only be taken on restaurant's money.
