### ISSUE TITLE
Dispatch : instead of looking from the restaurant address, algo is looking from the delivery address

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#145]
Way to go : 
 - Check existing JS tests for dispatch, [starting here](https://github.com/coopcycle/coopcycle-web/blob/master/js/tests/dispatch.js#L54).
 - Write a new test that creates : 1 customer, 1 restaurant, 2 couriers (one close to the restaurant, one close to the customer), and delivery. Assert that the delivery is dispatched to the courier closer to the customer. Take example/code snippet from the other tests
 - Run `make mocha` to run tests and see it fail
 - Fix the code
 - Run `make mocha` to run tests and see it succeed !

PS : actually an other interesting edge-case not tested here is when the courier is IN the restaurant (same position), could be fun to test if it works. If you have ideas for other unrelated tests scenarii that's good, go for it.

**Comment by alexsegura** [comment]
Fixed by @Ladias-Elie 

8d9e40625568f3308f500daf247cb37fc968420b
0e0c1c6b624acd3dba3f0357d2cab4499bdb9c34
bd02160c9424cd4e427af36343aae9f3a9072f5f
