### ISSUE TITLE
AdressPicker error with no data

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#146]
<img width="530" alt="capture d ecran 2017-11-24 a 15 31 17" src="https://user-images.githubusercontent.com/1162230/33214528-9db936f4-d12c-11e7-91aa-d0305b5d0cee.png">

To reproduce: Clear site data (LocalStorage, cookies), then go to restaurants page.

**Comment by Atala** [comment]
That's for me, I forgot to implement this.

**Comment by Atala** [comment]
Fixed by now, see #160
