### ISSUE TITLE
Allow configuring minimum amount depending on zones

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#1477]
Everythings in the title, eventhough we can raise the "delivery price" for the customer, it would be nice to be able to raise the minimum cart for the further zones, so that we can make the trips profitable.

**Comment by alexsegura** [comment]
This would mean making the minimum amount dynamic, using the pricing rules system. 
It is interesting to make all kind of amounts dynamic, but it makes things more hard to trace & debug. 

Also, it could conflict with other things. For example let's say that you have a zone with a minimum amount, and a radius distance constraint that makes it impossible to reach this zone.

**Comment by Paul-Eraman-CoopCycle** [comment]
I think this is not a great idea because we want a clear message about minimums to the client app-wide. Can we close this or does someone super want this?

**Comment by Paul-Eraman-CoopCycle** [comment]
cant prioritize right now, closing
