### ISSUE TITLE
Cart display on restaurant page is partially covered by footer

### ISSUE THREAD

**Issue by vincentdcom** [coopcycle/coopcycle-web#1482]
**Describe the bug**
When going back to the restaurant page from the cart page, "mini" cart appears below some footer elements when scrolling down.
Also, tip does not appear in "mini" cart.

**To Reproduce**
1. Create order, go to cart page
2. Click on restaurant name / link at top of the page
3. Scroll down to bottom of page (change window size if needed)
4. See error as per screenshot below

**Expected behavior**
All page elements should scroll under the footer. Tip should appear before Total in mini cart.

**Screenshots**
![image](https://user-images.githubusercontent.com/1901398/84588389-44d52b80-ae27-11ea-9518-6aaea6c5bc3c.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser : chrome

**Comment by ERAMANrepartos** [comment]
I believe this is fixde
