### ISSUE TITLE
Allow two different pricing rules for Click&Collect and Delivery

### ISSUE THREAD

**Issue by dingusdong** [coopcycle/coopcycle-web#1483]
When adding an item in the Restaurant - Products menu there would be two possible pricing entries.

The option to have two different prices for each item, dependant on the customer selection Click&Collect and Delivery when ordering.

Restaurants want to have the same prices (as a customer instore) for Click&Collect and have slightly higher prices for delivery.

**Comment by ChloeOLVO** [comment]
Lot of restaurants in Paris are asking for this feature.
For the same product, restaurants should be able to propose:
1/ Price for click and collect
2/ Price for delivery

Impact in backoffice:
In product list section, two column (1 for C&C prices the other for Delivery Price)
In product allow parameter prices HT, TTC and chose taxes for two types of prices: C&C and Delivery



Impact for clients in frontend:
On the product presentation two prices should appear "X euros C&C" and "Y euros Delivery"
Then on order recap, total is different whether you choose C&C or Delivery

**Comment by ChloeOLVO** [comment]
@alexsegura do you know if this feature could be a priority? (It would help us and make new fees of RESTO.PARIS more acceptable toward restaurant!). Thanks!

**Comment by ERAMANrepartos** [comment]
This is implemented i believe
