### ISSUE TITLE
Option "manage or not opening hours" #restaurants

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1487]
**Describe the bug**
When you select option "permission to change their opening hours" it give to the restaurant user  one time to change and they can't manage their hours indefinitely after. 

**To Reproduce**

**Expected behavior**
However (at my opinion) if you give permission to restaurant user, it has to stay possible to manage themself opening hours until you decide to deselect it (for example : conflict between opening hours of coop and restaurant can happens). On our side It create a lot of emails to change hours for restaurants each weeks. We prefer give maximum autonomy to restaurant. So it's cool to have this option just need to improve.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
Thank you @TifaineSicklo, it was an odd bug ☹️
