### ISSUE TITLE
When there are many time slots, the list is too big

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#1488]
Can you change that, it's not esthetic
![bug wasabi](https://user-images.githubusercontent.com/43618873/84818030-21bc9e80-b016-11ea-983b-2b024aff346c.PNG)

**Comment by alexsegura** [comment]
@damienlapoitavelo do you have an idea on how to display it better?

**Comment by damienlapoitavelo** [comment]
@alexsegura Yes, when time slots are succeeding without hourly hole, just keep the first and the last schedules. With picture exemple it stays :
From monday to saturday between 12:15 PM and 2:00 PM
From monday to saturday between 19:00 PM and 22:30 PM

**Comment by alexsegura** [comment]
Or maybe we could add the whole list, but with the first 4 elements displayed, and a "View more" link that reveals the rest?
