### ISSUE TITLE
Activity: download activity data on daytime ranges

### ISSUE THREAD

**Issue by Doyoubouilloux** [coopcycle/coopcycle-web#1492]
In order to produce data analysis for restaurants, we should be able to download data sheet with daytime, mounth time, year time ranges for these topics:
- Type of orders
- Orders by restaurants
- Revenue by restaurants
- Revenue for delivery (global and by restaurant)
- Revenue for reusable dishes (global and by restaurant)

**Comment by ERAMANrepartos** [comment]
This can be done by filering an export in excel
