### ISSUE TITLE
Add the possibility of adding weight/packages to restaurant products

### ISSUE THREAD

**Issue by CiciTW** [coopcycle/coopcycle-web#1498]
**In order to**  having a special pricing when a restaurant sells boxes of wine

**As a** restaurant or coop

**I want** to add a weight/packages option for some products so the client pays a supplement by ordering big heavy volumes from a restaurant (ie. boxes of wine)

**Whereas currently** its not possible and we have to create a specific restaurant for those kind of orders with a specific tarification

**Comment by ERAMANrepartos** [comment]
Too specific use case, closing issue
