### ISSUE TITLE
Add a delete option for promotions 

### ISSUE THREAD

**Issue by CiciTW** [coopcycle/coopcycle-web#1499]
**In order to**  delete unused or test promotions 

**As a** restaurant and admin

**I want** add a delete button for promotions

**Whereas currently** there's no such possibilities, the only way is to make sure the expiration time is in the past

**Additional context**
For the restaurants 
![image](https://user-images.githubusercontent.com/36208124/85201104-0f37b300-b2fd-11ea-8319-ed8667f3f98a.png)

For the admins 
![image](https://user-images.githubusercontent.com/36208124/85201126-30000880-b2fd-11ea-91a8-d7a1aea4c835.png)

**Comment by ERAMANrepartos** [comment]
Not a prioirity and related to overall deleting issues in other issues

**Comment by ERAMANrepartos** [comment]
Not a prioirity and related to overall deleting issues in other issues
