### ISSUE TITLE
Change/relocate the "suggest a restaurant" button

### ISSUE THREAD

**Issue by CiciTW** [coopcycle/coopcycle-web#1500]
**In order to**  suggest restaurants more easily and make the button findable

**As a** customer 

**I want** relocate the "suggest a restaurant" option to make it easier to find and to use. It can be put just at the bottom of retaurants or even integrated like restaurant miniatures

**Whereas currently** the button is at the bottom of the page, not very findable and useful

**Additional context**
Current state of the button : 
![image](https://user-images.githubusercontent.com/36208124/85201245-16ab8c00-b2fe-11ea-86cc-57f4334b1576.png)

1st possibility : 
![image](https://user-images.githubusercontent.com/36208124/85201278-72761500-b2fe-11ea-8c81-ba642a9b0265.png)

2nd possibility :
![image](https://user-images.githubusercontent.com/36208124/85201333-e57f8b80-b2fe-11ea-8e18-b74fc39d8e3e.png)

**Comment by alexsegura** [comment]
Fixed in fc4598fea37d984a422582e4b2039a69061d302b
