### ISSUE TITLE
Add a temporality to enforce menus of the day

### ISSUE THREAD

**Issue by CiciTW** [coopcycle/coopcycle-web#1501]
**In order to**  order for tomorrow the menu of tomorrow and not today's menu

**As a** customer / restaurant 

**I want** a possibility to add a dedicated delivery day for some products/menus

**Whereas currently** it's not possible. So in the case of a restaurant with a menu for each day , a customer can order for today the menu of tomorrow. 

**Additional context**
This case is quite specific to the situation of the Eraman Coop in Spain. Many of their restaurants work with menu of the day  so we created "menus as a product" : 
![image](https://user-images.githubusercontent.com/36208124/85201692-b880a800-b301-11ea-94e7-e589e75042c3.png)

The choosing of the plates is made with the options : 
![image](https://user-images.githubusercontent.com/36208124/85201710-d948fd80-b301-11ea-9137-6f710f9467d5.png)

So the thing would be to associate the products with a day so the menu of a specific day can be only ordered for that day

**Comment by alexsegura** [comment]
To speak in e-commerce language, menus of the day are actually a [variant](https://help.shopify.com/en/manual/products/variants).

Variants are hidden to the user, we generate variants dynamically when the customer chooses a combination of options. 
Users only edit products. 

We need to have variants for each day. 
We need to be able to configure a different description + set of options per day.

**Comment by ERAMANrepartos** [comment]
https://github.com/coopcycle/coopcycle-web/discussions/3621
