### ISSUE TITLE
No update if delivery and pickup have different time arrangements (time slot / at the earliest)

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1516]
If delivery is configurated with "time slots" and the pickup with "at the earliest", when I switch from one to the other, the update doesn't work and the order's page display a wrong time for delivery or pickup.

https://coopcycle.slack.com/files/U9YSA4QUW/F01661EEDNX/needrefresh.gif?origin_team=T4UV5JJJZ&origin_channel=C4UT4DGQ3

https://coopcycle.slack.com/files/U9YSA4QUW/F01661EHPU3/needrefresh2.gif?origin_team=T4UV5JJJZ&origin_channel=C4UT4DGQ3

**Comment by rayon9coop** [comment]
It happens when the customer chooses delivery and selects a another timeslot (not the one proposed) and then choose the pickup's option.

**Comment by rayon9coop** [comment]
Another issue related: on the restaurant's page, the informations about the hour of delivery/pickup appear both without explanation. So it's not easy to understand which hours correspond to what
![Capture d’écran 2020-06-28 à 17 24 13](https://user-images.githubusercontent.com/44605344/85951636-aab3ce00-b964-11ea-8056-55a6e72b1807.png)

**Comment by vova1vova** [comment]
the second issue, it also mentioned here https://github.com/coopcycle/coopcycle-web/issues/1497

**Comment by alexsegura** [comment]
Cannot reproduce anymore

Also, see #2001
