### ISSUE TITLE
Restaurant-list chronological order

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1517]
In order to achieve a better working flow when setting up new restaurants, as an admin, we would like to have also the possibility to let the platform visualize the restaurants in a chronological order (as it was). If just one of both visualizations is possible the actual one is better. 

#lowpriority #admin #restaurant #list #chronological

**Comment by agichim** [comment]
I'd suggest a view filter with options between "chronological" and "alphabetical".
