### ISSUE TITLE
delivery time bug

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#1527]
**Describe the bug**
![Capture](https://user-images.githubusercontent.com/43618873/86120456-a0184680-bad4-11ea-8238-39fd580c9932.PNG)
and at the same time
![Capture1](https://user-images.githubusercontent.com/43618873/86120473-aa3a4500-bad4-11ea-9f1b-d5a05d78fa49.PNG)
We have some problem which appear only with this restaurant. Sometimes they have 2 minutes to prepar a command. I supposed problems come to old age of this restaurant page opened since 2018.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
Fixed in #1999
