### ISSUE TITLE
Brand's name don't stay update

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1544]
**Describe the bug**
RAYON9 must be written in capital letters and all caracters sticked. I try ton change the brand's name in parameters'page. The new brand's name appaers on all pages and on the head of window's but some days later the old name come back.

**Comment by georgeowell** [comment]
@rayon9coop did you try changing it again? Maybe it got overridden in an update.

**Comment by alexsegura** [comment]
This is not a bug in the system. What is written in the field gets saved in database, keeping the capital letters, space, etc...
The only possible explanation that I see, is some browser auto-correct feature that keeps modifying the field.

**Comment by rayon9coop** [comment]
I don't think it's related to browsers because the name change on 
notification too... Here a scrrenshot of my thunderbird.



Le 19-07-20 à 13:42, Alexandre Segura a écrit :

**Comment by alexsegura** [comment]
Ok, I understand: the problem is in the deployment process which overwrites this value. Fixed it. So it's not in the software 🙂
