### ISSUE TITLE
Make a advantageous tarification rule for restaurant's final client

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1545]
It was useful to define dynamic pricing rules based on the amount of the order: delivery's price supported by final client = a fixed percentage of the total amount of the order until the amount of the order reach a defined amount.

Eg:
if order.itemsTotal < 50€ -> price of delivery supported by final client= 10% of order.itemTotal
if order.itemTotal > 50€ -> price of delivery supported by final client = 0€ 

This could increase the average amount of orders by encouraging the customer to add items until reaching amount allows offered delivery

**Comment by Paul-Eraman-CoopCycle** [comment]
we did this! :)
