### ISSUE TITLE
Allow same value for before and after in import csv.

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#1546]
In order to import precise time of pickup and dropoff
As a Admin
Who would benefit  to allow time slot to have the same value for before & after

See https://github.com/coopcycle/coopcycle-web/issues/905

**Comment by alexsegura** [comment]
There are 2 unfinished pull requests about this I think, #680 & #681

**Comment by alexsegura** [comment]
See also #677

**Comment by Paul-Eraman-CoopCycle** [comment]
All PR seem closed, so im closing this
