### ISSUE TITLE
Restaurant account user 

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1561]
**Describe the bug**
Not possible to fit&gourmande connect on its user account. Servor error.

**To Reproduce**
1. Go to 'sicklo.coopcycle.org
2. Click on 'connexion account'

3. See error on the vidéo

**Expected behavior**
Access to its user account.

![Sans titre2](https://user-images.githubusercontent.com/59088580/87020091-afce1400-c1d3-11ea-96a0-58907e2d4398.png)
![Sans titre](https://user-images.githubusercontent.com/59088580/87020098-b0ff4100-c1d3-11ea-8ff6-d4593ac9d348.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vincentdcom** [comment]
Confirmed "something weird is happening", tried to login with affected user credentials on another computer, and on two different browsers. I can login with my own user credentials on sicklo, but if I login with their credentials I :
- can browse the front end
- can put products in cart, view cart, etc
- can't access "my account" /profile.

**Comment by alexsegura** [comment]
Fixed in 878beecf78194c02527550e572b5ac57a84a66db
