### ISSUE TITLE
Use inclusive terminology

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1568]
Like [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb) 

Let's start by removing [blacklist](https://github.com/coopcycle/coopcycle-web/search?q=blacklist&unscoped_q=blacklist)

**Comment by Paul-Eraman-CoopCycle** [comment]
not currently planned
