### ISSUE TITLE
In order to prevent customers from ordering when we are closed I want to have a warning banner displayed on all pages

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#1573]
**In order to**  `achieve something`
I need a Banner in all pages of the website because I use it to prevent when we're closed but some clients happen on website directly in restaurants webpages

![Capture](https://user-images.githubusercontent.com/43618873/87418623-49316780-c5d2-11ea-82b1-2733faf6f0d3.PNG)

(url)

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by alexsegura** [comment]
There is the maintenance mode for this & customers can't order anymore from disabled restaurants (even if they ordered previously)
