### ISSUE TITLE
Delivery time on customer's orders screen has some extra characters

### ISSUE THREAD

**Issue by georgeowell** [coopcycle/coopcycle-web#1589]
**Describe the bug**

**To Reproduce**
- Make an order
- Be redirected to order page

**Expected behavior**
Delivery time displayed as "Delivery in 35-25 minutes" or "Delivery in 35 to 25 minutes" . What I actually see is "In -35 - -25 minutes"

**Screenshots**
![Screenshot from 2020-07-17 20-04-58](https://user-images.githubusercontent.com/18296993/87822123-d392f900-c868-11ea-880e-0647ffb4d903.png)

**Additional context**
Sorry I can't find where to fix this because of the code I don't really understand :smile: 

https://github.com/coopcycle/coopcycle-web/search?q=In+-+-+-+minutes&unscoped_q=In+-+-+-+minutes

**Comment by alexsegura** [comment]
Hmmm it is because the delivery time seems to be calculated... in the past 😐
I think it's more a problem of timezone

**Comment by alexsegura** [comment]
Duplicate of #1846
