### ISSUE TITLE
Introduce "delivery forms" concept

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1600]
Wether it is through the back-office as an authenticated customer, or through a form embedded in an iframe as an "anonymous" customer, it is now clear that there is a concept of "delivery form", that should be a first-class citizen in the platform. 

- [x] coopcycle/coopcycle-web#1423
- [x] #1681
- [ ] #1190

**Comment by joel-shiftdelivery** [comment]
@alexsegura 
Will this allow/require credit card payments when placing an order, especially for small or one-time deliveries?
Maybe similar to Shops, a pre-authorization occurs, then the transaction is finalized when the order is confirmed?

**Comment by alexsegura** [comment]
@joel-shiftdelivery this is already like this on the form that can be embedded on an external website 🙂

**Comment by ERAMANrepartos** [comment]
@alexsegura maybe im wrong, but i think the last task here has been finished. is that true? I'm closing, reopen if needed
