### ISSUE TITLE
In order to [add tips] As a [user] I want a button less

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#1606]
**In order to**  `achieve something`
A clear description of a goal you want to archive
When user choose to give tips, and finally reconsider his choice, he can't go back without return to zero. I think it's a bad mood for users because if they change choice about tips, they need to create a new command or loose money. It's a bad experience.

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by vova1vova** [comment]
Is it about the same issue as https://github.com/coopcycle/coopcycle-web/issues/1660?

**Comment by alexsegura** [comment]
Duplicate of #1660
