### ISSUE TITLE
Promotions

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1645]
The [promotion system](https://docs.sylius.com/en/latest/book/orders/promotions.html) of Sylius is really powerful. 

However, we only use a few parts of it, step by step. We must keep control over who setups promotions. 

The co-op running the service can only setup promotions that impact the price of delivery.
The restaurant can setup promotions that impact the price of products.

This issue is here to collect comments about types of promotions that should be added. 

- [x] #1545

**Comment by Paul-Eraman-CoopCycle** [comment]
closing, but will be creating epic soon related to this
