### ISSUE TITLE
Bugs with pricing conditions

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1656]
When setting a pricing structure for distance, if < or > is used to define pricing, the condition is read to be km. However, if you use "in" to define pricing, the condition is read in meters.

For Packages, when you choose "packages" the only option is for "containsAtLeastOne". After selecting that, when you attempt to select the type of package, it won't let you select one of the options shown, and instead shown this when you click on one of the package options:

![Screenshot from 2020-08-21 12-30-33](https://user-images.githubusercontent.com/64277836/90928439-b4c5dc00-e3ab-11ea-93cf-0dc52180ba7a.png)

**To Reproduce**
1. Go to "create a new pricing"
2. Set distance conditions to > or < and try to enter an order through a store with that pricing structure. The distances in your pricing structure are assumed to be km.
3. Change the pricing structure to "in" and re-test ordering through the same store with the same address. The distances in your pricing structure are now read as meters.

For Packages:
1. Go into pricing structure, and attempt to set a price with a package condition.
2. See error.

**Expected behavior**
The measure of distance should be consistent no matter which condition (<, > or in) is used, so everything is either in km since the condition says "distance (km)".

When you select a package option from the dropdown, it should allow it instead of reading "NaN".

**Screenshots**
This screenshot shows how distance has to be set currently for it to work properly 

![Screenshot from 2020-08-21 11-02-41](https://user-images.githubusercontent.com/64277836/90920909-fb143e80-e39d-11ea-9172-e8f0c1e45f9d.png)

**Desktop (please complete the following information):**
 - OS: Linux (Solus)
 - Browser: Brave

**Additional context**

**Comment by rayon9coop** [comment]
The issue with packages is also on our instance
![packages](https://user-images.githubusercontent.com/44605344/91126589-9e1dce80-e6a4-11ea-9e2f-2024cd5bb937.gif)
