### ISSUE TITLE
It is difficult to decrement tip on mobile

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1660]
Either we need to add a button with minus sign, or at least the `contenteditable` should be fixed

**Comment by vova1vova** [comment]
Is it about this page? And the only way to decrement it now is to edit the text with a keyboard?
<img width="445" alt="Screen Shot 2020-08-26 at 15 33 44" src="https://user-images.githubusercontent.com/1525555/91310091-b7607100-e7b1-11ea-9b10-d283a175f7a1.png">

**Comment by alexsegura** [comment]
Yes, exactly.
