### ISSUE TITLE
When the cart is empty, do not display delivery fee

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1663]
It does not make sense

<img width="379" alt="Capture d’écran 2020-08-24 à 19 59 10" src="https://user-images.githubusercontent.com/1162230/91079608-8c0c4380-e644-11ea-9e01-4d3bde08afee.png">

**Comment by ERAMANrepartos** [comment]
This now does not happen because you see a minimum order warning
