### ISSUE TITLE
Add import file options for "Menu"

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#167]
For the moment, it is only possible to add manually products on 'Menu'. Would be nice to import files with a huge list of products : .mdb .db .sql .csv

**Comment by alexsegura** [comment]
Let's do this!

Let's start with a simple CSV for example

```csv
section;name;description;price
Dishes;Pizza;The best pizza in town;9.99
```

**Comment by couleurmate** [comment]
`section;name;description;price;weight(kg);transportunit
Vegetable;Potato;Starch storage;0,55;0,19;bag
Dairy;Milk;Emulsified Colloid; 1,1;1,0;brick`

**Comment by couleurmate** [comment]
@alexsegura is implementing geocoding import

**Comment by couleurmate** [comment]
@alexsegura closed ?

**Comment by joel-shiftdelivery** [comment]
Looks like this was buried by everything else :)

Importing products/menus would be very helpful, especially as we start on-boarding more grocery stores and retail stores that may have hundreds of different items.

It would be nice if the import could specify options as well (ex: different flavours of yogurt) and the different pricing for the options, if applicable.
The options could also be added at a later time if too complex to easily include in the import now.

**Comment by PasLoin** [comment]
It will be great to have the options but i think in **first step** this simple CSV  help us : 

Name,Description,Enable,Price,Taxes (Taxation Name)

**Comment by paugavarda** [comment]
Hello, is there any possibility to add allergens in the CSV file? Thanks!
