### ISSUE TITLE
In order to fully use coopcycle for our deliveries I want stops be uploaded automatically from the customer

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1670]
**In order to**  use coopcycle for all our stops and be able to mix customers we need an automatic upload of stops. 
I would like stops from our customer to be uploaded to unassigned tasks. The upload can be triggered by the customers program or coopcycle. 

**As a** dispatcher it would prevent me from manually uploading tasks each day or sticking with paperwork. 
Couriers, dispatcher and customer would benefit from that change. 

**I want** automatic uploads to coopcycle triggered automatically by coopcycle or the customers software. Starting with our customer Gut Wulksfelde. I would like to have the function for more customers. 

**Whereas currently** we receive the goods without knowing where to deliver them. Also we only receive a paper list of all stops that we then have to put in the right order. 

**Additional context**
By having all stops in coopcycle it enables us to add extra packages that are along the way of the existing tour.

**Comment by joel-shiftdelivery** [comment]
@GuidoHaagen 
Are you asking for an option to set tasks to repeat every day/week?

Or for a bulk import option for Store owners similar to this #1679 ?

**Comment by alexsegura** [comment]
@joel-shiftdelivery no, @GuidoHaagen is asking for a way to "pull" the tasks from an external source.

**Comment by alexsegura** [comment]
Fixed in 342f6b562d6c4a1935195528932dc4fe0e539db9
