### ISSUE TITLE
Use units of volume to easely create complex tarification rules

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1677]
**In order to**  `easely create complex tarification rules`

**It would be helpfull to** 
`use volume units` in tarification rules by allowing to define a logical relation between volume units

For eg:
If this packages set is defined:
"Small" - volume units = 1
"Medium" - volume units = 2
"Large" - volume units = 3
so 
2 Small = 1 Medium
3 Small = 1 Large
1 Small + 1 Medium = 1 Large
...
and the price could be calculated easely even if there are differents  packages in the order.

**Whereas currently** `this happens`
Currently, Volume units is not used for tarification rules (not used at all?)

**Comment by Paul-Eraman-CoopCycle** [comment]
they are now :)
