### ISSUE TITLE
If 'weight' is required field, price must not be calculated if weight's field is empty

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1682]
**Describe the bug**
While the weight is a required field, when i try to order delivery from a store without filling the weight, to price is calculated as if the weight were O.  

**To Reproduce**
1. Use a tarification rule with at least two conditions on weight. For eg: 
- weight in 0..9000 =Price 1
- weight in 9001...20000 = Price 2 
2. Assign this tarification rule to a store and set 'weight' as required field
3. Create a new delivery and do not filling weight
4. See error: the price displayed is Price 1

**Expected behavior**
Require the filling of weight (and by the way for packages too) if it's a required field 

**Screenshots**
![Capture d’écran 2020-08-29 à 08 41 21](https://user-images.githubusercontent.com/44605344/91630661-7a73c480-e9d3-11ea-8bdd-be3912bbb8ad.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
Is this still happening @rayon9coop ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Now the form shows 0 by default, which fixes this by showing the 0 weight
