### ISSUE TITLE
On dashboard, some tasks disappear after refreshing page

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1689]
**Describe the bug**
On dashboard, some tasks disappear on map after refreshing page

**To Reproduce**
1. Go to 'Dashboard'
2. Import some tasks, assign some on several courriers and let some tasks unassigned
3. Click on 'refresh (F5)'
4. Some tasks disappear on map
5. Click on one task unassigned (in the list, on the right of dashboard), all tasks appear on map

![bugOnRefresh](https://user-images.githubusercontent.com/44605344/91720410-64166600-eb97-11ea-8d7d-3786fce0001c.gif)

**Comment by PasLoin** [comment]
We have exactly the same bug ; i was thinking it's linked to task imported between several date ; but i just notice that's not linked.

**Comment by ERAMANrepartos** [comment]
Does this still happen? I believe not but im not sure

**Comment by ERAMANrepartos** [comment]
@rayon9coop

**Comment by rayon9coop** [comment]
Yes, this still happen but differrently: when deleting (group of) unassigned tasks of a imported batch, all the tasks seems deleted, even the assigned ones
![bug](https://user-images.githubusercontent.com/44605344/234796072-7a0d691f-3b22-4fe8-abc9-2e402eebad67.gif)

**Comment by ERAMANrepartos** [comment]
Perfect thanks. I will place on the roadmap

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok this may still happen, but this is mentioned in a different issue and is now on the roadmap, so im closing
