### ISSUE TITLE
Phone number normalizer : extend region available in instance

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#1699]
**Describe the bug**
In our instance with region "Belgium" it s not possible to import phone number from another country

**To Reproduce**
Import a 33612345678 number in our instance. 

**Expected behavior**
Allow phone number for another country

**Comment by PasLoin** [comment]
@alexsegura ok thats work
I think if the phone is formatted in "international" (i.e +33612345678) format it will work. If not, it expects a national number. Don't forget the +  sign

**Comment by r0xsh** [comment]
Maybe related to this: https://github.com/coopcycle/coopcycle-app/pull/1515
