### ISSUE TITLE
Enable setting a Delivery Perimeter for Stores and Delivery forms

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1700]
**In order to**
Allow a fixed delivery Zone for Stores and prevent orders outside that zone from being placed, instead of having to manually reject orders placed outside our delivery zone.

This should be set similar to the "Delivery perimeter" that currently exists in Shops.

**As a** 
Store owner, this would provide an immediate clearer notice when attempting to place an order outside the Co-op's delivery area.

Admin, this prevents extraneous orders that we are unable to service from being placed and populating our Dashboard, which we then have to Refuse. It would also make the 

**I want** 
A "Delivery Perimeter" setting to be added to Stores, similar to how it exists for Restaurants currently (with the option of radius or Zone perimeter)

**Whereas currently**
You can set a zone in Pricing, but it does not prevent orders outside that zone from being placed.

**Additional context**

**Comment by joel-shiftdelivery** [comment]
It would be beneficial to have a Delivery Perimeter option for all ordering options (Sops/restaurants, stores, delivery forms, and hubs)

**Comment by Paul-Eraman-CoopCycle** [comment]
we just did this 🥳
