### ISSUE TITLE
Simplify ordering process for Stores: have a setting to allow a single combined Time slot for pickup/dropoff 

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#1709]
**In order to**
Simplify the ordering process for Stores and prevent mistakes with pickup/dropoff time slots when placing an order.

**As a** 
Store, this would prevent forgetting to change one of the timeslot and scheduling a pickup or dropoff for the incorrect time.

**I want**
There to be an option in a Store's settings to allow a single combined timeslot for pickup/dropoff to appear when placing an order. 
Ex: The "Time slot" under Pickup would be hidden, and only "Time slot" under dropoff would show. The choice of time slot there would schedule bot the Pickup and Dropoff for that time slot.

**Whereas currently** 
A Store must select both pickup and dropoff timeslot, even if they are the same

**Additional context**
The vast majority of our clients work on a combined pickup/dropoff window, with only ~5% using separate pickup and dropoff windows.

**Comment by ERAMANrepartos** [comment]
Specific issue to use case, and will be dealt with by general UI/UX improvements and next steps, so closing
