### ISSUE TITLE
In order to faster find errors when uploading stops I want the error message to show the line in which the error occurs

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1726]
**In order to**  make the error massages even more helpful it would be great to get the information on which line the error occurred to easy fix it. 

**As a** of a dispatcher I would benefit from it by easily finding the reason of a failed upload

**I want** to get the info in which line the problem happens. I wouldn't mind if it's just the first error line. 

**Whereas currently** you don't know the line that is responsible for the failed upload.

**Comment by Paul-Eraman-CoopCycle** [comment]
- [ ] Show the multiple errors that are occurring in the import
- [ ] Import only the correctly understood rows and not the erroneous rows
- [ ] Inform well to the user which rows have been imported and which not

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
