### ISSUE TITLE
Allow linking two or multiple tasks into an Order

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1731]
Do not make this mandatory. Tasks should still be able to remain unlinked if the user wants it so.

This can go hand in hand with issue #690.

**Comment by alexsegura** [comment]
Actually, tasks won't be attached _directly_ to an Order. 

An Order contains products. 
For example, when an Order is placed in the Store context, via the form in the back-office, under the hood it creates dynamically a product. This is what you see here: 

<img width="577" alt="Capture d’écran 2020-09-22 à 12 23 49" src="https://user-images.githubusercontent.com/1162230/93871175-83a03a80-fcce-11ea-9c01-38deb289f7b0.png">

The tasks are attached to a Delivery, which is itself attached to the Order. 

So, it could be possible to select 2 tasks (not more, the concept of "Tour" doesn't exist yet), create a Delivery from them, and create an Order. 

---

But **the price of the product should be entered manually**. 
So it means the UX would look like:
- Select 1 pickup + 1 dropoff
- Click on "Create order from selected tasks"
- A window opens, and asks to select a Store + enter a price

@agichim What do you think?

**Comment by agichim** [comment]
Let me get this straight:

You say,
> tasks won't be attached directly to an Order.

and then you say,
> Select 1 pickup + 1 dropoff
> Click on "Create order from selected tasks"

From the way I interpret that, in the bullet point you're saying that tasks created an order but also saying that tasks won't be attached directly to an Order. Maybe it's just a terminology issue, but it's confusing.

**Comment by alexsegura** [comment]
I mean the user interface hides what happens.

**Comment by agichim** [comment]
Ah, ok. Makes sense!

**Comment by agichim** [comment]
Sorry, I closed the issue. I opened it again.

**Comment by ERAMANrepartos** [comment]
@jimakker What is an order?

**Comment by Paul-Eraman-CoopCycle** [comment]
We did this!
