### ISSUE TITLE
MVP for "B2B" feature

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1768]
### Reduce the number of parameters for a company

- Allow defining a list of restaurants (those who have b2b_enable = true)
- Allow defining a list of time slots

### Workflow on frontend

- When the user switch to "b2b context", the restaurants which do not belong to the allow list are disabled
- If the user browses to a restaurant that does not belong to the list, show a warning message
- The delivery address is pre-selected and cannot be changed
- The delivery time slots are limited
- The delivery fees are offered by the company

**Comment by ERAMANrepartos** [comment]
@alexsegura Can you clarify what this means? What is b2b enabled? is this about the catering options that they have? As far as I know, users do not currently "switch to ´b2b context´"

**Comment by Paul-Eraman-CoopCycle** [comment]
We did this will business accounts
