### ISSUE TITLE
Store owners should be able to see the order price.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1774]
This is what admins see under the Orders tab 
![image](https://user-images.githubusercontent.com/51931067/94673368-858d7d80-030e-11eb-996c-a6b4fa65213f.png)

<br>

This is how the same order looks like for the Store owner on their account when they click to open an order. 
![image](https://user-images.githubusercontent.com/51931067/94673492-b79edf80-030e-11eb-9c51-61ea164024ae.png)

The Store owner does see the price when they create the order, but cannot see it afterwards.

**Comment by Paul-Eraman-CoopCycle** [comment]
Added! 🥳
