### ISSUE TITLE
Add price column in Store account

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1775]
Add a price column where the red marking is, or anywhere, really. It will make it easier for store too check their orders and price is most important, if they need to cross-check information with what the Coop invoices them.

![image](https://user-images.githubusercontent.com/51931067/94674579-4d873a00-0310-11eb-8056-5cc6c9005e3c.png)

**Comment by alexsegura** [comment]
Related to #1710

**Comment by Paul-Eraman-CoopCycle** [comment]
done!
