### ISSUE TITLE
pimp my navbar 

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#180]
1/ admin dashboard : change fa-lock (UX not obvious) for fa-user-o fa-home fa-dashboard
2/ different navbar for client - admin - restaurant - courier
3/ ```<ul class="nav navbar-nav">
        <li>
          <a href="/fr/restaurants">Restaurants</a>
        </li>
          <li>
          <a href="/fr/magasins">Magasins</a>
        </li>
      </ul>```

**Comment by alexsegura** [comment]
Fixed in 901cc51039389d93217082221152c20aba997752
