### ISSUE TITLE
Change name of Admin dashboard to Admin dispatch for consistency.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1810]
Rename the map dashboard, `dispatch`. Because that is where the dispatch of orders or tasks is happening. See image below.
![image](https://user-images.githubusercontent.com/51931067/95564859-47334500-0a17-11eb-8f21-7115f43f3306.png)
That should say `Admin dispatch`.

The consistency is weird because under the `Orders` section in the menu we have `Dashboard` there as well. 
![image](https://user-images.githubusercontent.com/51931067/95565032-83ff3c00-0a17-11eb-9ed4-115bf6afa413.png)

**Comment by ERAMANrepartos** [comment]
This is clearly a good idea based on taxonomy and clarity, i´m going to make a quickfix

**Comment by Paul-Eraman-CoopCycle** [comment]
Can we just change it to "Dispatch"?

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle I have changed to "Dispatch" for all languages is that ok ?

also do we change the lock icon to go to admin part to something else?

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/9996cbaa-fc4f-4b9e-a981-e571a2b07ea6)

**Comment by Paul-Eraman-CoopCycle** [comment]
Yes please...

**Comment by Atala** [comment]
idea?

**Comment by Atala** [comment]
ah the lock is a link to the dispatch that is true, but it is more the link to the admin part of the platform (because you login you arrive on restaurantS page and then you want to access the admin)

so i think just a button or a link called "TO ADMIN" ? or something of the like

**Comment by Paul-Eraman-CoopCycle** [comment]
but thats a different issue. in all places in the platform, this button takes you to dispatch. the fact that there is no main menu accessable in other certain places is a structure problem, not a naming problem

**Comment by Paul-Eraman-CoopCycle** [comment]
in my opinion haha
