### ISSUE TITLE
Add price column in .csv export from Admin dashboard

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1811]
Due to the way we pay per hour, we use the .csv export from Admin dashboard to check the `collection` and `drop-off` times for riders, to see how many hours they worked. 

If there would be a column of the price of each order would make it easier for us to check the same .csv export and create our invoices for our clients. 

This issue could be related to #1775

**Comment by ERAMANrepartos** [comment]
We also would very much like this at Eraman Repartos

**Comment by alexsegura** [comment]
You can instead use the orders export feature, and tick the "Add column with messenger who completed the order" box

<img width="614" alt="Capture d’écran 2021-02-09 à 19 51 51" src="https://user-images.githubusercontent.com/1162230/107412804-4cf97e00-6b10-11eb-9285-14ca4c411c6f.png">
