### ISSUE TITLE
Implement recipient/customer email field in "Create order" under Client/Store accounts.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1823]
Implementing the email field should send an email to the customer as well as to the store who created the order when a rider "collects", "starts" and "delivers" an order. 

Possible email template for CUSTOMER/RECIPIENT

### FOR COLLECTION:
SUBJECT: You order `XF4` from `store name` will be delivered shortly
BODY: Your order will be delivered in approximately 30 minutes. You can track your delivery following the link below: `public tracking url`.
Thank you

### FOR DELIVERY
SUBJECT: You parcel has been delivered succesfuly.
BODY: Thank you for your purchase. 

---

Possible email template for CLIENT/STORE

I guess an email like the template above to the customers would look weird if the store get the same email, as they should get a different kind of email:

### FOR COLLECTION:
SUBJECT: Order `XF4` has been collected.

### FOR DELIVERY
SUBJECT: Order `XF4` has been delivered succesfully.

---

Maybe the 2 different types of email is a separate issue. I'll leave it here for now. I guess just for now, the recipients getting an email can be very general and it can be the same information as the store/client gets.

**Comment by ERAMANrepartos** [comment]
This is complex because some coops may want this and some may not
