### ISSUE TITLE
Allow integration tasks/orders with a calendar. [tags: long-term, non-urgent]

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1829]

**Comment by agichim** [comment]
Has this been implemented or was it closed because it's trivial?

**Comment by Paul-Eraman-CoopCycle** [comment]
Hi alex! 
Not exactly. We are looking into integrating shift planning tools into CoopCycle at the moment, and without more info, it seemed like those new issues we are created cover what this is talking about. So more not to have multiple issues about the same thing. But if you want to add more info, maybe its slightly different or something

Hope all is well with you!
