### ISSUE TITLE
Empty upload folder is shown with 1 stop and cancelling it causes unwanted behaviour

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1831]
**Describe the bug**
We upload every week a spreadsheet with recurring stops. Once I distributed all of them to drivers the upload folder is still visible with a "1" even though all stops are assigned to drivers. When cancelling the folder I often get the error message "404" and all stops that are not assigned to divers from the same upload are cancelled. Even if they are on another day. 

**To Reproduce**
1. upload one spreadsheet with stops on different days
2. choose one day and assign all the stops to drivers
3. Often import folder was then still visible with the icon for "1" but I could not open the folder
4. When cancelling the upload folder the error massage "404" appears and all stops from the upload on other days are cancelled too

**Expected behavior**
Cancelling an upload folder should only cancel the stops you see in the folder (current day)

**Desktop:**
 - OS: Ubuntu
 - Browser firefox 81.0 (64-Bit)

**Comment by GuidoHaagen** [comment]
The reason here might actually be folders of upload containing stops on different days.

**Comment by ERAMANrepartos** [comment]
There are many visualization problems when anything (a task, order, group) spans more than one day and likely needs investigation.

**Comment by Paul-Eraman-CoopCycle** [comment]
@Atala maybe check if this still happens
