### ISSUE TITLE
Do not require login for "Suggest a restaurant"

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1832]
Maybe this https://york.coopcycle.org/en/restaurants/suggest shouldn't require a login. It would be better and simpler if anyone can suggest a business.

**Comment by alexsegura** [comment]
There is one problem with this → spam

Requiring a login prevents this, and also moderation by admins.

**Comment by agichim** [comment]
Spam as in spam from random people? Or spam/bot? 
Maybe introduce a CAPTCHA?

**Comment by ERAMANrepartos** [comment]
Implemented
