### ISSUE TITLE
Enable pricing calculation according to "order.itemsTotal"

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#1844]
`order.itemsTotal` is not injected in the pricing formulae - would that be possible to inject it in the formulae as well ?

**Comment by alexsegura** [comment]
Actually it already works no?

https://github.com/coopcycle/coopcycle-web/blob/08c4713da2dab7a71445878602de0d131e69da26/js/app/components/RulePickerLine.js#L27-L38

<img width="685" alt="Capture d’écran 2020-10-29 à 20 57 51" src="https://user-images.githubusercontent.com/1162230/97625927-7858d100-1a29-11eb-9fe4-9cb9d56d60a3.png">

**Comment by Atala** [comment]
The request was to have it in the price input on the right, like `price = order.itemsTotal * 0.3`  (percentage of order total like for foodtech)

**Comment by Paul-Eraman-CoopCycle** [comment]
who requested this @Atala?

**Comment by Atala** [comment]
cant remember sorry you can trash it if needed

**Comment by Paul-Eraman-CoopCycle** [comment]
okey sounds good
