### ISSUE TITLE
Double click to order 

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1849]
**Describe the bug**
Users have to clic two times to be redirected to the page of order.

Vidéo to show the problem.

[2020-10-21-11-34-51.zip](https://github.com/coopcycle/coopcycle-web/files/5414920/2020-10-21-11-34-51.zip)

**Comment by agichim** [comment]
Hey, this is not related to your issue. This little program creates .gif files really easily and you can upload them much faster and they're playable anywhere without downloading. http://blog.bahraniapps.com/gifcam/
