### ISSUE TITLE
Cannot install hirak/prestissimo

### ISSUE THREAD

**Issue by MxyL** [coopcycle/coopcycle-web#1853]
Getting this error when building the project

````
[InvalidArgumentException]
Package hirak/prestissimo at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
````

Just run docker-compose up and it'll crash while building php image

Cause is due to release of composer 2.
https://github.com/hirak/prestissimo/issues/233

I fixed this by modifying docker/php/install-composer.sh to use the previous version

line 14:

````
php composer-setup.php --quiet --version=1.10.16
````

But perhaps this package isn't needed anymore in v2.

**Comment by alexsegura** [comment]
Thank you @MxyL 

Yes, Composer 2.0 has parallel downloads, so it's not needed anymore

**Comment by Herz3h** [comment]
Ran into same issue, installed version 1 with:

```bash
 curl -sS https://getcomposer.org/download/1.10.17/composer.phar -o /var/www/symfony/composer 
```
