### ISSUE TITLE
Sync price for orders in Store account with price in admin account

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1854]
Store account screenshot of price 
![image](https://user-images.githubusercontent.com/51931067/97117920-bfc82000-16fe-11eb-9d14-c61abe994457.png)

This is the price that we can see as admin

![image](https://user-images.githubusercontent.com/51931067/97117929-db332b00-16fe-11eb-9d6d-21c19ce04fc0.png)

Basically, excl. VAT and incl. VAT are not linked.

**Comment by ERAMANrepartos** [comment]
Unclear and will likely be dealt with in other UI/UX issues, closing
