### ISSUE TITLE
Add "weight" column under the Deliveries section

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1855]
Add weight column where the Green mark is in the screenshot, so you don't have to open the delivery to see the weight.

![image](https://user-images.githubusercontent.com/51931067/97117972-35cc8700-16ff-11eb-9a68-6d01dd6b0b0c.png)

**Comment by alexsegura** [comment]
Fixed in 73f2c4f1df3d63503368d8de418e055df7dc5da9
