### ISSUE TITLE
Implement a visual symbol of order Status under Store account. 

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1857]
When a store places an order they should easily see in their list of orders if that order was cancelled, in standby (to be confirmed) or confirmed/accepted.

Basically, show a `red` (cancelled), `orange` (standby) or `green` (accept/confirmed) dot like in the screenshot. 
Red means order wasn't accepted by the coop.
Green means order was accepted. Accepted means → look at this issue #1856 

![image](https://user-images.githubusercontent.com/51931067/97118484-feaba500-1701-11eb-8c9f-9a887dfafabd.png)

**Comment by Pidgeon45** [comment]
A fulfilled status would also be useful on the 'Deliveries' screen.

**Comment by Paul-Eraman-CoopCycle** [comment]
done!
