### ISSUE TITLE
Implement pricing "condition" of "Cut-off time" depending on the day of delivery

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1869]
If a client/store creates an order after 12pm (cut-off time) and chooses `today` as delivery date the price updates accordingly. It means that orders created after 12pm with TODAY delivery will have a different cost.

The same applies if order is created after the cut-off time but with delivery date for tomorrow.

**Comment by ERAMANrepartos** [comment]
This can be done with the existing pricing rules its just annoying
