### ISSUE TITLE
Show selected account when user has both a Store and E-commerce accounts assigned

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1882]
Although it's obvious which account you're viewing, the name of the account, between a back-office account and an e-commerce account should be coloured indicating that that is the account being viewed currently. 

![image](https://user-images.githubusercontent.com/51931067/97804532-83d61300-1c48-11eb-9aa2-031c4a1e9103.png)

**TEST** is a back-office account
**Atelier Creativa** is an e-commerce account.

Related to issue #1871

**Comment by ERAMANrepartos** [comment]
No longer relevant due to interface changes
