### ISSUE TITLE
Product descriptions do not display newlines/carriage returns

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1883]
Description:
Product descriptions do not display newlines/carriage returns, which means that multiline descriptions are wrapped to one big blob of text. Could we support multiline descriptions?

**To Reproduce**
1. Go to a restaurant containing products with multiline descriptions (or create a test one)
2. See that the description text deletes newlines - line beginnings are concatenated onto previous line ends.

**Expected behavior**
New lines should start on a separate line

**Screenshots**
<img width="377" alt="Screenshot 2020-11-01 at 15 50 24" src="https://user-images.githubusercontent.com/12956046/97807706-3d89af80-1c5a-11eb-9735-1fa395bccede.png">
The new lines start with "2 x..." but are added to the end of the previous line

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by alexsegura** [comment]
Should work by using the [nl2br](https://twig.symfony.com/doc/2.x/filters/nl2br.html) Twig filter.

The template is there 

https://github.com/coopcycle/coopcycle-web/blob/f4c7d433e84861df0dfb106968384a2e99c3ca22/templates/_partials/restaurant/menu_item_content.html.twig#L6
