### ISSUE TITLE
Can't delete menus

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1885]
**Describe the bug**
Cannot delete restaurant menus in the menus page

**To Reproduce**
1. Create restaurant
2. Create menu
3. Go back to menu list page
4. Click wastebin/delete icon
5. Click "Are you sure?"
6. Get taken to menu detail page

**Expected behavior**
Menu is deleted instead of being taken to menu detail page. It seems like the second button is not hooked up to an action or it is at a lower layer than the clickable row.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by ERAMANrepartos** [comment]
We can´t delete anything due to the way the database works, which means that this is really a repeated issue. Closing
