### ISSUE TITLE
Pad between restaurant description and address + delivery times

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1886]
**Describe the bug**
No padding between restaurant description on the left and the address + delivery times on the right of the page.

**To Reproduce**
1. Create restaurant with long description, an address, and delivery dates
2. Go to customer-facing restaurant
3. See description come right up to the address and delivery times

**Expected behavior**
It would be nice for there to be some padding between the description on the left and the address + delivery times on the right.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by agichim** [comment]
Could you post a screenshot of this?

**Comment by davidcryer** [comment]
<img width="1023" alt="Screenshot 2020-11-13 at 15 34 13" src="https://user-images.githubusercontent.com/12956046/99089946-df4bbd80-25c5-11eb-97cf-8cbc326460db.png">

**Comment by Paul-Eraman-CoopCycle** [comment]
this has been redone
