### ISSUE TITLE
To prevent people from losing the delivery fees' money paid by the customer, find a solution

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#1890]
It could either be:
-A warning saying "if you want the money charged to the customer, please make sure you set this amount in the "amount invoiced by the co-op"

Or we could say that delivery fees being 100% of times destined to the co-op, we could make it automatic that these fees go to the co-op.

**Comment by Paul-Eraman-CoopCycle** [comment]
We will make a new design for these parts of the settings when we have resources, closing for now, but yeah definitely a problem
