### ISSUE TITLE
Add an ASSIGNED or DISPATCHED status for Tasks

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#190]
As for delivery, shouldn't we be add an `ASSIGNED` or `DISPATCHED` to tasks?

We need to do something anyway because there are inconsistencies see below.

Task is assigned in main dashboard
<img width="1392" alt="capture d ecran 2018-01-24 a 12 38 33" src="https://user-images.githubusercontent.com/4426585/35330350-8a5d4896-0103-11e8-8f23-5177a42092cd.png">

But delivery is not tagged as 'Dispatched' and can still be assigned : 
<img width="1392" alt="capture d ecran 2018-01-24 a 12 39 26" src="https://user-images.githubusercontent.com/4426585/35330372-a2abf050-0103-11e8-9a1b-abb2b502df80.png">

**Comment by alexsegura** [comment]
I'm currently fixing this (synchronize status of Task <-> Delivery). 
But actually everything can be managed via a Task, not even sure the Delivery class is relevant anymore.

**Comment by alexsegura** [comment]
Fixed in f2a3d366edd84b83e7aed242193cf0c1b72efb85 for Task <-> Delivery synchronization. 

For other task statuses, let's discuss it elsewhere.

**Comment by Atala** [comment]
I think we need `Delivery` at least in order to display it to customers/restaurant owners/shops, as they won't get the task concept.
