### ISSUE TITLE
Add postcode to customer detail in order information for stores and couriers

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1902]
Stores and couriers would like the customer's postcode along with their address when viewing orders, as street names can be duplicated across a region and therefore the address line is not always enough.

For couriers this is especially useful when they are placing the addresses into a tool to optimise routes, as without the postcode they don't often work. 

Currently, only the address line is visible without the postcode.

**Comment by agichim** [comment]
Can you post a screenshot? Is this in the app or somewhere on the platform?

**Comment by davidcryer** [comment]
Restaurant order screen:

<img width="500" alt="Screenshot 2020-11-13 at 12 18 58" src="https://user-images.githubusercontent.com/12956046/99071673-80c51600-25aa-11eb-9fbc-519f2ff8acd9.png">

Admin order screen:

<img width="610" alt="Screenshot 2020-11-13 at 12 17 56" src="https://user-images.githubusercontent.com/12956046/99071714-933f4f80-25aa-11eb-9117-52d522a9c7cd.png">

**Comment by agichim** [comment]
Ideally the postcode is show everywhere, on the dispatch, under Orders, under Deliveries and on the app for each task.

**Comment by alexsegura** [comment]
The street address is now formatted with city, district & postcode when user types. 
This is what is stored in database afterwards. 

![postcodes](https://user-images.githubusercontent.com/1162230/100420260-69942700-3086-11eb-994d-a9ee15b6fcc4.gif)
