### ISSUE TITLE
Promotion code disappears between "order" and "payment" steps

### ISSUE THREAD

**Issue by vincentdcom** [coopcycle/coopcycle-web#1910]
**Describe the bug**
When adding a promo code to an order, it disappears when going to the payment page.
Note : if I enter and apply the promo code then reload the /order page before clicking on the Order button, promo stays applied. Guess you already know where the problem is by now ^^

**To Reproduce**
1. Go to an instance and place an order
2. On the /order page (shopping basket recap), add a promo code. 
3. Click on Order button (commander)
4. See error : promo is not applied anymore

**Expected behavior**

**Screenshots**
Promo is applied :
![image](https://user-images.githubusercontent.com/1901398/98832966-c44e4180-243d-11eb-9638-6266755c1a53.png)
Promo has disappeared :
![image](https://user-images.githubusercontent.com/1901398/98833050-dc25c580-243d-11eb-8ef6-71ee9230fc3b.png)

**Desktop (please complete the following information):**
 - OS: Win 10 & Android 10
 - Browser Chrome

**Comment by alexsegura** [comment]
Fixed in aec607a741984662c4c4884041fe6d9d7f350398
