### ISSUE TITLE
Add labels to distinguish collection and delivery times

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1917]
The platform does not label the collection and delivery dates, so it is not clear what the times relate to in the restaurant page

**To Reproduce**
1. Create a restaurant with delivery and collection times
2. Go to customer-facing restaurant page
3. See delivery and collection times to right of restaurant description

**Expected behavior**
The collection and delivery times are clearly labeled

**Screenshots**
<img width="1023" alt="Screenshot 2020-11-13 at 15 34 13" src="https://user-images.githubusercontent.com/12956046/99090516-a7914580-25c6-11eb-8337-d8a250742244.png">

Can see no labels distinguishing Friday delivery slot and any day collection

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by alexsegura** [comment]
Closing in favor of #1924
