### ISSUE TITLE
In order to describe the packages typology to my clients As a admin I want add a description to each kind of package

### ISSUE THREAD

**Issue by MathildeS** [coopcycle/coopcycle-web#1918]
**In order to**  `describe the packages typology to my clients`
I want my clients to identify clearly the different kinds of package and the associated prices for delivery. 
Ex : I have a different price for big medium and small packages, all in the package set "colis". I want my client to identify what exactly I mean by a big package (ex : L + l + h > 150 cm).

**As a** `admin`

**I want** `something to be added or changed`
So far, I have super long names : 
- Grand colis : L+l+h ≤ 150 cm et/ou L ≤ 100 cm
- Colis de taille moyenne : L + l + h < 60cm (ex : boite à chaussures)
- Petit colis : format a4 et épaisseur 2cm max (livre, lettre, etc)
I'd rather have a package type name : petit, moyen, grand and an associated description to each of them. It would make it possible to have something clearer in the display and also in the formulas : (packages.quantity("Grand colis : L+l+h ≤ 150 cm et/ou L ≤ 100 cm") * 1000)  is hell. 

**Whereas currently** `this happens`
this occurred to me when setting the packages delivery form

**Comment by Paul-Eraman-CoopCycle** [comment]
@Atala this now exists in the package creation form, but it still doesnt show up in the order creation page right?

**Comment by Atala** [comment]
yes, but there are other issues for this #4585

**Comment by Paul-Eraman-CoopCycle** [comment]
perfect, thanks!
