### ISSUE TITLE
Issue in the price without tax calculation when using the form

### ISSUE THREAD

**Issue by MathildeS** [coopcycle/coopcycle-web#1920]
**Describe the bug**
I test the delivery integration widget I created. 
The price displayed seems wrong : the tax free price is wrong. It should be TTC price / 1.2 but it is not. 

**To Reproduce**
1. Go to https://biclooo.coopcycle.org/fr/forms/OvVMr86aqezQ
2. Order some package delivery
3. Confirm the order, you go to the confirmation page where you can see the price set
4. See the difference between the TTC price and the HT price : it is not right

**Expected behavior**
HT price should be TTC price / 1.2
not sure if this involves only the display here or the calculation in the system

**Screenshots**
![Screenshot 2020-11-14 at 15 07 35](https://user-images.githubusercontent.com/3449486/99149113-5e0b2e00-268c-11eb-83f1-26e0faca5190.png)

**Comment by ERAMANrepartos** [comment]
@alexsegura is this still a relevant issue?
