### ISSUE TITLE
To show next slot available for delivery possible AND next slot available for Click & Collect

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#1924]
In order to comunicate better to the consummer the difference between next slot for delivery and next slot for click and collect.

Currently the next slot showed is just "delivery". The issue is that the consumer may understand that click and collect is not available (in general restaurants put more slot for click and collect).

The modification should be:*
- On the front page " (en dessous de la photo du restaurant) "livraison demain entre XX et XX" et "Click & Collect Aujourd'hui entre XX et XX"
- On the restaurant page, add before the slots: Livraison/Delivery, and Click & collect. Currently it looks like it's a repetition of slots but we dont' know slots "of what" (en gros ça fait deux lignes avec des créneaux mais on comprend pas pq ya deux lignes).

![image](https://user-images.githubusercontent.com/74653993/99517117-4a630e80-298f-11eb-979f-2e3d2c106948.png)

![image](https://user-images.githubusercontent.com/74653993/99517382-98781200-298f-11eb-874b-6a0a359b4f24.png)

**Comment by ERAMANrepartos** [comment]
Generally there are a whole lot of problems about how the restaurants availability is shown to the customer. This probably needs a full rework
