### ISSUE TITLE
To parameter operational slots and leads for delivery (slot order, anticipated pick up, anticipated order)

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#1925]
Within Execution Parameters
In order to ensure operational delivery service we need to be able to have access to the following parameters:
1/ put minutes for anticipated lead times for orders (for instance we would like to put 1h30)
2/ Slot for delivery (very important for us - it has operational impacts.
3/ Anticipated pick-up at restaurant. Being able to agree with the restaurant to put "anticipated pick-up of XXminutes" for instance.

For orders placed "as soon as possible", we would like to be able to:
1 / deliver on a 30min slot (and not 10min as is currently the case)
2 / Being able to pick up the order 30min before the delivery window begins (to optimize our tours and give us more flexibility). This means that the restaurant, at a minimum, can only have 30 minutes to prepare its order.

> Nous voudrions pouvoir réduire le délais de prévenance pour les commandes à 1h30 (en l'état pas possible côté paramètre car l'unité est l'heure)
> Pour les commandes passées "au plus tôt", nous souhaiterions pouvoir:
1/ livrer sur un créneau de 30min (et non 10min comme c'est le cas actuellement)
2/ Pouvoir passer récupérer la commande 30min avant que le créneau de livraison ne débute (pour optimiser nos tournées et nous donner plus de flexibilité). Ca veut dire que le restau, au minimum, peut avoir seulement 30min pour préparer sa commande.

**Comment by ERAMANrepartos** [comment]
It appears to me that the parts of this that i understand are implemented, if not, please reopen @alexsegura
