### ISSUE TITLE
In order to check for failed deliveries as a dispatcher I want to filter failed dropoffs on the map

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1928]
**In order to**  `achieve something`
I want to daily track and followup on the failed dropoffs (stops, tasks)

**As a** `role`
dispatcher (tricargo)

**I want** `something to be added or changed`
in the filter function under tab "general" there should be added: "failed tasks"

**Whereas currently** `this happens`
it's missing, currently there are 3 general filters: finished, cancelled, unassigned

**Additional context**

**Comment by rayon9coop** [comment]
This should be particulary usefull to reprogram an second attempt on the next day. The process could be:
1. opening the day before's dashboard
2. filtering the tasks with the failed filter
3. duplicate the tasks
4. postpone the duplicated tasks to the next day

**Comment by Paul-Eraman-CoopCycle** [comment]
We have discussed in a different issue https://github.com/coopcycle/coopcycle-web/issues/3540 here having a place to visualize incidents and failures, but having a way to see them on the map may also be useful

**Comment by Paul-Eraman-CoopCycle** [comment]
We made a new one by accident: https://github.com/coopcycle/coopcycle-web/issues/3941

It's assigned and in production, should be finished soon

**Comment by Paul-Eraman-CoopCycle** [comment]
we did this!
