### ISSUE TITLE
In order to ease the life of a foodtech dispatcher, a couple requests from the 18th November 2020 discussion (Eraman/Kolyma2/York/Sicklo)

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#1930]
**Filter evolution:**

Time slots: Dispatch filters now only have large time slots.
For foodtech, it would be appreciated to have more precise filters when there are a lot of orders. 15min time slots for example.

-Shift filters: It would be great to have the possibility to hide the couriers that are not working on a current shift. (Like lunch couriers not being in the dashboard to help dispatch on the night

**Splitting the delay:**

The delay is a good feature to help dispatch and have orders coming at the right time. But at the moment, the 4 options are a bit wide. It would be great to either have these split up in shorter periods (5min?) or have the possibility to manually say how much delay you want to implement.

**Visualizing better the pick up and drop offs:**

When clicking on a task, the tasks lights up on the map. It would be great to have a way to visualize both tasks when clicking on a pick up for example, so as to see directly where the drop off is.

**Switching zones more easily:**

Right now, changing zone is done per restaurant. When business is good and there might be more orders than people on the street to deliver them, have the possibility to switch zone in emergency. (Like a DJ controller panel, alongside the delay, there could be a button "switch to rush hour zone" in order to prevent courier from riding too far in a busy period.

**Comment by 552020** [comment]
It would be nice that the tasks when grouped has been shown by pick up time and not drop off time or at least to have the possibility to choose. Low priority.

**Comment by 552020** [comment]
It would be nice also to be able to assign the task per drag and drop without having to open the courier "box". Very low priority.

**Comment by Paul-Eraman-CoopCycle** [comment]
we did most of this, and the rest is on its way in other issues 🥳

**Comment by 552020** [comment]
I got a notification in GitHub since you Paul answered to this issue. I spent the last three years learning programming (still suck a it) but if there are some small issue I can contribute to solve I'm glad to help.

**Comment by Paul-Eraman-CoopCycle** [comment]
Hey, hows it going? Good to hear! Help is always welcome haha
Could you give me any more info about what types of things you might feel comfortable working on? Then I could pick some issues that fit in that box
