### ISSUE TITLE
Getting a 500 Server error when "Requesting a quote"

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1931]
Restaurant has this enabled: "This restaurant also accepts quotes (e.g.: catering)" 
User also is enabled to request a quote.

And in this screen here when click "Request a quote" 
![image](https://user-images.githubusercontent.com/51931067/99850925-26155680-2b76-11eb-83f2-6e521fa00879.png)

it returns this 
![image](https://user-images.githubusercontent.com/51931067/99850955-2e6d9180-2b76-11eb-9e3e-0b7eba8e8fae.png)

**Comment by ERAMANrepartos** [comment]
@alexsegura is this still the case?
