### ISSUE TITLE
Configure the additional time for ordering on a value over than 10 days

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1940]
**Describe the bug**
It's not possible to configure the additional time for ordering on a value over than 10 days

**To Reproduce**
Go to the restaurant configuration page -> Execution
Encode 10 (or more) days for the "Additionnal time for ordering"
Save the changes
See in Execution, the "Additionnal time for ordering" is changed

**Expected behavior**
Recording the additionnal time no matter how many

**Screenshots**
![bug](https://user-images.githubusercontent.com/44605344/100428189-e8439100-3093-11eb-94cb-e938d3a14880.gif)

**Comment by alexsegura** [comment]
We can't do this because the banking pre-authorization is no more than 7 days
