### ISSUE TITLE
Possibility to see all the accounts wit Resto-owner-rights for a certain restaurant

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1942]
To have a better overview how many accounts are connected with a restaurant and has resto owner rights for a certain restaurant it would be nice to see this information on the resto page. very low priority.

**Comment by ERAMANrepartos** [comment]
This already exists for stores, would be good for restaurants too

**Comment by Paul-Eraman-CoopCycle** [comment]
not prioritizing currently
