### ISSUE TITLE
Redesign of product basket

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1950]
Related to this: https://github.com/coopcycle/coopcycle-web/issues/1353#issuecomment-737464255

Possibly look into the way Deliveroo do it. On the app they have 2 general tabs `Delivery` and `Collection`. When either tab is clicked the whole website refreshes showing the Businesses that do delivery or collection, if they do both, the businesses are shown in both Delivery and Collection.

Maybe in the same pop-up where the user is prompted to input the address make it mandatory to choose "Delivery" or "Collection. Inputting address can stay the same, not mandatory. 
Something like this? 
![image](https://user-images.githubusercontent.com/51931067/100923755-96599b80-34d7-11eb-8044-bfce38be8429.png)
Deliveroo make it mandatory to input the address before seeing the businesses. (I think this was discussed at some point).

If the customer changes their mind, and they want to Collect their food instead of having it Delivered, Deliveroo's way of doing seems pretty cool.

When on the specific business homepage you have this option:
![image](https://user-images.githubusercontent.com/51931067/100924960-3fed5c80-34d9-11eb-8434-6b99bbcf8c47.png)

When you click `Change` you get this popup
![image](https://user-images.githubusercontent.com/51931067/100925035-58f60d80-34d9-11eb-826b-eecaacd3697e.png)

If that business doesn't offer "Collection" than it should still show but it should be disabled, not clickleabe. In the same popup maybe they can also change their address and timeslot. 

So instead of having this: 
![image](https://user-images.githubusercontent.com/51931067/100926227-fe5db100-34da-11eb-80ee-15851325b3c3.png)

we could have this:

![image](https://user-images.githubusercontent.com/51931067/100926279-17666200-34db-11eb-9199-04fa69d2a2b4.png)

**Comment by alexsegura** [comment]
Fixed in 021d19031bcdae9de8025147fa5b5d67dc6bdf7d

![cart_redesign](https://user-images.githubusercontent.com/1162230/111065479-ede1ad00-84b1-11eb-87e7-c959f613a59a.gif)
