### ISSUE TITLE
Allow restaurant owner to preview their restaurant on the homepage

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1957]
The same way admins can see a restaurant/business that is not "enabled" on the homepage, it would be good for restaurant owners to be able to see how the restaurant would look like for customers with products and description.

**Comment by alexsegura** [comment]
It used to be like this, but since 081a80060b0673472b6676c36dc4dad171ffea76, disabled restaurants don't appear anymore in lists. Doing this was causing a lot of problems. Restaurant owners can still access the restaurant page.
