### ISSUE TITLE
Allow assigning orders by introducing the option in the right-click context menu

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1962]
**In order to**  `achieve something`
In the dispatch map allow selecting 1 or multiple unassigned tasks and by doing right-click show in the context menu the option of "assigning" those tasks to a courier.

**Whereas currently** `this happens`
Currently, the only option in the right-context menu is "Cancel Taks"

**Additional context**

![image](https://user-images.githubusercontent.com/51931067/101420806-e0cd8480-38ea-11eb-9c35-6d7921ce89f6.png)

**Comment by rayon9coop** [comment]
Yes please, we'd be great fans too !

Actually, we think it would be useful to add functionnalities to those already present by using the right click, such as : 

- assign
- move to the day before, to today
- complete the task
- duplicate
- ... ?

**Comment by ERAMANrepartos** [comment]
@rayon9coop please make a specific issue requesting these features :)
I´m closing this issue since the main request is now implemented
