### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by rolandn** [coopcycle/coopcycle-web#1970]
Config' : Docker in Ubuntu 18
After "docker-compose up" , finish by :   

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/bin/console on line 16
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 255

And nothing at localhost:80

**Comment by airsay** [comment]
How did you go about installing? I'm a new user on Ubuntu and I've had a bit more success installing. Maybe I can share my experience with you. My install has had some issues with nodejs connecting to redis so the css and js functionality doesn't work yet

**Comment by munoztd0** [comment]
same here

**Comment by alexsegura** [comment]
Still an issue? Please reopen if so.
