### ISSUE TITLE
Show specific information on "Order status" in public links for orders placed through the External Form.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1984]
**In order to**  `achieve something`
Show each step a order goes through in the public link. 

**As a** `role`
The customer who received the email with their "Order status" in the public link benefits from actually seeing the **real** and accurate status of the orders.

**I want** `something to be added or changed`
In the public link, these following steps of an order should be displayed.
Please not the wording has been changed as well "Created `on`" instead of `at` and the `at` has been moved between the date and the time.
- **Created on** Dec 17, 2020, `at` 10:41 PM
- **Accepted on** Dec 17, 2020, `at` 10:56 PM
- **Collected on** Dec 18, 2020, `at` 10:00 AM
- **Delivered on** Dec 18, 2020, `at` 10:09 AM

**Whereas currently** `this happens`
Currently, no status is updated in the public link. It simply shows the "Created at" and nothing else when you execute the different steps of an order.

**Additional context**
Screenshots:

Email: it's nice it says, "to track the status of your order" but because the status isn't being updated, there is nothing really to track.
Additionally, there are no Email notifications for Collections and Dropoffs for orders placed through the External Form. I will make a separate issue for this.
![image](https://user-images.githubusercontent.com/51931067/102554045-e03ba780-40bb-11eb-994f-746700353a96.png)

Public link: the order in the screenshot has been Accepted and Collected but the status doesn't change, yes, the webpage has been refreshed. 
![image](https://user-images.githubusercontent.com/51931067/102554122-0c572880-40bc-11eb-9879-86f4e8075ccc.png)

**Comment by agichim** [comment]
Links with #1986

**Comment by ERAMANrepartos** [comment]
The problem is that not every cooperative may want this feature. Should be part of an overall assessment about what should be visible by default, what is customizable

**Comment by Paul-Eraman-CoopCycle** [comment]
repeat issue
