### ISSUE TITLE
Implement Email notifications for Pickup and Dropoff for Orders placed through the External Form.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1985]
Currently, when an Order that has been placed through the External Form does not send the customer an email notification that that order has been collected or delivered. 

The only Email notifications that the customer receives is when the Order has been created (by the customer) and when the coop has accepted the order.

A screenshot of the only email notifications that the customer receives from the Coop
![image](https://user-images.githubusercontent.com/51931067/102554540-f302ac00-40bc-11eb-8de4-8486cca3df1e.png)

**Comment by ERAMANrepartos** [comment]
Some clients dont want a thousand emails. A better solution may be having a page with a non-changing url for an order that shows the order status, much like food orders
