### ISSUE TITLE
Slight re-design of the public link for tracking Orders

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1986]
There should be 2 separate categories/boxes
- Order status
- Order summary
Order summary is not the same as Order status. So it can be a little bit confusing.

Order status is keeping track of what happens to your order, accepted, rejected, collected, delivered, etc.
Order summary is the list of items in your orders alongside the price.

Currently it is like this:
![image](https://user-images.githubusercontent.com/51931067/102556068-f186b300-40bf-11eb-9ffd-0fe8d1f347d5.png)

I suggest it could look like this:
![image](https://user-images.githubusercontent.com/51931067/102556086-fb101b00-40bf-11eb-8931-951de8422550.png)

On a different note, it would be better if the "blue line" that marks the "road" is better if it's removed completely, only showing the 2 pins.

**Comment by agichim** [comment]
See #2243 re the blue line.

**Comment by Paul-Eraman-CoopCycle** [comment]
we have a new redesign, closing as an old issue
