### ISSUE TITLE
Managing delivery capacity and planning

### ISSUE THREAD

**Issue by Doyoubouilloux** [coopcycle/coopcycle-web#1989]
As regards Foodtech plateform and as a delivery company, we want to be able to manage our delivery capacity and planning in order to avoid client deception et fail deliveries due to lack of human ressources.

1/ Restaurant that can handle their own timetable and agenda, we want being able to do the same for delivery feature.
> determine from witch day+time to witch day+time delivery is not available for all restaurants on the plateform
> Inform client that try to order with delivery "delivery is not available at this time because..." (the because... is fulfilled by the "purpose" of the "absence")

2/ Allocate delivery capacity on a time slot
> on this time slot "11h - 15h" we are able to handle "50" deliveries for instance
> When we reach the limit of the delivery capacity on a time slot, a message shall inform clients "all our delivery man/woman are busy on the roads delivering. Please choose another time slot for delivery or choose to click and collect your meal". Delivery is thus desabled.

**Comment by agichim** [comment]
Here is a related issue to yours #1580

**Comment by Paul-Eraman-CoopCycle** [comment]
we did this :)
