### ISSUE TITLE
Name + ID in task-list

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#199]
Instead of displaying the adress, print the Name and unique ID of the task for list-group-item. Keep the timescale.

**Comment by alexsegura** [comment]
"A task has no name", like Arya in Game Of Thrones. 

Should we add a field to briefly describe the task?
There is also a comments fields, which is unused at the moment.

**Comment by couleurmate** [comment]
I meant : the name of the task's location.

Eg : pickup#666 - Krusty Krab 
Rue de l'éponge 42

**Comment by couleurmate** [comment]
A field "Name" should be added for the creation of a delivery and a column "Name" for the csv import
