### ISSUE TITLE
Test + improve JS Symfony config parser

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#20]
There is a [ConfigLoader.js](https://github.com/coopcycle/coopcycle-web/blob/b8e13a27b22c543a63ec3d22d4e906d5676ab1cb/js/api/ConfigLoader.js) class which allows to parse `*.yml` in JavaScript like Symfony. 

It should be tested against a few use cases to make sure it works correctly.
Maybe even test it against the test suite used by Symfony?

Also, it has a few bugs, for example [it doesn't load numeric arrays correctly
](https://github.com/coopcycle/coopcycle-web/blob/b8e13a27b22c543a63ec3d22d4e906d5676ab1cb/pm2.config.js#L71)

**Comment by Atala** [comment]
Also it is to be used cautiously, as thing like `%kernel.logs_dir%` are not interpreted by JS program.

**Comment by alexsegura** [comment]
Not relevant anymore since everything is now loaded via env variables
