### ISSUE TITLE
In order to manage store holidays  As a admin I want to be abble to configure closing date for Stores.

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#2000]
Add the same concept of "restorants holiday" for stores.

Curently for stores that use the API when they close we must disable the order in woocommerce or change the Prior notice (hours) in the store configuration. (bad workaround because need to change it frequently during closing time).

If we can configure holidays for store ; the next delivery slot available is in the next opening date.

**Comment by AdrienSICKLO** [comment]
Should we close this one?

**Comment by PasLoin** [comment]
No it's still not possible to close temporaly a store with planning schedule

**Comment by ERAMANrepartos** [comment]
Now it is

**Comment by Paul-Eraman-CoopCycle** [comment]
not planned, stores dont need to be closed since they are private b2b entities. the customer just doesnt order those days
