### ISSUE TITLE
Order basket disappears with "Allow pre-ordering" unchecked and show message "Pre-orders is disabled".

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2004]
**Describe the bug**
Under a restaurant, if the option "Allow pre-ordering" is unchecked the order basket disappears when you click on the option to change the delivery time.
![image](https://user-images.githubusercontent.com/51931067/103386636-c062a580-4af7-11eb-814c-d59b5203c4b6.png)

After a few hours of this issue happening I can't reproduce it anymore. Continue reading the issue though.

**To Reproduce**

 These were the steps though:

1. Go into restaurant settings
2. Uncheck "Allow pre-orderind" 
![image](https://user-images.githubusercontent.com/51931067/103386660-d40e0c00-4af7-11eb-9418-6c46a12def30.png)
3. Save settings
4. Go to restaurant homepage
5. Click on the delivery time as if you were to change it
6. As soon as it's clicked it the whole basket section disappears.

**Expected behavior**
When "Allow pre-orderings" is unchecked somewhere on the resto homepage there should be some text saying "You can only order during the opening hours of the restaurant" or "This restaurant has disabled pre-orders".

**Comment by alexsegura** [comment]
Fixed in d9a4a7247ef00c082f7fd4bd67d31a2dd7a7b7dd
