### ISSUE TITLE
In order to keep access to my personal data, As a User I want the delivery co-op to be able to block orders without activating the maintenance mode

### ISSUE THREAD

**Issue by taratatach** [coopcycle/coopcycle-web#2006]
**In order to**  `keep access to my personal data`
Personal data includes addresses, invoices and being able to close the account.

**As a** `User`
Mainly users but the co-op and restaurants (or stores) could also benefit from this depending on implementation details (e.g. SEO, visibility…).

**I want** `the delivery co-op to be able to block orders without activating the maintenance mode`
As a user, I should be able to access my saved addresses, invoices and closing my account even if orders can't be placed (e.g. coursiers are on holidays).
Ideally, I would still be able to navigate the list of restaurants while not being able to place an order and I should see when the co-op plans to re-open (if such a data is defined).

**Whereas currently** `the delivery co-op has to activate maintenance mode`
Today, if a co-op wants to block orders (e.g. during holidays), their only option is to activate the maintenance mode which blocks users from accessing their data and the list of available restaurants.

**Additional context**
This is what a user has access to when the co-op coursiers are on holidays at Sicklo!:
![Screenshot_2021-01-01 Sicklo](https://user-images.githubusercontent.com/580382/103443069-c6719700-4c5b-11eb-849b-879a78daa4f6.png)

**Comment by ERAMANrepartos** [comment]
To do this well we need to have global opening hours for the cooperative that are prioritized OVER the restaurant hours
