### ISSUE TITLE
Using GPLv3 library while beeing non-FLOSS

### ISSUE THREAD

**Issue by johanfleury** [coopcycle/coopcycle-web#2017]
Hello.

_Disclaimer: I have nothing against you using a non-FLOSS license (even if I think you should not state that your project is Open Source as other have expressed in #1908)_

I just wanted to let you know that your project is using a GPLv3 licensed library: `@4tw/cypress-drag-drop`) and that you might want to have a look at this.

According to the GPLv3 terms if your project “links” to a GPL licensed piece of software it could be considered a derivative work and be required to be licensed under a GPL equivalent license (which currently is not the case).

I’ve not dug too much into the source code so I don’t know to what extent this library is used in `coopcycle-web`, but you might want to pay extra attention to the licenses of your external dependencies.

**Comment by alexsegura** [comment]
Hi, 

This has never been actually used (75dda86232df7aeedfb97d25c64723eea9277345), so I removed it.
