### ISSUE TITLE
Allow administrators to complete a task

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#202]

**Comment by alexsegura** [comment]
Deleting a task is possible with #200

**Comment by Atala** [comment]
? I didn't see it while reviewing the PR. How would you do it?

**Comment by alexsegura** [comment]
Only unassigned tasks can be deleted. 

<img width="615" alt="capture d ecran 2018-02-13 a 12 13 15" src="https://user-images.githubusercontent.com/1162230/36147121-4d4284b2-10b7-11e8-9d24-251c7c09e30c.png">

**Comment by Atala** [comment]
Oh ok.. Maybe a disabled button + tooltip "Only unassigned tasks can be deleted" for assigned tasks?

Can you updat ea task status somehow from the dashboard?

**Comment by alexsegura** [comment]
Ok, I can do this.

**Comment by alexsegura** [comment]
I believe this is already fixed.
