### ISSUE TITLE
Re-enable CSRF on embed forms

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2022]
Since we can now use `SameSite=None, Secure` (47292a0b4fbfd667f230695eff31c77e499ee4ca), we can now re-enable CSRF (#735)

**Comment by agichim** [comment]
Does this take too much time to do? We have a potential restaurant we could work with and they asked if customers could buy straight from their website.

**Comment by alexsegura** [comment]
Seems it's broken again. Maybe it's due to some changes in Symfony. 

- symfony/symfony#44541
- symfony/symfony#44518

**Comment by alexsegura** [comment]
Colsing in favor of #3082 3084
