### ISSUE TITLE
Add "Deliveries" button in the Store settings section 

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2023]
Please add a button titled "Deliveries" which takes you to see the deliveries of that specific store, where the red mark is in the screenshot,

![image](https://user-images.githubusercontent.com/51931067/103813156-880f1a00-5057-11eb-9432-bd6d5184af0f.png)

**Comment by alexsegura** [comment]
Obsolete since fc5b85df4412fc71ff6f15fee0551f05b3b6f389
