### ISSUE TITLE
In order to print from desktop browser As a restaurant I want to have a new printing template for orders

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#2028]
I want to print from a desktop browser in the same format as in the application (prettier and more understandable).

Currently, the browser prints the entire page and doesn´t understand how to print many features.

These are to be printed to a receipt printer, just like in the app.

**Comment by ERAMANrepartos** [comment]
This is an interesting feature because the navigator doesnt break at the volume that the app breaks at, but people need the app to print tickets.

**Comment by Paul-Eraman-CoopCycle** [comment]
not something we want to support
