### ISSUE TITLE
Make it clear that shop/restaurant test orders, made when the platform isn't live, are test orders.

### ISSUE THREAD

**Issue by Pidgeon45** [coopcycle/coopcycle-web#2040]
In order to avoid confusion between live and test orders, visually flag test orders in some way.

For the benefit of admin, I want a visual flag/demarcation/separation between orders made when the platform is NOT in live mode. 

At the moment there is no information on platform to inform admin whether a order was made in live mode or whether it was a test order.

**Comment by ERAMANrepartos** [comment]
also in the excel export later
