### ISSUE TITLE
In order to choose the good option As a customer I want to be able to zoom product picture

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2041]
**In order to**  `choose the good product option`
We have a restaurant that sells lots of different pastas. Customer may not know every one. Thus we uploaded a schema of all pastas to help customer choose his favorite one.

![Screenshot from 2021-01-16 09-05-50](https://user-images.githubusercontent.com/11749973/104806883-f16ef580-57da-11eb-87bc-f8fc82c6bf3a.png)

**As a** `customer`
Mostly for customer

**I want** `to zoom product picture`
When clicking product picture, I want picture to widen to see it more comfortably and be able to choose the good pasta between the various available.

**Whereas currently** `this happens`
When clicking product picture, product is added to cart.

**Additional context**

![Screenshot from 2021-01-16 09-05-41](https://user-images.githubusercontent.com/11749973/104807027-e4063b00-57db-11eb-993a-378e8ff3db93.png)

**Comment by m09** [comment]
I second this one, it seems shops have pretty nice pictures of their food but we cannot zoom on them.

**Comment by Paul-Eraman-CoopCycle** [comment]
we have redone this page, old issue, closing
