### ISSUE TITLE
date with hour in command instructions

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2049]
**In order to**  `achieve something`
A clear description of a goal you want to archive
When restaurants open coopcycle for a new command from the alert mail, they received that :  
![image](https://user-images.githubusercontent.com/43618873/105061467-d40b8700-5a79-11eb-8f65-315fc357ab24.png)
and delivery day doen't appear. In this exemple command was made today ( tuesday ) 1:30pm and a delivery for thursday. But restaurants officers think it's for the next 12:45 and prepar command to the wrong date.

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software
With the preparation hour, add the date.

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by TheoPatros** [comment]
Maybe linked to #2066 ?

**Comment by ERAMANrepartos** [comment]
This would be useful, and since it is easy, we should do it ASAP. However, #3618 has a more detailed proposition

**Comment by Paul-Eraman-CoopCycle** [comment]
Closing due to repeat of 3618
