### ISSUE TITLE
Not accepting valid addresses, changing imported addresses, and setting incorrect pin locations

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2052]
**Describe the bug**
Related to this thread: https://coopcycle.slack.com/archives/C4UT4DGQ3/p1607103698041900?thread_ts=1605512422.278800&cid=C4UT4DGQ3

With the change of Geo-coding/autocomplete providers, there are a lot of addresses that are either not recognized, or put pins in the wrong location.
Our warehouse (1441 Powell St) is one of these addresses. The address is in OSM, so that shouldn't be the issue.

With this, we have been doing manual work-arounds to notify our couriers of the actual address, but we need to have addresses correctly recognized and working for stores and shops/restaurants.

**To Reproduce**
1. Go to admin dashboard and try to create a new order or enter address on customer ordering page
2. Try to enter "1441 Powell St, Vancouver, BC" or "968 Kingsway, Vancouver, BC" or "1056 Comox St" as an example
3. See error - unable to select the address, only shows saved addresses.

**Expected behavior**
When an address like 1441 Powell St is entered, it will put a pin in the correct location and accept the address as worked a few months ago.

**Screenshots**
![Screenshot from 2021-01-21 07-48-35](https://user-images.githubusercontent.com/64277836/105374970-1ee1e780-5bbd-11eb-826a-e741096b0fe3.png)

Desktop - multiple browsers and OS

**Additional context**
This is a blocking bug, preventing us from onboarding any further stores/shops until it can be fixed.
@alexsegura

**Comment by joel-shiftdelivery** [comment]
@alexsegura 
It seems Geocode.Earth is a (main?) provider for addresses, but addresses such as 968 Kingsway show up in Geocode.earth, but are not found in CoopCycle.

There are still huge numbers of addresses missing in Geocode.earth (such as 390 Industrial Ave or 1067 Marinaside Cres), but it has more addresses than show/are accepted in CoopCycle

**Comment by joel-shiftdelivery** [comment]
This is a list of some addresses not showing in CoopCycle. Any and all of the addresses should be able to auto-complete (with "Vancouver, BC" automatically added on the end)
1445 Powell  or 1445 Powell St
1067 Marinaside or 1067 Marinaside Cres or 1067 Marinaside Crescent
1111 Marinaside or 1111 Marinaside Cres or 1111 Marinaside Crescent
1099 Marinaside or 1099 Marinaside Cres or 1099 Marinaside Crescent
188 Aquarius or 188 Aquarius Mews
1056 Comox or 1056 Comox St
720 W 8th or 720 W 8th Ave or 720 west 8th or 720 West 8th Ave
1455 E 3rd or 1455 E 3rd Ave or 1455 East 3rd or 1455 East 3rd Ave
2575 Commercial or 2575 Commercial Dr
2586 Commercial or 2586 Commercial Dr

1600 Beach Ave is a weird one - it has 3 buildings at the same address, so sometimes a letter is added to tell which building. Currently only the generic 1600 Beach works correctly, but not the following:
1600M Beach or 1600 M Beach or 1600M Beach Ave or 1600 M Beach Ave
1600D Beach or 1600 D Beach or 1600D Beach Ave or 1600 D Beach Ave
1600L Beach or 1600 L Beach or 1600L Beach Ave or 1600 L Beach Ave

**Comment by joel-shiftdelivery** [comment]
@alexsegura 

Two more missing addresses we came across the other day:

146 west 13th ave or 146 w 13th ave or 146 west 13th or 146 w 13th
4655 Valley Dr

**Comment by joel-shiftdelivery** [comment]
@alexsegura
Some more addresses that do not work properly in coopcycle. These are the ones that are reported, byut

2285 West 16th Ave
2638 Hemlock St,
2298 McBain Avenue
404 East Pender St
2380 West 8th Ave
337 Gore Ave

On a likely related note:
When we import a spreadsheet, 1423 Continental St shows up in Redding, California for some reason, instead of Vancouver (see image). However, when manually creating a delivery with that address, it correctly populates to Vancouver.

![Screenshot from 2021-05-03 03-58-00](https://user-images.githubusercontent.com/64277836/116868583-e2625680-abc3-11eb-9cf1-5f46a0cac6fb.png)

**Comment by joel-shiftdelivery** [comment]
Doing a trial import from a store today.

Here was the addresses that were imported:
![Screenshot from 2021-05-07 02-10-49](https://user-images.githubusercontent.com/64277836/117427501-f49d0700-aed9-11eb-8db3-4031b8beb0b6.png)



Here is what ended up in CoopCycle Admin Dashboard:
![Screenshot from 2021-05-07 02-10-59](https://user-images.githubusercontent.com/64277836/117427518-fa92e800-aed9-11eb-8608-0d798c749abf.png)
![Screenshot from 2021-05-07 02-11-13](https://user-images.githubusercontent.com/64277836/117427528-fbc41500-aed9-11eb-937e-f75539876070.png)


Both pins were put in the exact same spot, a few blocks away from the addresses that were imported, and on the wrong side of the street.

![Screenshot from 2021-05-07 02-17-37](https://user-images.githubusercontent.com/64277836/117427980-73923f80-aeda-11eb-906e-cc4015dcc7fe.png)

**Comment by joel-shiftdelivery** [comment]
As it seems like this is primarily an issue with the geocoding service, here are some options I have found that seem to be much more reliable at geocoding addresses in Vancouver (testing a few addresses anyway), while costing $450/month per million transactions or less. ($.45 per 1000).

HERE (formerly owned by Nokia): https://developer.here.com/pricing
Geoapify: https://www.geoapify.com/
Geoconcept: https://en.geoconcept.com/geoptimization-apis
TomTom: https://www.tomtom.com/products/

**Comment by ERAMANrepartos** [comment]
Fixed by using google maps, which sucks, but is unfortunately the best way to resolve these problems
