### ISSUE TITLE
Normal 10 digit phone numbers not accepted when placing an order

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2053]
**Describe the bug**
When entering a phone number as a customer placing an order, the phone number is not accepted unless it includes the "+1" country code before the phone number.
Canada/US never includes country codes when entering a phone number, just the 10 digit phone number.

**To Reproduce**
1. Go to a restaurant and attempt to place an order
2. When entering the Phone number, entering a phone number in any regular fashion (5555555555, 555-555-5555, 1-555-555-5555, etc) and clicking order, the phone number is erased with the error "This value should not be blank"
3. The only way around this is to enter "+1" country code before the phone number. This is never done normally in Canada/US, so is a significant bug.

**Expected behavior**
Any form of a 10 digit phone number, with or without country code, should be accepted: 5555555555, 555-555-5555, 1-555-555-5555, (555) 555-5555, +15555555555, etc.

**Screenshots**
![Screenshot from 2021-01-21 08-13-15](https://user-images.githubusercontent.com/64277836/105378323-8ea5a180-5bc0-11eb-9e62-c5f5a1c40082.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Brave, Firefox (probably all)]

**Smartphone (please complete the following information):**
 -Haven't tested on smartphones yet

**Additional context**
In Canada/US, phone number are not written with a country code, and if they are, it is just a "1" and not "+1". Because of this, any field for phone number should accept any 10 digit number.

**Comment by TheoPatros** [comment]
For anyone wanting to address this issue: https://www.itu.int/oth/T0202.aspx?parent=T0202

It looks pretty up to date (at least for Canada: informationss date from 2018)

**Comment by joel-shiftdelivery** [comment]
> For anyone wanting to address this issue: https://www.itu.int/oth/T0202.aspx?parent=T0202
> 
> It looks pretty up to date (at least for Canada: informations date from 2018)

I think it's even simpler than that: Just remove validation of the phone number, other than ensuring it is 10 or 11(if country code included) numbers.

Also, I forgot to mention, this was previously working, and I'm not sure what/when something was changed that created this bug.

**Comment by joel-shiftdelivery** [comment]
@alexsegura 

This is still an issue for checking out in a restaurant. I believe it was fixed for stores from the slack thread below. Can we do the same for restaurant checkout?

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1616698704060700?thread_ts=1616607359.048500&cid=C4UT4DGQ3

**Comment by alexsegura** [comment]
Sorry for this odd bug. Actually, we were using the region code (`CA-BC`) instead of the country code (`CA`), and `libphonenumber` didn't match anything ☹️

However,  `5555555555` is definitely not a valid phone number, use `5062345678` for example to test.
