### ISSUE TITLE
Changing informations client

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#2063]
**Describe the bug**
Clients cannot update their information when they have a account. Number phone or email. 

**Expected behavior**
Important they can manage it because it creates problems when you try to contact them at dispatch or messenger.

**Additional context**
I add an other problem link : when clients are not users (suscribe on the platform) and order they can't follow their state order so it create a lot of call on dispatch and when you are late some of them think it didn't work. I think really important they know when it's accept by the restaurant, pickup by the messenger and finish complete) with receipt of the order.

**Comment by ERAMANrepartos** [comment]
Is this still true @TifaineSicklo ?

**Comment by alexsegura** [comment]
> when clients are not users (suscribe on the platform) and order they can't follow their state order so it create a lot of call on dispatch and when you are late some of them think it didn't work. I think really important they know when it's accept by the restaurant, pickup by the messenger and finish complete) with receipt of the order.

This is fixed.

**Comment by alexsegura** [comment]
Allowing to change phone number would be easy.

**Comment by Paul-Eraman-CoopCycle** [comment]
have we done that ?

**Comment by vladimir-8** [comment]
We are working on a fix for two issues related to phone numbers:

- https://github.com/coopcycle/coopcycle-web/pull/4767
- https://github.com/coopcycle/coopcycle-web/issues/4797

Please re-open this issue if you see other cases when it fails
