### ISSUE TITLE
Confusing email information

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2066]
**Describe the bug**
When restaurant owner receives a new order email, information displayed confuses him as it indicates "Preparation at 11:21" while it's the time the customer took the order.

**To Reproduce**
1. As a customer place an order to a restaurant you own
2. Check your emails
3. See error

**Expected behavior**
Display more (or more useful) information. Among others what is expected by customer : 
* **Date and time of preparation** cause they thought order was for today while it was for next day
* **Customer name** as it is most of the time the way to identify an order
* **Order number** as it is another way to identify an order

**Screenshots**
This order was taken on January 26th at 11:21 for a delivery on January 27th between 20:20 and 20:30.

The email the restaurant received :
![Screenshot from 2021-01-26 15-33-59](https://user-images.githubusercontent.com/11749973/105858736-f22e3580-5feb-11eb-81ae-a3ba5584064d.png)

The actual delivery : 
![Screenshot from 2021-01-26 15-36-10](https://user-images.githubusercontent.com/11749973/105858976-46d1b080-5fec-11eb-9d2f-d3e2568b24b0.png)

**Desktop (please complete the following information):**
- All

**Smartphone (please complete the following information):**
 - All

**Additional context**

**Comment by TheoPatros** [comment]
Maybe linked to #2049 ?

**Comment by biologeek** [comment]
Hi @TheoPatros, it is kinda related yes. After checking with the restaurant, there are some more places where the date should be added. Some days ago they prepared a meal that was ordered for the next day cause they didn't have the day on the order page.

**Comment by damienlapoitavelo** [comment]
I thought the problem was solved when the staff of a restaurant said me the day appears inside order details. It was about 10 days after I reported it on github ( probably last february ). But since few weeks, the precision of the day inside order details has disappeared. Why ? I'm obligated to call restaurant every time orders are for another day than today.

**Comment by biologeek** [comment]
Maybe a regression. @alexsegura  what do you think about that ?
