### ISSUE TITLE
Order cancelled problem

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#2081]
**Describe the bug**
The client called to cancel the order, so the dispatch canceled it. Dispatch refuse the order and justify "ask by the client". Next morning the order appear on the administration panel and the client has the notification that the restaurant prepare it.

![6030d4bf-6f20-4681-98e6-5b0db9d780f7](https://user-images.githubusercontent.com/59088580/106581046-b7278700-6542-11eb-8f89-8dc83c77519c.jpg)
![Inkedcommande 15WW_LI](https://user-images.githubusercontent.com/59088580/106581052-b7c01d80-6542-11eb-98cb-72c55187c1cb.jpg)
![Inkedliste des commandes_LI2](https://user-images.githubusercontent.com/59088580/106581054-b8f14a80-6542-11eb-9f83-3536c1ef84c4.jpg)
![Inkedpanel administration_LI](https://user-images.githubusercontent.com/59088580/106581058-b8f14a80-6542-11eb-9ff9-96e0d03a79d0.jpg)

**Comment by ERAMANrepartos** [comment]
@TifaineSicklo Has this happened repeatedly?
