### ISSUE TITLE
In order to promote the way your contribute to the digital commons, I suggest avoiding the use of "open source" in the project description

### ISSUE THREAD

**Issue by bzg** [coopcycle/coopcycle-web#2091]
Thank you very much for your work on Coopcycle!

AFAIU, the Coopcyle source code belongs to the "software commons": it is the result of a collective effort and it is reusable for those who respect some conditions.

"Software commons" is larger than just "free software", which need to be licensed under a FSF- and OSI-approved license.

Since the term "open source" was coined in the late 90', many people got confused: is "open source" the same thing as "free software"? The basic answer is yes, "free software" and "open source software" both refer to the very same set of software, but the expressions have different connotations.

I am not sure if everyone is aware of it, but many hacktivists spend an awful lot of time fighting this confusion, a time that we'd rather spend on fixing bugs.

Today, we see another kind of confusion: it's not about two expressions referring to the same thing, but about a single expression referring two different things.

Indeed, "open source" is sometimes used to refer to software commons that are not licensed under a FSF- or OSI-approved license. Why? My guess is this: for the people using this expression in this liberal way, "open source" first and foremost refers to a movement, perhaps an attitude, rather than just... source code.

E.g. there is this recent announcement of ["a New Kind of Open Source Organization"](https://ethicalsource.dev/blog/oes-announcement) promoting licenses that are not open source, strictly speaking.  If the idea was to redefine what "open source" should mean then the title should have been "a New Kind of Open Source". But as it reads now, it looks like there is a new organization within the realm of what "open source" _currently_ means, which is set by the [open source definition](https://opensource.org/osd).

Similarily, Coopcycle presents itself as "open source", as previously noted in [this past (and closed) issue](https://github.com/coopcycle/coopcycle-web/issues/1908): but it is not available under an open source license, so... it's confusing. 

This confusion hurts in two ways: it hurts the free software movement because it makes the task of those trying to clarify things a bit more difficult. And, in the long run, **it also hurts the movement of those who want to promote other approaches of software commons**, because it makes their distinct voice inaudible, it merges their cause into that of "open source".

So, in general, I suggest to use "open source" the way it is defined and commonly used and to avoid it in Coopcycle presentations.

Perhaps you can coin another term to refer to what you stand for?

Let me know what you think!

**Comment by alexsegura** [comment]
The terms "open source" and "free software" are nowhere to be found in the source code of this repository, nor in the project description

> many hacktivists spend an awful lot of time fighting this confusion, a time that we'd rather spend on fixing bugs

Yes, I'll be waiting for your contributions.
