### ISSUE TITLE
Add checkbox to select multiple orders

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2094]
Add a column with checkbox where when selected, multiple checkboxes, orders can be accepted or rejected at the same time, without having to open each order.

![image](https://user-images.githubusercontent.com/51931067/107088456-de0ce400-67f4-11eb-88c9-d307e112defd.png)

**Comment by ERAMANrepartos** [comment]
Maybe should be a button not a check box

**Comment by Paul-Eraman-CoopCycle** [comment]
Repeat, closing
