### ISSUE TITLE
Enable "editing" billing information for customers

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#2110]
Currently, clients cannot "edit" facturation information during the order. 
It's by default delivery adress and name of the person who order.
We have a lot of corporate client who wish to have billing information with their company.
Ideally, they should be able to edit billing information (different from delivery information) during the check out.

THank youuuu

**Comment by ERAMANrepartos** [comment]
This is a larger ERP issue that currently is addressed by the fact that invoices are made manually, and when this is no longer the case, will be dealt with as a part of that new feature
