### ISSUE TITLE
Put the restaurant phone number in pickup task details

### ISSUE THREAD

**Issue by vdegove** [coopcycle/coopcycle-web#2118]
**In order to**  contact easily restaurant, and send automatic SMS notifications for pickup time to restaurants through the Pedalo synchronisation,

**As a** `dispatch/admin

**I want** the restaurant number to be added in the phone section of the pickup task, in the admin dashboard, accessible too through the API. This number would just be a copy of what is displayed for the restaurant.

**Whereas currently** the field is left blank, and we don't send any SMS notification to the restaurant.

**Comment by alexsegura** [comment]
1/ Add a migration to copy the existing phone numbers from the restaurant object to the address object (there is a phone number on both). 
2/ Copy the phone number from the restaurant to the address on updates. This could be done with a Doctrine listener before update, like in [AddressListener](https://github.com/coopcycle/coopcycle-web/blob/1c2f6ce5e9ba03c32db19a20f099252710e28211/src/Entity/Listener/AddressListener.php)

**Comment by ChloeOLVO** [comment]
1/ Keep the restaurant number "public" (available on the website for clients)
2/ Add a field for the restaurant phone number related to the address object

![image](https://user-images.githubusercontent.com/74653993/109166068-94247780-777c-11eb-8efe-a1a1d9aa5db9.png)

**Comment by ChloeOLVO** [comment]
Hey, @vdegove and @alexsegura  : is it now ok if I ask restaurants to put their phone number so that they receive notification for food pick-up?
