### ISSUE TITLE
Allow to put 2 criteria for delivering parameter: zone + a number of km around the restaurant

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#2119]
The idea is:

    To have a zone for delivery (no "drop off adress" outside of this zone) = Paris intramuros (more or less)
    Only enable for restaurants inside this zone delivery for drop off adress inferior to X km (here on RESTO.PARIS it's 4km)

Je le mets aussi en français: En gros l'idée c'est d'avoir une double condition pour la livraison: Une zone + un nombre de km max autour du restaurant. L'idée c'est qu'un restaurant en limite de zone, avec un périmètre de 4km max pour la livraison, ne puisse pas avoir une commande hors de la zone générale.
Exemple: un restaurant porte d'Aubervilliers (à la limite de Paris), s'il y a une commande 4km au sud vers le canal Saint Martin c'est ok, mais s'il y a une commande 4km au Nord au fin fond d'Aubervilliers on ne veut pas que ça soit possible

**Comment by AdrienSICKLO** [comment]
@alexsegura  this is already possible, should we close it?
