### ISSUE TITLE
In order to manage multiple hub As a Store I want the system choose pickup hub depending of dropoff location

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#2133]
For a store that send us delivery with the API ; adding the possibility to manage multiple hub (pickup)

As a Store manager and Admin allow to configure the automatic choose of witch hub to use ; depending on a Zone and adress of dropoff. 

The pickup location is automaticly generated and the information is send back thru the api to the store to suply the hub with stock.

**Comment by ERAMANrepartos** [comment]
This issue is unclear, and also seems to be outside of the current scope of the coopcycle project. If not so, please reopen the issue and clarify the enhancement being requested @PasLoin
