### ISSUE TITLE
Width of side panel should stay fixed 

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#216]
![side_panel](https://user-images.githubusercontent.com/1162230/36313740-d09e4850-1332-11e8-8dde-0c6ab8874b16.gif)

**Comment by couleurmate** [comment]
And responsiveness 
![screenshot_20180219-093607](https://user-images.githubusercontent.com/13315760/36368636-7b4519a6-1558-11e8-93e3-7d3b452171f4.png)

**Comment by Atala** [comment]
@couleurmate : it is a completely different issue

Do you think it is important (i.e. access to the dashboard from your phone) and should be prioritized?

**Comment by alexsegura** [comment]
The dashboard is not really intended to be used on a mobile phone 😐
