### ISSUE TITLE
Enable restaurant to create "set menu" (formules)

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#2174]
Issue: Currently, restaurant cannot create a "set menu" (breakfast set menu "formule petit déjeuner" for instance) with the products they have already created. They need to create a product called "Set Menu" and then add option (which stand for products)..
1/ It creates complexity for parameters and add work for restaurants
2/ It is more complex this way for restaurants to follow stock products and statistics of products consumption. Indeed, if they have a product "set menu", they don't see in statistics what has been most ordered for instance.

Proposal: Enable restaurant to create "set menu" with already existing products
a) In the restaurant parameters, next to "products", "option" etc. There would be a "set menu" (formule).
b) in this set menu you shall be able to add existing product (but not the price associated)
c) set up a price for this "set menu"
d) add existing option as well to this set menu.
e) being able to add this set menu within a "menu section" (it would then behave like a product when added in the menu section)

**Comment by ERAMANrepartos** [comment]
https://github.com/coopcycle/coopcycle-web/discussions/3621
