### ISSUE TITLE
Enable GDPR consent for customers

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#2175]
Issue: Client's data cannot be used by delivery companies since they don't give their GRPD consent while ordering on the plateform. This data could really be usefull to send client satisfaction survey, contact specific clients as regards their preferences and reward them or propose them services that correspond to their needs (i.e. clients who make big orders, or order all the time at the same restaurant)

Proposal: 
a) Add GRPD consent in the client ordering process before they proceed to payment
b) Enable admin to have access to client database with the following datas:
- Number of order per week
- Name of the restaurants in which they ordered
- Date of the last order
- Average prices of ordered passed on the plateform
c) Give the possibility to activate an email sent to the client after the order is "completed" (terminée) in which the admin car add a link with a client satisfaction survey.

**Comment by agichim** [comment]
Important regarding cookies. The user needs to be able to **Accept** or **Decline** cookies.

See https://noyb.eu/en/noyb-aims-end-cookie-banner-terror-and-issues-more-500-gdpr-complaints
And this: https://www.cnil.fr/fr/cookies-et-autres-traceurs-la-cnil-publie-des-lignes-directrices-modificatives-et-sa-recommandation
