### ISSUE TITLE
Entity ApiUser should be called User

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#218]
Simple, beautiful

**Comment by johnnybigoode** [comment]
Oh hi. 

This seems easy enough, I think. 

Something like a search and replace?

![image](https://user-images.githubusercontent.com/2698584/93718831-f71e3c80-fb54-11ea-9cc3-7a9d7e064bef.png)

Thing is, I get some errors when running the tests:

```
WARNING: The S3_CREDENTIALS_KEY variable is not set. Defaulting to a blank string.
WARNING: The S3_CREDENTIALS_SECRET variable is not set. Defaulting to a blank string.
WARNING: The S3_REGION variable is not set. Defaulting to a blank string.
```
 
And then it just crashes

```
In ToolsException.php line 34:
                                                                                                              
  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE craue_config_setting (n  
  ame VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY  
  (name))':                                                                                                   
                                                                                                              
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists' while executin  
  g DDL: CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, v  
  alue VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))                                                          
                                                                                                              

In AbstractPostgreSQLDriver.php line 70:
                                                                                                              
  An exception occurred while executing 'CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, sect  
  ion VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))':                        
                                                                                                              
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists                  
                                                                                                              

In PDOConnection.php line 91:
                                                                                              
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists  
                                                                                              

In PDOConnection.php line 86:
                                                                                              
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists 
```

What am I doing wrong? =(

**Comment by alexsegura** [comment]
Yes, search and replace should work haha 🙂  
However, the table in database can't be named `user`, because it's a reserved Postgres keyword.

**Comment by alexsegura** [comment]
About the errors: how are you running the tests? Locally, the tests are supposed to be launched against a running Docker machine. Do you have the Docker machine running?

**Comment by johnnybigoode** [comment]
Oh, for some reason I thought they'd be separated...

I'm having problems with minio.

This is the result](https://pastebin.com/raw/0hfMmSeX) of `docker-compose ps`

So I'll need to get their ID with ´docker ps -a´ , [that prints everything.](https://pastebin.com/raw/WjLMejYF) so I can get their logs:

minio/mc 

<pre>mc: &lt;ERROR&gt; Unable to initialize new alias from the provided credentials. Get http://minio:9000/probe-bucket-sign-w009v1iz6yxa/?location=: dial tcp: lookup minio on 127.0.0.11:53: no such host.
</pre>

minio/minio
<pre>
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters</pre>

Maybe I need to set specific credentials? Any ideas?

**Comment by johnnybigoode** [comment]
So I also noticed this:

```
WARNING: The S3_CREDENTIALS_KEY variable is not set. Defaulting to a blank string.
WARNING: The S3_CREDENTIALS_SECRET variable is not set. Defaulting to a blank string.
WARNING: The S3_REGION variable is not set. Defaulting to a blank string.
```
I realized that the values from .env.dist weren being loaded because it was not .env

So now I can get the dockers to work =D

The tests are running too! Awesome. 

Do you have suggestions about naming the user table on postgres?

**Comment by alexsegura** [comment]
The problem with Minio should be fixed in 0f69ea303be0d64b42386a775b433c6026e7b3ba

**Comment by alexsegura** [comment]
> Do you have suggestions about naming the user table on postgres?

Honestly, I would just let it like this atm. As it is defined in the [table attribute](https://github.com/coopcycle/coopcycle-web/blob/0f69ea303be0d64b42386a775b433c6026e7b3ba/src/Resources/config/doctrine/ApiUser.orm.xml#L3), it can stay like this.

**Comment by johnnybigoode** [comment]
So, minio-mc still complained about it, but it [returned successful](https://pastebin.com/raw/ssd6XcXq) for the bucket creation. So that's a non-issue atm #?

So the first step would be to run the tests after creating the test database.

`make phpunit`

Returned 

```
OK, but incomplete, skipped, or risky tests! Tests: 357, Assertions: 953, Skipped: 2.
```
The offending tests do not use User:

```
There were 2 skipped tests:

1) Tests\AppBundle\Entity\Sylius\ProductTest::testSetReusablePackagingThrowsLogicException

/var/www/html/tests/AppBundle/Entity/Sylius/ProductTest.php:15

2) Tests\AppBundle\Sylius\Taxation\Resolver\TaxesInitializerTest::testUpdatesRate

/var/www/html/tests/AppBundle/Sylius/Taxation/TaxesInitializerTest.php:54
```
then

`make behat`
```
--- Failed scenarios:

    features/deliveries.feature:783
    features/orders.feature:302
    features/orders.feature:562
    features/restaurants.feature:22
```

Should I be worried?

`make mocha`

`10 passing (17s)`

Welp, at least one is fully passing.

**Comment by alexsegura** [comment]
PHPUnit just says that some tests have been skipped, it's "normal". 

Can you create a pull request with your changes? It will run the whole suite on Travis, we will see better.

**Comment by johnnybigoode** [comment]
I made the pull request @ #1742
