### ISSUE TITLE
German Translation: "Confirm Email" button has wrong label

### ISSUE THREAD

**Issue by oracle2025** [coopcycle/coopcycle-web#2192]
**Describe the bug**
I got the 

**To Reproduce**
1. Go to 'https://kolyma2.coopcycle.org/register/'
2. Select Language "Deutsch" (Germans) andFill out Sign Up Form
3. Wait for the confirmation email to arrive
4. See Button Labeled "E-Mail wiederholen"

**Expected behavior**
The Confirm Email Button should be labeled "E-Mail bestätigen"

**Screenshots**
![Bildschirmfoto 2021-03-14 um 19 38 35](https://user-images.githubusercontent.com/111086/111080360-6bcba580-84fe-11eb-9d4b-b46dba20526f.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox

**Comment by alexsegura** [comment]
Hi @oracle2025 thank you for reporting this. 

Can you use our crowd translation tool to make the change directly? 🙂 
https://translate.coopcycle.org/translate/coopcycle/emails/de/?checksum=ca65302a7873f97b

No need to register, you can suggest a translation, and I will accept it.

**Comment by oracle2025** [comment]
Done 👍

**Comment by alexsegura** [comment]
Fixed in 46a93025416a39de5aa3ea54d7baed80f130fae1

Thank you @oracle2025
