### ISSUE TITLE
Suggested username is longer than 15 character limit

### ISSUE THREAD

**Issue by oracle2025** [coopcycle/coopcycle-web#2196]
**Describe the bug**
When signing up, the system will suggest an username based on the email address, but the suggestion is longer than the 15 character limit for usernames, if the name in the email is longer.

**To Reproduce**
1. Go to https://kolyma2.coopcycle.org/register/
2. Enter Email address: "guenther.kastenfrosch@example.com"
3. Look at "Suggestion"
4. See that the suggested username "guenther_kastenfrosch" is longer than the 15 character limit for usernames

**Expected behavior**
I expect the suggested username to be within the 15 character limit

**Screenshots**
![Bildschirmfoto 2021-03-15 um 09 32 10](https://user-images.githubusercontent.com/111086/111125254-b5a1a380-8571-11eb-8167-1e973df23dc7.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox

**Comment by alexsegura** [comment]
Hi @oracle2025 thank you for spotting and reporting this 🥰

**Comment by oracle2025** [comment]
Thanks for the quick fix @alexsegura ☺️
