### ISSUE TITLE
Reorganize project layout

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#22]
I would suggest to move `js/app` to `assets/js/components` or `assets/js/scripts` and rename `js/api` to `api` , as it is not clear what does what in my opinion.

**Comment by alexsegura** [comment]
Yes, sure. 

I'm not a Webpack expert, I suppose how it is configured right now is not really following best practices. 

But right now the priority is to add [missing features](https://trello.com/b/1l2M4xBW/roadmap), I think the dev environment is stable enough. 
Make it work, then make it right. 
I have almost finished decoupling the e-commerce stuff from the logistics stuff (`opening-hours` branch), next week we can start prioritizing new features. 

Let's keep this issue open for later 😉

**Comment by Atala** [comment]
Agree.

The problem is not for webpack build. It is more that is difficult to understand for a new-comer to understand that the `js` folder contains both jsx components for the PHP website and independant Node apps.

**Comment by Atala** [comment]
Wont be done now, closing.
