### ISSUE TITLE
Allow different prices based on length of delivery time slot

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2204]
**In order to** provide more flexibility in our business offerings, and to better meet client needs, we would like to add a pricing configuration where we can set pricing based on how long of a time window is selected by a store/client.
Example:
1 hour delivery window  (9-10, 10-11, 11-12, etc) selected: $25 base rate
3 hour delivery window (9am-12pm, 12pm-3pm, etc) selected: $15 base rate
All day time window (9am-5pm, 9am-9pm, etc) selected: $8 base rate

**As a co-op** this allows us to offer more flexibility and options for clients, so we can better meet their timing needs. It also allows us to have a smoother onboarding process, without needing to ask as many question to figure out exactly what their exact timing needs are. We can instead onboard automatically, and they will be able to select from the range of time window options/prices depending on their changing needs.

This also allows us to price for inefficiency, as it is likely that shorter delivery windows mean less efficient routing (and therefore higher cost) whereas longer time windows allow us the flexibility to make things more efficient and provide a lower cost service.

**I want**
From the client's view when placing an order, maybe there is an additional dropdown menu allowing them to select the type of delivery window ("1 hour", "3 hour", "All day, etc). After they select an option, the current menu showing all the time window options will populate with the selected type of time windows, allowing them to specify the day and time.

For the admin's view, the setup could be included in the current pricing configuration and time slots system, or be located in a different place for configuration.
The rest of the pricing configuration would continue to be applied in addition to the base rate for time, as it currently does.

**Whereas currently** it is only possible to have a single base rate, even if we offer an "all-day" (9am-5pm) time window as well as shorter "rush" time windows (9am-12pm, 12pm-3pm, etc), because the only pricing for time is based on how far in advance an order is placed, not how quickly an order needs to be delivered after it is picked up.

The work-around we have for this is to have multiple stores for the same client, but that is cumbersome and very annoying for the client.

**Additional context**
Here is an example of pricing we have previously used for manual order requests:
![Screenshot from 2021-03-17 15-44-41](https://user-images.githubusercontent.com/64277836/111548352-cf8ce300-8737-11eb-9fe7-8e3c24da6675.png)

**Comment by ERAMANrepartos** [comment]
In general we have to completely rethink how prices are created and presented to the client

**Comment by ERAMANrepartos** [comment]
We actually have this now 🥳 
You can make a price rule that looks at time range as a factor
