### ISSUE TITLE
Import is too slow and may timeout if > 50 tasks

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#222]
Reported by Raphael

**Comment by alexsegura** [comment]
This is due to geocoding. 
First, we can increase the max execution time as a quick workaround. 
Then, it would be cool to have some queue system to perform long running tasks.

**Comment by alexsegura** [comment]
I couldn't reproduce it locally, can you?

**Comment by alexsegura** [comment]
Would be fixed by #721
