### ISSUE TITLE
Improve hubs UI/UX

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2242]
- [x] Allow enabling/disabling hub (8f3fd0f9440a7b40a309f93fa423cdec8fbb848c)
- [x] Add separators for each vendor when serializing order as text (6981e8ff764638e93573d611015fb271fd18ae85)
- [x] Allow vendors to view hub orders in the app ⚠️ (127e1385330ae4c7c9352303ca635517e6ad9cff)
- [x] Suggest other restaurants on checkout summary page (aafaf44614318541cf2c6e2d629d39e4d7b81679)
- [ ] Add banner on restaurant page about hub
- [ ] Allow adding text to describe the hub, improve hub page design
- [ ] Allow switching to other restaurants in hub on restaurant page

**Comment by Paul-Eraman-CoopCycle** [comment]
Not helpful, we need a real workshop for this- closing for the moment ''
