### ISSUE TITLE
No system top menu when seeing "My account" as admin.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2245]
**Describe the bug**
Clicking on "My account" as admin, menu disappears.

![image](https://user-images.githubusercontent.com/51931067/112889996-3f06b900-90ce-11eb-867f-5d21fad0419a.png)

**Comment by ERAMANrepartos** [comment]
This appears fixed in my instance, closed 
![image](https://user-images.githubusercontent.com/77277854/234858386-8d99c2e9-46fb-43a6-ad18-825962f62771.png)
