### ISSUE TITLE
Options with product are in the right order for clients, but totaly reverse for restaurant

### ISSUE THREAD

**Issue by verninantoine** [coopcycle/coopcycle-web#2259]
**Describe the bug**
Customer see options in the right order, the one we organized in the "product" page. 
When the order arrived to the restaurant, all options are reversed.
Like : "entrée + plat + dessert" become "dessert + plat + entrée" for restaurant.
This is difficult for many restaurant 

![bug 2](https://user-images.githubusercontent.com/77128043/107932606-0a0b3080-6f7e-11eb-864f-61431d55f2d4.jpg)
![bug 1](https://user-images.githubusercontent.com/77128043/107932609-0aa3c700-6f7e-11eb-987a-abf7223ce370.jpg)
![bug 3](https://user-images.githubusercontent.com/77128043/107932611-0b3c5d80-6f7e-11eb-9ce2-274f0bb75bb3.jpg)

**Expected behavior**
Options should appear in the same order for client and restaurant

**Desktop (please complete the following information):**
 - OS: restaurant got Lenovo M8 Android

**Comment by alexsegura** [comment]
Actually this is something that may be fixed on API side
