### ISSUE TITLE
In order to deal with multiple restaurants in the same city, As admin I want to create delivery zones for a restaurant

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#2264]
I want to have an additional settings option where rather than just creating a maximum delivery radius based on kilometers, I can upload a zone in which deliveries are possible, and outside that zone deliveries are not possible. 

I would also like that if someone tries to order outside of that zone, there is a pop up (optional) that suggests ordering from the other restaurant.

**Comment by joel-shiftdelivery** [comment]
@ERAMANrepartos 
You can already specify what zones a delivery is allowed in.

Under the "Deliveries" tab, then "Zones" on the left side, you can upload geojson files to create zones you want. 
![Screenshot from 2021-04-06 16-58-41](https://user-images.githubusercontent.com/64277836/113791915-8f4ad000-96f9-11eb-967b-3d5adabc376f.png)


Then under a restaurant, click "Fulfillment" and at the very bottom of the page you can set "Delivery perimeter" to "Zone" and choose which zone you want to allow deliveries in.

**Comment by ERAMANrepartos** [comment]
Thanks! Sorry!
