### ISSUE TITLE
HUBS → No error prompt when clicking Save

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2270]
When saving a hub there is no error prompt if a field has not been filled in.

The only fields that throw an error are `name` and `address`.

**Comment by alexsegura** [comment]
It happens when the error is not in the current tab

**Comment by agichim** [comment]
Another error it throws being in the correct tab is this. 

![image](https://user-images.githubusercontent.com/51931067/113830004-12156e80-977e-11eb-8fab-3064c3e1dd4f.png)

I believe the error should show even when you are **not** in the correct tab. This way it respects the way the "Resto creation" works. You can input only **some** data and you can SAVE and then **more** tabs appear.

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
