### ISSUE TITLE
Disable platform delivery and takeaway fields when their respective fulfillment option is unchecked

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2274]
Currently, you have to input a number in both the following fields, see screenshot:
![image](https://user-images.githubusercontent.com/51931067/113986281-fc1eb100-9844-11eb-8755-23c798da7624.png)

In the scenario above, under Fulfillment, the Delivery option is checked and the Takeaway/Collection option is unchecked. Perhaps it would be good, that the respective field under Settlement should be disabled completely when either Delivery or Collection is unchecked. Maybe it's a good standard to follow, to not allow any edits when something is not enabled or checked.

**Comment by ERAMANrepartos** [comment]
But you may temporarily disable pickup for some reason, and dont want that to influence. Really, one issue is your pricing and another is availability, i don't think they should be linked. unless @alexsegura you think otherwise, im closing
