### ISSUE TITLE
Strpe fees diasppear again

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2297]
Two restaurants advertise me than Stripe fees has disappeared from stats page since one week.
![image](https://user-images.githubusercontent.com/43618873/115040957-48679200-9ed2-11eb-825d-b128fb494e9d.png)

**Comment by alexsegura** [comment]
Fixed in 8f5982fa0f47530ea53185e562ef365cc1b4d7cc
