### ISSUE TITLE
Enable Telnyx for cheaper SMS pricing

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2305]
**In order to**  provide SMS delivery notifications that are 25-66% cheaper than Twilio.
https://telnyx.com/pricing/messaging

Related to: https://github.com/coopcycle/coopcycle-web/issues/1241

**As a** co-op, this improves scalability and reduces operational costs as SMS use and deliveries grow.

**I want** Telnyx to be added as an SMS gateway option
https://telnyx.com/products/programmable-sms

**Whereas currently** only Twilio (more expensive almost everywhere) and Mailjet (limited availability? - pricing not available for most countries) are options for SMS notifications.

**Additional context**
I did a comparison of pricing in different countries and outside of Brazil, Telnyx is 25-66% cheaper than Twilio, and cheaper than Mailjet in 50% of countries pricing is available for.

![Screenshot from 2021-04-20 19-26-38](https://user-images.githubusercontent.com/64277836/115487838-5a1ca280-a20e-11eb-9eef-752a49ccba1e.png)

**Comment by ERAMANrepartos** [comment]
I don't believe anyone is using SMS notifications at the moment, I'm going to put in review
