### ISSUE TITLE
Allow customizing color of map markers

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#231]

**Comment by alexsegura** [comment]
I would prefer to generalize this (i.e, not only for groups), and achieve it using **tags** (see #219). 

Here is what I'm going to do: 
- introduce a tagging system for tasks (much like GitHub, each tag has a color which can be customized)
- both tasks & groups can be tagged
- when a task / a group is tagged, the marker(s) use the color of the tag
- when there are several tags on a task / a group, the first one in the list is used

**Comment by alexsegura** [comment]
See #233
