### ISSUE TITLE
We would like to be able to toggle visibility for the reoccuring tasks feature on the admin panel

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#2315]
![image](https://user-images.githubusercontent.com/77277854/115846949-b6f0a680-a422-11eb-919e-864878c12143.png)
We would like a button that allows us to hide or make visible these reoccuring tasks. Would improve funcionality significantly.

**Comment by AdrienSICKLO** [comment]
@AniaCuapio  here is the button that doesn't work
![image](https://user-images.githubusercontent.com/59842043/120507392-0ed9e000-c3c7-11eb-9d31-4647cf8b2c03.png)

**Comment by alexsegura** [comment]
Ok actually this button is not mapped to anything.

https://github.com/coopcycle/coopcycle-web/blob/a4ca24c3752a29804c84997f89cc5e2982a3c380/js/app/dashboard/components/UnassignedTasksPopoverContent.js#L38-L40

---

1 - Create a new Redux action type `SHOW_RECURRENCE_RULES` & a new Redux action function `showRecurrenceRules(yesOrNo)` ([actions.js](https://github.com/coopcycle/coopcycle-web/blob/master/js/app/dashboard/redux/actions.js))

2 - Create a new Redux state property `isRecurrenceRulesVisible` & handle the `SHOW_RECURRENCE_RULES` action type in the reducer function ([settingsReducers.js](https://github.com/coopcycle/coopcycle-web/blob/a4ca24c3752a29804c84997f89cc5e2982a3c380/js/app/dashboard/redux/settingsReducers.js))

3 - Show/hide the recurrence rules based on the values of the state property `isRecurrenceRulesVisible` ([UnassignedTasks.js](https://github.com/coopcycle/coopcycle-web/blob/a4ca24c3752a29804c84997f89cc5e2982a3c380/js/app/dashboard/components/UnassignedTasks.js#L131-L136))

4 - Make the setting persistent in session storage, to avoid having to uncheck the box all the time. Check how it's done for the filters [middlewares.js](https://github.com/coopcycle/coopcycle-web/blob/a4ca24c3752a29804c84997f89cc5e2982a3c380/js/app/dashboard/redux/middlewares.js#L92-L108) & [index.js](https://github.com/coopcycle/coopcycle-web/blob/a4ca24c3752a29804c84997f89cc5e2982a3c380/js/app/dashboard/index.js#L80-L89)
