### ISSUE TITLE
[Hub] click and collect problem

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2318]
**Describe the bug**
With the hub, new problems appear in other pages like that : In this picture, restaurant which hasn't activate clik and collect have click and collect. It's not possible to complete a click and collect command but customers see "currently unavailable" and it's not good.
I discovered that because I selected click and collect in another restaurant page before.
![image](https://user-images.githubusercontent.com/43618873/115968489-7d11c400-a538-11eb-9a77-9ebdfd0529c0.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
