### ISSUE TITLE
In order to print customer name As a resto I want customer full name in Order API

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2331]
**In order to**  `achieve something`
Print customer full name instead of his email on order ticket

**As a** `role`
Resto

**I want** `something to be added or changed`
In  GET /api/orders/{id}  endpoint, please add a field "displayName"  to customer object

**Whereas currently** `this happens`
it does not exist

**Comment by alexsegura** [comment]
Fixed in coopcycle/coopcycle-app@3665723c77b42197a3a44a8f251ed33947c96230
