### ISSUE TITLE
[Hub] Stripe fees on stats page

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2334]
**Describe the bug**
With a hub command, the stripe fee appears in every shops and add to stripe fees from others commands. I thought stripe fees from hub commands will be payed by deliveries coops.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ERAMANrepartos** [comment]
The solution here is that the cooperative takes responsibility for the Stripe fee, which is also the correct practice generally in order to not charge stripe % fees on tips and delivery fees to restaurants.

@alexsegura can you please confirm that this is correct, and if so, close the issue?

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
