### ISSUE TITLE
In order to improve UX of custumers, it would be better to change the formulation of values 

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2338]
In the restaurant part
When options are configured for a product and when the minimum and maximum number of values to be chosed is the same, the display is weird: "Please choose between x and x values"

Maybe another formulation would be better: "Please choose exactly X values" 

![Capture d’écran 2021-04-28 à 17 47 40](https://user-images.githubusercontent.com/44605344/116434814-08e26380-a84b-11eb-8709-78cc84ba73ac.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
done!
