### ISSUE TITLE
Refactor current "Dashboard" where live orders can be viewed.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2342]
Currently, there are 2 ways of seeing live orders on the platform:
- Under `Orders` and clicking on `Dashboard` in the top right corner. This shows live orders for **all** Restaurants at once.
- Under `Orders` in the settings of each individual Restaurant.

The proposed refactoring would allow the following:
- Dashboard would be renamed `Live orders` or `Live overview` (naming can be discussed some more)
- The `Live overview` will have a more visible location on the platform
- Once you open/click on `Live overview`, the default view will be seeing Live orders of **all** Restaurants but on the same page, by a simple `dropdown` menu you can select any Restaurant and the `Live overview` will simply show **only** the orders of the selected Restaurant. 
- Additionally, perhaps on the same `Live overview` page when viewing a **specific** Restaurant there can be a notification if Live orders have come in at a different Restaurant so that the Admin/Dispatcher can change the view to that Restaurant or to **all** Restaurants. Perhaps when clicking on the dropdown menu, a coloured bubble with a number on it next to the Restaurant name can indicate the number of new live orders.

**Comment by agichim** [comment]
A draft Glossary was written https://github.com/coopcycle/coopcycle-docs/wiki/Glossary-(draft)

**Comment by Paul-Eraman-CoopCycle** [comment]
This is being referenced in the new discovery process for restaurant and dispatch interface, but the issue itself is being closed as a new discovery and design process is needed, but the concept is good and will be integrated most likely
