### ISSUE TITLE
[Hub] In order to [enhance the hub] As a [role] I want [a new banner]

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2344]
**In order to**  `achieve something`
![idée hub](https://user-images.githubusercontent.com/43618873/116593028-f2a6d700-a920-11eb-91ed-1d9697893e86.png)
Sorry, I'm a Gimp noob but I hope you'll understand my idea : a clickables icons for others hub shops directly on the shop page. I think it's seems to be more understandable for users.

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
