### ISSUE TITLE
No price is visible in Deliveries on the system nor in the .csv export for orders placed via Plugin

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2349]
Considering the API plugin doesn't call the price, the orders place via the plugin should still show the price on the system. Currently, the way it is, it looks like the price doesn't exist for those orders.

See screenshot 
![image](https://user-images.githubusercontent.com/51931067/116795235-68e73d00-aacb-11eb-9daf-a57e4ad47e7f.png)

**Comment by vladimir-8** [comment]
@agichim I'm trying to understand how this part works, and I'm not able to find any delivery where the price section is displayed. I've tried:
delivery for the restaurant: 
https://demo.coopcycle.org/admin/deliveries/3227

deliveries for the store:
with order: https://demo.coopcycle.org/admin/deliveries/3159
without order: https://demo.coopcycle.org/admin/deliveries/3172

For which deliveries do you have the price section displayed?

**Comment by vladimir-8** [comment]
and is it the same issue: https://github.com/coopcycle/coopcycle-web/issues/1774 ?

**Comment by ERAMANrepartos** [comment]
They are related issues, but not the same. They are all different representations of a core issue about pricing

**Comment by Paul-Eraman-CoopCycle** [comment]
remaining issues in:
https://github.com/coopcycle/coopcycle-web/issues/4685
https://github.com/coopcycle/coopcycle-web/issues/4686

closing
