### ISSUE TITLE
Metrics 📊

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2367]
This issue to group all the ideas of metrics.

**Comment by alexsegura** [comment]
By @PasLoin 

> Nombre moyen de kilomètres parcourus/course : total des kilomètres parcourus (xxxxx km) divisé par le total des livraisons effectuées (xxxxx) = x,x km par course
Nombre moyen de kilomètres parcourus par jours par coursiers
Total de kilogrammes transportés
Maximum de livraisons/jour
Moyenne de livraisons / jour : 
Nombre de “tasks” par mois :
Nombre de clients en 2020 : xx clients uniques
Compensation émissions carbone

--- 

> Nombre de drop par heure
Jobs Completed (last 24 heures)
Jobs Cancelled
Jobs Failled
Tracking Links Opened
% Completed On Time
% Not in  Time / LATE
Hourly Distribution of Jobs
Average Task Duration

**Comment by alexsegura** [comment]
cc @CCCC-Jorrit

> Actually the rate of "empty" kilometers vs. "loaded" kilometers and with how many drops per kilometer would also be very interesting, because that's one of the most important economic figures to earning better

**Comment by ERAMANrepartos** [comment]
This seems like less of an issue and more of a...what is larger than epic? Maybe we close the issue and put a metrics element into the roadmap...
@alexsegura
