### ISSUE TITLE
wrong direction of the arrows from mobile website

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2369]
**Describe the bug**
![bug flèche1](https://user-images.githubusercontent.com/43618873/117155022-b65df580-adbc-11eb-94d3-95a2fffbbc42.jpg)
![bug flèche2](https://user-images.githubusercontent.com/43618873/117155051-bc53d680-adbc-11eb-99e3-8c052d1ba6fd.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
It's intented behavior
