### ISSUE TITLE
Add task.description attribute 

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#237]
**Now**
type | address.name | address | after | before | comments

**Then**
type | address.name | task.description | address | after | before | comments

**Comment by alexsegura** [comment]
We already have an `address.description` field, I think this is what you want. 
However, it is not displayed in the app & it is not managed by import. 

<img width="606" alt="capture d ecran 2018-02-26 a 13 42 08" src="https://user-images.githubusercontent.com/1162230/36671173-049db012-1afb-11e8-9073-0739783df229.png">

**Comment by couleurmate** [comment]
OK, close enough. Though, those instructions should be more related to the task than the adress _per se_. 

(BTW, that's in this modal that `dropoff` & `pickup` should be reversed :wink: )

**Comment by Atala** [comment]
@couleurmate what's the difference between `description` and `comments` ?

**Comment by couleurmate** [comment]
`description` is rather the instructions in order to totally fulfill the task. Eg : _5 crates and 7 spoons needed_. It should appear way much higher, just after `adress.name`.

`comments` are facultative information that is not really needed but could help. Eg : _doorbell broken, just yell_ 

I mean everything is there, but mixed. If you look at Bruzz : 
`task.description` = n magazines to be delivered. It is as important than `address` and `address.name`, it should be displayed together
`address.description` = additional info for reaching `address` like _third floor_
`comments` = optional info that could somehow useful

**Comment by alexsegura** [comment]
I think we already have it all, its just a matter of UI/UX, and maybe make it more trivial to complete. 
I'm not a big fan of multiplying the fields. 
One textarea for the address & one textarea for the task is enough.
