### ISSUE TITLE
In Pricing, "Items total" bug

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2375]
**Describe the bug**
When using "Items total" as a pricing condition and "in" to set a an applicable range, it does not seem to save properly, or if it does save, it does not show any information after saving.

**To Reproduce**
1. Go to 'Pricing'
2. Set an 'Items total' condition with "in" 
3. Click Save

**Expected behaviour**
It should save the 'Items total' condition as specified, and show the same after the save/refresh.

**Screenshots**
Condition to save:
![Screenshot from 2021-05-06 15-42-40](https://user-images.githubusercontent.com/64277836/117374628-5d589500-ae82-11eb-9b35-df9886b29280.png)

After saving:
![Screenshot from 2021-05-06 15-42-56](https://user-images.githubusercontent.com/64277836/117374670-69445700-ae82-11eb-846e-7d770bdc7f26.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave

**Comment by joel-shiftdelivery** [comment]
Might be related:
There is some weird behaviour with different items affecting delivery price that is not in compliance with the pricing rules set:

Here are the pricing rules as set:
![Screenshot from 2021-05-07 09-54-43](https://user-images.githubusercontent.com/64277836/117483294-68f79a80-af1a-11eb-98d0-68da0828e4f5.png)


So anything between $25 and $30 should be charged $2 for price ($6 total as $4 is distance). But instead there is this odd behaviour:

![Screenshot from 2021-05-07 09-52-11](https://user-images.githubusercontent.com/64277836/117483449-93e1ee80-af1a-11eb-91ae-ef4c88b63529.png)
![Screenshot from 2021-05-07 09-51-22](https://user-images.githubusercontent.com/64277836/117483451-947a8500-af1a-11eb-8e50-9191bf239efc.png)

**Comment by alexsegura** [comment]
@joel-shiftdelivery the original issue is about display: the rule is stored correctly. It's when displaying the range that it's broken.
