### ISSUE TITLE
Send start time and dropoff time to Kimai API 

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2386]
I don't know if this is really possible with the Kimai API and this is not urgent whatsoever.  

https://www.kimai.org/documentation/rest-api.html

Kimai is a time-tracking software. I'm self-hosting it and it has exactly all the features we need to track the amount of time worked and then see stats, create invoices to pay the courier, etc. And we use all of this, even the creation of invoices is exactly as a coop would need

The implementation I imagine is that when a rider "starts" a delivery it sends the start time to Kimai and when they finish a delivery it sends the finish time to Kimai and it gets saved in Kimai. 

This mostly works for coops where couriers get paid hourly, but the software could be used anyway for seamlessly tracking the time couriers work.

**Comment by ERAMANrepartos** [comment]
The concept is good, but we are looking now at other options instead of kimai, closing the issue
