### ISSUE TITLE
Images in Product pop-up don't have a symmetric layout

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2389]
Perhaps the pop-up should be slightly bigger than the image's proportion and enlarge when there is a 16:9 image.
Perhaps being able to see 1/4 of the next image and being able to swipe with the cursor.
![imagePopup](https://user-images.githubusercontent.com/51931067/117740002-638aa080-b1f7-11eb-9ac1-e8da790a8a55.gif)

![image](https://user-images.githubusercontent.com/51931067/117739824-0a227180-b1f7-11eb-953d-8c4bd349fc48.png)

**Comment by ERAMANrepartos** [comment]
Given that there is another issue about the photos generally and it needs a complete rework, I´m going to close this issue
