### ISSUE TITLE
Missing template for /help/admin/apps in case-sensitive FS

### ISSUE THREAD

**Issue by ccoreilly** [coopcycle/coopcycle-web#239]
There is a typo in the [template uri](https://github.com/coopcycle/coopcycle-web/blob/9a68729ebfbf3061c0ca03e31d3e1268c89144e1/src/AppBundle/Resources/config/routing/help.yml#L53) of the routing file help.yml which throws an error when accessing /help/admin/apps in case-sensitive filesystems.

Line 53:
`template: admin/SmartphoneApps/index`

Should be:
`template: admin/smartphoneApps/index`

**Comment by Atala** [comment]
Would like to contribute to the repo by fixing it? :)
