### ISSUE TITLE
Emails send in spanish while it should be in french

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2393]
**Describe the bug**
![Capture d’écran 2021-05-08 à 13 03 12](https://user-images.githubusercontent.com/44605344/117789118-4af6a680-b248-11eb-9f16-7aa62428e131.png)

A custumer send us this email, received after placing an order in a restaurant. This email is in spanish while our instance is in french

**Comment by alexsegura** [comment]
Duplicate of #1547
