### ISSUE TITLE
When two businesses A (the good one) and B are at the same adress, Geocode.Earth may return business B as Point of interest which overwrite business A in the dashboard/on the map

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#2396]
from Jerome Crow :
"
no it means that since the update for recurring orders, geoloc shows random stores or businesses as address, leading to los of confusion. So if for example we deliver to an address to Business AXX and at the same address there's also Business BXX and it's more well-known (or whatever triggers it) it shows this business, even though it's got nothing to do with our delivery
"

**Comment by ERAMANrepartos** [comment]
This is both unclear, and I believe, fixed by using the correct google maps integration
