### ISSUE TITLE
Create a JS function to create users in DB

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#24]
The JS tests use the PHP command to create users.

It means that JS tests depends on PHP. It is also an issue for #23 .

It implies that the JS model should map entirely the DB entry.

Would that cause any issue?

**Comment by alexsegura** [comment]
Users can register via the website & authenticate to obtain a token via the HTTP API, which is the PHP/Symfony stuff. 
On the WebSocket/Node.js side, users can't register or authenticate, they need to provide a token. 

I don't think this is an issue to create users via Symfony CLI, it is the CLI for the whole app.
It is a reliable interface: the commands won't change, we don't interact directly with the database.

**Comment by Atala** [comment]
I got that. The issue I have is that I am using docker, so I can't use the CLI from the nodejs container. So I can't run the mocha tests locally.

**Comment by alexsegura** [comment]
Ok I didn't realize that 😅

You are right, the best way is to create a `User` model to create users in JavaScript. 
With the ORM you should be able to serialize/unserialize the `roles` field in database easily.

**Comment by alexsegura** [comment]
Fixed in bc5198581bcdf06682ca4cdc5763174b342ae84b
