### ISSUE TITLE
#glitch Fullscreen button should display selected date 

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#240]
On `/admin/dashboard/fullscreen`, `fullscreen` button display the today date. It would be more obvious to display the date picked if any.

**Comment by alexsegura** [comment]
To achieve this we need to move the fullscreen button inside the `<iframe>`

**Comment by alexsegura** [comment]
Not relevant anymore since ee1d851605bda6a2a8887d72bc7b8bfdc7a126c0
