### ISSUE TITLE
UK tax_category.base_intermediary returns Price zero when importing product via .csv

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2402]
tax_category.base_intermediary for Great Britain doesn't have a tax % → see [code here](https://github.com/coopcycle/coopcycle-web/blame/c310a0d456d6b1c651db3c9abfea834edeb6c7be/src/Resources/config/taxation.yml#L109)

This tax works when choosing it from the dropdown menu when adding a product manually.

I imported a .csv file with 
<kbd>tax_category.base_standard</kbd>     
<kbd>tax_category.base_intermediary</kbd> 
<kbd>tax_category.base_reduced</kbd>      
and they all import fine except for `intermediary` tax. See screenshot

![image](https://user-images.githubusercontent.com/51931067/118193655-fb7acb00-b43f-11eb-9e88-42591b6e6de4.png)

**Comment by joel-shiftdelivery** [comment]
Pull request removes "reduced" rate to and replaces it with "intermediary" rate.

Still need to have the system show an error when trying to import a tax category that isn't set for the country code on a CoopCycle  instance.

**Comment by Paul-Eraman-CoopCycle** [comment]
not prioritizing, closing
