### ISSUE TITLE
Improve the recurring tasks by allowing tags and separating them from the stores

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2418]
**In order to** actually use the recurring tasks in an efficient way.

**As a** dispatcher

**I want** the possibility to have all the features available in Coopcycle for the recurring tasks (such as tags, courrier, ...). Also, it would be handy to separate the link with a store and be able to create recurring tasks on their own.

**Whereas currently** very limited options are available for recurring tasks (name, phone, note). And they have to be linked to stores in order to be created.

**Comment by ERAMANrepartos** [comment]
They should be linked to a store 😉  but the rest for sure

**Comment by Paul-Eraman-CoopCycle** [comment]
So workarounds are:

1. making a "rayon9 random" shop
2. associating shops with tags
3. sorry assigning is annoying...

something seem not possible to automate, and we dont want to make the interface too messy
lets workshop this and make new issues with more specific solutions, im closing this issue in particular

**Comment by rayon9coop** [comment]
Okay, I don't think we understand each other :-)
I'll try to explain again: 
When creating a delivery (link to a store), the form asks for information : 
**A for Pickup:** 
1. pickup address
2. the name of the location + telephone number + name of the person in charge
3. time slot (set for this shop)

**B for dropoff**
4. package (defined for this shop)
5. weight 

**C for both PU/DO**
6 and 7. comments
8 and 9. tags
![image](https://github.com/coopcycle/coopcycle-web/assets/44605344/f7674b7a-1ba0-4069-a3c3-0ffb4f692fcb)

When you create recurring tasks, the form should at least ask you for the same information than the ones asked for creating deliveries. In recurring tasks, the form 
- doesn't ask for packages, but for weight
- doesn't ask you to select the time slots defined for the store, but asks you to enter a manual time slot 
- doesn't ask for tags. 

The idea is to systematize the information associated with tasks, deliveries and orders. From my point of view, there's no reason for the information to be different and these differences make things messy

**Comment by Paul-Eraman-CoopCycle** [comment]
i think we made this feature backwards. Instead of having a "make a recurrent rule" tab in the admin dashboard, it should be that when you make a task from a store, you can make the task recurring (with all its characteristics) with a pop up modal that offers once a week, every other week, custom, etc 
(inspiration here comes from the way it is handled in Sling)

This fixes your issue without making more clutter and more technical debt

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok so! We are doing this. But this isn't a single github issue its a whole thiiiiing

here is a "issue of issues" that tracks our current status on dealing with this redesign: https://github.com/coopcycle/coopcycle/issues/8

all your requests are in there! I'm going to close this issue as it is too large, but we will be implementing the requested changes in a series of smaller github issues after we finish the discovery and design phases
