### ISSUE TITLE
SMS does not seem to connect with Mailjet or send

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2419]
**Describe the bug**
We have been trying to activate the SMS to a customer when their delivery is started, but have been unable to get it to work.

1. We have an active Mailjet account and token
2. SMS is enabled in our CoopCycle instance settings, with Mailjet set as the gateway, and the Mailjet token saved
3. I created a couple test deliveries from our 'Demonstration store' and went through the process to assign them to a courier, start each task, complete the task, etc
4. No SMS was received (multiple phone numbers were tried as the customer number)
5. Mailjet doesn't show that is has received any SMS requests to send
6. I have confirmed with Mailjet that our account is active and enabled for SMS sending in Canada and the US.

![Screenshot from 2021-05-17 14-32-08](https://user-images.githubusercontent.com/64277836/118559395-bb0b9d80-b71c-11eb-99b7-1421ca8dad91.png)

**Expected behavior**
After setting up a Mailjet/Twilio account and enabling SMS in CoopCycle (with the appropriate token), the SMS feature to notify customers should work automatically.

**Desktop (please complete the following information):**
 - Browser: Brave

**Smartphone (please complete the following information):**
 - Device: Nokia 7.1
 - OS: Android 10

**Comment by ERAMANrepartos** [comment]
Does anyone use SMS notifications other than Shift?
