### ISSUE TITLE
Allow Admin to delete group task imported in modal

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#242]
After the admin imported wrong CSV file "task group", please :
- Allow Admin to delete group if not assigned
- Log the delete action

**Comment by Atala** [comment]
Hey Rafael, 

Thanks for this one, I just edit it so you can see the good format

**Comment by alexsegura** [comment]
However, the action is not logged 😐

We need to make something global for that.

**Comment by Atala** [comment]
Arf @alexsegura I asked Ellie to work on it :/

**Comment by Atala** [comment]
Yes we should log admin actions, I did something similar at my last job.

**Comment by alexsegura** [comment]
See #173
