### ISSUE TITLE
To saving time, it would be useful to have the possibility to duplicate a tarification rule

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2423]
Some tarification rules are complex. Writing them make the risk of mistakes higher. 

On creating a new store or restaurant, it will be easier to duplicate a tarification rules and then make some minor modifications on the copy rather than re writing almost all the rules.

**Comment by ERAMANrepartos** [comment]
This is now the case! 🥳 

In the pricing page you can duplicate a rule by clicking "manage" and then "duplicate"

![image](https://user-images.githubusercontent.com/77277854/236684995-50682b33-3d9e-4936-8395-fff8a6ff7f4f.png)
