### ISSUE TITLE
Date doesn't change in Resto Stats

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2427]
Changing date always goes back to a specific date. See gif. 
Even if the date on the left displays the correct date, it seems the **real** date is the fixed date (May 1st), because I'm changing to a date where there are orders and no orders show.

![changeDateStatsResto](https://user-images.githubusercontent.com/51931067/118901097-5f9f0280-b90a-11eb-9249-1d120eed45e4.gif)

**Comment by agichim** [comment]
This might just be an issue in the York instance.

**Comment by alexsegura** [comment]
It is normal, it's because you have selected "Date", which means a single day.

**Comment by alexsegura** [comment]
Maybe we could show a different title depending on if "Date" or "Month" is selected?
