### ISSUE TITLE
Order without VAT product

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#2433]
**Describe the bug**
An order 1QDH, doesnt be calculate with restaurant tva, i check if it was a general problem, other orders same day same restaurant, but it was only on this one.

**To Reproduce**
1. Go to orders list
2. Click on 1QDH order
3. Scroll down to product and vat detail
4. See 20% for delivery but not the 10% or 20% (because beers) for product, or it's 20% for everything ?

**Expected behavior**
Just know what hapenned, how to solve this ?

**Screenshots**

![bug TVA](https://user-images.githubusercontent.com/59088580/118992812-412a1d00-b985-11eb-8f2a-ddd9c66b0987.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
we are tracking this in other issues and addressing now, closing here
