### ISSUE TITLE
[HUB] Note field for the restaurant when ordering needs updating for Hub orders

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2437]
Here when customer leaves a note for the restaurant, I imagine the note goes to all the Restaurants from where the customer made his order. 
Either there needs to be a input field for every Merchant in that order or a specification to the customer stating `This note is seen by every resto, make sure you write the name of the Resto for who the note is` ← I think this is not a solution really. 
Not sure what should be done.

![image](https://user-images.githubusercontent.com/51931067/119201536-014b5e80-ba87-11eb-8783-6b63b6c402bb.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
