### ISSUE TITLE
[HUB] Important changes to Order viewed by Hub Restos and Dispatcher

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2438]
- Dispatcher and Resto should see the name of the Hub plus the name of the Resto when viewing Orders in the Dashboard
- Dispatcher should see the products separated by Merchan
- Resto should **only** their own products, and not the products of the other Merchants in Hub orders.

Screenshot of how it currently looks → Scroll down to see screenshot with changes.
![image](https://user-images.githubusercontent.com/51931067/119203068-1e356100-ba8a-11eb-8e5f-6ea24cbe0ce0.png)

Improvements:
- Hub name and resto name
- All restos each with their separate products
![image](https://user-images.githubusercontent.com/51931067/119203621-6739e500-ba8b-11eb-98b7-7ef2a80f0aa7.png)

**Comment by alexsegura** [comment]
> Dispatcher and Resto should see the name of the Hub plus the name of the Resto when viewing Orders in the Dashboard

I don't understand, how can this be possible, as there are multiple restos? `Hub > Resto A, Resto B`
