### ISSUE TITLE
[HUB] Should HUBS have a Collection option in Fulfillment or not.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2439]
Will there be a customer who will purchase a Collection from different shops in one order and go collect themselves?

Can Restos part of a HUB offer collection? If YES, than **all** the shops have to offer collection or not offer it. 

If NO, the Collection setting should be removed from `Fulfillment → Hubs`

**Comment by ERAMANrepartos** [comment]
It should just be disabled, collection makes no sense for the hubs use case
