### ISSUE TITLE
[HUB] Fulfillment in Hub and in Hub Restos and not-Hub Restos doesn't work correctly

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2440]
If 2 Restos are part of a Hub, one of the Restos overrides the Fulfillment of the other Resto. This means, an order can be placed on a Resto where its Fulfillment indicates that the Resto is closed. 

I removed the bully Resto that overrides the Fulfillment from the Hub and the overriden Resto uses its own Fulfillment as normally. 

I tested all of the above making sure the Cart was empty and that I was on the page of the individual Resto and it's probably a cache issue, which is not good. I also tested all of the above in an incognito window and the Resto doesn't override the other Resto's Fullfilmment **BUT** the next issue is:

The Hub Fullfilment overrides correctly the Fulfillment of the Restos, but, 1 Restos is open on Monday, the 2nd Resto is open on Tuesday and the Hub is open on Wednesday. 
**The Hub allows ordering for Wednesday from Restos that are actually closed for delivery**.

**Comment by Paul-Eraman-CoopCycle** [comment]
no longer using hubs, closing
