### ISSUE TITLE
[HUB] Can't accept new Order from Hub and how should a new Order be accepted

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2441]
On the York Collective instance Orders coming from the Hub cannot be accepted by any of the multiple Restos on the same order and Dispatcher/Admin cannot accept Order in the General Dashboard ![image](https://user-images.githubusercontent.com/51931067/119208922-18e11200-ba9c-11eb-83f7-317dbc73a7f1.png) (when clicking Accept, the wheel spins and nothing happens
![cantAcceptOrder](https://user-images.githubusercontent.com/51931067/119209253-817cbe80-ba9d-11eb-93d2-3deef386ff4e.gif)

 nor can the order be accepted in the Orders section when viewed 
![image](https://user-images.githubusercontent.com/51931067/119208943-2c8c7880-ba9c-11eb-81d1-6aaf13f28761.png)
Clicking Accept below returns a 500 error but the order is not accepted.
![image](https://user-images.githubusercontent.com/51931067/119209080-c18f7180-ba9c-11eb-9388-cff1780184a8.png)

I tested this on the Demo instance and any Resto or Admin can accept the Order.

But, although products from multiple restaurants should be ready and collected at the same time, NO resto should be allowed to accept the order and that order change to Accepted to the other Restos. This could lead a Resto to not preparing an order if they did not accept it themselves, options:
- the Dispatcher should be the only one accepting Hub orders (not a good option) or
- each Resto accepts their own order without changing anything for the other Restos, but the other Restos get a little message specifying which Resto has already Accepted the order so they know they have to start preparing the order.

**Comment by Paul-Eraman-CoopCycle** [comment]
No longer using hubs, closing
