### ISSUE TITLE
"Error 500" tarification

### ISSUE THREAD

**Issue by Scrat44** [coopcycle/coopcycle-web#2445]
**Describe the bug**  
Pricing page on "Delivery" menu, is kind of broken with "error 500" for one of our pricing.
We can't open the Pricing page of "Test Antonin", it's triggering the "error 500".
Nonetheless, we can open other created pricing pages. But when we add one rule and save it, it's the same "error 500"'s appearing.

**To Reproduce**  
1. Go to "Delivery" menu
2. Open a Pricing page created
3. Add a rule and try to save it
4. Trigger the "error 500" page

**Labels**
bug

![pricing1](https://user-images.githubusercontent.com/68964194/119398029-4534a280-bcd7-11eb-9895-c470e553de55.PNG)
![add rule 1](https://user-images.githubusercontent.com/68964194/119398031-4665cf80-bcd7-11eb-97b4-040a078ee5b0.PNG)
![error 500](https://user-images.githubusercontent.com/68964194/119398036-46fe6600-bcd7-11eb-821e-f7400624e79b.PNG)

**Comment by alexsegura** [comment]
Fixed in 8eefb00f5c34949659daec57b9b178a67a48f0fa
