### ISSUE TITLE
In order to [add easily the bancontact payment option] As a [shop]

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2458]
**In order to**  `add easily the bancontact payment option, 

**As a** `shop/restaurant`

**I want** 'an easy way to add this payment option on stripe.

**Comment by rayon9coop** [comment]
Bancontact is the most used way to make cards paiement in Belgium. 

https://www.bancontact.com/en

**Comment by ERAMANrepartos** [comment]
Got it. So you want a shop to be able to pay you using this?

**Comment by rayon9coop** [comment]
a customer who wishes to order from anywhere on coopcycle (restaurant but also on our online order form: https://www.rayon9.be/commander-une-livraison/)
In Belgium, if we want to welcome new cooperatives to CoopCycle, adding bancontact as a means of payment on the application is a good idea because young people generally don't have a credit card but they all have a bancontact payment card.

**Comment by ERAMANrepartos** [comment]
Got it thank makes sense. Also, if we dont want to split the payment from a customer between the coop and a collaborator, it makes these integrations easier

**Comment by r0xsh** [comment]
I think there's a simple way to enable that with Stripe: https://stripe.com/docs/payments/bancontact

**Comment by rayon9coop** [comment]
@alexsegura and Adrien said it's not so simple and needs some dev on coopcycle side. Maybe you could talk with them?

**Comment by ERAMANrepartos** [comment]
No worries @rayon9coop ill bring it up in the next sprint planning to evaluate if its easy or not and update here with what we can do

**Comment by Paul-Eraman-CoopCycle** [comment]
We will be doing this in https://github.com/coopcycle/coopcycle/issues/50, which is up next, so we will track there. closing this as a duplicate
