### ISSUE TITLE
As a restaurant/Co-op I need to know when Coupons are being used

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#2482]
2 levels for this I think:
-Somewhere in the statistics should it be shown
-But also, live it should be know that a person is either using a promotion code and/or a coupon

**Comment by vladimir-8** [comment]
@AdrienSICKLO just for my understanding, I've read this document about promotions https://docs.coopcycle.org/en/admin/orders/promotions/ , which one do you refer to, when you say "a promotion code and/or a coupon"?

**Comment by ERAMANrepartos** [comment]
Theoretically we should know about both, right?
