### ISSUE TITLE
When starting an order coopcycle automatically puts pickup, when it should be delivery.

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#2486]
![image](https://user-images.githubusercontent.com/77277854/120629134-ca515180-c465-11eb-9af3-10316d3447e2.png)

This should automatically be delivery, not pickup.

**Comment by alexsegura** [comment]
The delivery fulfillment method is indeed the [default](https://github.com/coopcycle/coopcycle-web/blob/285550631112d4e83d9ee232e09d668f03542536/src/Entity/Sylius/Order.php#L349). 

Maybe you started an order in another restaurant/shop, choosed collection, and then went to another restaurant/shop?
Please provide a reproducible use case where collection is applied by default.
