### ISSUE TITLE
Implement online/offline Toggle button for Stores and remove "Create orders" checkbox

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2490]
Make a few changes to Stores so that it maintains a standard with Restaurants.
Add the description and toggle button indicated by the green arrows in the screenshot. 
The toggle button would replace the "Create orders" checkbox, which should be removed.
Add a Title for the 3 remaining checkboxes as in the screenshot

![image](https://user-images.githubusercontent.com/51931067/120872834-b6a60800-c597-11eb-901c-b40b7a3d9b20.png)

**Comment by alexsegura** [comment]
Shouldn't "Create orders" be more explicit than just "Enabled/Disabled"?

Actually what "Create orders" means is "Retail price"

**Comment by Paul-Eraman-CoopCycle** [comment]
Is being reworked in Pricing V.2
