### ISSUE TITLE
[STORE] When selecting Deliveries tab in a Store, display the deliveries on the right and keep the Store settings on the left.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2500]
Allow clicking on Deliveries and keeping the settings on the left as with the other settings and display the deliveries where the red rectangle is.

![image](https://user-images.githubusercontent.com/51931067/121076003-c9098700-c7cd-11eb-9a04-954e43c68250.png)

**Comment by ERAMANrepartos** [comment]
This is part of a much bigger UI/UX issue about the stores setup. Closing, but dont worry this is going to be a big thing in the roadmap to deal with soon.
