### ISSUE TITLE
[DELIVERIES] Keep active setting tab when opening a sub-level hierarchy setting

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2506]
Clicking on **Timeslots** will keep the Timeslot tab on the left ACTIVE indicated by the color blue. 
Clicking on **+ Add** in order to add a timeslot, the Timeslot tab should stay ACTIVE.
![image](https://user-images.githubusercontent.com/51931067/121203375-f60d7680-c86d-11eb-81d1-9a1429719d21.png)

![image](https://user-images.githubusercontent.com/51931067/121203348-f279ef80-c86d-11eb-899f-d8a8a127200d.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
looks like we did this
