### ISSUE TITLE
[RESTAURANTS] Change/translate wording for Restaurants section overall

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2523]
- [x] Restaurants → E-commerce / Shops
- [x] Rename "Menu" to "Catalog"
- [x] Remove `categories` in Restaurants → General → Type of business
- [x] Remove `Restaurants` and `Stores` section titles on the homepage of an instance (#2602).
- [ ] #2603

**Comment by agichim** [comment]
@alexsegura will create a commit on 1 translation.

**Comment by alexsegura** [comment]
@agichim can you take #2603?
