### ISSUE TITLE
Taxes: Base> Reduced rate should not appear for ca-bc

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2527]
**Describe the bug**
The tax Base> Reduced rate was removed in #2406 but is still showing in our instance, when it should not appear.

**To Reproduce**
1. Go to a restaurant settings page
2. Click on Products and edit for any product
3. Click on 'Taxes'

**Expected behavior**
When using the tax menu for ca-bc, the options should on;y be Alcohol, Standard, Intermediary, and Tex exempt.

Reduced rate should not be an option for ca-bc

**Screenshots**

![Screenshot from 2021-06-11 04:46:58](https://user-images.githubusercontent.com/64277836/121682213-a519a000-ca70-11eb-9cf0-e357b0e4836d.png)

**Additional context**
Pull #2406 should have removed Base> Reduced rate, but it did not

**Comment by Paul-Eraman-CoopCycle** [comment]
not something we are going to prioritize, closing
