### ISSUE TITLE
Order confirmation email is sent even if payment fails

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#253]

**Comment by Atala** [comment]
@alexsegura is it fixed by all the changes you made for sylius integration or should I look into it?

**Comment by alexsegura** [comment]
Sylius integration is not finished yet, & this is unrelated.

The thing is, we need to persist the order before creating the payment.
But the email is sent [when the `Order` is persisted](https://github.com/coopcycle/coopcycle-web/blob/cb5ffea08a3a3063c0e250f3ee9c121e0f510a9a/src/AppBundle/Controller/OrderController.php#L153).

The obvious fix is to stop sending the email from [`OrderSubscriber`](https://github.com/coopcycle/coopcycle-web/blob/cb5ffea08a3a3063c0e250f3ee9c121e0f510a9a/src/AppBundle/EventSubscriber/OrderSubscriber.php#L109), but from `OrderController`, once payment has succeeded.

**Comment by Atala** [comment]
Ok, will do

**Comment by alexsegura** [comment]
This was fixed in Sylius refactoring, email is sent when payment is authorized successfully.
