### ISSUE TITLE
Opening automatically when adding a new courrier to the dashboard

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2531]
**In order to** gain time

**As a** dispatcher

**I want** an automatic opening of a courrier field right after it's been added to the dashboard

**Whereas currently** when you add a new courrier to the list of people working on a given day, you still need to open it afterwards.

<img width="233" alt="2021-06-14 10_53_12-Microsoft Store" src="https://user-images.githubusercontent.com/44605344/121865920-c1327100-ccfe-11eb-9021-6d1e56a9c1a7.png">

**Comment by AniaCuapio** [comment]
The documentacion on the library is here, use preExpanded property
https://github.com/springload/react-accessible-accordion

The archives are here:
- TaskLists.js
- TaskList.js

**Comment by alexsegura** [comment]
It's not easy at all to implement with [react-accessible-accordion](https://github.com/springload/react-accessible-accordion)

Maybe we need to switch to something else, like [react-collapsible](https://github.com/glennflanagan/react-collapsible)

**Comment by Paul-Eraman-CoopCycle** [comment]
Unfortunately this is one of those super annoying things that seems easy
given that there is a very easy work around (one click) I´m going to close this due to lack of prioritization
