### ISSUE TITLE
delivery information - bottom of the restaurant page conflict

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2533]
**Describe the bug**
When you unroll restaurant menu, delivery information follow you : great feature. But : 
![Screenshot_2021-06-14-17-27-07](https://user-images.githubusercontent.com/43618873/121920528-6fa6d800-cd38-11eb-9d08-9b0e2293d8fd.png)
Problem on computer and tablet ( panoramic view )

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
Duplicate of #1482
