### ISSUE TITLE
HUB - experiences & improvement suggestions

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#2540]
HUB with restaurants

In Sicklo we experienced (because of a bug) a HUB order 29T5 a client made involuntarily. For the HUB test we did, everything was disable (in execution) but restaurant were link so the client start his basket on one restaurant and just change his mind with an other restaurant associate to the hub (chance, hazard) and hub happens like that for the client side. As we see now we delete restaurant HUB user, it can't happen again.

![Hub](https://user-images.githubusercontent.com/59088580/122186058-ed302c80-ce8d-11eb-8b97-c7ef2d526a32.png)

![Hub2](https://user-images.githubusercontent.com/59088580/122186060-ee615980-ce8d-11eb-8876-4e8802a2886a.png)

What happens 
The order appear on the "dashboard" named by the test hub (gare europôle) and on the administration panel named by address. Dispatch can see only products list and delivery informations of the Order. If you go to the order details dispatcher can see the two restaurants were concerned and products associated to them. Restaurant receive all the products list and restaurant list too on their side.

![détails 29T5](https://user-images.githubusercontent.com/59088580/122186113-fc16df00-ce8d-11eb-95b7-da04712b89b4.png)

![Inkedpanel administration 29T5_LI](https://user-images.githubusercontent.com/59088580/122187366-43ea3600-ce8f-11eb-83ab-801caeb972f1.jpg)

![29T5 dashboard](https://user-images.githubusercontent.com/59088580/122186216-1c469e00-ce8e-11eb-80eb-0e36e4908abf.png)

![commande 29T5](https://user-images.githubusercontent.com/59088580/122186111-fb7e4880-ce8d-11eb-9e28-4e2b8d6eeffa.png)

Also we check on Stripe, the paiement capture of this order was on our Sicklo instance Stripe.

![Stripe 29T5](https://user-images.githubusercontent.com/59088580/122186496-60d23980-ce8e-11eb-9cd6-39cafc45cd1a.png)

To improve the HUB i have some suggestion :

- Dispatch side : See details restaurants and products list associate to them on the dashboard and on have the clear name to indicate it's a Hub order on the administration panel and not just the address. 
- Best could be paiments manage on stripe restaurant instance because we are not the seller of products, so for facturation and comptability going to be complicated how stripe hub works now.
-  Client side : Be more clear their using hub. For example a pop up ? Also In Sicklo we think about the HUB as a fonctionnality reserve to professionnals (company, association) so it could be nice to have a page specific to the hub we could send to company, because products volume are more interesting in this fonctionnality for us.

**Comment by agichim** [comment]
Hey, I've made a few issues regarding Hubs, maybe you can add more info in comments in each specific issue. 
Also, change the title of the issue to something a little bit more specific.

Here's the issues I created:

#2437 #2438 #2439 #2440 #2441 #2270 #2271

I don't think HUBS is totally read to be used **live**. It needs a lot of improvements.

**Comment by Paul-Eraman-CoopCycle** [comment]
We have stopped using hubs, closing the issue
