### ISSUE TITLE
Add color attribute in task JSON output

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#255]
When a task is tagged, the first tag in the list overrides the color for the task marker on a map. 

To be able to easily change the color in the app without making complex operations in the app, the JSON output, `TaskNormalizer` should add a `color` property directly.

**Comment by Atala** [comment]
Should we close this?

**Comment by alexsegura** [comment]
Not yet please, we'll do that for the next release of the app.

**Comment by alexsegura** [comment]
Color management actually belong to the UI, it makes no sense to have it in API data
