### ISSUE TITLE
a wrong notification apears when you want to pay with classic bank card ( probably only for french coops )

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2557]
**Describe the bug**
When you choose to ,pay with a classic card a restaurant which accept EdenRed card a notification appears which ask to pay with a classic card because this restaurant doesn't accept EdenRed card :
![Capture](https://user-images.githubusercontent.com/43618873/122892612-d2eec680-d345-11eb-91ef-eb853dd9d86b.PNG)
1) Why this notification appears ? I just chose classic card payment.
2) Why notification say it's not possible to pay with EdenRed card although this is possible
I think this is a notification provided for others situation which appears here.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
Edenred has been redone, i believe this no longer occurs
