### ISSUE TITLE
Add package and weight info so that the courrier can see it

### ISSUE THREAD

**Issue by livraison-stains** [coopcycle/coopcycle-web#2566]
when a delivery is created via the form, the courier doesn't know witch type of package and which weight he can retrieve.

**Comment by alexsegura** [comment]
We need to modify [DeliveryListener](https://github.com/coopcycle/coopcycle-web/blob/69f549f2f46a0691337d5879260ca8c2498a63d0/src/Entity/Listener/DeliveryListener.php), to write comments in the pickup task before saving in database.

See `CoopCycleExtension::gramsToKilos` to format `$delivery->getWeight()` properly. 

https://github.com/coopcycle/coopcycle-web/blob/69f549f2f46a0691337d5879260ca8c2498a63d0/src/Twig/CoopCycleExtension.php#L197-L200 

See how it's done in Twig template to convert packages to text. 

https://github.com/coopcycle/coopcycle-web/blob/69f549f2f46a0691337d5879260ca8c2498a63d0/templates/_partials/delivery/list.html.twig#L50-L59
