### ISSUE TITLE
When creating récurrent task, i would like to be able to fill the same form as the delivery form with adress column, tags time slot, compagny name, access instructions, contact, contact number, comments. 

### ISSUE THREAD

**Issue by livraison-stains** [coopcycle/coopcycle-web#2570]
**In order to**  `achieve something`
A clear description of a goal you want to archive

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by vladimir-8** [comment]
@livraison-stains is it the same as https://github.com/coopcycle/coopcycle-web/issues/2418 ?

**Comment by livraison-stains** [comment]
Yes, exactly.

**Comment by vladimir-8** [comment]
okay, then it's keep one task for this issue
