### ISSUE TITLE
Keep desired options order

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2576]
**Describe the bug**
Options in product are randomly sorted, even after reordering them on product modification page. 

**To Reproduce**
1. Go to product modification page
2. Reorder options as desired
3. Save product
4. Go back to product modification or select product in restaurant menu => options are randomly sorted

**Expected behavior**
Sometimes sorting options allows customer to choose his menu options with a certain logic (for a burger, choosing the bread before the drinks for instance). Chosen order of options should be kept on all pages and application screen which is not the case currently

**Screenshots**

Expected order (before saving) : 
![Screenshot from 2021-06-28 11-23-31](https://user-images.githubusercontent.com/11749973/123613142-7a1aa480-d803-11eb-9c47-c6db63c1a4bd.png)

After saving in restaurant menu : 
![Screenshot from 2021-06-28 11-24-05](https://user-images.githubusercontent.com/11749973/123613261-91f22880-d803-11eb-99dc-fc57fa6a0812.png)

After saving in product modification page : 
![Screenshot from 2021-06-28 11-24-41](https://user-images.githubusercontent.com/11749973/123613317-9d455400-d803-11eb-8fbf-ab3c54308fe6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ERAMANrepartos** [comment]
This has been fixed, you can drag and drop the options into the correct order

**Comment by r0xsh** [comment]
The plateform inverse the order of options and there is no way to reorder product options

![bug](https://github.com/coopcycle/coopcycle-web/assets/5613584/6181c9c9-0b89-4992-934a-785664479a8a)

**Comment by Paul-Eraman-CoopCycle** [comment]
I believe this no longer happens, closing
