### ISSUE TITLE
Add the possibility to filter the markers on dashboard map

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#258]
Tags for task have been merged in #233 .

We should now add the ability to filter the marker on the map by tags. On the UI-side, I think same as GH is nice (a dropdown with the list of tags), please check it out.

No need to do backend stuff, only React.

**Comment by couleurmate** [comment]
it fixes #256

**Comment by Atala** [comment]
Done 63002a3f67cb9ed0edb6397a8de02957539f7626
