### ISSUE TITLE
Improve management of OSRM with Docker & Ansible

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#26]
I'm such a n00b...

Right now the `osrm-docker` Ansible role [configures Supervisor to start the Docker containers](https://github.com/coopcycle/coopcycle-web/blob/7409ac162b19e6ff4614813b8a6f59c52f95f882/ansible/roles/osrm-docker/tasks/install.yml). 
It doesn't work at all: Supervisor has no clue to check if the process is running, and when there is an error, it starts containers forever.

Instead we should use [Ansible's `docker_container`](https://docs.ansible.com/ansible/docker_container_module.html) to start & manage the containers. 
Also see [restart policies](https://docs.docker.com/engine/reference/run/#restart-policies-restart) to handles system reboots.

**Comment by alexsegura** [comment]
Partial fix f34c54ba6ab89939f351f9eb8bec7ec7c0d5cbee

**Comment by Atala** [comment]
I think you should set the [restart policy](https://github.com/coopcycle/coopcycle-web/commit/f34c54ba6ab89939f351f9eb8bec7ec7c0d5cbee#diff-33a7d2c5603eb08c398354fb7dfa3597R41) as `always` ([ref](https://blog.codeship.com/ensuring-containers-are-always-running-with-dockers-restart-policy/))
