### ISSUE TITLE
In order to avoid losing time, as a customer, save information when I decide to modify them in the form

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#2600]
![image](https://user-images.githubusercontent.com/59842043/124484976-5e3b7380-ddac-11eb-9fb7-276f6bf4ca34.png)

When at this page I click on "modify", it takes me back to the form which comes out empty. Would be interesting to have it filled with the previous information so that as a customer, I do not have to do it all over again.

**Comment by Paul-Eraman-CoopCycle** [comment]
To arrive at this page go to the [Formulas page](https://demo.coopcycle.org/admin/forms) and click on the id # of one of the [formulas](https://demo.coopcycle.org/admin/forms/2)  to see the order creation page for non-clients (can be anyone)

**Comment by Paul-Eraman-CoopCycle** [comment]
closing becasue https://github.com/coopcycle/coopcycle-web/issues/1190 fixes the issue by putting the payment info in the same page, which is a better UX
