### ISSUE TITLE
Implement option to add `<script>` in the platform header.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2608]
It would be interesting if we had the option to implement scripts inside the header of each instance. 

For example, [Chatwoot](https://github.com/chatwoot/chatwoot) would be something interesting to have on the platform. It's a chat app, and to implement you need to put the script anywhere on the platform. Currently there is not persistent place to place a script so that it shows everywhere. 

We've implemented Chatwoot on our own website, but I was wondering if it would be useful to have it on an instance. With Chatwoot you don't need an account in any platform, you can just write a message straight up.

**Comment by alexsegura** [comment]
If Chatwoot needs to be implemented, then it must be implemented _explicitly_, instead of via a custom `<script>`

Adding a way to inject custom scripts exposes the platform to XSS attacks.

**Comment by agichim** [comment]
But Chatwoot gives you multiple options to implement and one of them is "specifically" the option to implement via a `script`. If one of the official methods of implementation is a `script` does that still mean that Chatwoot are aware that their script can expose the platform to XSS attacks?
