### ISSUE TITLE
Stores: Saved Addresses remove customer name and contact # requirement

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2615]
**Describe the bug**
In a store, when creating a delivery with a saved address that does not have a contact name or phone number, those fields are removed from the order process and not allowed to be filled.

**To Reproduce**
1. Go to create a delivery in a store
2. Click on a saved address without a contact name or phone number
3. See the fields disappear

**Expected behavior**
Contact name and phone number fields should always be visible and editable when creating a delivery. The should always be required to place a delivery, even for saved addresses that may not have a name or number saved with them.

**Screenshots**
![Screenshot from 2021-07-09 08-33-26](https://user-images.githubusercontent.com/64277836/125102629-5b809d00-e090-11eb-9a3e-123301ae23b1.png)
![Screenshot from 2021-07-09 08-32-54](https://user-images.githubusercontent.com/64277836/125102632-5c193380-e090-11eb-89f9-6ebaddecff1a.png)

**Comment by alexsegura** [comment]
Now the telephone/contact name fields will re-appear, if necessary. 
This still doesn't allow to modify all the details all the time, but it's a first step. 

![addr_fields](https://user-images.githubusercontent.com/1162230/130479517-53d289ad-795a-415c-a375-b602b7eb90d9.gif)
