### ISSUE TITLE
Create role-specific Help pages

### ISSUE THREAD

**Issue by ccoreilly** [coopcycle/coopcycle-web#264]
Currently when not logged in, if you access the Help page through the footer link you get information which is intended mostly for the admin of Coopcycle.

I would suggest limiting access to admin specific help pages to the admin role and creating help pages for the relevant features for each role. #

**Comment by Atala** [comment]
As discussed with @alexsegura we're gonna setup a static website for support/help

I think it is ok if restaurant owners are directed to support.coopcycle.org/restaurant (which will be a subpart for admins) 

Closing this for now.
