### ISSUE TITLE
In order to avoid confusion I want an order to be created if "Create orders" setting is enabled (proposal)

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#2648]
**In order to** avoid confusion and have consistent behavior for deliveries created via different flows (manually on the dashboard, mobile app, API, imported etc.)

**I want** `an order to be created if "Create orders" setting is enabled

**Whereas currently** an order is created only for deliveries added manually (individually) via the dashboard by an admin/store and not for deliveries added via API, mobile app, or via the import button 

**Additional context**
Issues caused by it:
https://github.com/coopcycle/coopcycle-web/issues/2350
https://github.com/coopcycle/coopcycle-app/issues/1137

relates to: https://github.com/coopcycle/coopcycle-web/issues/2490

**Comment by r0xsh** [comment]
Fixed by: #3608
