### ISSUE TITLE
When the customer makes a delivery request for a package or a package, we have the option of sending him a payment link by email. It does not work.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2670]
When the customer makes a delivery request for a package or a package, we have the option of sending him a payment link by email. It does not work.

![bug lien de paiement](https://user-images.githubusercontent.com/83431363/117568680-fcb79b00-b0c1-11eb-89b4-7942e99f90ee.png)

**Comment by Paul-Eraman-CoopCycle** [comment]
fixed, closing
