### ISSUE TITLE
I have a display bug on my web instance, in my opinion the bug is only for my instance (https://fast-and-curious.coopcycle.org/fr/)

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2674]
I have a display bug on my web instance, in my opinion the bug is only for my instance (https://fast-and-curious.coopcycle.org/fr/)
![bug d'affichage instance web](https://user-images.githubusercontent.com/83431363/116856576-aa770580-abfb-11eb-9bfe-128edca59406.png)

**Comment by alexsegura** [comment]
Fixed in 94fbdb6e635ae2c2d347a48e62fec174da0184f3
