### ISSUE TITLE
The order of the options, of the products in the menu is not respected. A customer who wants to buy a kebab can see a suede pie first, then the sauces, then the drinks, and finally his kebab.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2679]
The order of the options, of the products in the menu is not respected. A customer who wants to buy a kebab can see a suede pie first, then the sauces, then the drinks, and finally his kebab.

**Comment by alexsegura** [comment]
Duplicate of #2576
