### ISSUE TITLE
Display the details of each customer's orders (number of orders, price, 1st order placed, etc.). This allows the restaurant to be able to build loyalty properly.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2680]
Display the details of each customer's orders (number of orders, price, 1st order placed, etc.). This allows the restaurant to be able to build loyalty properly.

**Comment by alexsegura** [comment]
Fixed in d32a8fcfc0317a7d6f63b12836d4aad81d19aa18
