### ISSUE TITLE
Delivery export format is not adapted for multiple points

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2726]
When exporting deliveries, it exports one line _per delivery_, and columns are designed to support only one pickup + one dropoff. 

| pickup.address | pickup.after | dropoff.address |
|----------------|--------------|-----------------|
| ...            | ...          | ...             |   |   |

The export format would need to be changed to be more "Excel-friendly", and to support any number of tasks, without requiring a variable number of columns.

**Comment by ERAMANrepartos** [comment]
Closing this issue due to the fact that we are currently working on a complete revamp of the universal excel, which includes this as a part of the epic

**Comment by ERAMANrepartos** [comment]
Closing this issue due to the fact that we are currently working on a complete revamp of the universal excel, which includes this as a part of the epic
