### ISSUE TITLE
Option is unlimited instead of limited as set

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2728]
**Describe the bug**
Values in an option set as limited (to 1 for example) appears unlimited when displayed in the menu. Thus the customer can choose as many of it as he.she wants, when it should only be possible to select 1 (or the limited set amount)

**To Reproduce**
1. Create an option
2. Tick this option is a supplement
2. Add a value and insert a max value (1 in my example)
3. Fill in the fields of name, price and tick activate.
4. Save and go on the website version
5. Select the product and see that you can select an unlimited amount of that value

**Expected behavior**
You should be able to select just 1 and not able to go unlimited

**Screenshots**
![2021-08-26 12_25_10-RAYON9](https://user-images.githubusercontent.com/44605344/130951712-3c03b9da-027e-4c1e-85d6-ddde6b9e8ed2.png)

![2021-08-26 12_25_37-RAYON9](https://user-images.githubusercontent.com/44605344/130951750-01f2bda1-37e4-4ca2-a955-61e57f795d6b.png)

![2021-08-26 12_30_09-G du Bol - RAYON9](https://user-images.githubusercontent.com/44605344/130951781-39ba75c6-9498-48be-b054-a7d512a1dc1e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Professionnel
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
I found a way around it by making it a compulsory option and having to choose between 2 values.

**Comment by Paul-Eraman-CoopCycle** [comment]
Fixed 🥳 

![Image](https://github.com/user-attachments/assets/cdc31180-fe2b-4590-a673-84346cb33578)
