### ISSUE TITLE
operating bug when you activate/desactivate products in products list

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2776]
A restaurant activate/desactivate his products with icons at the left side : 
![InkedScreenshot 2021-09-14 at 11-58-52 La Poit’ à Vélo_LI](https://user-images.githubusercontent.com/43618873/133240789-7a7582a1-a795-4037-8a8d-f09a76f391a9.jpg)
And today a problem appears : 
![InkedScreenshot 2021-09-14 at 12-01-10 Grand Ours - La Poit’ à Vélo_LI](https://user-images.githubusercontent.com/43618873/133240876-8efdb60b-7b91-4600-9460-b4882f6b9ded.jpg)
I regulate the problem in activate save, desactivate and save again inside product detail.

**Comment by ERAMANrepartos** [comment]
Old bug, seems to not be happening now.
