### ISSUE TITLE
When a customer is ordering from a smartphone, it could be more intuitive to change the time and day of delivery

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#2778]
**In order to**  change easily and intuitively the time and day of the delivery

**As a** customer

**I want** `the possibility to change the time and day from this screen (1) AND/OR to show more clearly on this screen where it's possible to do so (2)
![Inkedphoto1631695057_LI](https://user-images.githubusercontent.com/44605344/133400483-fe7e1294-404e-4066-8fcf-738d45a7b789.jpg)
(1)

![Inkedphoto1631695057 (1)_LI](https://user-images.githubusercontent.com/44605344/133400517-fef0523c-ad18-4678-9ff4-879b29007e03.jpg)
(2)

**Whereas currently** now you can only click here if you want to change it. It's not possible on the next ordering screen.

**Additional context**
Sorry if I'm not super clear. Would be happy to explain more in details if needed.

**Comment by Paul-Eraman-CoopCycle** [comment]
We need to completely rework this screen and it's in progress, this is part of it, closing due to repetition
