### ISSUE TITLE
Wording issues "Shops", "Boutiques" should replace "Restaurant" in the admin panel

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#2812]
**Describe the bug**
On the "Create shop" page, a lot of thing are still referring to the old "Restaurant" (I just checked in french and english) on demo.coopcycle.org . It should be changed no ?

See screenshot below (+ the tooltip when hovering the basket on top as well)

<img width="1392" alt="Capture d’écran 2021-09-29 à 09 37 57" src="https://user-images.githubusercontent.com/4426585/135224400-47133ce3-b7b2-47a2-8f4f-efe4ff9a2851.png">

**Comment by ERAMANrepartos** [comment]
I know this is kind of controversial, but I don't think we want to do this. The entire B2C platform is very clearly made from its roots as a food delivery platform, which can be seen by the inability to modify multiple products at once, the way options is created, the menu design.....
I think we should consider the platform a food delivery platform, and focus on using woocommerce for example for B2C shops.

However, either way, it is a biiiiig issue that should be roadmapped, not just a small translation issue.

**Comment by Atala** [comment]
I think you should change "Boutiques" to "Restaurant" in french (i dont know how it is put in other lanaguages), small change but would add clarity for the top bar

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/554fab6c-707c-449a-b9f6-e24b2fe02832)

**Comment by Paul-Eraman-CoopCycle** [comment]
It should be changed to restaurant yes. but i dont understand how language changes work in the platform. every time i ask mex he says to use the translation platform which is not very easy to understand and i dont want to break anything. 

If you are up for changing that to "restaurants" in all languages, please do 👍
