### ISSUE TITLE
Allow to override minimal amount per product

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2815]
It should be possible to override the minimum amount, if the order contains a specific product. 

For example, if the minimum amount is 15€, but the order contains a specific product that is 10€ (i.e above the minimum amount), it should be possible to order anyways. 

It can be implemented through a checkbox on the product page.

**Comment by ERAMANrepartos** [comment]
Why should this be possible? It completely defeats the purpose of the minimum amount. I'm going to close this issue...but if you have a good use case please reopen with a new comment
