### ISSUE TITLE
In order to spend less time on making invoices. As an admin I want more info on the export file.

### ISSUE THREAD

**Issue by livraison-stains** [coopcycle/coopcycle-web#2818]
In order to spend less time on making invoices. 

I'd like to be four colums added to the export file : 

- one collumn with the name of the customer account that order the delivery
- one collumn with the packages description of the delivery
- one collumn with the weight description of the delivery
- one collumn with the price of the delivery

People who use the app for B to B doesn't use the direct payement and therefore make several invoices at the end of month. It will save us ton's of time if we have this feature 

Whereas currently we have to : 

- Sourting out all delivery and put them on different board
- Then looking for the packages and the weight on the customer account
- Make the calculation for the price
A clear and concise description of what happens now

**Comment by ERAMANrepartos** [comment]
This now exists in the shops and admin exports, and we are working on a universal export with all the relevant information
