### ISSUE TITLE
zone - hub

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#2847]
Lire les commentaires de la cliente. J'ai vérifié en essayant moi-même et checké les zones des commerçants concernés. L'adresse de la cliente est dans toutes les zones de livraison
![image](https://user-images.githubusercontent.com/43618873/137112423-e5fc35e6-e70f-4d55-93fd-6835dff6af56.png)

**Comment by ERAMANrepartos** [comment]
@alexsegura can you take a look at this and explain the issue?
