### ISSUE TITLE
In order to order confidently As a customer I want address distance etc. checked immediately and not just when adding an item

### ISSUE THREAD

**Issue by moeffju** [coopcycle/coopcycle-web#2855]
**In order to**  `order confidently from a restaurant`
I want to start an order and be confident that it is possible and can be fulfilled

**As a** `customer`

**I want** `distance and other checks to be run on page load and the user to be informed`
When a customer opens a restaurant page, it should immediately check distance to the selected address and run other checks and then inform the customer that the address is e.g. out of delivery range, and allow to choose another address.

**Whereas currently** `users are only told when they add the first item to the order`
When I use e.g. [khora.berlin](https://khora.berlin/) not all views honor the address I have set, so sometimes I will open a restaurant, get excited to order, and then when adding the first item to the basket, will be told "this address is too far"

**Additional context**
![image](https://user-images.githubusercontent.com/14829/137712124-22e5da08-43ff-4c17-af5f-a003bd4b8971.png)
(1) restaurant page opened without address set, e.g. because user used the tabs on the start page

![image](https://user-images.githubusercontent.com/14829/137712249-97015af5-509d-4bf7-98e2-87297fcc953d.png)
(2) after adding first item, user gets popup without any guidance/help/message to choose address

![image](https://user-images.githubusercontent.com/14829/137712348-4ee4170c-b316-49d9-ae27-43048af34f67.png)
(3) after choosing address, user is told it is too far

I've also had cases where the address was set when loading the restaurant page, but still I had to add an item first (1) - then I immediately got message (3) that the address is too far.

**Comment by ERAMANrepartos** [comment]
I believe this has been fixed and now the address is asked first, specifically to fix this issue.
