### ISSUE TITLE
Address setting is lost when using tabs to switch views on "shops" page

### ISSUE THREAD

**Issue by moeffju** [coopcycle/coopcycle-web#2856]
**Describe the bug**
When a user clicks one of the tabs on the /shops page, the address setting is lost when entering a shop sub-page.

**To Reproduce**
1. Go to a CoopCycle instance (e.g. khora.berlin) that has different types of shops (e.g. Restaurants, Wineries) and where you have addresses saved
2. Choose an address
3. The page refreshes with a geohash and address parameter and your view is limited to shops that deliver to your selected address
4. Click on one of the tabs (e.g. "Restaurants")
5. the geohash/address params disappear from the URL, and when opening a shop page, the delivery address is not set (but it is still visible in the address input field)

**Expected behavior**
I expect to still see only shops that are compatible with my selected address, and when I click one, I expect the delivery address to be carried over

**Screenshots**
not needed, can just check URLs

**Desktop (please complete the following information):**
 - OS: Tested with Windows and Mac (but it's using the browser anyway so....)
 - Browser: Firefox

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
i believe this is fixed, if this is still occuring please write here
