### ISSUE TITLE
Installation : make install error

### ISSUE THREAD

**Issue by dlicitra** [coopcycle/coopcycle-web#290]
I'm installing the software following the guide on a Linux Ubuntu Mate 4.13.0-37-generic on a x86_64 machine. 

When i launch the command `make install` i get this error:

> Updating the "app/config/parameters.yml" file
> > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> 
> Fatal error: Uncaught RuntimeException: Cache directory "/srv/coopcycle/var" is not writable. in /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:310
> Stack trace:
> #0 /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(192): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/srv/coopcycle/...', '<?php \nnamespac...')
> #1 /srv/coopcycle/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(265): Symfony\Component\ClassLoader\ClassCollectionLoader::inline(Array, '/srv/coopcycle/...', Array)
> #2 /srv/coopcycle/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php(59): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::doBuildBootstrap('/srv/coopcycle/...')
> #3 {main}
>   thrown in /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 310
> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception
> 
>                                                          
>   [RuntimeException]                                     
>   An error occurred when generating the bootstrap file.  
>                                                          
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
> 
> Makefile:2: set di istruzioni per l'obiettivo "install" non riuscito
> make: *** [install] Errore 1
> 

What is the problem? If I start the container, all the services start except PHP.

The steps are:
> git clone ...
> cd coopcycle-web
> sudo docker-sync start
> sudo docker-compose -f docker-compose.yml -f docker-compose-dev.yml up
> sudo make install

**Comment by Atala** [comment]
I couldn't reproduce but I think I know where it comes from.
Can you cherry-pick the commit 78a7d99c and try again ?

**Comment by dlicitra** [comment]
What i did:

- [x] git clone https://github.com/coopcycle/coopcycle-web.git
- [x] git cherry-pick 78a7d99c61c4b5b802240674016ae894635fee54
- [x] sudo docker-sync start
- [ ] sudo docker-compose -f docker-compose.yml -f docker-compose-dev.yml up
- [ ] sudo make install

docker-compose give me the first error:
> Fatal error: Uncaught RuntimeException: Cache directory "/srv/coopcycle/var" is not writable. in /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:310
> webpack_1   | /srv/coopcycle/node_modules/@symfony/webpack-encore/lib/config/parse-runtime.js:62
>webpack_1   |             throw new Error('Cannot determine webpack context. (Are you executing >webpack from a directory outside of your project?). Try passing the --context option.');
>webpack_1   |             ^
>webpack_1   | 
>webpack_1   | Error: Cannot determine webpack context. (Are you executing webpack from a >directory outside of your project?). Try passing the --context option.
>webpack_1   |     at module.exports (/srv/coopcycle/node_modules/@symfony/webpack-encore/lib/config/parse-runtime.js:62:19)
>webpack_1   |     at Object.<anonymous> (/srv/coopcycle/node_modules/@symfony/webpack-encore/bin/encore.js:17:23)
>webpack_1   |     at Module._compile (module.js:624:30)
>webpack_1   |     at Object.Module._extensions..js (module.js:635:10)
>webpack_1   |     at Module.load (module.js:545:32)
>webpack_1   |     at tryModuleLoad (module.js:508:12)
>webpack_1   |     at Function.Module._load (module.js:500:3)
>webpack_1   |     at Function.Module.runMain (module.js:665:10)
>webpack_1   |     at startup (bootstrap_node.js:201:16)
>webpack_1   |     at bootstrap_node.js:626:3
>coopcycleweb_webpack_1 exited with code 1


After that, i run `make install` with the second error

>fatal error: Uncaught RuntimeException: Cache directory "/srv/coopcycle/var" is not writable. in /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:310
>Stack trace:
>#0 /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(192): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/srv/coopcycle/...', '<?php \nnamespac...')
>#1 /srv/coopcycle/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(265): Symfony\Component\ClassLoader\ClassCollectionLoader::inline(Array, '/srv/coopcycle/...', Array)
>#2 /srv/coopcycle/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php(59): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::doBuildBootstrap('/srv/coopcycle/...')
>#3 {main}
  thrown in /srv/coopcycle/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 310
>Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post->install-cmd event terminated with an exception
                                                         
>  [RuntimeException]                                     
>  An error occurred when generating the bootstrap file.  
                                                         
I suppose i miss some steps or there is a problem with sub-shells in the installer script

**Comment by Atala** [comment]
Can you try the following : 
```
docker-compose build --force-recreate php
docker-compose up php
```
?

**Comment by alexsegura** [comment]
Closing as stale
