### ISSUE TITLE
Stop using numeral.js because of coupling between currency and locale

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#294]
<img width="561" alt="capture d ecran 2018-04-06 a 16 52 37" src="https://user-images.githubusercontent.com/4426585/38427989-fe38af86-39ba-11e8-8ba1-93f9b4470cad.png">

I don't think we can solve this with numeralJS ([ref](https://github.com/adamwdraper/Numeral-js/issues/165)) because it associates currency & locale which is unfortunante

@alexsegura should I look for another formatting solution?

**Comment by alexsegura** [comment]
Ufff, looks like there are few options for this, maybe something damn simple is sufficient? 

Like [this](https://css-tricks.com/snippets/javascript/format-currency/)
