### ISSUE TITLE
Allow being delivered after a restaurant is closed

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3009]
For example, if a restaurant closes at 10:00PM, then customer should be able to order for 10:00PM + preparation time + delivery time.

**Comment by alexsegura** [comment]
To avoid modifying the algorithm too much, we are going to add the average preparation time + the average delivery time to the upper bound of the closing time. 

To calculate the average preparation time: 

```sql
SELECT ROUND(AVG(EXTRACT(EPOCH FROM TO_CHAR(preparation_time::interval, 'HH24:MI')::interval) / 60)) from sylius_order_timeline;
```

**Comment by lucasferraro** [comment]
> To avoid modifying the algorithm too much, we are going to add the average preparation time + the average delivery time to the upper bound of the closing time.
> 
> To calculate the average preparation time:
> 
> ```sql
> SELECT ROUND(AVG(EXTRACT(EPOCH FROM TO_CHAR(preparation_time::interval, 'HH24:MI')::interval) / 60)) from sylius_order_timeline;
> ```

@alexsegura We should calculate the AVG for each restaurant, shouldn't we? Because with this calculation of the avarage the preparation time of one restaurant will be affected by the preparation time of all other restaurants.
