### ISSUE TITLE
Add pricing condition based on timeslot size

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3013]

**Comment by AdrienSICKLO** [comment]
@lucasferraro 
So you understand the "business" part of this. 
Price of delivery is based on the delivery conditions. The harder it is, the more expensive. Right now, we have a few possibilities to characterize hardness (weight, pick up time slot, distance etc...). But another condition that can be making things hard or easy is "how much time you have to deliver? In fact, if I have 1 week to do it, it is very easy, and I can probably optimize another trip, so we are making good money. But on the other hand, if people ask me to be somewhere in a 15min time slot, there is a good chance that I can't optimize, and therefore I will make the price more expensive!
