### ISSUE TITLE
Upgrade to Node 16.x

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3022]
> Cannot find module 'true-case-path'

This happens when running a fresh installation on Linux. 
Seems related to outdated Sass version. 
We need to upgrade Node-Sass + Webpack Encore.

**Comment by alexsegura** [comment]
See also #2954

**Comment by alexsegura** [comment]
We must upgrade, as `node-sass` 5.x will never support Node 16.x (sass/node-sass#3106)

**Comment by alexsegura** [comment]
It seems that `webpack-encore` does **NOT** need `node-sass` anymore (symfony/webpack-encore#225), so this might be a first step.

**Comment by r0xsh** [comment]
Tested and the fix seems to work fine :+1:
