### ISSUE TITLE
Show weight and package information in the task popup on dispatch dashboard

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3043]
RIght now, the agregated weight and packages appear in the pick up task **comments**. 

With the implementation of the multi drop off, we need the amount of kg and packages to be shown in each task.

Question:
Should it be in the comments?
Should we create another section?

**Comment by livraison-stains** [comment]
Hello, 

I think it must be in a package section, as comment are meant for "call me when the messenger is downstairs" kind of info.

**Comment by alexsegura** [comment]
This needs to be implemented **BOTH** on the web and on the app

**Comment by alexsegura** [comment]
Since #3112 the API is returning packages information.

**Comment by alexsegura** [comment]
Fixed in #3137
