### ISSUE TITLE
Support multiple tasks when calculating prices

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3047]
With the multistop option, it has become important to create pricing rules that can match this feature.

A distance condition is not relevant as the client is not aware of what the fastest route could be.

Therefore, a new condition based on the number of points is important.

There should be the possibility to add a "discount" like with the packages, as in "First point is 9, and other points will be 5"

**Comment by alexsegura** [comment]
From @biologeek

> imagine we are asked to pickup 210 kg of goods and deliver following quantities :
> Customer A, zone 1 : 10kg,
> Customer B, zone 1 : 55 kg,
> Customer C, zone 2 : 145 kg
> Conditions :
> Pickup : 10 €
> Each point in zone 1 : 7 €, in zone 2 : 9 €
> + 5 € every 20 kg above 20 kg
> We would bill 20 € for pickup as we can only take 200 kg at a time
> + 7 € for point A
> + 7 € for point B + 10 € for extra weight
> + 9 € for point C + 35 € for extra weight
> Gives us a total of 88 € !

**Comment by AdrienSICKLO** [comment]
About this:

Pick up condition is ok using
If distance > 0 = 10 for first pick up
If total.weight > 200kg = 10€

Considering a new price per point using a zone condition on top, we would have most spec covered.

The only thing missing here would be a condition based on weight per point.Would need a "total weight" condition or "total volume" condition, and a weight per point and volume per point condition for points that go over the contracts' conditions.

Other question, should we implement a "price for pick up" condition or do we consider that we have other ways to create it (like if distance> 0 = X)

**Comment by livraison-stains** [comment]
May be you can add a rule as : "if using multi stop" discount "20%" for "4 points" ?

**Comment by alexsegura** [comment]
Also check Crow's pricing model for inspiration: https://crowberlin.de/en/price-list/
