### ISSUE TITLE
Name of the store not appearing on the app

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3065]
**Describe the bug**
The name of the store appearing at the beginning of tasks on the dashboard doesn't appear on the name of the task in the app.

**Expected behavior**
The name should also appear in the tasks in the app, to make it clear for which client/store we're riding

**Screenshots**
What it shows on the dashboard, name of the store is Storeshippers : 

![image](https://user-images.githubusercontent.com/44605344/150510583-488f3d93-0096-446a-8277-966375d8c5b7.png)

What it shows on the app : (we would want Storeshippers to also appear first in the name of the task)

![image](https://user-images.githubusercontent.com/44605344/150510928-562f61c1-89e8-44a3-96ee-4c56246e1a6b.png)

![image](https://user-images.githubusercontent.com/44605344/150511018-4165e785-18cf-4afa-98c7-8cb7685db540.png)

**Smartphone (please complete the following information):**
Device: Samsung Galaxy X Cover 4s
OS: Android 11

**Comment by ERAMANrepartos** [comment]
This should definitely be fixed. Having the same information represented partially differently in different places is a huge problem in a logistics solution

**Comment by Paul-Eraman-CoopCycle** [comment]
Look to me like its fixed, let me know in comments if not (but in eraman looks like yes)

🥳
