### ISSUE TITLE
UI/UX Remove admin breadcrumb

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#308]
In most cases I think it is not useful (backward link is already in navbar) + take space
<img width="1170" alt="capture d ecran 2018-04-15 a 13 09 54" src="https://user-images.githubusercontent.com/4426585/38777844-12c47de0-40af-11e8-9dbb-17288153f6b0.png">

@alexsegura what do you think?

**Comment by alexsegura** [comment]
The platform is going to be redesigned, closing.
