### ISSUE TITLE
Understand if the delivery is planned or ''as soon as possible''

### ISSUE THREAD

**Issue by mcorreggiari** [coopcycle/coopcycle-web#3114]
Sometimes happens that we receive an order to drop-off 1 hour later (for example) and we don't know if it is planned or the type ''as soon as possible'' (if it is quite big and far can be).

We want known, if it is possible, to add the information into the order if customer choose the ''as soon as possible'' mode or choose a specific time for the delivery (drop-off planned).

Thanks

**Comment by ERAMANrepartos** [comment]
What would this look like practically speaking as a feature

A nivel práctico, como una mejora especifica, esto que sería como _feature_?
