### ISSUE TITLE
Add a setting to enable/disable marker colors

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3150]
Following #2122, dispatchers have been complaining that the markers/polylines having the avatar color can be confusing. 

We need to introduce a setting to toggle it (default disabled, like before).

**Comment by AdrienSICKLO** [comment]
Don't know how hard it is, but people have asked whether it could be possible to choose courier's colour.
But first step as in "possibility to enable or not" is already grand

**Comment by alexsegura** [comment]
@AdrienSICKLO there used to be an issue about associating an arbitrary color to a messenger (#1646). It's not hard, but currently there's an "algorithm" that generates a color based on the username, which is great because it doesn't require any actions from admins. The main problem is using the same color, both in the backend and the frontend (which is what was required to display polylines in the same color as the avatar)

Also linked with #3166

**Comment by AdrienSICKLO** [comment]
I didn't get how hard it would be to give possibility to change colours manually, because the algorithm makes bad choices.
Could you enlighten me?
