### ISSUE TITLE
Implement FTP synchronization based on SIRET for Edenred

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3153]
To get new restaurants, work on the Edenred solution to have them on the platform

**Comment by ERAMANrepartos** [comment]
What needs to happen for this feature to exist?
@AdrienSICKLO @alexsegura

**Comment by Paul-Eraman-CoopCycle** [comment]
not closed until its in the finished column! sorry 🙏
