### ISSUE TITLE
Colors of the different courriers all went green

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3166]
**Describe the bug**
When earlier the different courriers on the dashboard all had one different colour (easy to distinguish them), they now all appear in green

**Screenshots**
![image](https://user-images.githubusercontent.com/44605344/157851876-1efdc3ee-769d-4334-aa4c-ef12d1b4cc10.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Professionnel
 - Browser : chrome

**Comment by alexsegura** [comment]
It is because the courier usernames are pretty close, and the hashing algorithm that generates colors is generating the same color for all of them

**Comment by ERAMANrepartos** [comment]
This would be solved by the issue #1646 in which colors can be manually assigned, so I´m going to close this as a repeat issue
