### ISSUE TITLE
Export spreadsheets asynchronously

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3177]
When exporting deliveries on a large range of dates, we are getting 504 timeout errors. 

To fix this, the deliveries export needs to be done asynchronously, like when exporting tasks.

**Comment by alexsegura** [comment]
As an intermediary solution, we could also implement this export using pure SQL, it seems possible with one big query. 
Because what seems to cause timeouts is the time spent in PHP building objects, not executing SQL. 

<img width="1177" alt="Capture d’écran 2022-04-05 à 12 54 37" src="https://user-images.githubusercontent.com/1162230/161742141-eaf6e07d-05ed-4e16-8773-809c3ec80b00.png">

**Comment by alexsegura** [comment]
Since 03e689ca610096dd5f23010ead6821463e53c108, the export should be more optimized.

**Comment by Paul-Eraman-CoopCycle** [comment]
is this still relevant @alexsegura ?

**Comment by vladimir-8** [comment]
Deliveries export should be deprecated in favour of orders (and maybe tasks) exports. That are already asynchronous: https://github.com/coopcycle/coopcycle-web/issues/4596
