### ISSUE TITLE
As an administrator I want to access order billing informations for further processing

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#3220]
**In order to**  make billing easier, automate bill calculations and crosscheck with Stripe data

**As an** administrator only

**I want** to retrieve billing information (delivery paid, platform fees, stripe fees, Stripe payment id, ...) through an API endpoint for each order either individually or through a time period

**Whereas currently** you have to manually download the CSV export file, then process it. 

**Additional context** This would allow us to automate huge part of the billing process, cross check with Stripe payments to prevent payment failures and finally simplify billing

**Comment by ERAMANrepartos** [comment]
We do the same thing manually. This would be a huge improvement, but also should be developed carefully and with a good deal of thought

**Comment by Paul-Eraman-CoopCycle** [comment]
we did this
