### ISSUE TITLE
In order to add flexibility to the restaurant onboarding process, As an administrator I want to have the ability to connect Stripe to the cooperative 100%

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#3222]
**In order to**  `achieve something`
In order to be able to offer more and better solutions to restaurants that are possible clients, I would like to be able to let the cooperative have 100% of the money paid by a client, to then at some future point pay to the restaurant as we wish. 

Possible usages:
1. A very common tactic used to onboard restaurants in my cooperative is the "try it out and see what happens" approach, which requires making the trial as easy as possible. SOMETIMES (not always) it would be useful to be able to do a trial in which they don't have to go through the trouble of making a stripe account.
2. Restaurants that are paid "manually" at the end of the month would facilitate the process of offering refunds and enacting economic sanctions on restaurants for unhelpful behavior, since all the money would be in the cooperatives hands.
3. A restaurant doesn't trust Stripe but trusts us

**As a** `role`
Cooperative members who interact directly with restaurants could find this useful in ways that we may not be currently aware of. It adds flexibility to an aspect of the cooperative in which flexibility is very important.

**Comment by alexsegura** [comment]
Already implemented in d84fe52fefbee26f2074ded912b02fa0e0d1bd03
