### ISSUE TITLE
Possibility to change groups

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3223]
4 different needs:
- Possibility to change the name of an Import/Group
- Add task to a group with a right click
- Ungroup a task from an existing group with right click
- Creating a group with just one task in it.

**Comment by lucasferraro** [comment]
I'm creating different PRs for each request so it's easier to read and check changes

- [x] [Possibility to change the name of an Import/Group](https://github.com/coopcycle/coopcycle-web/pull/3228)
- [x] [Add task to a group with a right click](https://github.com/coopcycle/coopcycle-web/pull/3227)
- [x] [Ungroup a task from an existing group with right click](https://github.com/coopcycle/coopcycle-web/pull/3229)
- [ ] Creating a group with just one task in it.

**Comment by lucasferraro** [comment]
Closed by
#3229 
#3228 
#3227
