### ISSUE TITLE
Problems with addresses being saved

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3235]
**Describe the bug**
As an admin, and we believe with some normal user accounts, it SEEMS that if you have an already saved address, but in the front page put in a different address, the old saved address appears.
Additionally, without a user account, many times after putting in an address in the main page, once having selected a restaurant, the inputted address does not appear and it is not made clear that the address has not been saved. 

https://user-images.githubusercontent.com/77277854/168344655-ed336c1c-b8b8-4358-a6d6-139c594ecda6.mp4

Vivaldi, desktop computer (linux)

https://user-images.githubusercontent.com/77277854/168345260-d47bf4ec-7ff7-42bb-bf5d-6692a0ffddb0.mp4

https://user-images.githubusercontent.com/77277854/168344957-fb05581a-c820-46bf-b110-34efbf79e02d.mp4

**Comment by biologeek** [comment]
Linked to https://github.com/coopcycle/coopcycle-web/issues/3244 in a way. Known addresses are not taken by Coopcycle

**Comment by ERAMANrepartos** [comment]
@alexsegura I looked at #3244 and there is definitely a root bug that is creating multiple issues of this type. Have you looked at this?
