### ISSUE TITLE
In order to make better decisions for the route to take as a courrier, I want streets contained in a red list to visually appear on the map

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3236]
**In order to**  make it easier for the courriers to know which streets (too steep or dangerous or.. ) not to take,

**I want** the possibility to create a red list of those streets so they would appear visually on the courrier's map in the app.

**Comment by ERAMANrepartos** [comment]
Sorry, but I cannot imagine how this could be created in a way that works as a federation with a common technological solution over a diverse geographic space. I´m going to close the issue. If you think the feature requested can be described in a more specific way that can be useful for all collectives, please make a new issue.
