### ISSUE TITLE
New group name editing feature not working due to apparent loading error

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#3238]
**Describe the bug**
After modifying the name of a group, when clicking the check Mark, the screen freezes and nothing else can be clicked. The screen must be refreshed and the change has not been saved. 

**To Reproduce**

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/77277854/169101297-069befeb-d7c0-45ff-bd24-8c0dbe6c110d.MOV
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Tried for firefox and vivaldi in debian

**Additional context**

**Comment by lucasferraro** [comment]
Hi @ERAMANrepartos ! 
I tried on firefox, chrome and vivaldi in ubuntu and it works for me.

Could you open the browser developer console (press F12 and go to "Console" tab) and try to see if there is any error message there after you click on "check" button?

Also, have you tried to save changes pressing "Enter"? The changes can be saved when you click on check button or when you press "Enter" key (and can be undone, before save them, when you click "cancel" button or press "Escape" key).

**Comment by ERAMANrepartos** [comment]
Ok so I tried that, and in doing, ended up waiting longer before refreshing, and it turns out it does work! it just takes a while....and since I was refreshing before it finished, the change didn´t save

so my bad. But definitely a bit slow, as long as people are aware it shouldnt be a problem

**Comment by lucasferraro** [comment]
Hmm ok, maybe we can show a loading overlay in that section or in whole page until operation is done to prevent this kind of scenarios and to give more feedback to user.

**Comment by lucasferraro** [comment]
This feature has a LoadingOverlay which indicates that the edit operation is in progress. With that should be cover the case when the operation is slow and user needs some feedback about what it's happening.

https://user-images.githubusercontent.com/4819244/170780674-9a12a2f1-5d50-44b7-b5af-732b5c965853.mp4
