### ISSUE TITLE
Impossible to define a variable amount paid by the customer (for new shops/restaurants)

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3244]
**Describe the bug
No matter what choice is made for pricing, only the choice of a fixed amount is recorded.

**Reproduce**
Steps to reproduce the behaviour:
1. Go to a restaurant account, under the "Conditions" menu
2. Click on 'Yes' for the question "The amount paid by the customer is variable". Choose a pricing rule
3. Save and test an address

This feature is operational on existing shops with the setting set to variable. It does not work if I want to the setting be set on variable on new stores.

![bug](https://user-images.githubusercontent.com/44605344/170217017-d48089e7-251b-4ed3-a648-7779d08504bc.gif)

**Comment by biologeek** [comment]
As discussed previously, there is a bug lying when user selects a known address in the list. In this case, cart is not updated and address is not considered. 

When user inputs a new address it updates the cart as expected

**Comment by ERAMANrepartos** [comment]
@alexsegura this is a critical error right?

**Comment by Paul-Eraman-CoopCycle** [comment]
I think this is fixed, closing
