### ISSUE TITLE
Add a section influence the behavior for existing modifiers

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#325]
Adding a new section mess with existing modifiers fields (?)

<img width="802" alt="capture d ecran 2018-04-25 a 10 53 47" src="https://user-images.githubusercontent.com/4426585/39235734-02dcb3be-4877-11e8-9248-df79a333e052.png">

**Comment by alexsegura** [comment]
Fixed in 7fcef47fde614fa8c2b11932eb8371cee35c230e
