### ISSUE TITLE
Multi dropoff recurrent tasks are missed

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#3262]
**Describe the bug**
For a recurrent task containing a single pickup and multiple dropoffs, when exporting deliveries CSV, the CSV contains only 1 line with pickup address and first dropoff address. All other dropoffs are missed.

**To Reproduce**
1. Go to admin dashboard
2. Create a recurrent task set with 1 pickup and multiple dropoffs
3. Generate tasks
4. Go to Deliveries menu
5. Export CSV
6. See issue

**Expected behavior**
Best approach here would be to have for each dropoff same pickup address. For instance with previous example : 

DPPD commandes	2 b Rue au Bouchet, 21000 Dijon, France	11/04/22 06:20	68 Rue Charles Dumont, 21000 Dijon, France	11/04/22 07:00		6.009
DPPD commandes	2 b Rue au Bouchet, 21000 Dijon, France	11/04/22 06:20	1 Rue Jacques Cellerier, 21000 Dijon, France	11/04/22 07:30		6.009
DPPD commandes	2 b Rue au Bouchet, 21000 Dijon, France	11/04/22 06:20	4 Rue de l’Hopital, 21000 Dijon, France	11/04/22 08:00		6.009

**Screenshots**
![Screenshot from 2022-06-06 13-06-51](https://user-images.githubusercontent.com/11749973/172150071-d0a8e649-7da7-4eb3-ab9f-10201c242543.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 
**Smartphone (please complete the following information):** 

**Additional context**

**Comment by ERAMANrepartos** [comment]
This is part of the universal export issue we are working on now, this should be fixed very soon. Closing issue due to repeat
