### ISSUE TITLE
Postal code is not displayed when using Google Maps

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3264]
When using Google Maps, we use the [description attribute](https://github.com/coopcycle/coopcycle-web/blob/d957b75fd9329252ac05b381eda7c9424a6735c4/js/app/components/AddressAutosuggest/google.js#L60) of predictions, and the string doesn't contain the postal code. 

<img width="460" alt="Capture d’écran 2022-06-28 à 13 44 29" src="https://user-images.githubusercontent.com/1162230/176171052-c3d7e61d-04a1-44ce-b54f-4ebcfef1961d.png">

The problem is that a prediction doesn't contain the postal code. 

<img width="830" alt="Capture d’écran 2022-06-28 à 13 55 04" src="https://user-images.githubusercontent.com/1162230/176172440-fb8cc6f8-bb79-4e2d-af54-bd87e5522ed7.png">

To obtain the postal code, we would need to call the `geocode` service for each prediction, before the user clicks on it. 
This would increase costs, and reduce performance. The Google Maps SDK is not intended to be used like this, you are supposed to call the `geocode` service once the user clicks on a suggestion.

**Comment by ERAMANrepartos** [comment]
Why is this a problem?
