### ISSUE TITLE
In order to increase sellings As a restaurant/coop I want to improve the displaying of possibilities for clients 

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3282]
When a solution is not available (for eg. delivery is not possible today), the app just say "Not available at the moment". The client have to find (alone) how to choose another solution (eg. pickup on site by clicking on little link "Change" next to the "Delivery" mention). This could discourage clients to order with another solution (eg. pickup on site) or in another restaurant. If they come twice and twice the solution is not available, maybe they didn't come back at all.

If a client want to order in a restaurant A and the delivery is not available today, the app should offer some alternatives:
- pick up the order on site (if available)
- order in restaurant B, C or D (same taxonomy/neighbourhood/...) if any alternative is available in the restaurant A

**Comment by rayon9coop** [comment]
![ImproveDisplayingOptions](https://user-images.githubusercontent.com/44605344/174591329-7f1d4902-0518-439d-9045-651adbad990b.gif)

**Comment by Paul-Eraman-CoopCycle** [comment]
we have redesigned this, closing as an old issue, though we will work on this UI more in the future
