### ISSUE TITLE
Several bugs with restaurant's opening days

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3284]
**Describe the bug**
- Restaurant is closed (in the planning) on next saturday but it appears open if "pickup on site" is choosed
- Sundays aren't set as open days on "execution page" but the "pickup on site" is showed available on next sunday
- Number of shipping choices is set on "6" but the next 6 opening days doesn't appears if  "delivery" is choosed (neither if pickup on site is choosed except on next Sunday .... but is not configured to be open)

Restaurant: https://rayon9.coopcycle.org/fr/restaurant/13-oncle-to
![bug](https://user-images.githubusercontent.com/44605344/174595216-afb689be-c874-40f6-9a5e-1099810391be.gif)
m

**Comment by alexsegura** [comment]
Fixed in 2e1c7cbb1a2a38b0ddb9798e1ed1ee6a5b8efdde
