### ISSUE TITLE
Incorrect error message when ordering with a form : "Your card was declined..." when it's not the case

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3292]
**Describe the bug**
The app shows "Your card was declined. This transaction requires authentication." when it's not the case: the transaction is accepted, the payment is debited, the tasks created and the notification has been sent by email. 

**To Reproduce**
1. Go to a form to order a delivery
2. pay online
3. See the message error

**Expected behavior**
Not show this message :-) which introduces doubt (and mistrust) for the customer

**Screenshots**
![image](https://user-images.githubusercontent.com/44605344/175569776-e151da81-9151-401a-b9d8-8df8e79c80d7.png)
![image](https://user-images.githubusercontent.com/44605344/175570134-89093efa-450f-46e6-b5fc-6ae543e2a1cb.png)

**Comment by alexsegura** [comment]
"This transaction requires authentication" seems to be the [`authentication_required` decline code](https://stripe.com/docs/declines/codes)

> The customer should try again and authenticate their card when prompted during the transaction. If the card issuer returns this [decline code](https://support.stripe.com/questions/authenticated-payment-declined-with-an-authentication-required-decline-code) on an authenticated transaction, the customer needs to contact their card issuer for more information.

It _may_ be a super specific error in our implementation, for _some_ banks. 

@rayon9coop do you see a pattern? Type of card, bank...

**Comment by rayon9coop** [comment]
Except belgian cards/bank, i can't identify a pattern.
I tried with a mastercard, from belfius bank

**Comment by Paul-Eraman-CoopCycle** [comment]
@alexsegura any thoughts on this?

**Comment by Paul-Eraman-CoopCycle** [comment]
How common is this @rayon9coop ?

**Comment by rayon9coop** [comment]
I don't know

**Comment by Paul-Eraman-CoopCycle** [comment]
closing for the moment, if we hear it happening again we can reopen (we have more logs now)
