### ISSUE TITLE
Unable to Create restaurant - The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by MunirajM** [coopcycle/coopcycle-web#3301]
Hi, We tried adding a new Restaurant on the demo website(https://demo.coopcycle.org/admin/restaurants/new) from admin but we are getting the error as in the screenshot https://tinyurl.com/234k5z84 when trying to add the restaurant details and submit the form.

Are we missing something?

Thanks!

**Comment by alexsegura** [comment]
Fixed in 22c882162ac0995b748b6c88a9d30b70e05d91da

**Comment by alexsegura** [comment]
@MunirajM can you try again? It should work now.

**Comment by nanostuffs** [comment]
hi @alexsegura , thanks for your quick fix and able to create Restaurants now!

**Comment by MunirajM** [comment]
Hi @alexsegura,

Thanks for your quick response and able to create restaurant now!
