### ISSUE TITLE
Details from recurrent rules not showing on tasks

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3307]
When filling details on the recurrent rules, the contact and phone number details are not displayed nor on the dispatch nor on the APp for the courier. See pictures

![image](https://user-images.githubusercontent.com/59842043/177355352-e59e6998-0ecc-4ee0-b06a-94323fd45f50.png)
![Screenshot_2022-07-05-16-45-20-277_fr coopcycle](https://user-images.githubusercontent.com/59842043/177355565-52b355b2-abe6-4b01-8f92-bf0277e1cf4d.jpg)

**Comment by alexsegura** [comment]
The `contactName` is not displayed by the app actually, even for "normal" tasks

https://github.com/coopcycle/coopcycle-app/blob/8ce1f42f36a480875acc420a540b993255a53b06/src/navigation/task/components/Details.js#L45-L47

Would need a small change on the app to display it properly.

**Comment by alexsegura** [comment]
For the phone number, we need to investigate. Indeed, the `telephone` property seems to be correctly stored in the `task_rrule.template` column in database (the JSON is correct, it is stored at `address.telephone`). 

Maybe it's the same issue as #3306.

**Comment by biologeek** [comment]
Seems like an issue with address updating. When creating a recurrent rule the address is half saved (contactName, company and telephone are not saved). When creating new tasks from recurrent rule, it does not update the address even though it has more data in template.

**Comment by alexsegura** [comment]
This should have been fixed here 5064c0a0883bedfb5bd693b463b7fa10368f440e...69713f2bf58f302450d74f121784d6eb1aa1ac57
