### ISSUE TITLE
Adding manual price onto recurrent deliveries

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3308]
When editing recurrent rules, there should be a possibility to set a manual price for each point. 

Then, when exporting data, (Linked to [#3262](https://github.com/coopcycle/coopcycle-web/issues/3262)), a price column should be telling us the price attached to each point.

**Comment by ERAMANrepartos** [comment]
I believe this problem is related to the same problems that we are trying to solve with dynamically priced multi-point deliveries and the universal export, correct @lucasferraro ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok we are tackling this now and I have a question. Do we want to have a price per point manually put in, or do we want the price to come from the pricing rules attached to the store? I think the second option right? Since they are recurrent tasks, there shouldn´t be random pricing that requires manual input right?

**Comment by AdrienSICKLO** [comment]
In an ideal world, I think all prices should be answering a pricing rule.
Yet in my talks to many cooperatives, it seemed that with the same potential client, they could have gone through the process of "quotes" for certain routes/locations/conditions that would differ from a "global offer" type. 

So this might be annoying but I think keeping a manual pricing set up on recurrent rules would be preferable.

**Comment by Paul-Eraman-CoopCycle** [comment]
But can you just make a pricing rule that reflects the use case of that service, so it only affects that recurrent task?

**Comment by AdrienSICKLO** [comment]
No, since you can't have more than one pricing rule for each client. 
The use case I have is a client that has ONLY specific requests: "that far away location every week Monday between 12 and 2"
Or "that other side of the city, Tuesday before 5pm,but you have to take shit from there also"
So pricing rule would not work

**Comment by Paul-Eraman-CoopCycle** [comment]
Closing due to out of scope, we can discuss in person
