### ISSUE TITLE
Tasks' icons overlay

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#331]
![selection_052](https://user-images.githubusercontent.com/13315760/39351503-09872500-4a02-11e8-8452-7e9bb7f27653.jpg)

**Comment by alexsegura** [comment]
I restored the padding on the right. 
Only for assigned tasks, to save space.

<img width="283" alt="capture d ecran 2018-05-25 a 13 32 46" src="https://user-images.githubusercontent.com/1162230/40542356-2a58f6ee-6020-11e8-8484-f98c7e3ec5d1.png">
