### ISSUE TITLE
Fix Woopit

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3332]
- [x] Update the `WoopitSubscriptionsCommand` to use API keys auth method instead of OAuth (9a71e38d98140ec8ef1591b5ff6e7267050026d8)
- [x] The `TaskListener::preUpdate` doesn't seem to be invoked when uploading images (e1134558e16df2e4c67295a3c78ea0e0550cd00e)
- [x] We shouldn't concatenate `addressLine1` & `addressLine2` in `CreateDeliveryTrait` / `UpdateDeliveryTrait`. Just use `addressLine1`. `addressLine2` should end up in the address description. 
- [x] We should parse the `packages` array, and put in into the task comments.

**Comment by lucasferraro** [comment]
@alexsegura 
Emilie told us by email that documents/pictures now are attached to the order that we've been testing, but in logs I don't see any handle of `AppBundle\MessageWoopitDocumentWebhook`.
After looking at the code I figured out that maybe we have some missing configuration [here](https://github.com/coopcycle/coopcycle-web/blob/e3b03b97ce87bf78261f40ec7437fe145399585f/app/config/config.yml#L161)?

**Comment by alexsegura** [comment]
@lucasferraro nice catch. Yes, it means the message was handled synchronously.
