### ISSUE TITLE
match address to address.name if saved restaurant or shop  

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#334]
One could therefore search and find an `address.name` while creating a new task

**Comment by Atala** [comment]
You mean to have a search field in the task form?

**Comment by alexsegura** [comment]
I think this is fixed.

Now, a store can have multiple addresses (and a default address for backward compatibility)

<img width="936" alt="Capture d’écran 2019-03-23 à 12 25 19" src="https://user-images.githubusercontent.com/1162230/54865546-1b823880-4d67-11e9-8008-a288b06b347b.png">

Also, when creating a delivery in the context of a store, the address picker now lists store addresses

<img width="823" alt="Capture d’écran 2019-03-23 à 12 26 38" src="https://user-images.githubusercontent.com/1162230/54865560-4a98aa00-4d67-11e9-8a30-571963ed792d.png">

Let's continue this discussion in #501
