### ISSUE TITLE
Marker : point&click and drag&drop

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#335]
Admin should be able : 

- to click on map for creating a task (optional)

- to drag & drop a created task. Sometimes geocoded address doesn't fit with reality

**Comment by Paul-Eraman-CoopCycle** [comment]
There is a plus button on the top right for creating a task, and the suggested way to move a pin is the address, since we need a correct geolocated address for things not to break in the UI for the messenger
