### ISSUE TITLE
Style password reset page

### ISSUE THREAD

**Issue by ccoreilly** [coopcycle/coopcycle-web#337]
Style is missing on password reset page:

![screen shot 2018-05-06 at 19 26 15](https://user-images.githubusercontent.com/11149784/39676050-f60b4736-5163-11e8-976f-0ffe47c7ae2c.png)

**Comment by alexsegura** [comment]
Go to http://localhost/profile/change-password to see the page.

We need to [override FOSUser templates](https://symfony.com/doc/current/bundles/FOSUserBundle/overriding_templates.html)

**Comment by alexsegura** [comment]
Fixed in #626
