### ISSUE TITLE
In order to [improve rider safety] As a [rider] I want [to have a panic button I can push in case of danger]

### ISSUE THREAD

**Issue by Camenavr** [coopcycle/coopcycle-web#3398]
**In order to**  `achieve something`
Add a pánico button if a woman from the federation is being harassed

**As a** `role`
All the women in this federation

**I want** 
We want support of the federation and take care of us

**Whereas currently** `this happens`
Its usual that we tend to be harassed while working

**Additional context**
In México with ITDP make a session for discuss our struggles and choose this solution

**Comment by NuriMensakas** [comment]
Una mejora importantísima y necesaria. Todo el apoyo des del estado español!

**Comment by ERAMANrepartos** [comment]
@NuriMensakas 
 Puedes explicar de manera detallada de como sería este feature? Es decir, estas en el reparto y estas entregando un pedido. Este buton, en que parte de la app esta? Que pasa cuando se usa? Se alerta a dispatch? Desde que tipo de notificacion? Como es diferente que hablar por Zello?
Me parece un feature muy importante, y hay que pensar bien como desarrolarlo y que haría de manera detallada.
