### ISSUE TITLE
How to manage registration through the API?

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#34]
We need to manage registration through external websites & native apps. 

As a first implementation, there is a [register endpoint](https://github.com/coopcycle/coopcycle-web/blob/d066a2dc4c5d27bc8c4b7b9c5d09833aea21c195/src/AppBundle/Action/Register.php) which automatically activates the user. 
But this seems not really satisfying, at least it could lead to lots of spam.

How to manage email verification anyway?
Is there a better way with API Platform?

**Comment by clementtalleu** [comment]
Why we dont use the natural behavior of api platform and just send the json request with name/username/email to the entrypoints `/people/  with the json content and let the api platform serializer do the job ?

The just add an event listener from the framework event system which activate automatically the account, or call a MailManager which will send a verification email with an unique token.

a post-write event  to send the email verification
then a custom operation for the verification which enabled the user ?

https://api-platform.com/docs/core/events

**Comment by Atala** [comment]
Done, closing.
