### ISSUE TITLE
Name of a store not updated after changing in the admin pannel

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3405]
**Describe the bug**
When the name of a store is changed, it does not updated everywhere. It appears correctly (=new name) on the [dashboard/deliveries] and on the [dashboard/stores] and not correctly (=old name) on the task details and in the application. 

**To Reproduce**
1. Create and configure a store
2. Save it
3. Change the name of the store
4. Genrate order or deliveries
5. See the differents name displayed

![nameOfTheStore_in_Admin dashboard_Stores ](https://user-images.githubusercontent.com/44605344/191721506-5f1bb5e5-2b38-47e6-86c0-7d828004144c.png)
![nameOfTheStore_in_Admin dashboard_Deliveries_#6575](https://user-images.githubusercontent.com/44605344/191721523-48e9a70c-4086-404e-baba-3a7908edf188.png)
![nameOfTheStore-in_details_of_task](https://user-images.githubusercontent.com/44605344/191721547-4d22806d-7fd3-4f4a-b9a9-8d4bfacde805.png)
![nameOfTheStore_in_courrier_app](https://user-images.githubusercontent.com/44605344/191721559-a8559090-9337-489d-838f-8b1073a7827f.jpg)

**Comment by biologeek** [comment]
May be related to address modification not propagated when an element of it is modified

**Comment by Paul-Eraman-CoopCycle** [comment]
Same as https://github.com/coopcycle/coopcycle-web/issues/3896, closing and tracking there
