### ISSUE TITLE
Command refused but Deliverie still visible on store dashboard

### ISSUE THREAD

**Issue by RSCMontreuil** [coopcycle/coopcycle-web#3409]
**Describe the bug**
A store made a mistake in a command so I refused it. The task are cancelled as expected, but the delivery is still there, with no specific attribute showing it is cancelled.

**Expected behavior**
A clear "cancelled" status should appear on the delivery

**Comment by alexsegura** [comment]
Cancelled tasks will now be shown with a ~strikethrough~

<img width="602" alt="Capture d’écran 2022-10-24 à 11 41 50" src="https://user-images.githubusercontent.com/1162230/197497695-44e49b40-4c38-4093-9d31-90cc7aa091cd.png">
