### ISSUE TITLE
To [avoid unnecessary emails] As [dispatch], maybe it's not necessary to receive notification emails when generating reccuring tasks.

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3412]
When a dispatch generate reccuring tasks, it's not necessary to send emails to notify for these tasks as if the tasks was created by the owner of the store.
Maybe it's necessary to notify but with another types of notifications (Eg: the task for [store] is correctly generated)

**Comment by ERAMANrepartos** [comment]
This is a larger issue about notifications and how they function, which is a new epic we are going to be dealing with during in the 2023 dev seminar. I am going to close this issue, but expect a new and very detailed issue about notifications to be created soon that takes this into account.
