### ISSUE TITLE
Impossible to change rules sequence in tarfication configuration

### ISSUE THREAD

**Issue by RSCMontreuil** [coopcycle/coopcycle-web#3415]
When configuring a tarification and using the "first corresponding rule" mode, if I change the sequence of rules and then save, the change is not saved.

![Impossible to change rules sequence in tarfication configuration](https://user-images.githubusercontent.com/105007527/192781398-335300fb-1353-4e0e-8389-eed64defd254.gif)

 - OS: Windows 7
 - Browser : Firefox 105.0.1

**Comment by AdrienSICKLO** [comment]
@alexsegura

**Comment by alexsegura** [comment]
Fixed in c012c92ea3e47b6fa326d8016c4c6692b76e9821
