### ISSUE TITLE
When a store adds deliveries with one pick up and multiple drop off, only the first drop off is linked

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3442]
**Describe the bug**
When a store adds deliveries  with one pick up and multiple drop off, only the first drop off is linked with the pick up and all these tasks show up in a random order instead of the tasks' number's order.

**To Reproduce**
1. The store introduces a delivery with one pick up and multiple drop offs. 
2. The tasks show up on the dashboard but only the first drop off is linked with the pick up. In addition, they all show up in a random order.

**Expected behavior**
All drop offs should be linked with the pick up and they should appear in the order of the tasks numbers.

**Screenshots**
I'll add a screenshot next time it happens promise! 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
OS: Windows 11 Professionnel
Browser : Chrome

**Comment by alexsegura** [comment]
Fixed in ee1f85fb617bd9f8e3c10e4022268ddef47adfb2
