### ISSUE TITLE
In order to be more efficient As a dispatcher I want the possibility of uploading csv files with groups in it

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3445]
**In order to**  be more efficient

**As a** dispatcher

**I want** the possibility to add a column :group: in the csv files so when the file is uploaded, the different tasks show up on the dashboard within different specific groups. 

*Whereas currently** it's not possible

**Comment by ERAMANrepartos** [comment]
This seems easy, but maybe I´m wrong. And for sure would be a good improvement!

**Comment by lucasferraro** [comment]
@rayon9coop @ERAMANrepartos 
How should this work with same group names? Should we allow to make different imports with same group name or a group name should be limited to just one import?

**Comment by rayon9coop** [comment]
Allowing different imports with the same group name for the same day can lead to confusion in reading the tasks and thus defeat the purpose of the group feature.

**Comment by lucasferraro** [comment]
> Allowing different imports with the same group name for the same day can lead to confusion in reading the tasks and thus defeat the purpose of the group feature.

I agree. 
I'm not pretty sure if we can implement (at least in an easy way) that a same name can be used for different days but not for the same. I'll check and give it a try and let you know.
Thanks

**Comment by ERAMANrepartos** [comment]
Hi! 
So I spoke with @alexsegura and the naming thing is a user problem, not a database problem. Currently there is no problem in the platform if two groups have the same name. So this means that it is just a user question, and theoretically, it makes sense to have unique group names anyways right?

I propose we add this capability without doing anything in regards to the names, and communicate when we push the feature that you should have unique group names

**Comment by rayon9coop** [comment]
Ok, great

**Comment by lucasferraro** [comment]
Ready for review in this PR https://github.com/coopcycle/coopcycle-web/pull/3643

**Videos with examples**

https://github.com/coopcycle/coopcycle-web/assets/4819244/5f026152-db00-40a4-bc17-0e4c1c9ffd0a
- Tasks with group name in csv file are grouped under that name after the import.
- Tasks without a group name in csv file are grouped under a default group (Import d/m h:s) as was the case before this implementation.

https://github.com/coopcycle/coopcycle-web/assets/4819244/066f3891-68d2-41be-874c-e31ab7229084
- Tasks with a group name equal to an already used one are imported and grouped in a new group but with the same name as the existing one (users should avoid this case).

**Comment by rayon9coop** [comment]
Nice @lucasferraro

**Comment by ERAMANrepartos** [comment]
@rayon9coop 
can you test this in real life and see if it is working correctly?

**Comment by rayon9coop** [comment]
It works! thanks

**Comment by ERAMANrepartos** [comment]
Woo! 🥳
