### ISSUE TITLE
In a multi-drops configuration (1 pickup + x dropoffs), unassigning (or reassigning) one of the dropoffs automatically unassigns (or reassigns) the pickup

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3454]
**Describe the bug
In a multi-drop configuration (1 pickup + x dropoffs), the pickup seems to be linked to all drops in the list. So de-assigning (or re-assigning) one of the dropoffs automatically de-assigns (or re-assigns) the pickup.

But it happens that some of the tasks encoded by a store's user are splited on two or more couriers. 

**To Reproduce**
1. Go to a store
2. Create one pickup and 3 dropoffs
3. Assign all these tasks to a courier
4. desassign one of the drop
5. see the pickup desassigned too

**Expected behavior**
When the pickup is assigned to a courier, it should stay assigned to this courier when de-sassingating drops or when re-assignating drops to another courier.

**Comment by ERAMANrepartos** [comment]
This is very important. By their nature, multi-dropoff orders are very likely to have the different drop offs done by multiple riders, so this makes things complicated.

**Comment by rayon9coop** [comment]
At the moment, to get around this issue, we use this annoying way: 
- duplicate pickup task 
- create groups 
- assign the groups to different couriers 

BUT the original pick-up must be done before all the drop-offs, otherwise an error occurs and the drop-off task cannot be completed. 
A solution would be to add a right click features called "split" for multi-drops orders. Spliting a multi-drops orders could create two groups of orders with one pickup in each

**Comment by Paul-Eraman-CoopCycle** [comment]
@alexsegura 
Remember we were talking about "locking" and "unlocking" routes? Should this be something we do with orders that are associated together this way? like, they would do this normally. But if you click a lock icon to "unlock" the 3 tasks, then you can reassign the tasks individually?

**Comment by Paul-Eraman-CoopCycle** [comment]
working now!
