### ISSUE TITLE
Allow duplicating a pricing rule

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3486]
Add a button on the list of pricing rules to duplicate a pricing rule. 
After the pricing rule is duplicated, the user should be redirected to the new pricing rule. 

Maybe the name of the pricing rule should be "Name of the duplicated rule (1)"

**Comment by alexsegura** [comment]
Duplicate of #1334

**Comment by lucasferraro** [comment]
> Maybe the name of the pricing rule should be "Name of the duplicated rule (1)"

I chose to prefix the name with "Copy of <Name of the duplicated rule>" so we avoid confusions with a number as a suffix, number that should be incremental to avoid repeated names.
