### ISSUE TITLE
In order to [save time and avoid mistakes] As a [dispatch] I want [a better reading and quick identification of recurring deliveries.]

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3502]
We make many deliveries for the same customer (some days, up to 6). We have set up this with the "recurring deliveries" function and this makes it easier for us to manage in this case. But with so many deliveries for the same store, it is not easy to identify on the dashboard each recurring delivery because there are few visible differences between each of them (see screenshot 1 below: days of the delivery and number of tasks in the recurring deliveries are the only visible differences). Often, when we want to know which reccurent delivery it is, we have to click on it to see the details in the pop up window. And when we close the pop-up window, the reccurent delivery we have just clicked on is not highlighted, so it is easy to be confused and not know which one has just been opened.

A clear description of a task you want to archive
Better reading and quick identification of recurring tasks.

**Like a** `role
This feature will be useful for dispatching.

**I want to** "add or change something".
Add the ability to name recurring deliveries. As you can see on screenshot 2 (photoshoped): the name could be displayed instead of "every week" (because this is not useful).

If this proposal is difficult to implement, at least highlighting the reccurent delivery we just clicked on will be useful in the meantime. 

<img width="272" alt="image" src="https://user-images.githubusercontent.com/44605344/208633362-cdafbd4a-6ce3-47dd-984d-2d2616f97df2.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/44605344/208634562-7ea54dbb-5218-4d9b-8c17-5a93f7964bd2.png">

**Comment by ERAMANrepartos** [comment]
@rayon9coop How is this different than #3452 ?

**Comment by rayon9coop** [comment]
It's the same one #NoteForMyselfNotIntroduceGithubBeforeCoffee

**Comment by AdrienSICKLO** [comment]
This is in technical review?

**Comment by Paul-Eraman-CoopCycle** [comment]
yep
