### ISSUE TITLE
On dashboard, be able to zoom in on a picture without having to download it

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3505]
**In order to**  save time to check a picture a courrier has taken on a task

**As a**dispatcher 

**I want** to be able to click on the picture attached to the task and have a zoom on it

**Whereas currently** the picture automatically downloads in order to see it.

**Comment by rayon9coop** [comment]
In the same area, it would be nice if the picture displayed in the POD file would be bigger

**Comment by ERAMANrepartos** [comment]
This specific issue was not thought of in the near future, but the visualization of the photo by a store without downloading is, and I believe that solving one issue would solve the other.

**Comment by Paul-Eraman-CoopCycle** [comment]
Yup this is a repeat
