### ISSUE TITLE
Be able to split the pick up and drop off of one delivery between two different courriers

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3507]
In the case of a delivery for which one courrier does the pick up and another one does the drop off, we have to wait until the pick up is done so we can unassign the 2 tasks and reassign the drop to the second courrier.

It would be great if the 2 tasks could move independently OR if we could create a hub stop in between the 2 tasks. For example, right click on the pick up -> route through hub -> it creates a drop off task at the hub for this delivery. Then the second courrier can pick up the task at hub and have the drop off task from the beginning.

**Comment by ERAMANrepartos** [comment]
Given that we often have to pass deliveries between riders, there is a whole concept here that we have not begun to touch that is a interchange point. This can both serve for picking up by one rider who then gives to another for dropoff, but also for things like doing a bunch of pickups in the morning that are taken to the office for sorting, then delivered in the afternoon, and other similar use cases.

**Comment by Paul-Eraman-CoopCycle** [comment]
Looks good to me! just did a test



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/001c1128-c50d-4d24-8793-dbe43a656bdb)
