### ISSUE TITLE
In order to avoid mistakes and save time,  I want [PRINT SHIPPING LABEL] for the deliveries created from a store

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3511]
When a store gives us a lot of packages to deliver, it's easy to make mistakes if the packages aren't labeled. Having the ability to print shipping labels when creating deliveries is helpful in avoiding mistakes and saving time. 

The print button could be added in two places: 
- On the "create a delivery" page (use case: the store owner creates a delivery, prints the label and sticks it directly on the package).
- on the deliveries page (use case: the dispatcher prints the labels, gives them to the courier in charge of collecting/delivering the packages who will stick them him/herself). 

<img width="933" alt="image" src="https://user-images.githubusercontent.com/44605344/209542304-b77148e4-7c2b-480b-8dc6-8741b7b8f722.png">
<img width="941" alt="image" src="https://user-images.githubusercontent.com/44605344/209542351-7a0c26ac-6773-420b-b7eb-485f7ea56a64.png">

**Comment by ERAMANrepartos** [comment]
https://github.com/coopcycle/coopcycle-web/issues/3629

**Comment by Paul-Eraman-CoopCycle** [comment]
What information should be on this shipping label? other than a tracking element such as a QR code or bar code?

**Comment by rayon9coop** [comment]
Yes, a qr code or a code bar + 
- name of place (company)
- name of contact
- adress
- phone number

**Comment by Paul-Eraman-CoopCycle** [comment]
https://github.com/coopcycle/coopcycle-web/issues/3629 
repeat of this, closing
