### ISSUE TITLE
Correct data privacy issue with GPS tracking

### ISSUE THREAD

**Issue by RSCMontreuil** [coopcycle/coopcycle-web#3515]
**Describe the bug**
The delivery tracking starts when the delivery is assigned to a rider. Hence the store can see courier position, possibly for a very long time (can be a week if dispatch is done early).

see https://coopcycle.slack.com/archives/C4VH560ES/p1671629560784849?thread_ts=1671099658.184979&cid=C4VH560ES

**Expected behavior**
Tracking should start when courier starts the task: when courier hits the "start" button on app or maybe when he finishes previous task on his run.

**Comment by ERAMANrepartos** [comment]
When you say "the delivery tracking" what do you mean? A store cannot see a courier position as far as I know... 
@alexsegura ?
