### ISSUE TITLE
In order to save 2 clicks As a client/admin on the delivery form I want have default package set already chosen

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3526]
I use the packages for this client just to mention the number of parcels in each delivery. So I just have one package that is "parcel"

When I create a delivery, the form says "choose your type of package"
![image](https://user-images.githubusercontent.com/59842043/213665949-e2b8db11-88c7-4f49-a943-2c6bad64736b.png)

We enter a lot of deliveries everyday and it could save us a bit of time if by default, the only package we have would be chosen:

![image](https://user-images.githubusercontent.com/59842043/213666150-793ac92c-e8c7-4d39-a6fa-bce344b64bed.png)

**Comment by alexsegura** [comment]
Actually, it should be auto-selected when there is **ONE** package. It is a very small micro-optimization.
