### ISSUE TITLE
I need to give possibility to show or not price to BtoB customer

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3538]
I'd like to have the possibility to choose not to display the price to a customer even when pricing rule is attached and orders are enabled.

I think this setting should happen here:

![image](https://user-images.githubusercontent.com/59842043/216947528-5d38a0c0-7b6d-4c13-8f26-454958e27ab5.png)

**Comment by ERAMANrepartos** [comment]
@AdrienSICKLO What is the use case here?
