### ISSUE TITLE
Delivery over several days does not appear in store deliveries list

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#3539]
**Describe the bug**

A delivery which pickup is over 2 or more days, does not appear for store nor in admin delivery list. It only appears as tasks on dashboard.

**To Reproduce**
1. Create a delivery for which pickup is over 2 days
2. As a store admin, go to delivery list
3. Acknowledge delivery is not visible
4. As a Coopcycle admin, got to store, then to its delivery list
5.  Acknowledge delivery is not visible

**Expected behavior**
Delivery should be visible, either in today's or tomorrow's deliveries

**Screenshots**

Pickup task :
![Screenshot from 2023-02-06 18-38-49](https://user-images.githubusercontent.com/11749973/217047104-2ccd6bed-3a05-4b3f-b90c-e3cd4e3b0cae.png)
Delivery list (visible delivery is not the same) :
![Screenshot from 2023-02-06 18-50-42](https://user-images.githubusercontent.com/11749973/217047199-ba6a76ca-351d-45f1-8f91-80f3d131d989.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Additional context**
After testing with dropoff, having it over 2 days does not affect delivery visibility. It only bugs when pickup is over 2 days.

**Comment by Paul-Eraman-CoopCycle** [comment]
Fixed! 🥳
