### ISSUE TITLE
In order to save time and collect valuable information as a dispatcher, I want to filter the tasks in which the couriers have written a comment

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3540]
**In order to**  `achieve something`
I want to daily track and followup the info collected by couriers

**As a** `role`
Dipatcher in first but to every couriers because they would profit of the previous experiences 

**I want** `something to be added or changed`
in the filter function under tab "general" there should be added: "tasks with courier's note"

**Whereas currently** `this happens`
If I want to read the comment, I have to open each task or export all the tasks and read comments in csv

**Comment by ERAMANrepartos** [comment]
Where are you imagining this feature? I dont know where you mean when you say "under tab ´general´". 
Maybe really, this is a "reports" dashboard that we do not yet have that could tell us how the day before has gone with relevant information about if the deliveries were done in their time frames, number of deliveries done, comments / incidents made...

**Comment by rayon9coop** [comment]
Tab "Général" is there
<img width="655" alt="image" src="https://user-images.githubusercontent.com/44605344/235307967-30b14dde-a756-47ec-9410-7e097074c09f.png">
Yes a "reports" dashboard will do the job. Anything with easy way to show comments added to tasks by courriers

**Comment by ERAMANrepartos** [comment]
Got it, makes sense. thanks!

**Comment by Paul-Eraman-CoopCycle** [comment]
Maybe a better place would be to have any order not successfully completed in all its tasks to show up in a tab in the shops history page that would be called "incidents"

**Comment by rayon9coop** [comment]
> Maybe a better place would be to have any order not successfully completed in all its tasks to show up in a tab in the shops history page that would be called "incidents"

This seems to me less practical for a dispatcher but useful for a store owner. But from my point of view, these are two different uses: my issue concerned the difficulty for a dispatch to quickly identify failed deliveries (pickup and/or dropoff).

**Comment by Paul-Eraman-CoopCycle** [comment]
we are doing this in incidents, this is repeated in other issues.

already can be done really if you use incidents. anyways, onward and upward :)
