### ISSUE TITLE
"View all restaurants" link ineffective on Firefox

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#3542]
**Describe the bug**
The "View all restaurants" is ineffective on up-to-date Firefox desktop browser

Works on Safari and Chrome.

See attached GIF for illustration.

Can provide further information if necessary.
![see all restaurants](https://user-images.githubusercontent.com/101735534/217352815-91a86437-a35f-4462-b893-a8434198694b.gif)

**Comment by ERAMANrepartos** [comment]
@alexsegura what is happening here??

**Comment by alexsegura** [comment]
The (transparent) top menu overlaps the link when there is not enough space.

![sicklo_menu_bug](https://github.com/coopcycle/coopcycle-web/assets/1162230/fcf41ad1-ae67-4c42-b4b1-427498a47eab)
