### ISSUE TITLE
Improving the "tour" concept

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3552]
There has just been introduced the concept of Route.

A couple remarks:

- [x] #3590
- [x] #3591
- [x] #3595
- [x] #3597
3-It is not possible to add a task to existing route folder by dragging and dropping.

**Comment by rayon9coop** [comment]
An additional remark: when creating 2 tours from 1 PU and several DROP created in a store, the tasks remain attached together (when unassigning one of the two routes, the tasks of the other route also unassign)

**Comment by rayon9coop** [comment]
![bug](https://user-images.githubusercontent.com/44605344/221530955-98a2bb72-5457-47ab-9f03-145a4eb06cc0.gif)

**Comment by rayon9coop** [comment]
Another remark: the colour band on the left of the tasks of the same tour should be unified, to facilitate reading. In the gif, the color still the one created when the store created the tasks (the colors was not modified when creating a tour)

**Comment by alexsegura** [comment]
@rayon9coop 

> Another remark: the colour band on the left of the tasks of the same tour should be unified, to facilitate reading. In the gif, the color still the one created when the store created the tasks (the colors was not modified when creating a tour)

It's not possible, the color bands will stay related with linked tasks (pickup linked with a dropoff). It's a "historical" meaning, and it's hard to change this.

**Comment by fortyoneandahalf** [comment]
Just jumping on here to offer my services with user testing and providing feedback for the tours/routes changes. This is functionality we (tricargo) have been pushing for for a while and would potentially make heavy use of, so happy to spend some time helping to make it as good as possible.

**Comment by ERAMANrepartos** [comment]
Yeah we if we want to take last mile seriously (we do) this is an important thing to have done, and done well

We havent worked past the first implementation of this, but for sure we need them to be able to be done with imports
