### ISSUE TITLE
I want orders that a restaurant delays to automatically change in the admin dashboard

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3564]
**Describe the bug**
If I have the admin dashboard open during a shift, and an order is on the top of the list (when ticked as see in groups, the first option), if a restaurant delays an order, it does not automatically change the time or order in the orders list. 

**To Reproduce**
1. Do a shift
2. Restaurant delays and order
3. The time and position in the admin dashboard does not change until page refresh

**Expected behavior**
Automatically updating

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/77277854/222821363-29e6b400-e03e-431b-89d7-5427e60fbd4e.png)

**Comment by ERAMANrepartos** [comment]
related to #3081
