### ISSUE TITLE
I would like a new order organization option where they are organized by color by time ranges

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3565]
**In order to**  `achieve something`
In order to better understand how many orders will need being picked up in the next time ranges (10 min, 20 min, 30 min for example) 

**As a** `role`
As a dispatcher in admin dashboard

**I want** `something to be added or changed`
I want another organizational option in the list that organizes by pickup times in 15 min ranges

**Whereas currently** `this happens`
Currently there is no good way to see visually the volume of orders in the next 10-30 minutes in an organized way, and it is easy for an order to be lost in the mix. 

**Additional context**
What we want is not just in list, but an option that ADDS A NEW COLOR BAR in which pickups within 10-15 min are red, 15-30 in yellow, after in green AS WELL AS an indicator of the total number of each category

![image](https://user-images.githubusercontent.com/77277854/222823209-540f5f1c-045b-40ad-b3d0-728f494d687f.png)

**Comment by ERAMANrepartos** [comment]
In retrospect, this is really about a larger issue about the visualization of orders over time, and is an epic we need to deal with more globally.
