### ISSUE TITLE
In order to facilitate dispatch with high volumes I want to be able to hide rider profiles with one click

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3568]
**In order to**  `achieve something`
In order to save time during the stressful first 30 minutes of a dispatch shift for urgent deliveries (food) I want to make it easier to apply a filter to rider profiles in the admin panel

**As a** `role`
As an administrator using the admin panel 

**I want** `something to be added or changed`
I want a button to hide riders directly on the panel

**Whereas currently** `this happens`
Currently I have to open up the filter box, hiding the names of the riders, remember the rider I want to hide (no visible organization that I see to facilitate this) and desactivate them, scroll down to the save button, and save. 

**Additional context**
It is a small issue, but a small fix. Is a significant task given the stress levels during the time period this is usually an issue, and one that grows exponentially over time.

![wanttonotseeriders](https://user-images.githubusercontent.com/77277854/222856824-77595b02-3189-4873-80e0-a3a7fb57b580.gif)

![image](https://user-images.githubusercontent.com/77277854/222857524-55e1f1f9-40b0-4d5b-a2e3-fa7facb6af6a.png)

![image](https://user-images.githubusercontent.com/77277854/222857497-9046ceaf-01f4-4d5b-be5c-06974ef19e3d.png)

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle do you want the interface to be like in your screenshot above or is it enough that it is available in the filters modal as here

![Image](https://github.com/user-attachments/assets/96349445-ba60-47c6-9889-c766b36ece1f)

**Comment by Paul-Eraman-CoopCycle** [comment]
itd be better like on my screenshot i think, because then you dont forget what you are filtering and loose track of things, but if this is what we have now, its fine for the moment. id just make an issue for the interface ive mentioned to put in a design "to do later" bucket
