### ISSUE TITLE
Introduce multiple reusable packaging, a.k.a "formats"

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3577]
It should now be possible to configure multiple packages for a single product. 
For example, it should be possible to configure 1 medium package + 1 small package. 

Basically, there should be a "+" button, to add more rows of reusable packaging. 
Also, right now the database relationship is 1-1 between products and packagings, it should now become a 1-n relationship. 

This needs to be implemented for IMPEC, but this also needs to fit with our "internal" system.

**Comment by ERAMANrepartos** [comment]
This issue is unclear. Please clarify.
