### ISSUE TITLE
Delivery creation failed

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3578]
**Describe the bug**
Creating a delivery with two tasks does not work (the two tasks are not linked)

**To Reproduce**
1. Import a task (pickup)
2. Create a drop
3. Select both
4. Click right and create delivery
5. see error
![delivery](https://user-images.githubusercontent.com/44605344/225560407-3a56ddb1-ba15-4fe7-a375-7f0c10ff70a9.gif)

**Comment by ERAMANrepartos** [comment]
@alexsegura @r0xsh @lucasferraro 
who can take a look at this? This is a critical error

**Comment by r0xsh** [comment]
I know that @jimakker & @alexsegura are currently working on this part. Maybe the issue #3595 will solve this issue

**Comment by ERAMANrepartos** [comment]
@alexsegura will #3595 solve this too?

**Comment by rayon9coop** [comment]
I just tried, this error still happening, yes

**Comment by Paul-Eraman-CoopCycle** [comment]
Sorry, but can you check this again? @rayon9coop

**Comment by rayon9coop** [comment]
Seems working now

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
