### ISSUE TITLE
Allow rate limiting orders by time window for a restaurant

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#3580]
**In order to**  `achieve something`
I want to make it possible to limit the total amount of product sold to be picked up in a 15 minute time range (alternatively, a total number of orders)

**As a** `role`
As a restaurant owner/chef

**I want** `something to be added or changed`
I want to define a maximum amount of basket amount in euros that can enter in a specific time range, and any order that pushes the total over the limit, this order will be put into the next delivery range slot. 
For example: for increments of 15 minutes, my restaurant can make a total of 10 orders with an average size of 2 hamburgers with fries, which is generally a 30 euro order. I want to be able to state that in 15 minutes the limit is 300 euros of product, and if an order enters that pushes the total income from that 15 minutes over 300 euros, then that order will be put into the next 15 minute pickup or preparation time range.

**Whereas currently** `this happens`
Currently I can use "rush mode" to increase my preparation times, but this is a REACTIVE response and not at all dynamic. So no matter if I use this or not, I can have 10 orders enter within 5 minutes, all with the same pickup time. This is impossible to prepare, and during such a shift, I cannot stop to pick which 5 orders I want to delay, delay them one by one, etc

**Additional context**
Restaurant options in regards to normal preparation time and rush preparation time
![image](https://user-images.githubusercontent.com/77277854/225335647-6db69ec8-64a5-4815-8f2c-29835919a495.png)

Button to active Rush Mode as a restaurant
![image](https://user-images.githubusercontent.com/77277854/225335907-56d15ee3-6e3f-4a3b-b734-0bcea2741bd7.png)

Dispatcher delay bar for entire cooperative delivery service
![image](https://user-images.githubusercontent.com/77277854/225335790-8da4e124-5e57-45a1-abcc-b4c874a7a3e9.png)

The "Cumplimiento" menu page on a restaurant with opening hours and other configurations, where we imagine this feature would exist, potentially as a piece of information you add to the time ranges for delivery range options of 10, 30 or 60 minutes
![image](https://user-images.githubusercontent.com/77277854/225336349-ecb9630c-fa8a-48a1-bc09-1a629b2771a3.png)

MORE CONTEXTUAL INFORMATION
In a more general sense, we want to add more tools to a restaurant in regards to how orders enter. This is because traditionally a restaurant has a relatively low level of orders and the issues could be resolved with the "rush mode" or manually by delaying individual orders. Now we are having, and hope to have, more restaurants with 50+ orders in a night. To do this effectively we need more tools that allow restaurants and the cooperative to manage their "production". Other options might include:
1. A button that closes the next available 15 minute pickup window time range
2. A delay bar for individual restaurants that only affects their orders
3. Splitting the visual organization in the application of orders into time ranges with borders between them, and allowing the possibility to drag and drop an order from one time range into another, with automatic notification to the cooperative and the client about the change in pickup time

And a photo of

**Comment by alexsegura** [comment]
Linked with #1989 & #1418

**Comment by ERAMANrepartos** [comment]
A new concrete proposal
Here are three photos: 
1. An opening hours set of rules that function as a range, within which the algorithm picks 10 minute windows for delivery to the client2. 
2. An opening hours set of rules that function as a block of time in which a delivery will happen (no algorithm)3. 
3. A proposal in which the second type of rules (just a time that chosen by the cooperative) also has a limiting factor (the red dots). There would be a field that asks how many total orders can enter for this delivery window, after with, that time rate would close, as if we were to un click the blue box manually and click save on the page. 

It is not perfect and a better option would be to do this with pickup time not drop off, but for the moment this would solve 80% of the problems, and would not involve changes to the rest of the code, i assume, since it is really just automating a process that we can already do manually




![C74ABAB7-59E0-42C6-B3D9-23CB4451887F](https://user-images.githubusercontent.com/77277854/226100265-57d26430-26d3-4343-9ff9-69e6edb312ab.jpeg)
![BB698496-B9D4-4228-ABE0-B58FE4B62989](https://user-images.githubusercontent.com/77277854/226100268-405f5db8-6f6f-4311-8abe-9d2c2747b147.png)
![6E1EBEAD-9212-4ED9-8ECE-C158B2842B85](https://user-images.githubusercontent.com/77277854/226100269-6eca2ca3-b62e-47f9-adef-029c8ded7950.png)

**Comment by alexsegura** [comment]
To implement this, we need to add another check in the [ShippingDateFilter](https://github.com/coopcycle/coopcycle-web/blob/ca4f5df9ef37c5b0abcad6d695abc9e0ff9247b2/src/Utils/ShippingDateFilter.php), that returns false if the corresponding dropoff slot should not be proposed to the customer. 

What we want, in the end, is a rule for each restaurant where we can say : 

> No more than X orders by ranges of Y minutes

⚠️ When we say "by ranges of Y minutes", we talk about **the pickup time**, because this is what the restaurant is interested in. 

---

1/ Add 2 columns to the `LocalBusiness` class, to store the settings:
- `max_orders_range_duration` (ex: 20 minutes)
- `max_orders_amount` (ex: 10)

By default, they are NULL, which means there is no limits. 

2/ Add a class `PickupRangeQueue`, that holds the logic to check if the ranges are full, etc. 

```php

interface PickupRangeQueue 
{
  // Returns false if $pickupTime has more than or equal number of orders 
  // for the corresponding range
  // We also have $order, to load the settings for the restaurant
  public function isRangeFull($order, $pickupTime): bool;
  
  // Increments the counter for the corresponding range in $order
  public function increment($order);
}
```

Probably, it would be best to materialize the queue in Redis, for best performance. 

3/ Add a listener in `app/config/message_bus/order.yml`, that increments the counter when the `order:created` event is triggered.

**Comment by alexsegura** [comment]
Some interesting stuff about rate limiting in [this article](https://www.codementor.io/@arpitbhayani/system-design-sliding-window-based-rate-limiter-157x7sburi)

**Comment by ERAMANrepartos** [comment]
Possible related error: We had an order come in AFTER eatyjet was manually closed tonight, which sounds to me like it may be related to the "entrance point" issue that @r0xsh and I were talking about.
code is 2N40 from Saturday the 15th.

overall the filter is working, but tonight for example, the 10 minute ranges starting at 19.40 go as follows:
5
4
1
2
4
5
4
5
6
4
4
4
5
4
6
6
4
4

When the filter should be at 4 orders per 10 minutes. 
So good, but some stuff is slipping through. Its good enough we can defend it to the restaurant, but any thoughts on how to find those entrance points?
thanks!

**Comment by ERAMANrepartos** [comment]
https://github.com/coopcycle/coopcycle-web/issues/3650
