### ISSUE TITLE
Bulk actions on tasks

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#359]
It should also be possible to select several task (via CTRL + click), and apply bulk actions on them.

- [x] #1341
- [x] #1697 
- [x] #1273
- [x] #1356
- [x] #836

**Comment by alexsegura** [comment]
[react-contextify](https://github.com/fkhadra/react-contexify) looks cool for this.

**Comment by alexsegura** [comment]
Some progress in a8b05784a9bba454ba41440fd1061bdf5c2eb322
It's only about selection, you can still perform no action on the selected tasks 

![task_multi_toggle](https://user-images.githubusercontent.com/1162230/40544835-daa528c0-6029-11e8-8ced-af181f873186.gif)

**Comment by alexsegura** [comment]
Added the possibility to cancel several (unassigned) task at once in 3c818783c084989410031adada47aed64c2177cc

![bulk-cancel](https://user-images.githubusercontent.com/1162230/66079457-61188d00-e564-11e9-8d0e-820bb4789884.gif)

**Comment by couleurmate** [comment]
Dupplicate several tasks would be a useful option ;)

**Comment by couleurmate** [comment]
bulk assignement too

**Comment by alexsegura** [comment]
Since #1696 it is possible to select markers by drawing an area (with CTRL key)

**Comment by alexsegura** [comment]
Since 1ce313ae4ef4fa89b1c30fb88d58f273bf5e7b61, it is possible to change the date of several tasks at once.

<img width="656" alt="Capture d’écran 2021-02-10 à 14 10 50" src="https://user-images.githubusercontent.com/1162230/107516448-b9c25600-6bac-11eb-84b7-aeb4356a31cc.png">

**Comment by Paul-Eraman-CoopCycle** [comment]
Has been done! 
🥳
