### ISSUE TITLE
Optimize Webpack build

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#36]
Webpack build currently takes up to 4 minutes to complete. 
This is way too long. 

We need to find ways to reduce the build time.

**Comment by alexsegura** [comment]
When using Node 8, it now takes less than 3 minutes.

**Comment by Atala** [comment]
Which version of webpack? I just updated it in my work branch to `3.5.5`.

In my container
```
real	1m 22.70s
user	1m 20.10s
sys	0m 2.26s
```

If the problem persists, this look nice: http://engineering.invisionapp.com/post/optimizing-webpack/ .

**Comment by alexsegura** [comment]
@Atala is it the time for the `webpack -p` command?

**Comment by Atala** [comment]
Yes - can you try again? I changed the webpack version in `master` .

**Comment by alexsegura** [comment]
Ok now it takes around 2 minutes 👍 

<img width="580" alt="capture d ecran 2017-08-29 a 01 50 17" src="https://user-images.githubusercontent.com/1162230/29798519-be712dfc-8c5d-11e7-8b91-88366d02c9c8.png">

Which version of NPM are you using? 
Please make sure to commit the `package-lock.json` file each time you update packages 😉

**Comment by Atala** [comment]
Yes sorry, I messed up at some point.

```
/srv/coopcycle # node -v
v8.2.1

**Comment by alexsegura** [comment]
Let's ropen it later if needed.

**Comment by alexsegura** [comment]
Since we are using Bootstrap Sass, Webpack is very slow. 

I'm trying to profile it using [this](http://webpack.github.io/analyse/)
