### ISSUE TITLE
Extend options on right-click menu of assigned tasks

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3605]
In the dispatch map allow selecting 1 or multiple assigned tasks and by doing right-click show in the context menu the options:

- assign to another courier (same day)
- move to the next (open) day
- duplicate
- copy (not duplicate) -> on this click, it opens a New Task pop-up window with all the data of the copied task (unlike duplication, copying allows to change some data without changing the data of the copied task)
- finish task

Related to :https://github.com/coopcycle/coopcycle-web/issues/1962
and https://github.com/coopcycle/coopcycle-web/issues/3604

**Comment by Paul-Eraman-CoopCycle** [comment]
finishing right now, duplicate
