### ISSUE TITLE
Which payment processor do you use?

### ISSUE THREAD

**Issue by s33d3r** [coopcycle/coopcycle-web#361]
Which payment processor do you use?
Is it possible to run coopcycle in countries outside Europe?
Have you thought about using stripe?

**Comment by Atala** [comment]
We are indeed using Stripe as a payment processor.
It is possible to run CoopCycle outisde Europe, but we don't support multi-currency yet.
If you have a specific use case and want to work with us, please send us a mail at contact@coopcycle.org .
