### ISSUE TITLE
If I have too many orders/deliveries in my xxx.coopcycle.org/admin/deliveries page history, it breaks how the page is loaded and responds with a 504 error, and I cannot access any info related to stores

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3622]
**Describe the bug**
Upon reaching over around 500 deliveries in both the "Today" and "Upcoming" categories, the xxx.coopcycle.org/admin/deliveries can no longer load due to an excess of deliveries trying to be represented. This has the consequence of:

1. Cannot upload any more tasks as an administrator from the /deliveries page
2. Store cannot upload tasks, view history, or access any of their portal since their landing page is responding with 504 error
3. All information inside of the /deliveries page (pricing rules, zones, store settings, etc) is inaccessible without knowing the independent urls of those pages

**To Reproduce**
1. upload 500+ deliveries for today and or tomorrow
2. try to enter xxx.coopcycle.org/admin/deliveries
3. See 504 error

**Expected behavior**
Not having a 504 error

**Desktop (please complete the following information):**
 - Only happens on web browser I believe, we didn´t test in the app

We can fix this by limiting how deliveries are represented on the page, but we should also think about how to better refactor this page and its information.

**Comment by ERAMANrepartos** [comment]
Solution: Implement tabs in the page for Today, Upcoming, and Past so that they do not all need to upload at the same time. This is a short term fix until the stores dashboard is redone later this month.
