### ISSUE TITLE
Creating an order from two tasks in the admin dashboard only works 25% of the time

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3624]
**Describe the bug**
When right clicking a pickup and a dropoff the option to create an order only works some of the time, the rest of the time it has no effect. 

**To Reproduce**
Steps to reproduce the behavior: _from the admin dashboard in the web browser_
1. Make a pickup and dropoff task
2. ctrl+click each so they appear in yellow
3. right-click and select "create order"
(Also see here error #3623 )
4. select a shop
5. Most likely see tasks remain unaffected (in my quick test it only worked 25% of the time)

**Expected behavior**
It creates an order

**Screenshots**
![createorderrightclick](https://github.com/coopcycle/coopcycle-web/assets/77277854/30658cf4-e0dc-42c5-9862-c634b1f27802)

**Desktop (please complete the following information):**
 - Firefox web browser

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle maybe check again this one?
