### ISSUE TITLE
Colors band of the two tasks of an order are randomized on the app while they are correctly displayed on dispatch pannel

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3645]
**Describe the bug**
It's all in the title ;-)
This bug does not help couriers to understand the link between two tasks if they do not follow each other. For example, if a courier has to do this round: 
PickUp ORDER1 
PickUp ORDER2
PickUp ORDER3
Dropoff ORDER2
Dropoff ORDER3
Dropoff ORDER1

the color bands on the left in the app could help to understand which pickup is related to each dropoff:

**Expected behavior**
The same bands colors in the app than in the dispatch pannel (and not randomized, obviously)

**Screenshots**
<img width="266" alt="2023-05-19 08_04_09-RAYON9" src="https://github.com/coopcycle/coopcycle-web/assets/44605344/87d93892-147b-4bb1-8052-8f54a94eb1db">
![photo_2023-05-19_08-03-47](https://github.com/coopcycle/coopcycle-web/assets/44605344/101742a1-6ee1-4940-ac97-1f09b0448335)

**Comment by Paul-Eraman-CoopCycle** [comment]
@rayon9coop can you check if this is still the case?

**Comment by rayon9coop** [comment]
This is fixed, yes!
