### ISSUE TITLE
Address not recognised by app although it exists in GoogleMaps

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3647]
**Describe the bug**
The adress Rue Visé - Voie 81, 4000 Liège is not recognised by the app althought it exists in GoogleMaps.

I have tried 3 ways to create a delivery with this address:

1. Import a delivery (linked to a store): in this case, the application returns an error "The price could not be calculated" 

2a. Import a task with this address (not linked to a store): in this case, the application deletes the house number and creates a task with this address "Rue Visé - Voie, 4000 Liège" (without the house number).
2b. Correct the adress manually (insert a house number and select the adress suggested by Google): the app erase the house number after saving the modification

3a. Create a pick-up task and a drop-off task by clicking on "+": This creates a task at the correct address (with the house number) 
3b. Create a delivery with these two tasks (with the right click option, linked to the same store than step1): this create a delivery with the exact adress (but this is the most annoying way to do this :-)

**Screenshots**
![bug](https://github.com/coopcycle/coopcycle-web/assets/44605344/24b6d63f-2b2d-4255-b80a-9df9f63288ee)
![bug2](https://github.com/coopcycle/coopcycle-web/assets/44605344/f2d16534-812a-42cc-bba6-65d6df396192)
![bug3](https://github.com/coopcycle/coopcycle-web/assets/44605344/28c4c2d6-2772-4a11-baea-89a4f8044b25)

**Comment by Paul-Eraman-CoopCycle** [comment]
Can you confirm this is still happening and it is with Google Maps activated?

**Comment by rayon9coop** [comment]
No, this not happened anymore (fyi Google maps is activated since long time in our instance).

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
