### ISSUE TITLE
Tax calculation is wrong

### ISSUE THREAD

**Issue by ccoreilly** [coopcycle/coopcycle-web#365]
Tax is not being calculated correctly. The following example from the demo illustrates it.

The product has a tax of 10% and the delivery a tax of 20% which should give a total tax of:
16,08 * 10% + 3,50 * 20% = 2,343 €

![screen shot 2018-05-28 at 13 21 59](https://user-images.githubusercontent.com/11149784/40612281-24bea2c2-627a-11e8-8094-8671c6a8c70e.png)

**Comment by alexsegura** [comment]
You are right, there was an error: the tax amount for delivery was not added to the tax total. 

However, your formula is wrong 🤓
**Taxes increase the price excluding tax**. 
- Excl. tax = `100`
- Incl. tax = `100 * 1.2 = 120`
- Tax = `20`

But on the platform, **prices are tax inclusive**. 
So, the formula is : 

- Incl. tax = `16.08`
- Tax = `(16.08 - (16.08 / (1 + 0.1))) = 1.46`
- Excl. tax = `(16.08 - 1.46) = 14.62`

And if we apply the taxes to the price excluding tax, everything is ok: `14.62 * 1.1 = 16.08`

In you example above, the the tax total should be `1.46 + 0.32`

**Comment by ccoreilly** [comment]
Thanks for fixing this Alex. 
You are right, I forgot the 16.08 is the price including tax.
