### ISSUE TITLE
In order to improve usability of the notifications, as a dispatcher I want to be able to scroll the modal

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3655]
**In order to**  `achieve something`
Be able to scroll in the changelog to see past actions

**As a** `role`
Dispatcher

**I want** `something to be added or changed`
To be able to scroll down and up the past actions

**Whereas currently** `this happens`
I can only see the last 5 actions

**Additional context**
![imagen](https://github.com/coopcycle/coopcycle-web/assets/77277854/ed642a77-c3b1-4259-8756-78c088d2b0c3)

**Comment by alexsegura** [comment]
I agree there should be more than 5 notifications, but IMHO we shouldn't implement (really) endless scroll inside the popup.
Instead, there should be a link in the popup, that leads to a page listing all the notifications.

**Comment by alexsegura** [comment]
Yeah currently the implementation is really dumb... what disappears is what has been seen by user, i.e always the last 5 notifications.

https://github.com/coopcycle/coopcycle-web/blob/393148759acfef96da8c60fdf2286c943a6b11a0/src/Controller/ProfileController.php#L426-L437
