### ISSUE TITLE
In order to improve usability, as a dispatcher or restaurant manager/cook I want the search bar to function correctly in the orders dashboard

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3660]
**Describe the bug**
The search bar in the orders dashboard appears to be a * based query, which results in unusable results for specific (non general) searches. In photos the examples are

- no search
- searching "3" returns any order with a 3 in it (i believe)
- searching a specific order code returns a number of results that appear unrelated

**To Reproduce**
1. Go to ['...'](https://demo.coopcycle.org/admin/restaurants) or https://demo.coopcycle.org/admin/foodtech/dashboard/2023-05-28
2. Try to search
3. See error

**Expected behavior**
The search to have a clear function. What is it searching? using what rules? If we only have a single search bar (no filters) then we should have it search only order code, name, and address and return results based on an = rules

**Screenshots**
![imagen](https://github.com/coopcycle/coopcycle-web/assets/77277854/17b15f7b-73c5-4821-8fde-4719d212dc18)
![imagen](https://github.com/coopcycle/coopcycle-web/assets/77277854/4ca68b50-b212-4327-8e56-9157bc40ed15)
![imagen](https://github.com/coopcycle/coopcycle-web/assets/77277854/8c23ceff-760c-4ef6-ad99-7b91e4b2e29c)

**Desktop (please complete the following information):**
firefox

**Comment by Atala** [comment]
https://coopcycle.slack.com/archives/C05QBHGD51T/p1719313856687779

i do find different results from thomas and serge , i dont know why

to be investigated

**Comment by Atala** [comment]
sorry wrong issue
