### ISSUE TITLE
Server selection stopped working

### ISSUE THREAD

**Issue by AwesomeKuro** [coopcycle/coopcycle-web#3671]
Switching between servers is not allowed.
Contact information from each server isn't the expected information after server selection.

**Comment by DanielBustillos** [comment]
it would also be desirable to see all the messages in a grid, so all the are shown to the user without swiping

**Comment by AwesomeKuro** [comment]
@DanielBustillos

**Comment by DanielBustillos** [comment]
Please find the details below:

**Issue 1: Switching between servers is not allowed**
As mentioned by @Paul-Eraman-CoopCycle, when accessing a city with multiple coops, the app displays a horizontal list of coop names. However, two issues have been observed:

Swiping does not work to navigate between coops.
The coops on the far right of the screen do not receive the same visibility as the initial ones.
To address this, I suggest modifying the presentation of coops by displaying them in a list format, similar to the city selection. This would ensure better navigation and equal visibility for all coops in the app.

**Issue 2: Inconsistent contact information after server selection**
Although I could not replicate this issue personally, it has been reported that the information displayed in the left panel of the app does not match the selected courier (server). While I will make further attempts to replicate this problem, I have come across another related issue:

**Issue 3: "Under Maintenance" text displayed when selecting Mexico City in the City Menu**
Upon selecting Mexico City from the 

City Menu, an "Under Maintenance" text is shown. Please refer to the following image:

<img width="234" alt="city selection" src="https://github.com/coopcycle/coopcycle-web/assets/18301658/49e52214-1afd-4c13-9036-b5f25a0245e4">
