### ISSUE TITLE
In order to identify special clients during service, I want to be able to associate tags or flags with clients

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3684]
**In order to**  `achieve something`
To improve customer service I want to be able to identify users as 
1. VIP
2. ProblemClient
3. WeSkrewedUp

In such a way that later, when they create a new order, this special status can be communicated to the relevant users. 

**As a** `role`
Everyone

**I want** `something to be added or changed`
In a user´s profile page I want a clickable button that can identify them as a VIP, PC, or WSU
I DO NOT WANT THEM TO SEE THIS INFORMATION IN THEIR PROFILE

Also, should these categories be modifiable by the cooperative? If so, if would be easy to use the existing tags feature and the cooperative makes a tag associated with them.

HOWEVER then the visualization of those types of "Flags" (flags alert you to important information in real time that you might miss otherwise, tags are an organizational tool) must be different. maybe a bar instead of a circle. 

**Whereas currently** `this happens`
Nothing, we cannot do this

**Additional context**
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/2f27d3b8-fb0c-4bfd-99bf-7c0d83fdc45c)

**Comment by AwesomeKuro** [comment]
What does "bar instead of a circle" mean? Which UI element is this referring to?

**Comment by alexsegura** [comment]
To make an entity "taggable", it needs to implement the `TaggableInterface` and use the `TaggableTrait`, much like in the `Store` class or the `Task` class. So in this case, it needs to be added to the `Customer` class. 

Then, you can use the `TagsType` form type inside the `UpdateProfileType` form type to have a tags input

https://github.com/coopcycle/coopcycle-web/blob/df74398e21659e288ff717638dcd1bde5b23a2c9/src/Form/StoreType.php#L80-L82

**Comment by AwesomeKuro** [comment]
I tried setting tags up with User and Customer, I can see the form being able to select tags, but I cannot get them saved.
I don't know what else I would have to set up, or I did wrong.

https://github.com/coopcycle/coopcycle-web/commit/730e29744c002ff4774ab09f087679338aa8493e

**Comment by AwesomeKuro** [comment]
For the tags to not show in the profile page
I implemented it but as i didn't see any other method to check if the user has the admin role, i used isSuperAdmin
Do i have to implement a different method?

Tags now show on the admin/orders page. But i couldn't implement the same for the foodtech dashboard...

**Comment by Paul-Eraman-CoopCycle** [comment]
After testing, the tag doesn´t appear:

- [ ] If the tagged user makes an order from a shop 
- [ ] Food order - seen in the admin panel 
- [ ] As a courier either in the map or the list view

It appears that they are only in the orders dashboard
I will make new issues for these use cases



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/83558ebc-e12c-4677-9242-8fd334cecc6d)

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/ce96d512-cf7c-41e6-a1eb-22204984d960)


![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/77fed2ba-439e-4a2d-a61d-b991f1c4ed02)


![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/ab282a21-f3b7-42f5-9f6a-eefbd281fd06)
