### ISSUE TITLE
CoopCycle does not get alerted to some orders that are created in Stripe

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3688]
**Describe the bug**
An order is created in Stripe but does not show up in CoopCycle. Seems to occur more frequently if we close a restaurant for the evening

**To Reproduce**
Check the following orders in Eraman

Order 2TBE (no modo localizar a la persona) para Maickers
2 pagos erroneo y cancelado por mi
Receipt from Eraman Koop
Receipt #1312-9939
 AMOUNT PAID
€27.95   
DATE PAID
May 5, 2023, 10:51:44 PM   

Order 2TNA  (tenemos email de la persona) para Eatyjet
Receipt from Eraman Koop
Receipt #1699-9785
AMOUNT PAID
€26.40   
DATE PAID
May 6, 2023, 8:53:17 PM   

Order 2TH7 (no modo localizar a la persona) para Eatyjet
Receipt from Eraman Koop
AMOUNT PAID
€35.00   
DATE PAID
May 6, 2023, 9:03:30 PM   

Order 2U39

Order 2U51

Order 2U4W
hizo 2 pedidos existoso Order 2U5A

Order 2U6T

Order 2U7M

Order 2U8E

**Expected behavior**
All Stripe orders to be communicated successfully to Eraman

**Comment by Paul-Eraman-CoopCycle** [comment]
Empty customer bug

**Comment by Paul-Eraman-CoopCycle** [comment]
june orders fitting this decription eraman

Pollo Bueno
37EN  delivery  6/25/2023 13:00
34IC  delivery  6/11/2023 14:30

El 7 (todas en fila, tres pedidos seguidos)
353M  delivery  6/14/2023 22:05
352E  delivery  6/14/2023 21:05
34ZH  delivery  6/13/2023 21:55

Dolomiti
34YZ  delivery  6/13/2023 22:00
37O2  delivery  6/25/2023 22:15
352C  delivery  6/14/2023 20:46

Koxka
323G  delivery  6/2/2023 22:00

Txoko
317C  delivery  6/13/2023 21:30
33YU  delivery  6/9/2023 23:00

Arkupe
355H  collection  6/15/2023 12:50

Txakurzain
352J  delivery  6/14/2023 19:00
33B0  delivery  6/15/2023 14:00

Dottor Pizza
33SO  delivery  6/14/2023 20:55
371P  delivery  6/23/2023 22:40
37YM  delivery  6/28/2023 22:00

Burger House / Maikers
35YC  delivery  6/18/2023 00:05
353S  delivery  6/14/2023 22:40

Mano Lenta
34X6  delivery  6/13/2023 15:00

eatyjet
3895  collection  6/30/2023 23:00
3672  collection  6/18/2023 21:00
34A9  delivery  6/10/2023 23:00
36CX  delivery  6/18/2023 23:30
38DL  delivery  6/30/2023 22:15

**Comment by Paul-Eraman-CoopCycle** [comment]
Patched but not fixed, moved to backlog

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle if you can find any recent examples, please add them here, and I can try to find any traces in the logs. 

So far, I have not been able to reproduce this issue, so I propose in the app:

1. update the stripe library to do a minor cleanup/refactoring
2. log errors to Sentry for all unhappy paths
3. maybe show a different error message to a user if the payment succeeds, but an error happens after that

It's also possible that some of these orders come from the website, but I'll not look at it for now until we have any evidence of that

**Comment by vladimir-8** [comment]
Closing this issue, as it currently happens less often than it used to. If it happens again, lets look at each case individually first
