### ISSUE TITLE
Restaurants reopening without admin intervention, allowing erroneous orders

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-web#3696]
Certain restaurants that were previously marked as closed are reopening without any action from the admins. This issue is allowing customers to place orders at these restaurants, even though they are actually closed. As a result, erroneous orders are being placed, causing frustration for both customers and cooperatives.

![image](https://github.com/coopcycle/coopcycle-web/assets/5613584/7c5aa89f-9645-4328-b8ad-625790141041)

**Comment by Paul-Eraman-CoopCycle** [comment]
Nope :/

**Comment by Paul-Eraman-CoopCycle** [comment]
hasnt happened in a long time, closing until we get more reports
