### ISSUE TITLE
Translate calendars

### ISSUE THREAD

**Issue by theneilkirk** [coopcycle/coopcycle-web#370]
As a user, date selectors should be in my selected language.

<img width="1170" alt="screen shot 2018-06-01 at 22 13 53" src="https://user-images.githubusercontent.com/38278363/40863936-a4afa05e-65e9-11e8-936d-d153d0482332.png">

**Comment by alexsegura** [comment]
Fixed in 330d74631fdb487094703c02381cff068bd10d06
