### ISSUE TITLE
Pay in cash option has a step that cannot be completed

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3702]
**Describe the bug**
When in the "payment" step of the foodtech order process as a B2C customer where there should be the option to pay by card or by cash (latin america), there is a money icon that should be clickable and that will activate pay by cash. 
This money icon is not clickable, and does not do anything. 

**To Reproduce**
1. Go to Payment as a foodtech customer
2. Click on the money icon
3. See error

**Expected behavior**
the cash payment feature to function

**Screenshots**
![imagen](https://github.com/coopcycle/coopcycle-web/assets/77277854/9c6129e3-b04c-449b-854f-274ed3d5a996)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucasferraro** [comment]
Already fixed. There was a missing configuration in that Data Base instance.

**Comment by Paul-Eraman-CoopCycle** [comment]
Where is this deployed so it can be tested?

**Comment by lucasferraro** [comment]
> Where is this deployed so it can be tested?

This was an error related to Bogota instance. It has been fixed and can be tested there.

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
