### ISSUE TITLE
To [manage tours or groups] As a [dispatcher], I want [a right-click menu with different options on them]..

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3704]
All is in the title :-)

In the menu, it could be interresting to have possibility to:
-<s> move whole group or whole tour to the next day : for now, the only way to do that is to select tasks one by one</s> ->  #3853
- create a tour with a whole group of tasks (no mandatory pickup)
- create a delivery with a whole group of tasks (pickup mandatory)
- undo group
- undo tour

**Comment by Atala** [comment]
In the menu, it could be interresting to have possibility to:
- move whole group or whole tour to the next day : for now, the only way to do that is to select tasks one by one -> https://github.com/coopcycle/coopcycle-web/issues/3853

    create a tour with a whole group of tasks (no mandatory pickup) -> no pickup is mandatory
    create a delivery with a whole group of tasks (pickup mandatory) -> exists already
    undo group 
    ~undo tour -> is deleting a tour is this issue #3715

**Comment by Atala** [comment]
Everything is already done or moved to other issues, so closing
