### ISSUE TITLE
In order to improve address book feature. As a [Dispatcher/courier] I want [to have more options to specify address]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3708]
Right now, address book works as follows:
![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/f5e12079-2d96-47b5-9030-660ef019e97c)

This feature helps us gain time. Yet some other options would be very much useful like:
-Opening hours of the client
-Instructions to enter.

Also, doing that, a way for the dispatcher/courier to quickly see problematic opening hours would be nice. But maybe tags do the job.

**Comment by Paul-Eraman-CoopCycle** [comment]
these options can be added in the address book in the additional info field. not perfect honestly, but a viable workaround. closing for now as not planned
