### ISSUE TITLE
Problem when selecting multiples drop offs and assigning them. 

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3709]
I noticed a bug while assigning deliveries to people. When you select through CTRL+Select on map with mouse option, and you select only drop offs, when you assign them, the software doesn't drag and drop both pick up and drop offs, just drop offs.

![Bug livraisons en pick up](https://github.com/coopcycle/coopcycle-web/assets/59842043/bce36ca7-bae8-4824-adef-6ffc247d9c9a)

Expected behavious would be to drag both pick ups and drop offs attached together

**Comment by Paul-Eraman-CoopCycle** [comment]
repeat issue, closing
