### ISSUE TITLE
Translate Store Hours elements

### ISSUE THREAD

**Issue by theneilkirk** [coopcycle/coopcycle-web#371]
As a user who has selected a language other than French, I should see Store hours in the selected language.

To reproduce:
1. Log in as admin
2. Navigate to Stores > Add new
3. See Opening hours

This was reproduced on local machine and on demo.coopcycle.org

I also couldn't find translations for these elements in https://translate.coopcycle.org

<img width="489" alt="store hours" src="https://user-images.githubusercontent.com/38278363/40944131-8a7359d8-684b-11e8-824b-aad46dbf5c31.png">

**Comment by Atala** [comment]
It is #99 that will be soon fixed thans to @Ladias-Elie !
