### ISSUE TITLE
Tours/routes appear and reappear instead of being deleted or not

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3714]
Right now, there's no possibility to delete a Tour. So the only way you have to delete it is to delete the tasks from the folder by clicking on the cross. When you have no tasks in a tour, the folder disappears.
Yet, the software still attaches that task to the tour. So when you reassign a task, it recreates the tour it was originally put in. 

See gif in issue #3709 

The solution would be to delete or not a route, and it then appears or does not appear accordingly

**Comment by jimakker** [comment]
I think this is the same bug as https://github.com/coopcycle/coopcycle-web/issues/3718

**Comment by Paul-Eraman-CoopCycle** [comment]
@jimakker should this be closed then? theoretically #3718 is fixed

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
