### ISSUE TITLE
When right-clicking on several tasks I want to be able to create a tour (no pickup mandatory) 

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3717]
**Describe the bug**
when selecting various tasks in the admin panel as a dispatcher or admin the way it does or does not allow the creation of routes is confusing.

No route option or any options- highlighting various pickups and no dropoff
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/097c686e-4ace-4969-9937-02d349d6e6af)

Route option - highlighting dropoff and pickups can make a route
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/d6ac00ea-09af-4410-a4f3-cc4b62711b2a)

Group option but no route - highlighting various pickups
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/848794bf-0c0b-4238-858f-e65b630ec582)

**Comment by jimakker** [comment]
Yes, a pick and a drop are needed to create a Tour (or Delivery). This, if needed, should be an enhancement not a bug?

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle what is the expected behaviour here? do you want users to be able to create tours without a pickup?

**Comment by Paul-Eraman-CoopCycle** [comment]
Well i dont know frankly. There does need to be a start and end point for each tour (should be the office!) but when im making a route i might not be thinking about that. 

Thinking about the workflow, we need to define the hubs of the coop i think if we are going to have routes, and when i make a route, it should ask from which hub this courier is beginning and ending his shift. 

Ill end a finished route with dropoffs for sure, but when im creating one im in a sort of brainstorming sketching mindframe, seeing how to make things fit together 

doe that help?

**Comment by Atala** [comment]
is there such notion as "coop hubs" in the platform yet? (+ be aware that HUBS are something else in the platform for now)

I see what you have in mind but you are answering me for a new feature it seems to me but I think for v1 we can keep it simpler. 

in my mind if there is no real reason we should remove the pickup is mandatory thing

**Comment by Atala** [comment]
As a side-note it is already possible to create a tour without a pickup so either we drop the requirement either we enforce it.
