### ISSUE TITLE
Can't add/edit Store Opening Hours

### ISSUE THREAD

**Issue by theneilkirk** [coopcycle/coopcycle-web#372]
As an admin adding a new Store, I must be able to set Store Opening Hours. Currently, clicking the 'Ajouter' button hides the opening hours.
To reproduce:
1. Log in as admin
2. Navigate to Stores > Create a new store
3. Click 'Ajouter' in the Opening Hours section

This was reproduced locally and on demo.coopcycle.org

<img width="1249" alt="hide opening hours" src="https://user-images.githubusercontent.com/38278363/40944522-07365ec4-684d-11e8-9250-bbc0ea8600dd.png">

----

As an admin editing a Store, I must be able to edit the Opening Hours.
To reproduce:
1. Log in as admin
2. Navigate to Stores > Manage > Settings
3. See Opening Hours section (or lack thereof)

This was reproduced locally and on demo.coopcycle.org

<img width="1187" alt="no opening hours" src="https://user-images.githubusercontent.com/38278363/40944602-4e32ec02-684d-11e8-8f7b-43a7bd17a416.png">

**Comment by alexsegura** [comment]
Ok I can reproduce it, there is an error in the console.

<img width="593" alt="capture d ecran 2018-06-05 a 10 35 31" src="https://user-images.githubusercontent.com/1162230/40964775-3d368e54-68ac-11e8-8098-7b39f2471ee8.png">
