### ISSUE TITLE
Routes are counted as a task in the number of tasks a messenger has assigned

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3723]
**Describe the bug**
When a rider is assigned a task, the number that should say how many tasks they have assigned counts the route as a task.

**To Reproduce**
1. Go to admin panel
2. Assign a route with tasks to a messenger
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/0dffb68c-1925-4488-a01c-2c0baf27fbd3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucasferraro** [comment]
There are other bugs related to routes and tasks:

- Wrong counting in the progress bar of completed/uncompleted tasks
- Unassign all uncompleted tasks action don't take into account tasks in a route.

https://github.com/coopcycle/coopcycle-web/assets/4819244/2db3b122-fcc1-493e-8db0-7ef5ff4759e9
