### ISSUE TITLE
Export of tasks creates a csv file in which some lines are not consistent with the format

### ISSUE THREAD

**Issue by En-Roue-Livr** [coopcycle/coopcycle-web#3736]
Some of these inconsistent lines are preceded by a blank line. See attached example/
[Extrait pour mex.xlsx](https://github.com/coopcycle/coopcycle-website/files/12396063/Extrait.pour.mex.xlsx)

**Comment by Paul-Eraman-CoopCycle** [comment]
Is this still occuring?
i have never seen this anywhere else

**Comment by En-Roue-Livr** [comment]
Hi Paul. Can you tell how this type of export is generated? I did not export anything since this failure.

**Comment by Paul-Eraman-CoopCycle** [comment]
Hey, just saw this coment. this is an export fom the order page 
https://demo.coopcycle.org/admin/orders

I believe this issue no longer occurs, closing for now. if you see it again please reopen
