### ISSUE TITLE
API endpoint to create deliveries for shop orders

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#374]
This is a proposal & an RFC to reintroduce an API endpoint to create deliveries. 
There used to be such an endpoint, but right now deliveries are [read-only](https://github.com/coopcycle/coopcycle-web/blob/823643d2d1a561be898350faf2e1ff4a340272dd/src/AppBundle/Entity/Delivery.php#L17)

The goal is to allow external systems (i.e, an e-commerce website) to create deliveries
This way, merchants having an existing e-commerce website could delegate the shipping to a coop using CoopCycle 
As an example, there is some draft work in [coopcycle-wp](https://github.com/coopcycle/coopcycle-wp) to add a CoopCycle Shipping Method in WooCommerce

### General idea

A `Store` in CoopCycle represents the external store. 
It provides a user account to the store owner, and allows grabbing an API Token. 
When an API call is received with a Store token, it creates a `Delivery` with a pickup address corresponding to the store address defined in the back-office. 

### Authentication

I'm not sure we can use JWT authentication as-is for those tokens, as they need to have a long TTL. 
Maybe we will need to use a custom token system & authenticator in Symfony Security?

### Keep track of the external order

I think we will need to keep track of the order on the external system. 
Maybe we could create a "fake" order in our system too?

### JSON payload

Here is an example of JSON payload 

```
POST /api/deliveries
{
  pickup: {
    before: "2018-06-08 12:00:00"
  }, 
  dropoff:  {
    address: {
      streetAddress: "67, rue de la Sorbonne", 
      firstName: "Jane",
      lastName: "Doe", 
      telephone: "+33612345678"
    },
    before: "2018-06-08 14:00:00"
  }, 
  order: {
    code: "00000001"
  }
}
```

**Comment by Atala** [comment]
I think keeping track of the delivery ID/delivery status should be the responsibility of the external site requesting a delivery.

IMHO, it would be sufficient to have a `metadata` field that can store arbitrary JSON from the client.

Side-feature would be to configure webhooks for store, but I think it is out of scope for a first iteration.
