### ISSUE TITLE
I rename the Store and the old name appears in admin panel and in the rider tasks 

### ISSUE THREAD

**Issue by padinspy** [coopcycle/coopcycle-web#3740]
**Describe the bug**
When I change the name of a shop, the old name continues to appear in various places; but NOT in the store name field in the shop configurations page.

**To Reproduce**
<img width="1280" alt="Capture d’écran 2023-08-31 à 17 15 18" src="https://github.com/coopcycle/coopcycle-web/assets/97370943/e53c465b-f30b-4e56-b9a0-115d879a495a">
<img width="1280" alt="Capture d’écran 2023-08-31 à 17 15 13" src="https://github.com/coopcycle/coopcycle-web/assets/97370943/22bc57a4-2baa-4bee-954f-778818a177bc">

1. find an old shop
2. rename it as an administrator
3. make deliveries or orders
4. See error in admin panel or as a rider

**Expected behavior**
The new name to appear in all places starting from the moment i make the change in the name

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
Same as https://github.com/coopcycle/coopcycle-web/issues/3896, closing and tracking there
