### ISSUE TITLE
Old Magasin name appears in the tasks

### ISSUE THREAD

**Issue by En-Roue-Livr** [coopcycle/coopcycle-web#3741]
Since the deletion of Magasins is impossible, I recycle those that are not used.
- I renamed Caves G in Epicerie P.
- I create a command for this customer.
- The name that appears in the tasks is Caves G.
Please either allow the deletion of Magasins or correct this bug.

**Comment by Paul-Eraman-CoopCycle** [comment]
is related to this: https://github.com/coopcycle/coopcycle-web/issues/3740

will track there, closing this issue
