### ISSUE TITLE
Ghost pins after correction/cancellation of a task

### ISSUE THREAD

**Issue by En-Roue-Livr** [coopcycle/coopcycle-web#3744]
Import the attached file. The 4th address of the tour is wrongly interpreted, and the resulting mileage is 494 km.

Option 1 : Double-click the task and correct the address with "3 rue Jean-Jacques Rousseau, Annecy". The address is stored and the pin is moved, but the mileage is unchanged and the route still uses the ghost pin. Refreshing the page and using the optimisation icon don't help. You ave to unassign and reassign the task. Then mileage and the route are correct. This is a workaround if you can keep the task.

Option 2 : Double-click the task and cancel it. The mileage is now zero and no route is displayed. Unassign et reassign all tasks. The mileage is 494 km again and the cancelled task is still taken into account even though it has no pin. You have no more chance to correct the address. This is a major bug because the data confuses the dispatcher, the courier and the invoicing.

Remaining ghost data can be seen on 26/05/2023 of En Roue Livr instance.

**Comment by Atala** [comment]
Done
