### ISSUE TITLE
Multi-currency support

### ISSUE THREAD

**Issue by theneilkirk** [coopcycle/coopcycle-web#375]
As a cooperative that doesn't operate in a country using Euro, I should be able to transact in another currency.

As a cooperative in the UK, I must be able to operate in GBP.

**Open Questions**

- [ ] Is true multi-currency support required?
- [ ] Which currencies should be supported?
- [ ] Which currencies can be supported?

**Comment by alexsegura** [comment]
There is now a setting to parameterize the currency per instance. 
For now, let's test with EUR & GBP.
