### ISSUE TITLE
Notifications not going to zero after deleting all the notifications

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3750]
**Describe the bug**
I deleted all my notifications but the notifications modal in the admin panal (and other places) still shows "3"

**To Reproduce**
1. delete your notifications
2. See modal not at 0

**Expected behavior**
The number should go to zero

**Screenshots**
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/b4038e9b-da48-44ee-9f81-e0a3bf925ad7)

**Desktop (please complete the following information):**
 - OS: ipad
 - Browser Firefox

**Comment by lucasferraro** [comment]
Hi @Paul-Eraman-CoopCycle , I can't reproduce this bug. I tried with different users and for all of them after remove all notifications the counter went to 0. Is it still happening for you?

**Comment by Paul-Eraman-CoopCycle** [comment]
Fixed, closing! 🥳
