### ISSUE TITLE
In order to [facilitatate giving back my reusable packages] As a [client] I want [to change how many of each category I want to give back]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3754]
See in picture, I cannot give back only one of the three different packages I have of a single category.

To solve problem I would need to mention the number of packages to give back.

![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/a7745848-7c87-4903-9182-28224a8850a0)

Potentially interesting enhancement could be that the platform suggests that you give back all packages you are supposed to have?

**Comment by alexsegura** [comment]
Also, the summary is now clearer, and suggests to return containers if possible. 

<img width="975" alt="Capture d’écran 2023-09-07 à 14 43 56" src="https://github.com/coopcycle/coopcycle-web/assets/1162230/26803375-88f7-4c26-ab3e-ec454914331e">
