### ISSUE TITLE
Support for timezones

### ISSUE THREAD

**Issue by theneilkirk** [coopcycle/coopcycle-web#376]
As a cooperative, I should be able to set my timezone.

**Comment by alexsegura** [comment]
The first thing to do is to store dates in UTC in the database. 

See [Handling different Timezones with the DateTime Type](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/working-with-datetime.html#handling-different-timezones-with-the-datetime-type) in Doctrine docs. 

See also [Storing Date/Times in Databases](https://derickrethans.nl/storing-date-time-in-database.html)

> To store information in a database, I would use a char column-type to store the whole America/Santiago timezone identifier and another char column-type to store the date/time (in the yyyy-mm-dd hh:ii:ss format). Alternatively, you can pick a 'datetime' column-type, as long as that type ignores timezones altogether. For MySQL that is the DATETIME column-type, and for PostgreSQL the TIMESTAMP or TIMESTAMP WITHOUT TIME ZONE column-types.



There is also a [TimezoneType](https://symfony.com/doc/3.4/reference/forms/types/timezone.html) if we need to manage the timezone in settings.

**Comment by alexsegura** [comment]
In bb865727bd768e594f6687d720458c0ef8fb4259 & 65ff6858565e8dccab80353c9051d342b65e152b, there is a minimal support for timezones.

In short, the timezone is injected via a PHP-FPM param, so all dates in PHP use this timezone by default. Also, the same timezone is set globally in Moment.js.

**Comment by alexsegura** [comment]
https://kylekatarnls.medium.com/always-use-utc-dates-and-times-8a8200ca3164

**Comment by ERAMANrepartos** [comment]
Not necessary, close
