### ISSUE TITLE
In order to [know the state of my deliveries] As a [store owner] I want [the information availabe]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3760]
At the moment it is not possible for the store to easily know if a delivery is yet to be done, has been picked up or has been done. 

![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/8c703e4a-d52a-453f-bd4a-3dc05f865395)

A simple use of pictograms ✅ would help significantly the customer to feel better about the deliveries he's giving us.

**Comment by r0xsh** [comment]
Close for duplicate: #3806
