### ISSUE TITLE
In order to [have the same capacity as a store owner] As a [admin] I want [to have the same dashboard when going on the deliveries section of store]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3761]
The new dashboard is only accessible when registered as a store owner, not an admin 
![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/0f23d698-4692-44b9-95d9-6f438f44c0f9)

If you use "dashboard" in the URL instead of admin, you will see the new dashboard. Otherwise, you'll end up on the old one. 

![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/8399ef8a-0eec-4f27-9668-ef644823f1f7)

**Comment by Paul-Eraman-CoopCycle** [comment]
we have made improvements here
