### ISSUE TITLE
Api still not making prices

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3766]
**Describe the bug**
The API with carrefour should be making prices for deliveries by making them into orders, but it is not

**To Reproduce**
1. Go to samo instance
2. Click on orders
3. See that there are no orders from carrefour
4. Clicking on a delivery also seeing that there is no price associated

**Expected behavior**
Carrefour market deliveries should be made correctly into orders and a price should appear

**Screenshots**
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/37ec8c58-6fc6-4a6b-809c-bccefc92be67)
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/136ac9e9-487e-4150-8f6d-46ca5d616756)
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/ebbe0bb1-fc05-4dc6-bf76-62f95a7815b3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/dfa87315-073b-4ee5-850c-d87badd47733)

**Comment by alexsegura** [comment]
Fixed in e8527b8d86faaa19b1cc0ec880b5bb2f270bfb81
