### ISSUE TITLE
Enhance Task Rescheduling Feature

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-web#3767]
The current Task Rescheduling feature is a "MVP" that allows dispatchers to reschedule tasks. However, to improve the feature's functionality for dispatchers, we need to implement the next iteration.

**1. Different Pricing for Rescheduled Tasks:**
Currently, when a dispatcher reschedules a task, the pricing remains the same as the original task. However, it would be beneficial to allow dispatchers to set a different pricing for rescheduled tasks. This can be useful when additional costs or discounts need to be applied due to the rescheduling.

**2. Reschedule Counter in Export:**
To provide better visibility and reporting on rescheduled tasks, we should introduce a new field in the task export data that shows a reschedule counter. This counter will indicate how many times a particular task has been rescheduled. This information can be invaluable for analyzing trends and optimizing task scheduling and dispatching.

**Comment by Paul-Eraman-CoopCycle** [comment]
We are doing #1 directly in the incidents page, and #2 is something that is interesting, but we will return to in a workshop about incidents V.3
