### ISSUE TITLE
Excel file with several tabs is rejected upon importation of a tournée. 

### ISSUE THREAD

**Issue by En-Roue-Livr** [coopcycle/coopcycle-web#3790]
L’importation d’une tournée n’admet pas que le fichier Excel ait plusieurs onglets.
Nous importons des tournées à partir des données fournies par le transporteur. Pour la conversion des données, nous utilisons un fichier Excel intermédiaire qui possède plusieurs onglets. Le premier est celui qui contient les données pour CoopCycle, avec les bonnes en-têtes, y compris address. Son importation génère un message d’erreur inadéquat : "You must provide an "address" (alternatively "address.streetAddress") or a "latlong" (alternatively "address.latlng") column". Le message devrait être "The file should have only one tab" ; mieux encore, l’importation pourrait ignorer les onglets qui n’ont pas le format attendu.
Remarque : le message reste affiché tant qu’on est sur cette page. Une croix de fermeture serait bienvenue.

**Comment by alexsegura** [comment]
For me, it's not a bug. The file should be provided in the expected format, period. 

> Event better, the import may ignore tabs that don't have the expected format.

Sorry, but no. If we did this, we wouldn't be able to distinguish valid files from invalid ones, and invalid files would be ignored instead of triggering errors.
