### ISSUE TITLE
Improve error response when uploading files

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3791]
As mentioned in this closed issue:
https://github.com/coopcycle/coopcycle-web/issues/3790

When importing an excel with multiple tabs and an error occurs as an administrator, the message is not clear. We need the error message to communicate that "in tab X the column A has an incorrect header"

**Comment by r0xsh** [comment]
Fixed by: https://github.com/coopcycle/coopcycle-web/commit/408687913e46e6bcd7a287536aa32e55d2150b0c
