### ISSUE TITLE
How could it be possible to add document to a delivery request ?

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-web#3794]
**In order to**  `achieve something`
A clear description of a goal you want to archive

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
A clear and concise description of what is to be added or changed in the software

**Whereas currently** `this happens`
A clear and concise description of what happens now

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
Repeated, closing
