### ISSUE TITLE
Stabilize Mocha tests

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#38]
Sometimes the Travis build fails on Mocha tests. They are timing out. 
Most of the time, clicking on "Restart build" solves the issue.

We need to make sure tests run correctly on each build.

<img width="1325" alt="capture d ecran 2017-08-20 a 19 04 59" src="https://user-images.githubusercontent.com/1162230/29496814-bffb0ae6-85da-11e7-82fc-cdc6c9344b71.png">

**Comment by Atala** [comment]
Added a potential fix, please reopen if it happens again.

**Comment by alexsegura** [comment]
Still the same : https://travis-ci.org/coopcycle/coopcycle-web/builds/269913681

**Comment by alexsegura** [comment]
The issue has disappeared magically, let's reopen if it appears again.
