### ISSUE TITLE
In order to have consistency with flags, I want the flag for comments to appear in the admin dashboard

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3800]
Right now flags about comments that are appearing in the orders dashboard do not appear in the admin dashboard and they should

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/ab41ef5c-9188-42c6-96a9-a8271ad97dd9)

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/50de78d4-7376-4e3f-b9ad-082342b02b59)

**Comment by Paul-Eraman-CoopCycle** [comment]
Comments for the restaurant should show up in pickup and comments for the delivery should show up in the dropoff

**Comment by Paul-Eraman-CoopCycle** [comment]
Other than the flag in the task in the panel, this also is a good thing to have inside the task for sure. I don't know if its better to have here or in the "more information" part at the beginning, but this looks good to me here yes

**Comment by lucasferraro** [comment]
I think "more information" section is related to instructions/info of the address or contact. For now I think is fine outside that section.

**Comment by vladimir-8** [comment]
It seems that it has already been reviewed and merged: https://github.com/coopcycle/coopcycle-web/pull/3819 Should we close it? @Paul-Eraman-CoopCycle
