### ISSUE TITLE
Assigned tasks cannot be reordered in bulk

### ISSUE THREAD

**Issue by fortyoneandahalf** [coopcycle/coopcycle-web#3812]
**Describe the bug**
When trying to reorder tasks assigned to a rider within the Assigned panel of the admin dashboard, they can only be reordered individually. Trying to select multiple tasks and drag them all at once results in a variety of strangeness in the UI - in particular, the tasks often appear in the list at the point they were dragged to, but the original list entries remain, and some tasks then cannot be selected/deselected.

Refreshing the page to clear the UI bugs shows the tasks in their original position, without having been moved at all.

**To Reproduce**
- Create four tasks and assign them to a rider.
- Highlight the final two tasks in the rider's list of assigned tasks and drag them to the top of the list.
- Observe the UI bugs mentioned above.
- Refresh the page.
- Observe the tasks remain where they were originally.

**Expected behavior**
The selected tasks should be moved to the point in the list to which they are dragged.

**Screenshots**
[Screen recording](https://drive.google.com/file/d/1in4IP2xnbIjTzqvHOuUn2B20WTo3cwEn/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by Paul-Eraman-CoopCycle** [comment]
This buggy behavior should be fixed for sure, but i also think our upcoming routes feature will fix this specific use case, keep an eye out in the next weeks
