### ISSUE TITLE
Inaccurate behaviour of the search engine in delivery form

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3821]
Hard to understand the pattern that makes the behaviour of the search engine. Sometimes, it does not work the way it should be, see GIF below.

The follwing steps were done:
-Search by name --> Not found
-Delete the first attemp, right the name in full script "Caisse" --> Finds it.
-Delete the second attemp, try again with the same attempt using the same letters --> Work.

![search engine](https://github.com/coopcycle/coopcycle-web/assets/59842043/c5cbb1bc-24c0-4dc5-ad24-fd736330938b)

**Comment by Paul-Eraman-CoopCycle** [comment]
https://github.com/coopcycle/coopcycle-web/issues/3825

**Comment by vladimir-8** [comment]
See also: https://github.com/coopcycle/coopcycle-web/issues/4017#issue-2144186548

**Comment by Paul-Eraman-CoopCycle** [comment]
Ideally this field should search:

- addresses
- Names
- Contact names

from the saved customers for that shop. For example, for the shop BIO, their saved customers are themselves, and a "name" client: https://demo.coopcycle.org/admin/stores/26/addresses

**Comment by Paul-Eraman-CoopCycle** [comment]
Fixed by https://github.com/coopcycle/coopcycle-web/issues/3825
🥳
