### ISSUE TITLE
Customers can add extra stops and edit order information after the order has been created. (this is bad)

### ISSUE THREAD

**Issue by IheringERAMAN** [coopcycle/coopcycle-web#3822]
**Customers can add extra stops and edit order information after the order has been created.*
Self-explanatory video

1. Go to '.../admin/deliveries' , (can be done also from customer dashboard)
2. Click on 'See/task number'
3. Click on '"add stop" then "save"'
4. See new stop added

[Screencast from 2023-10-26 13-10-47.webm](https://github.com/coopcycle/coopcycle-web/assets/149066170/c41fcd6c-c78d-435a-a656-b2847feca300)

**Comment by vladimir-8** [comment]
See also: https://coopcycle.slack.com/archives/C4UT4DGQ3/p1721049618933879

**Comment by Paul-Eraman-CoopCycle** [comment]
solution is to remove "save" button
