### ISSUE TITLE
In order to improve usability of the task creation form, as a dispatcher or shop owner I want to be able to search names of clients that allows their corresponding information to appear from "saved addresses"

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3825]
Right now you can search your "saved addresses" by searching in the address field with the street of the client, but this is the only way to search. 

When saving an address you are saving a client name, address, and other characteristics. 

We would like to be able to search in the name field for the names of clients from those saved addresses, click on which would then automatically populate the rest of the fields in the task.

**Comment by Paul-Eraman-CoopCycle** [comment]
not closed until its in finished! sorry 🙏

**Comment by Paul-Eraman-CoopCycle** [comment]
Tested, its AWESOME
Personally id have the field appear "open" by default, not hidden, now that im using it, but thats a personal taste thing so lets call it done for now and see what others thing about that later

**Comment by AdrienSICKLO** [comment]
Hey,
This is GREAT, the quickness of the search + its effectiness make this super useful!
I strongly back Paul's idea. Saved addresses is the standard way of inputing orders here in Nantes, so it shouldn't be an option.
