### ISSUE TITLE
Rethink order codes to reduce chance of similar codes

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3829]
With high volume we get confusing codes. For some reason, there is a significant amount of chronology in the way the codes are created. 

I would propose that instead of the 1st two digits almost being 100% chronological, randomizing all 4 letter/digits and removing letters that often can be confusing. these would include the letters i, L, e, o, v or u, q, p or f, and m or n, and leave all the numbers

instead of getting what is seen in the photo below, we should have more like

3W10
7N8B
5RNU

etc

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/05f42df2-ec94-4549-99e3-924139a771b8)

**Comment by alexsegura** [comment]
The idea is to use Crockford's [Base32](https://www.crockford.com/base32.html) instead of Base36

**Comment by r0xsh** [comment]
I think this is where the change may take place
https://github.com/coopcycle/coopcycle-web/blob/57549ee25157b6289928f94b0de85ba30fba1c27/src/Sylius/Order/OrderNumberAssigner.php

**Comment by lucasferraro** [comment]
And the change would be just to change the "to_base" param from 36 to 32?

`$number = strtoupper(base_convert($order->getId(), 10, 32));`

Which I didn't understand too much in our last meeting is something about some possible collisions with the existing order numbers.

**Comment by alexsegura** [comment]
Also worth looking at

https://github.com/maksverver/key-encoding

**Comment by Paul-Eraman-CoopCycle** [comment]
So...it's still basically the same

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/b31c5adf-5461-4ac1-bd71-b9c13359b558)

We eliminated some letters that seem similar to numbers, but the main thing would be to make the first two digits also change. right now we effectively only use the 3rd and 4th digits because the others are useless. 

I took a look, other platforms use 3 digit codes, but the codes actually are different

**Comment by Paul-Eraman-CoopCycle** [comment]
repeat of #3770 closing
