### ISSUE TITLE
Reduce dependencies imposed by Dockerfile

### ISSUE THREAD

**Issue by 4x10m** [coopcycle/coopcycle-web#383]
#69 #92 

Currently, the way that `Makefile` and `docker-compose.yml` are made imposed use some dependencies that are windows ported but not so compliant.
I think it's a pity to make all this project on Docker and keep some platform-dependencies problem.

To fix that, we could study the state of the art of cross platform scripting but before, i purpose to try to delegate all of the work made in those files to Docker. I mean refactoring `Makefile` and `docker-compose.yml` to do them work from docker and just have a shell script for parsing arguments.

WIP

**Comment by alexsegura** [comment]
Fixed in #816
