### ISSUE TITLE
Possibility to activate automatic acceptance of orders for a high volume restaurant

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3830]
For cooperatives that have high volume and work well, we want to be able to activate automatic acceptance. In this situation, a tablet would ding 2/3 times and immediately print the ticket, and the order would immediately pass to the accepted column.

**Comment by vladimir-8** [comment]
Duplicate; https://github.com/coopcycle/coopcycle/issues/49
