### ISSUE TITLE
Auto-completion adress bar broken

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-web#3847]
**Describe the bug**
We can write an adress in the bar, but we can't select an adress in the bar without an connected account, the auto-completion service is broken. Otherwise, with admin and normal account, it works like normal.

**To Reproduce**
1. Go to the browser https://naofood.coopcycle.org/fr/
2. Do no connect to your account
3. Click on the bar and write an adress
3. See the error, no auto-completion and adress proposition is working.
4. Then you can't select an adress and order

**Expected behavior**
An adress proposition should appear in the adress customer bar with the auto-completion service.

**Desktop (please complete the following information):**
 - Browser, chrome

**Comment by alexsegura** [comment]
You need to fix it on your Google Cloud account, closing
