### ISSUE TITLE
tasks disapearing

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#3855]
**Describe the bug**
since the update (not sure if relevant), some tasks disapear on admin/dashboard (seems like a random behaviour)
they still appear on the map and on the courrier app but not in the assigned task on right part of the admin/dashboard panel
some times they will randomly reappear in the un-assigned section

**To Reproduce**
1. Go to 'admin/dashboard'
2. Create tasks assigne them
3. update the page on the browser
4. See error (not 100% time)

**Expected behavior**
tasks should be assigned and moved in different orders

**Screenshots**

**Desktop (please complete the following information):**
 - Browser :chrome, safari

![delete](https://github.com/coopcycle/coopcycle-web/assets/146206239/989182ca-7a8d-4d95-a7cd-de84263337a4)

**Comment by Atala** [comment]
The whole dispatch code as changed, will reopen if needed
