### ISSUE TITLE
In order to minimize my number of clicks As a [consumer] I want to be directly directed on my manage deposit options when I connect my IMPEC account

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-web#3866]
**In order to** have a better experience by minimizing my number of clicks

**As a** consumer which already ordered with zero-waste packaging / already have an IMPEC account

**I want** to go to the manage my deposit page directly without going throught the "add deposit" page

**Whereas currently** when I connect my account, I have the "add deposit" page with an option of "give back my containers" which sent my back to the shopping cart. 

**Additional context**
Carefull here because the new IMPEC accounts must have this "add my deposit" page. 

![4eme commande](https://github.com/coopcycle/coopcycle-web/assets/83373118/72512c4f-14d4-497c-8d1a-f110b8f72956)

**Comment by alexsegura** [comment]
Not manage on CoopCycle, closing
