### ISSUE TITLE
Add Twitter Cards meta tags

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#387]
See [Optimize Tweets with Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html)

**Comment by batuhantastekin** [comment]
What do you want dude? I don't understand

**Comment by sfishel18** [comment]
hello 👋 i came across your organization searching for open source projects fighting climate change. i really like the product and the mission behind it, and i'd love to contribute a little bit if i can.

on this specific issue, what do you have in mind for improving the twitter card experience? afaict you're getting some functionality just from the open-graph meta tags you already have:

<img width="1006" alt="Screen Shot 2022-05-13 at 9 43 30 PM" src="https://user-images.githubusercontent.com/294695/168411037-1c9cd753-ec47-4aa2-af45-2e50b9187c3d.png">

**Comment by alexsegura** [comment]
Hi @sfishel18 thank you for your message!

It's a 4 years old issue when almost nobody was using the platform, and when priorities were not a nightmare to manage, so honestly I think it's not so relevant anymore. 

You are right it looks pretty good particularly for a restaurant page, so I will close the issue. 

<img width="991" alt="Capture d’écran 2022-05-15 à 20 42 56" src="https://user-images.githubusercontent.com/1162230/168488852-e4d5f524-92be-4720-accd-9dccf660af11.png">

**Comment by sfishel18** [comment]
ah 🤦 i didn't notice when the issue was created. i see the other two issues with the `good first issue` label are also pretty old. do you have any recommendations for a new contributor? or could i just take a look at recently filed bugs and grab one that looks interesting?

**Comment by alexsegura** [comment]
@sfishel18 

I guess you landed here looking for the "good first issue" tag? I'm sorry, we are not so good in curing issues and applying tags ☹️

Apart from this issue, what would you like to contribute to? I mean, backend, frontend..?

**Comment by alexsegura** [comment]
@sfishel18 sorry, I posted my last message without actualizing the page before

> do you have any recommendations for a new contributor? or could i just take a look at recently filed bugs and grab one that looks interesting?

Yes. Maybe the very first step is to run the Docker environment, did you succeed in doing it? 

We have a [roadmap](https://github.com/orgs/coopcycle/projects/9/views/1) with a backlog of issues we are interested in atm, but maybe they are too high level to get started...

What about #3128? It's relatively simple and doesn't require too much knowledge and setup.

**Comment by sfishel18** [comment]
@alexsegura no worries! #3128 looks perfect, i'll start with that one. i'm getting a 404 from that roadmap link, maybe i'm missing some permissions?

> Apart from this issue, what would you like to contribute to? I mean, backend, frontend..? 

in my day job i do mostly frontend development with React, and i work a lot with our DevOps team on things like CI/CD, developer tooling, and observability. so if you have anything in those areas i could help with, great. and if not, also great 😃. i'm happy to jump into something new
