### ISSUE TITLE
Display bug : order total products and number of items does not match what the customer actually paid for

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#3873]
**Describe the bug**
For instance 2ORQ (#125414) at Les Coursiers Rennais

Display is wrong but the customer paid the right price.
However it is problematic because the restaurant doesn’t always check the total amount and can prepare more items than paid for and end up with a net loss.
It’s the second time in 2 days. I don’t know if any one else had this bug.
Order displays 3 pizzas when the customer ordered and paid  2. The restaurant prepared 3 pizza.

**To Reproduce**
Idk

**Expected behavior**
correct display

**Screenshots**
![admin 2ORQ](https://github.com/coopcycle/coopcycle-web/assets/101735534/7197f7e6-1875-492b-95b3-a2856f33cbc7)
<img width="1078" alt="CSV 2ORQ" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/6786e0e4-eaa8-4945-945e-318218bf0eae">
![customer confirmation 2ORQ](https://github.com/coopcycle/coopcycle-web/assets/101735534/4b706452-6b38-468a-b446-5802591c3ed5)
![customer receipt 2ORQ](https://github.com/coopcycle/coopcycle-web/assets/101735534/a3fadf71-1c5e-44e2-898b-7c9497a112b9)
<img width="1280" alt="restaurant order 2ORQ" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/908addc6-d809-40a2-9a09-cf8d72122d0f">
<img width="1280" alt="stripe payment 2ORQ" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/efc8f3dc-72b1-44f1-a045-586abede25e5">

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
 - n/a

**Additional context**

See attached slack thread here :
https://coopcycle.slack.com/archives/CQDUL440P/p1699869814791059

**Comment by Paul-Eraman-CoopCycle** [comment]
Is this a frequent bug?

**Comment by Paul-Eraman-CoopCycle** [comment]
I would close this due to how old it is, but messing with the money is bad. @vladimir-8 do we have any way of looking at logs to see if this is still occuring? if not, i guess we close until we see it happen again?

**Comment by Paul-Eraman-CoopCycle** [comment]
wait its closed, but still a good question haha
