### ISSUE TITLE
order disappear from shop

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#3875]
**Describe the bug**
My customer asked for a delivery threw their shop (as a shop manager)
My customer made a mistake in the time slots, he asked me to change the hour for drop off 
After I clicked on "enregistrer" (save) the order it disappeared from our delivery dashboard but still appears on my admin dashboard

**To Reproduce**
1. Go to 'a shop (as a shop owner) and ask for a delivery, as an admin change the hour of the delivery once received
2. Click on 'enregistrer'
3. check your deliveries linked to the shop

**Expected behavior**
delivery should be there

**Screenshots**

**Desktop (please complete the following information):**
PC google chrome

![delete](https://github.com/coopcycle/coopcycle-web/assets/146206239/d1d9d613-8366-4253-9dbc-7de46817646c)

**Comment by Paul-Eraman-CoopCycle** [comment]
Was resolved 🥳
