### ISSUE TITLE
In order to make it quicker and easier for local stores to repeat recurring and complex deliveries, As the store owner or person who creates the deliveries. I would like to have a button to repeat deliveries.

### ISSUE THREAD

**Issue by iheringdelirrage** [coopcycle/coopcycle-web#3881]
To reduce the time spent on creating deliveries, expecialy those with multiple stops.

As the store owner or person who creates the orders.

I want to have a button to repeat the services I usually order, without spending too much time on it, especially on orders with many addresses.

Additional info: It is important that I can change date and time and  packages after the repeat button

EXAMPLE:

![reorder](https://github.com/coopcycle/coopcycle-web/assets/74983540/bedfb367-7a24-4ee9-b0f2-5f05a7778f4a)

**Comment by vladimir-8** [comment]
Related to https://github.com/coopcycle/coopcycle-web/issues/4523#issuecomment-2244041330

**Comment by Paul-Eraman-CoopCycle** [comment]
Yes
