### ISSUE TITLE
Cancelling order-activated tasks from the order summary page leads to a 500 error because of technical debt

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3888]
video here on slack: https://coopcycle.slack.com/archives/C4UT4DGQ3/p1700500508502859

because deliveries were turned into orders, the deliveries "refuse" button cancels all the tasks, which then cancels the order, which creates problems

**Comment by r0xsh** [comment]
## Root cause
```mermaid
graph TD
    A[Cancelling the order] -->|Triggers| B[Cancelling all linked tasks]
    B -->|Triggers| C[All tasks are cancelled]
    C -->|Triggers| D[Trigger cancellation of already cancelled order]

```

Additional context: https://coopcycle.sentry.io/issues/4612494724/
