### ISSUE TITLE
Have migrations start from an empty schema.

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#39]
First migrations is [here](https://github.com/coopcycle/coopcycle-web/blob/67089347e3610a5ae791fd184d9aff939086d93a/app/DoctrineMigrations/Version20170504105009.php) and suppose there are already some tables created in the DB (`menu_item`, `restaurant`, aso).

It is not very clean, the migration process should work from scratch, so we can use `doctrine:migrations:migrate` .

**Comment by alexsegura** [comment]
See #15

**Comment by Atala** [comment]
Won't do, closing.
