### ISSUE TITLE
In order to [recover the .csv export] As an [admin] I want [to be able to restore mistakenly canceled orders]

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#3909]
**In order to**  `recover the .csv export`
I want to be able to have the .csv export correct when an order is mistakenly (misclick) canceled by a restaurant (or rider?) but is delivered.

**As an** `admin`
Need to feature for admins.

**I want** `to be able to restore mistakenly canceled orders]`
I want to be able to restore these orders, so that they correctly appear in the .csv export and the stats page for the restaurant.

**Whereas currently** `no option to do so`
Atm, as an admin, you need to ask a dev to do so. And we all know there are better ways to make use of their time.

**Additional context**
You can force capture for the Stripe payment independently in Stripe. I do not think the restored order needs to be linked to the Stripe payment.

**Comment by Paul-Eraman-CoopCycle** [comment]
done!
