### ISSUE TITLE
Implement orders export using Cube

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3913]
Currently we are using the optimized but messy [RestaurantStats.php](https://github.com/coopcycle/coopcycle-web/blob/ed9bdececaff731342aee187260b74deb9115322/src/Utils/RestaurantStats.php) class to implement the orders export. 

It should be possible to implement it properly using Cube, for example using a [view](https://cube.dev/docs/reference/data-model/view). 

To make sure nothing is broken, functional tests with real database data should be added.

**Comment by Paul-Eraman-CoopCycle** [comment]
dependent on: https://github.com/coopcycle/coopcycle-ops/issues/28

**Comment by alexsegura** [comment]
Closing as obsolete, we will continue using PHP & raw SQL for exports.
