### ISSUE TITLE
PHP script are not PHP interpreted on Windows

### ISSUE THREAD

**Issue by 4x10m** [coopcycle/coopcycle-web#392]
In the Makefile, we use the php container to create and configure the database.
After some test, it seems that this container fail to interpret the shebang and throw idiot error as `': No such link or directory` on Windows.

After some test, we are sure that the problem is that the shebang is not interpreted and we hot fixed it by explicitly executing it with `php` command.

`docker-compose run php php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis' --env=dev`

Related to #388 

https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by alexsegura** [comment]
Fixed in #508
