### ISSUE TITLE
Foodtech order was processed as click & collect when the option is disabled for the restaurant

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#3920]
**Describe the bug**
A customer was somehow able to process an order in click & collect for a restaurant where the option is disabled. 

**To Reproduce**
N/A
No tracker data available for this order.

**Expected behavior**
Customer should not be able to select click & collect when the option is disabled for the restaurant.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
[Order is 3XNQ (#128695)](https://lcr.coopcycle.org/admin/orders/128695) 10/12/2023 restaurant [Presto](https://lcr.coopcycle.org/admin/restaurants/40) (Les Coursiers Rennais).
![Screenshot 2023-12-11 at 15-05-54 Les Coursiers Rennais](https://github.com/coopcycle/coopcycle-web/assets/101735534/603f5375-3fcb-4452-a89c-75d9015a77f8)
<img width="1280" alt="Capture d’écran 2023-12-11 à 15 08 22" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/b86f8b7a-2947-4e60-af7f-f87c9f205c0e">
<img width="1280" alt="Capture d’écran 2023-12-11 à 15 08 43" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/7d39fe7f-792f-4aa3-af81-c5dce75886c7">

**Comment by Paul-Eraman-CoopCycle** [comment]
Given how old this is and the lack of more examples, closing for the moment. if we see it happen more we will reopen, but lets hope recent improvements have made it stop happening.
