### ISSUE TITLE
In order to [manage customer service loyalty] As a [commercial/sales/communication person] I want [more information available about the users.]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3932]
I'll go back to this issue later, writing notes with Fredo

-Frequency of orders
-How recently did orders happened
-Average amount spent with identifiable tips for example
-In what restaurants orders are placed

**Comment by Paul-Eraman-CoopCycle** [comment]
we are redesigning now, closing this for the moment
