### ISSUE TITLE
[Routes v2] Unable to drag n drop several tasks into a tour

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3937]
When selecting multiple tasks from the list of tasks in order to create a tour, multiple options are possible. 

- Selecting multiple tasks, creating a tour. The expected behaviour is good as it creates a tour with the selected tasks
- But when you create a route folder and then you select multiple task and try to drag and drop it, only the task under the click is being dragged and dropped into the route folder.
![selection routes](https://github.com/coopcycle/coopcycle-web/assets/59842043/a2bccffa-1756-4142-bce1-c9657e9a00a0)

**Comment by Atala** [comment]
OK it is almost a bug as multi tasks dragndrop is supported for assigning tasks

**Comment by alexsegura** [comment]
Fixed in #3954
