### ISSUE TITLE
To improve an existing feature, i want the "progress" bar to reflect correct colors and incidents

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3944]
<img width="370" alt="Screenshot 2023-12-21 at 23 10 42" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/cf7344c2-9fd6-43e4-964c-c1fe971cc7e2">

- [ ] completed should be green to reflect color schema of coopcycle
- [ ] incident tagged tasks should appear as yellow not white
- [ ] cancelled tasks should appear as red
- [ ] in progress tasks should appear as grey (to indicate its not empty by accident)

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle we discussed with @r0xsh 

incidents "can not be" yellow in the progress bar because it will mix success/fail with incidents and these are separate concepts. antoine will add a picto on the top bar and when you hover it, it will display the list of tasks with an incident.

**Comment by Atala** [comment]
OK

so if understand well:

green -> completed + completed with incidents
yellow -> failed + failed with incidents
red -> according to your first message : cancelled? but what is cancelled? does that exists?
grey -> remaining tasks

and the percentage on the right is?

(in this case how do you know that a succesfull task has an incident on it?)

to be checked with antoine!

**Comment by Paul-Eraman-CoopCycle** [comment]
Hey! Yep that is exactly it. cancelations do exist and we should be alerted to them for sure because its a really bad sign (lost business for some reason)

the percentage...i guess i dont know what the function of the percentage is. Im not sure its useful. is it to see how much of the route is completed? in which case its anything not remaining. is it to see how much of the route was done successfully for incident management? other...

i guess we need to ask what people want represented here

**Comment by Atala** [comment]
OK I am not exactly sure how a cancellation is represented in our (software) system, is it a particular incident or a failed delivery? I have never heard about it before. @r0xsh you know what is it?

no problem to do what you want here as it is quite easily modifiable, but it was not 100% clear! antoine is gonna do it next week, so maybe check with him
