### ISSUE TITLE
In the dashboard when drag'n'droping a task from a tour it should move the task itself not the whole tour

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3953]
from @AdrienSICKLO

**Comment by Paul-Eraman-CoopCycle** [comment]
i dont understand, how would moving a task from a group move the group?

**Comment by Atala** [comment]
at the moment if you  start dragging a task in a group it will move the whole group

![Uploading Peek 10-01-2024 15-24.gif…]()

**Comment by Atala** [comment]
at the moment if you  start dragging a task in a group it will move the whole group

![Peek 10-01-2024 15-24](https://github.com/coopcycle/coopcycle-web/assets/4426585/8ebefe63-77e3-4aa1-a5bb-4532de546fed)

**Comment by Atala** [comment]
Splitted in two different issues, one for tour tasks one for group tasks
