### ISSUE TITLE
In the dashboard, tours need to be "unlocked" in order to be modified

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3959]
It has been discussed that we need to protect tours somehow to avoid mischanges, for example when riding a bike.

However it is a pain in the ass if you have to unlock each time when you are organizing your day at the office.

As a developer I will add that the dasbhoard is a lot of code so the least we add the best it will work.

Possible ways of doing things:
- unlock once a tour / all the dashboard and it is done for a page refresh
- unlock for a certain time a tour / the dashboard
- ...

**Comment by Paul-Eraman-CoopCycle** [comment]
looks like its working fine as is, that locking thing was an idea of mine that i think was wrong in hindsight, so closing as not planned for now
