### ISSUE TITLE
When "creating a delivery" from the dashboard in a certain order, delivery (linked tasks) are not assigned in the correct order 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3961]
**Describe the bug**
When "creating a delivery" from the dashboard in a certain order, delivery (linked tasks) are not assigned in the correct order. Dropoff is before pickup in the TaskList.

I think the problem appears is the dropoff is created before the pickup. However it seems they are linked in the correct order (next attribute of the dropoff is the pickup).

The problem is in the `groupLinkedTasks` function, which doesnt returns the dropoff before the pickup in the array.

I think it is not critical because for foodtech the deliveries will not be created from the dashboard. And in the general case I dont know if this action is used a lot. However even if we remove the "create delivery" action the underlying bug will remain.

**To Reproduce**
In the dashboard
1. Create a dropoff
2. Create a pickup
3. Multiselect and then "Create delivery"
4. Assign one of the task
5. Tasks are not in the correct order in the courier taskslist

**Expected behavior**
Dropoff should be before pickup

**Screenshots**

**Comment by Paul-Eraman-CoopCycle** [comment]
how are people making deliveries from the dashboard? you mean by selecting two tasks in the map and right clicking make a delivery?

if so, i want to get rid of this functionality. can we run a query to see if it is being used @Atala or is that impossible cuz front end?

**Comment by Atala** [comment]
we need another tracking mechanism for front end stuff

as for this issue, it is fixed now
