### ISSUE TITLE
In order to reduce the number of unhappy customers I want to prevent customers from paying twice when a product is disabled

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#3964]
**In order to**  `reduce the number of unhappy customers`

**I want** `prevent customers from paying twice`

A few possible options:

- Disable the `Pay` button

- Navigate back to the cart

- Allow payment to proceed and let the restaurant to refuse the order

**Whereas currently**:

When a product is disabled after a customer opens a Payment page. We show an error message on the web while it’s still possible to pay again:

![Screenshot 2024-01-10 at 12 11 22](https://github.com/coopcycle/coopcycle-web/assets/70273239/577d2933-27f5-44a5-8bb3-9cdbce8fcbb4)

**Comment by vladimir-8** [comment]
Option 3: "Allow a customer to proceed with the checkout flow" will be implemented in https://github.com/coopcycle/coopcycle-web/pull/3971

**Comment by Paul-Eraman-CoopCycle** [comment]
looks like this is good, I'm going to close. if you see anything different in the logs let me know :)
