### ISSUE TITLE
Pick-up address resets when changing amounts with keypad

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#3968]
**Describe the bug**
The pick-up address resets when changing amounts using keypad

**To Reproduce**
1. Go to `admin/stores/`
2. Click on `create new delivery`
3. Fill in the pick-up address
4. Change the number of package **using your keyboard** 
5. Clears pick-up address 

**Expected behavior**
Pick-up address shouldn't change

**Screenshots**
![pick-up address changing](https://github.com/coopcycle/coopcycle-web/assets/101735534/ce613fcf-6eae-4ae0-9501-a5677675a612)

**Comment by Paul-Eraman-CoopCycle** [comment]
fixed!
