### ISSUE TITLE
As a dispatcher, I want to be able to unassign tasks, remove task from tour, remove tasks from group with drag'n drop

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3973]
As a dispatcher, I want to be able to move tasks to "unassign" from tour/groups/tasklist with drag'n drop

**I want** `something to be added or changed`
Support drag'ndrop to remove tasks

**Comment by Paul-Eraman-CoopCycle** [comment]
- [ ] unassign tasks
- [ ] remove task from tour
- [ ] remove tasks from group

**Comment by Paul-Eraman-CoopCycle** [comment]
we need to do the groups one, the rest is working

**Comment by Atala** [comment]
yes this is the issue for groups. there is another issue for tours.

to be prioritized compared to other issues , because it is quite a work
