### ISSUE TITLE
As a dispatcher, when I right-click on a linked task, I want the action taken on it to only affect this task, not the linked ones

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3974]
Expected behavior for linked tasks :
 - dragndrop -> affect all tasks
 - right-click + action -> affect only selected tasks

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle can you test and close please ? this should work

dont unassign task in tour with right click it is broken (other issue)

**Comment by Paul-Eraman-CoopCycle** [comment]
Does right click and move to tomorrow also break things? cuz i did that and it broke hehe

**Comment by Paul-Eraman-CoopCycle** [comment]
![rightclickunassign](https://github.com/coopcycle/coopcycle-web/assets/77277854/f8768c0d-d765-4299-9fb3-b0a3ecbe4a74)

would it be possible to have drag a task from a messenger and drop towards that map unassign? to avoid having to drag all the way up?

like this:
![dragtomap](https://github.com/coopcycle/coopcycle-web/assets/77277854/70714ad6-6b7a-43b3-a87b-b1453ab8536b)
