### ISSUE TITLE
Make multi-dropoff orders work with time-based and km based pricing rules

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3977]
Currently multi-point pricing works UNLESS you use time-baed rules or km-based rules

we need to implement multi-dropoff pricing for:

- [ ] time-based rules
- [ ] km-based rules

Time based is a technical solution that is already defined by @alexsegura , please explain in comments.

Km based is harder, and the current suggestion is to have the platform offer to optimize the route for the client. This would look like:

**Case 1:**  I have one pickup and three dropoffs with the same time characteristics, but I have put them in an order that is geographically inefficient. If I decline the optimization, this will charge me XXX€ for the kms. 

<img width="449" alt="Screenshot 2024-01-21 at 18 12 09" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/13acc781-8130-4123-99b1-15980b7031e5">

However, if I push the optimization button, it will reorder the dropoffs into a more efficent route and only charge me X€
<img width="415" alt="Screenshot 2024-01-21 at 18 13 42" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/277d0968-452f-4e09-acb9-c7da225a9b4b">

**Case 2:** I have one pickup and 3 dropoffs. Dropoffs 1 and three can be delivered throughout the entire day, but dropoff 2 has a precise time range of 15:30 to 16:00 and the pickup is after 9:00. In this case, the VROOM optimizer we have currently would put that dropoff last no matter the geographic location, given that it must be delivered after the others. Basically, we use the existing VROOM engine (it works with time ranges), and the km of this route creates the price. 

<img width="495" alt="Screenshot 2024-01-21 at 18 16 04" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/b096090b-506b-470b-a22d-cd28aeab284b">

Having documentation for this INSIDE the platform for clients is a MUST

**Comment by Paul-Eraman-CoopCycle** [comment]
small

**Comment by alexsegura** [comment]
Can we split this issue into 2 different issues? 

Time-based should be fixed in #4422, but distance-based in harder.

**Comment by alexsegura** [comment]
See #4432

**Comment by Paul-Eraman-CoopCycle** [comment]
closing in that case 🥳
