### ISSUE TITLE
Rutas Compartidas Error de precio

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3988]
email chain

--

Hola! 

Siento ser vuestra pesadilla estas semanas. 

Os cuento un poco: en Mensakas estamos con la integración de Coopcycle con [Rutescompartides](https://rutescompartides.cat/). La idea es que el productor que hace una ruta, pueda ver los hubs que hay en Barcelona (y que están registrados en rutes comparties), para poder dejar su producto allí pero además, programar su envío. Todo desde rutas compartidas. Kapis hizo la integración del forms de Coopcycle que yo le pasé con unas tarifas standard. El tema es que sin la API el forms le da un precio, pero cuando lo hace desde la API, da un precio distinto y superior. Os copio traducido del catalán lo que me comentó Kapis, el programador: 

Iván (Kapis), [25 ene 2024, 11:56:48]:
Nuri he probado de nuevo una comparativa entre el precio sugerido por la API utilizando el token de la tienda rutescompartides y el formulario de checkout the rutescompartides que también nos pasaste y hay bastante diferencia... el precio sugerido por la api es siempre muy alto (en cualquier distancia... 28,75€ como podéis ver a la primera captura... y el precio real que sugiere el formulario de mensakas antes de hacer el pago es de 9,65€ con IVA incluido...

Plataforma de entrega para empresas de trabajadores

Formulario RutesCompartides: https://mensakas.coopcycle.org/ca/forms/GKWp78V1Y9o0

API Client ID Rutescompartides: ee179ea53cb646642065d5e3a822b467

Para calcular el precio vía API (si quieres pasárselo a los desarrolladores de coopcycle) estoy gastando esta gritada:
   url = f'https://mensakas.coopcycle.org/api/retail_prices/calculate'

    payload = {

        "pickup": {

        "address": origin,

        },

        "dropoff": {

            "address": destination,

        }

    }

Pienso que tiene que ser algún detalle o fallo tonto. Queremos ponerlo en público ya para que empiece a funcionar para productores pero este tema nos tiene encallados desde hace un tiempo. Agradezco cualquier ayuda! 

Un abrazo!

--
fin email

![2024-01-26 17 59 58](https://github.com/coopcycle/coopcycle-web/assets/77277854/0d1baf7e-859d-4deb-b440-d4ab6669d67c)
![2024-01-26 18 00 09](https://github.com/coopcycle/coopcycle-web/assets/77277854/1982dc91-8372-4a94-9e67-5b0d9f39282d)
![2024-01-26 18 00 17](https://github.com/coopcycle/coopcycle-web/assets/77277854/185f38e3-29e3-487a-b538-6b7b723e94b0)

**Comment by alexsegura** [comment]
Answered by email

**Comment by Paul-Eraman-CoopCycle** [comment]
Reopening, lets close when its fixed haha :)

**Comment by Lirca** [comment]
No sé exactamente qué es un payload; en las pruebas que había hecho (con un paquete de 1kg para ser entregado desde Mensakas C/València 72 hacia Avinguda Roma, 72), me daba un valor de 28,75€.

A ver si Kapis puede concretar mejor esto del payload o si con la dirección y valor que os he pasado, ya os sirve...

Gracias!

**Comment by numeropi** [comment]
Disculpeu, he pogut solucionar-ho via RutesCompartides, no s'estava passant les destinacions correctes a la API, 

ara ja retorna sense possar horaris una quantitat raonable 14,34€ com podeu vore a l'exemple...

![imagen](https://github.com/coopcycle/coopcycle-web/assets/56868560/116cf4c2-bf9b-4f54-b0d3-0f98fd94b2aa)

**Comment by Paul-Eraman-CoopCycle** [comment]
Great! Glad to hear it :) 

Ill send out an email
