### ISSUE TITLE
CSV Import : if you import a CSV file with tab as delimiters, it wont be able to parse at all and won't show the import in the "deliveries import tab" 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3991]
Please find attached the file below

In the dashboard : 
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/2fa52e57-ce47-4086-94a9-64167364fe9a)

In the deliveries import panel
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/216061ce-159d-47be-b389-3edb40cd48f3)

The file
[Import Livraisons LYRECO 01022024 (1).csv](https://github.com/coopcycle/coopcycle-web/files/14122325/Import.Livraisons.LYRECO.01022024.1.csv)

**Comment by alexsegura** [comment]
Strange, the delimiter [should be auto-detected](https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/#pipe-or-tab-separated-value-files)

**Comment by Atala** [comment]
I look at it quickly so I am not 100% sure that was a tab as separator, maybe sthg weird like several comas or I dont know. It should show in a text editor with correct settings.

did you reproduce locally ?
