### ISSUE TITLE
A class use an unknown variable

### ISSUE THREAD

**Issue by clementtalleu** [coopcycle/coopcycle-web#40]
The class : `AuthenticationWebSuccessHandler` use an unknown variable `$referer` at line 23

https://github.com/coopcycle/coopcycle-web/blob/67089347e3610a5ae791fd184d9aff939086d93a/src/AppBundle/EventListener/AuthenticationWebSuccessHandler.php#L23

**Comment by Atala** [comment]
Should be `$request->headers->get('referer')` (+ add a test)

**Comment by alexsegura** [comment]
Fixed in 94b3f6ee91f381866adf0d953656d4689fe89516
