### ISSUE TITLE
In order to clean our coopcycle As an admin I want to be able to delete stores

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#4003]
**In order to**  `achieve something`
in order to Delete store that are not in use, I want a delete store button on the web version

as an admin

I want a button to delete stores that are out of use

**Whereas currently**  there is no way to delete a store

**Additional context**
We worked with companies that do not work with us anymore or literally closed, so in our store list we got plenty of stores that are useless, we want to delete them

**Comment by Paul-Eraman-CoopCycle** [comment]
- [ ] stores
- [ ] shops
- [ ] pricing rules
- [ ] time slots
- [ ] Formulas
- [ ] package sets
- [ ] zones
- [ ] tags

**Comment by Atala** [comment]
Actually it is more complex than i expected. A store is linked to all these objects, so we need to define behaviour for each of them

|object | behaviour |
| --- | ---- |
"store_address" |
"delivery" |
"store_time_slot" |
"delivery_quote" |
"api_app" |
"urbantz_hub" |
"woopit_integration" |
"delivery_import_queue" |
"api_user_store" |
"task_rrule" |

**Comment by Paul-Eraman-CoopCycle** [comment]
What does "define behavior " mean? Decide what happens to them?

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
