### ISSUE TITLE
In order to understand I need to pay my packaging deposit As a [customer] I want [a alert pop up to tell me I need to fill the deposit part of the basket]

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-web#4011]
**In order to** avoid frustration when completing my order

**As a** customer

**I want** an indication that I need to fill the deposit payment part in the cart

**Whereas currently** I can click on "order" button which is blue but I cannot finalize my order
For example, when i don't fill my email adress or phone number, when I click on "order" I have an indication which pops to tell me what I need to fill before proceeding.

**Additional context**
![commande](https://github.com/coopcycle/coopcycle-web/assets/83373118/3774e36c-b605-4cb9-a919-bfd7f40aa6fc)

![image](https://github.com/coopcycle/coopcycle-web/assets/83373118/834e0c22-130c-4180-b10c-ff55440b3547)

**Comment by alexsegura** [comment]
We can't add a standard HTML form error there, but now the error message appears clearly. 

<img width="1086" alt="Capture d’écran 2024-02-19 à 12 38 13" src="https://github.com/coopcycle/coopcycle-web/assets/1162230/ce8509be-dc8f-4982-91d3-fc23eb79e04b">
