### ISSUE TITLE
When clicking the X on many tasks in a route, the page turns blank

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4012]
Steps to reproduce
1. Create a tour with several tasks
2. Click on "x" quickly on several tasks
-> dashboard crash

SOLUTION : the tour should be disabled when we are executing the `modifyTour` action
1. add an overlay to disable the click on the tasks
2. disable the drop in the tour
3. add a loading spinner

=====

When clicking the X on many tasks in a route, the page turns blank
once refreshed, its ok

[Screen Recording 2024-02-19 at 11.51.23.zip](https://github.com/coopcycle/coopcycle-web/files/14335033/Screen.Recording.2024-02-19.at.11.51.23.zip)

**Comment by Atala** [comment]
I may have fixed it I dont know, will need testing
