### ISSUE TITLE
Moving a single task from a courier tasklist to an unassigned tours show inconsistent behaviour

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4013]
Steps to reproduce : 
- assign several tasks to a rider
- create an unassigned tour with several task
- drag a task from the courier takslist to the unassigned tour

-> it breaks

What is the solution? Forbid this move for the moment 

starting at 0:55

i assign a delivery to myself, make a route, move ONE task from me to the route

then it all breaks. see video, but i can explain more if needed

(video too big, i sent to people in private channels)

**Comment by Paul-Eraman-CoopCycle** [comment]
so we should put this in TO DO or Backlog right? cuz you didnt fix it, you just made it impossible as a quick fix

**Comment by Atala** [comment]
I think you should create a master issue with all the actions you want for the various right click menus for task, tour, groups, ... + close this issue

and then I will tackle that when we prioritize starting it after tour v1

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok ill put on my to do list
