### ISSUE TITLE
In order to avoid mistakes from customers, as an admin I want to disable the possibility to put several package for orders

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#4019]
**In order to**  avoid clients to put multiple packages

**As a** `role`
admin/dispatcher

**I want** `something to be added or changed`
I want to disable the possibility for a shop to put multiple package

**Whereas currently** `this happens`
the client always have the option to say that they have x times the package 

**Additional context**
we have set different package types with measures and a weight
last week, one of our client has put 5x "small boxes 15kg" max instead of "full cargo" but our tarification is based on the "contain at least" package thing
what i want is that if my client have 5 small boxes, he doesn't have the option to put several of them (as it doesn't change the price with our tarification), and there for will be "pushed" to choose the "full cargo" package type
<img width="960" alt="multiple package" src="https://github.com/coopcycle/coopcycle-web/assets/146206239/948e6b49-ffcf-49d4-82f9-242cd6cbdedb">

**Comment by Paul-Eraman-CoopCycle** [comment]
The feature that has been requested for this sincero by others is that when the packages have a weight or unit of volume that exceeds the vehicle's maximums, it would apply some another type of "base" price, which would reflect having to take a second bike
does this reflect the same problem?
