### ISSUE TITLE
As a dispatcher, I want to be able to move the tasks of a tour to the next day

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4024]
For now it is blocked to avoid dashboard crash. also the crash itself can not happen anymore. however we have to do this cleanly

As a dispatcher, I want to be able to move the tasks of a tour to the next day

- from the task modal
- from right click action

the task(s) should be unlink from the tour when it is moved to the next day

**Comment by Atala** [comment]
Temp fix is to disable right-click menu for tasks into tours. Will come back to it later

**Comment by Paul-Eraman-CoopCycle** [comment]
this should be in to do right?

also it works with groups

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/45c89ee8-1edc-4949-b251-b8855996f0e8)

**Comment by Atala** [comment]
not exactly, it is the bug related issue

i will modify the issue accordingly

**Comment by Paul-Eraman-CoopCycle** [comment]
for now, UI is just they have to take them out of the route, which makes sense to me...
for the moment, not planned
