### ISSUE TITLE
Reordering tasks in a tasklist is broken when there is a tour in the list + standalone tasks

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4025]
Bug reported on the enrouelivr instance

Inappropriate reordering of tasks when a "tournée" is used. See example in our CoopCycle instance, date Februray 18. If you try to reorder a task that doesn't belong to the "ouvrent tôt" tournée, it will jump to the top of the list. To the first or second position, whatever position you wanted to give to the task. Then if you unassign the tournée, the reordering works fine.

**Comment by Paul-Eraman-CoopCycle** [comment]
i didnt make the issue so not the best person. is it also in corbo? if so ill ask them to

**Comment by Paul-Eraman-CoopCycle** [comment]
Who should test this?
