### ISSUE TITLE
A previously assigned tour is filtered out when you filter out the courier it was previously assigned

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4026]
Reported by corinne on enrouelivr instance

assign a tournée to a coursier, unassign it, filter out the coursier. The tournée is also filtered out.

**Comment by Atala** [comment]
I think it has been fixed by the last refactoring on task.tour_id

let s see if someone can reproduce it

**Comment by Paul-Eraman-CoopCycle** [comment]
almost fixed, the tour is now visible but the tasks in it arent. so its not uncollapsable



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/aa03667a-add4-4d66-a917-3271a58acfc6)

**Comment by Atala** [comment]
it is the intended behaviour of the couriers filter

when the filter is set, unassigned tasks are not visible

this filter = show this courier's tasks

**Comment by Paul-Eraman-CoopCycle** [comment]
but the route is no longer assigned to the messenger, so nor are the tasks?

**Comment by Atala** [comment]
yes the tasks are not assigned anymore
but the "courier" filter hides also unassigned tasks

**Comment by Paul-Eraman-CoopCycle** [comment]
i dont understand

in the gif I have tasks that are no longer assigned to a messenger. I filter OUT that one messenger. the only thing that should happen is that i no longer see tasks assigned to that messenger. Instead, tasks disappear. 
im not trying to filter out unassigned tasks in the video, that would be a different button

should we do a video chat about it?

**Comment by Atala** [comment]
yes it is shitty behavior but it was implemented like this, unassigned tasks are filtered out

in the filters we should have a ON/OFF for unassigned tasks I agree, I already discussed that on slack actually

let s create a new issue ?

**Comment by Atala** [comment]
( i talked about it here [https://coopcycle.slack.com/archives/G01JR0YF5V3/p1707218683568089](https://coopcycle.slack.com/archives/G01JR0YF5V3/p1707218683568089) )

**Comment by Paul-Eraman-CoopCycle** [comment]
yeah that works. can you create it? you seem to understand the problem better

**Comment by Atala** [comment]
OK
