### ISSUE TITLE
Moving an assigned task to a route does not move the linked task IN THE WEB DISPATCH INTERFACE

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4029]
**Describe the bug**
title

**To Reproduce**
have an assigned task with a linked task
drag and drop one task to a route
the task moves to the route and the route moves to the messenger but dosnt assign the linked task

**Expected behavior**
the route should remain unassigned and the taska nd its linked task should move to the route

**Screenshots**
DM video

**Comment by Atala** [comment]
Linked to coopcycle/coopcycle-app#4029
