### ISSUE TITLE
 Be able to move a route directly from one messenger to another without unassigning

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4030]
**In order to**  `achieve something`
Be able to move a route directly from one messenger to another without unassigning

**As a** `role`
dispatcher

**I want** `something to be added or changed`

- [ ] when i click and drag an assign route over another rider, their modal should open up and allow me to drop the route into their assigned area
- [ ] if i right click the route, it should offer an option to reassign with a list of messengers

**Whereas currently** `this happens`
i cant, i have to move to unassigned first

https://github.com/coopcycle/coopcycle-web/assets/77277854/ddc7ad6c-6d2b-4347-804f-e5ff7a035d4a

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle I'd rather close this for now; and we will discuss the right-click menu in a next sprint or meeting or whatever

if you agree please close

**Comment by Paul-Eraman-CoopCycle** [comment]
illl take off this issue and put in the context section for routes v.2

**Comment by Atala** [comment]
no no it is a duplicate

**Comment by Paul-Eraman-CoopCycle** [comment]
ok closing
