### ISSUE TITLE
Cant darg and drop task into a route bug

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4037]
alois has video

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle should be fixed on demo could you try to reproduce?

**Comment by Atala** [comment]
sorry was unclear i just temporarily disabled the stuff so we get rid of the bug/inconsistent behaviour

I disabled all the moves not implemented yet so users dont get stuck.

I will close this as the bug is done and open a new issue with the feature

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok cool, make sure to add the new issue to the issue of issues
