### ISSUE TITLE
In the dispatch panel, we need add a "duplicate order" feature 

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4040]
Right now we can duplicate tasks in the admin dashboard, but this creates a task with no associated price or shop, just a task

I know there are use cases for this, so I don't want to delete it. Instead, we add a "duplicate order" button which allows you to duplicate that order exactly as it was, or take you to the order creation page with the information populated the same as that order.

This is a quick fix until we do a full rework of this stuff

![Untitled](https://github.com/coopcycle/coopcycle-web/assets/77277854/bed6f269-efea-4062-a408-6c07f80cd346)

**Comment by Atala** [comment]
problem : if we are in delivery case (1 pickup + 1 or more dropfooff) the user has to open modal on all the tasks and duplicate tasks for the moment, bad UX
main UX problem is that clicking on a delivery opens you a "task" modal so we shoudl fix this

personal advice: I think "duplicate exactly the same" should not move you outside of dashboar dbecause it is where you are doing stuff. should add a nice way to navigate from delivery to the order in the dashboard though.

**Comment by Atala** [comment]
my intake on this

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/f9ad7979-fe1e-410d-8207-eef9373f67cd)

**Comment by Paul-Eraman-CoopCycle** [comment]
Not sure i understand, can you overlay over the interface in the platform wiht how it would be seen?

**Comment by Atala** [comment]
sorry

when you double click on a delivery/order it doesnt open a task modal it opens a modal with two parts one which describes the order on the left, on the right the "normal" panel for the task (the one we have already)

**Comment by Paul-Eraman-CoopCycle** [comment]
we do this now in the order page
