### ISSUE TITLE
In the dashboard when drag'n'droping a task from a group it should move the task itself not the whole group

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4046]
at the moment if you start dragging a task in a group it will move the whole group

![Peek 10-01-2024 15-24](https://github.com/coopcycle/coopcycle-web/assets/4426585/8ebefe63-77e3-4aa1-a5bb-4532de546fed)

**Comment by Paul-Eraman-CoopCycle** [comment]
Repeat issue, closing
