### ISSUE TITLE
Misleading information about available time slots (Restaurant page)

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4050]
**In order to**  `provide clear information to customers`

**I want to** `show the earliest time slot available for the current restaurant, regardless of what the customer has selected in the restaurant where they started the order`

**Whereas currently**

When a customer starts an order in one restaurant; for example: now it's Tuesday; order a pickup on Tuesday at 12:20 (Screenshot 1) and then navigates to a different restaurant with a different schedule and/or fulfilment methods; current selected time slot and fulfilment method is displayed; even if it's not applicable to a shown restaurant (Screenshot 2)

Screenshot 1:

![Screenshot 2024-03-11 at 18 59 42](https://github.com/coopcycle/coopcycle-web/assets/70273239/4baea73f-68c1-4511-be07-29b3382bef93)

Screenshot 2:

![Screenshot 2024-03-11 at 18 59 49](https://github.com/coopcycle/coopcycle-web/assets/70273239/cc6a5c5c-8ad6-4fb0-835a-3aa51b91ba3c)

In the list of restaurants we correctly display the earliest time slot available for each restaurant

**Additional context**

There could be a similar problem related to 

fulfilment methods: https://github.com/coopcycle/coopcycle-web/issues/4081

minimum cart amount: https://github.com/coopcycle/coopcycle-web/issues/4095

**Comment by Paul-Eraman-CoopCycle** [comment]
testing says good to go
