### ISSUE TITLE
Beginning order in a restaurant then switching to a restaurant and beginning a new order crashes

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4058]
Steps to reproduce :
- begin basket in restaurant, add an item
- go to other restaurant
- select item,
- it returns a 200 AJAX request with "restaurant mismatch" error
- click "new order" in the modal
- notice 500 error in the AJAX requests

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/44efc76a-ee2c-4979-9dbc-6a52afc8cb60)

https://coopcycle.sentry.io/issues/5044345617/events/d5f952ad42f946be88ed41a0e179499b/?project=5294179&query=is%3Aunresolved&referrer=previous-event&statsPeriod=14d&stream_index=1

**Comment by alexsegura** [comment]
Fixed in 7437e50f36af26a4e0a53e3489f935fddc71cb16
