### ISSUE TITLE
Be able to see what has been selected on the map even if in multiple states

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4059]
In order to avoid people breaking things, we made it impossible to select multiple tasks that are in different states (unassigned, route, assigned). The following error shows up:

![dispatchmap](https://github.com/coopcycle/coopcycle-web/assets/77277854/bf24d25b-9dfe-4d37-aece-190c9a43eac8)

However, we actually just want to avoid them taking actions on tasks in multiple states. However, by making it impossible to select, it is more difficult to do dispatch with many tasks because you can't visualize things.

Proposal: allow multitaskstate selecting, just dont let actions be taken upon them. this way the visualization stays intact, but we don't have problems with the actions making unexpected bugs.

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle possibility to show the count of selected tasks on top of collapsable like tasklist header, tour header, what do you think?

could be shown on top of unassigned tasks as well. quite easy

see the tasklist below
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/a9d46f8b-ff78-4895-87e8-6fad01dd483c)

**Comment by Paul-Eraman-CoopCycle** [comment]
That looks nice on the right yes, but with

1.  The ability to see on the map what is selected
2. If the messenger is open, ability to see which tasks are highlighted 

Overall, i dont want to try to innovate here, i want to unbreak things we broke so it can still be used easily, and then do a real design workshop later to invent new features

**Comment by Atala** [comment]
OK

**Comment by Atala** [comment]
deployed on demo

**Comment by Paul-Eraman-CoopCycle** [comment]
I just checked, is it live yet?

**Comment by Atala** [comment]
lol no sorry 5min it is deploying

**Comment by Atala** [comment]
it is live @Paul-Eraman-CoopCycle

**Comment by Paul-Eraman-CoopCycle** [comment]
Im messaging you on telegram haha, i saw the slack message

**Comment by Paul-Eraman-CoopCycle** [comment]
its awesommmeeeee
