### ISSUE TITLE
Unassign by dnd should unassign delivery/order

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4064]
Atm dragndrop unassign single task

should move both

- [x] from assigned to tour
- [x] from tour to unassigned
- [x] from tour to unassigned

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle coming from tour to unassigned should move both ?

**Comment by Paul-Eraman-CoopCycle** [comment]
yep! all dnd should move all associated/linked tasks to the order
