### ISSUE TITLE
When assigning orders/tasks to a route they continue to appear in the unassigned column as well as the routes column

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4067]
**Describe the bug**
When tasks are associated to a route they still appear in the unassigned column until the page is refreshed

**To Reproduce**
1. select various tasks
2. make a route
3. see that they are both in the route and in the unassigned list

**Expected behavior**
they should only appear in the route column, no longer in the unassigned column

**Screenshots**
![routeproblemas](https://github.com/coopcycle/coopcycle-web/assets/77277854/fd0a4452-87f9-48be-be5b-df7b57c08894)

[routes2.gif.zip](https://github.com/coopcycle/coopcycle-web/files/14624953/routes2.gif.zip)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Atala** [comment]
Could not reproduce yet. Needs investigation.

**Comment by Paul-Eraman-CoopCycle** [comment]
could it be due to the high volume of tasks? maybe try with the same data, its still up on the demo

**Comment by Atala** [comment]
could not reproduce yet on demo. it is always possible that dashboard was in "incoherent state" that made it behaves strangely and could have been cleaned by a refresh.

were you working on poor network conditions ?

**Comment by Paul-Eraman-CoopCycle** [comment]
nope. good network and all

ill try again. has there been any change in the code since saturday?

**Comment by Atala** [comment]
no change

**Comment by Paul-Eraman-CoopCycle** [comment]
had to do with filters. fixed!
