### ISSUE TITLE
Esc button to deselect

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4068]
the only way to not have anything selected after having things selected is to draw a square on a part of the map with no points, which is not very UI/UX friendly.

[needescbutton.mp4.zip](https://github.com/coopcycle/coopcycle-web/files/14624955/needescbutton.mp4.zip)

request for escape button to deselect everything

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle "esc" keycode is already binded to "close search"

want to handle both with "esc" ?

**Comment by Paul-Eraman-CoopCycle** [comment]
does "bind" mean cant also be used somewhere else? because it would make sense to have it for both since you are never deselecting tasks on the map and searching at the same time

**Comment by Atala** [comment]
it can be used for both

but i think it is useful for people with search :
- go on search mode to get your tasks
- search -> select task
- search -> select another task
ad lib
and then "close search"
and the drag n drop with the previously selected tasks

what do you think ?

**Comment by Paul-Eraman-CoopCycle** [comment]
i think that makes the search function kind of clumsy, try to save things between search seems messy. 

the solution i see for that use case you are describing would be a selecting button (check box) that persists over time instead of just highlighting. or something like that, something more persisty than highlighting

**Comment by Atala** [comment]
not sure if we 100% understand each other here, we should talk about it

**Comment by Paul-Eraman-CoopCycle** [comment]
Taking out of Routes V.2 and backlogging
