### ISSUE TITLE
Information isnt saved in admin panel when assigning a messenger

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4070]
**Describe the bug**
Address updated info is lost if modal is closed, then opened, and messenger assigned

**To Reproduce**
1. open a task in the admin panel
2. put in a new address
3. press save
4. reopen model
5. assign to a messenger
6. press save
7. see order in original position with original address

**Expected behavior**
address to be saved after pressing save and not changing

**Screenshots**
[routeproblemas4.gif.zip](https://github.com/coopcycle/coopcycle-web/files/14624979/routeproblemas4.gif.zip)

**Comment by Atala** [comment]
actually you can see from the GIF that the adress is not correctly saved.

even if the pin has moved on the map, when the modal is re-opened the "direccion" field in the modal is wrong.

investigating

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/2f1652e1-d575-4db5-9809-7f2a847b9863)

**Comment by Atala** [comment]
it is definitely #4074
