### ISSUE TITLE
In order to work happily As a dispatcher I want selected tasks to clear automatically after some actions completions

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4071]
I guess we have to clear automatically selected tasks automatically after:
 - tour creation
 - tour modification
 - taskslist/rider assignment modification
 - tour deletion ?

others ?

@Paul-Eraman-CoopCycle 

related to #4068

**Comment by Paul-Eraman-CoopCycle** [comment]
i 

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/35d084cb-a4a0-48b5-bdac-fe9f15c2a9d6)

made this bug hapen by accident
