### ISSUE TITLE
 As a dispatcher I want the action to order unassigned tasks to actually work

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4072]
@Paul-Eraman-CoopCycle are these useful? do you know what it actually means ? can you tell me expected behavior for all of these?

then i will check if it works

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/240bc114-5054-4f61-a141-6752f0d0f08d)

**Comment by Paul-Eraman-CoopCycle** [comment]
this is one of those things where if we touch it I bet 10 people get very upset immediately because they were using it in ways we didnt know haha

i wouldnt make any modifications to that before a real workshop with last mile dispatchers

**Comment by Paul-Eraman-CoopCycle** [comment]
though i do understand it is used somewhat and is useful
but definitely could be improved

**Comment by Atala** [comment]
I cant tell for sure i didnt break it while changing the code

**Comment by Paul-Eraman-CoopCycle** [comment]
Well...lets see if anyone complains? Maybe ask in dev?
