### ISSUE TITLE
The rider available green / blue bar 

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-web#4078]
**In order to**  `achieve something`
Before the UI/UX MAJ design, the dispatch admin, had a green bar when the rider doesn't have any task.
And Blue bar when he has. So, on the blink of a eye, you can check the available rider and the busy ones.
But now, it's a green bar, and a bit of a blue bar at the right spot. We don't understand what informations it gives us.
But for sure, it suppresses one information that we were really fond of.
It's really hard to see now if someone is full green or green with a bit of a blue at the end of the bar.

**As a** `role`
The dispatcher

**I want** `something to be added or changed`
To be back the way we were before the UI/UX MAJ design.
Change the blue / green color for the busy / available rider system.

**Additional context**
![capturecoop](https://github.com/coopcycle/coopcycle-web/assets/144671333/d0268450-b0d6-4076-8cdd-1021d111ec66)

**Comment by r0xsh** [comment]
No information has been removed. In fact, the green bar has not changed its behavior. We've only added informations that wasn't represented before the update.
- The **green** part still represents tasks completed by the courier (as before).
- The **blue** part represents tasks currently being executed by the courier (so the larger the blue bar, the more busy the courier).
- There's also a **red** part representing cancelled jobs.
- And an **orange** part representing jobs that have been cancelled (this area is currently under development).


Does this answer your problem or did you have a different use case for this progress bar?

---
If you move your mouse over the progress bar, you'll be able to retrieve this information.

![image](https://github.com/coopcycle/coopcycle-web/assets/5613584/746347d8-5b37-4558-8add-81c86848a212)

**Comment by GuillaumeNaofood** [comment]
Exactly Paul.
The food is the opposite of what the last mile wants for this feature.

There is a change now R0xsh, there is no more full blue bar except for the 1st order.

And even worst, we don't even see the blue after 14 tasks or more. It's to tiny. 
In food, we just want a signal, an enhancement to see if the rider if occupied on tasks or available with all finished tasks.
The blue and green bar was usefull this way.

But you know what ?
I don't even know how is it usefull for last miles.
Because, we don't care anymore about the checked green tasks. In your feature, more the tasks you've done, and more little the blue and others colors bar will be. After 16 or 20 tasks it's almost not visible.

An idea for both, Food and Last Miles : 
Could be having the bar showing the progression of the current tasks ONLY.
This way, if you have 8 tasks in last miles, you'll have a good idea as dispatch how things are going, if being late, or if the rider is gonna be available soon.
Even for food, it will show if the rider is at the begenning of the blue bar (step 1/4 or step 3/4)

It gives an time notion with a blue bar which fills gradually. 
When every tasks are finished, it's green.

I don't get why is it usefull to see most of the green color in the bar, which is the past order already done for.
I prefere intels for the present and the futur if you ask me.

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok, all understood

@r0xsh what we need actually very simple:

We need the filters to effect this bar. What fixes the problem is if I have the filter DEativated so that I do NOT see finished tasks (this is what we do in foodtech), I want those tasks to NOT show in the color bar. 

so, if I have my config like this:
<img width="990" alt="Screenshot 2024-03-19 at 23 12 35" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/97591a93-3ae7-4560-a012-e1cddd8f8a40">

I want the photo from above to change like this
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/21006775-4a24-49b0-a515-306b4775f093)

but if the filter is deactivated, it would be like in the photo (with the todo option in the list)
