### ISSUE TITLE
In order to speed up the dispatch web page As a dispatcher I want to fetch packages data asynchronously

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4086]
If my understanding is good [these (https://github.com/coopcycle/coopcycle-web/blob/master/src/Serializer/TaskNormalizer.php#L97-L105) creates 1 (dropoff) or 2 (pickup) queries per task.

<s>So on Mensakas instance it is like 600 queries instead of 300 queries just for tasks.</s> -> look below!

It is hard to predict but it could gives us a speed boost when loading tasks from the dashboard.

As these data are only displayed in the task modal for now, maybe we could fetch packages data at modal opens? thus we could create an 2nd endpoint to get details on tasks?
 
Or maybe we could improve the PHP, so the query gets packages data at once?

**Comment by Atala** [comment]
with packages VS without packages

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/35997081-15b7-4bc5-a6a1-1740788fd7ce)

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/f282d207-6828-4799-ade2-c954517e0e22)

**Comment by alexsegura** [comment]
The problem is that we are retrieving the `packages` in API responses since the beginning, and I can't say what is consuming this.

**Comment by Atala** [comment]
Done differently with a big SQL query
