### ISSUE TITLE
filters broken for foodtech on web

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4092]
![filterbroken](https://github.com/coopcycle/coopcycle-web/assets/77277854/548302ff-0039-4307-8d9d-e137785ed2bd)

chrome

it shouldnt white screen of death ;)

**Comment by vladimir-8** [comment]
Duplicate: https://github.com/coopcycle/coopcycle-web/issues/4082
