### ISSUE TITLE
Miss an use in RestrictedDiet class

### ISSUE THREAD

**Issue by clementtalleu** [coopcycle/coopcycle-web#41]
The annotation `@ApiResource` is used in the `RestrictedDiet` php class but without the call to the vendor's class :  `use ApiPlatform\Core\Annotation\ApiResource;`  it will crash

**Comment by Atala** [comment]
How did you find theses (#40, #41) ? Static analysis?

**Comment by clementtalleu** [comment]
I just read some classes and my IDE did the job. 

But I think that install https://github.com/phpstan/phpstan will be a good idea, then travis to prevent merging bad coding style or php errors

**Comment by alexsegura** [comment]
Fixed in 94b3f6ee91f381866adf0d953656d4689fe89516
