### ISSUE TITLE
In order to [manage prices changes] As a [admin] I want [download and upload pricing rules]

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#4115]
**In order to**  `manage easely the prices changes` I want to change the way the pricing rules are set in the platform

Our rates change at least once a year (indexation linked to consumer price increases). In the case of complex pricing rules or multiple conditions, it's very annoying to change prices. It's time-consuming and error-prone, because the encoding is done manually. Also, if you make a mistake (click in the wrong place on screen), the window may close without saving, and you have to start all over again. 

This situation can limit the profitability of cooperatives: because changing prices is time-consuming, this work can be postponed, with each order placed on the old pricing rules costing money.

Furthermore, will all the conditions used in the pricing rules be maintained in the code in the future (unit of volume, type of bike, etc.)? If a condition used in a pricing rule is no longer developed or is removed as part of a structural change to the platform, all pricing rules using this condition will have to be recreated. This is potentially very annoying

**As a** `admin`

**I want to streamline the management of pricing rules by adding a "download pricing rule" button and an "import pricing rule" button instead of making changes manually online, on the pricing rules page.

This would allow for changes to be made to pricing in a downloaded CSV file (and potentially easily changing prices that have all increased by 5%, for example, through Excel formulas) but also to change conditions directly in the downloaded CSV file (using the search/replace functionality) and then import it into the pricing rules page after the changes.**

**Comment by Paul-Eraman-CoopCycle** [comment]
Currently not planned, closing, but will put in the discovery section of the excels epic planning
