### ISSUE TITLE
When you hide/show riders in the dispatch panel, always show the unassigned tasks for now

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4118]
**What we want :
 - if you hide some riders, then still show the unassigned tasks
 - for now we dont add a filter to hide/show unassigned tasks**

At the moment, 

- there is a global filter "always show unassigned tasks"
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/1dd96f7e-c595-4457-800a-86d952638c45)

- <s>unselecting a rider hides unassigned tasks. it doesn't take into account the above filter (which is a bug)</s> -> actually it is taken into account

- there is no "global filter" to hide all assigned tasks

**Comment by vladimir-8** [comment]
@Atala do you know what is the usecase for this global filter "always show unassigned tasks" ?

**Comment by Atala** [comment]
no, but paul told me it was there for some reason so we keep it for now

**Comment by Paul-Eraman-CoopCycle** [comment]
Tested, working!
