### ISSUE TITLE
Change the "lock icon" to go to admin panel in top bar to "Dispatch" text

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4124]

**Comment by Paul-Eraman-CoopCycle** [comment]
we need to make sure that it doesnt recreate the issue we had where in certain browsers the text disappeared due to formatting of the webpage. i cant find the issue, i think it was made by thomas

**Comment by alexsegura** [comment]
Can we ask designers, please?

**Comment by Paul-Eraman-CoopCycle** [comment]
I think we can change admin panel to dispatch panel without any issue

And we can change the icon as well

But changing out icons for text and so on, i agree we need a design opinion. Ill send links to this issue out one minute

**Comment by alexsegura** [comment]
The whole top navbar needs to be redesigned, also to make sure it fits all screen sizes. 

The lock icon was added to hotfix #3542

**Comment by Paul-Eraman-CoopCycle** [comment]
Agreed
Not sure when we will get to that though with so many design topics :/

**Comment by Atala** [comment]
is it ok to make the change if make sure that extra-top menu doesn't overlap with the content of the page? (with something like `overflow: hidden` for example)

**Comment by Paul-Eraman-CoopCycle** [comment]
@Pierre-LHOSTE

**Comment by Atala** [comment]
ok thanks for the feedback

@alexsegura if i go carefully and change the text for "desktop size" and display lock icon for "tablet size" it should work no?
