### ISSUE TITLE
Sometimes orders end up in an invalid state with double delivery adjustments and fees

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4128]
That could lead to multiple payments on Stripe: https://github.com/coopcycle/coopcycle-app/issues/1603

--

See recent occurrences on Sentry: https://coopcycle.sentry.io/issues/4985406179/events/?cursor=0%3A0%3A1&project=5294179&referrer=next-event

**Comment by Paul-Eraman-CoopCycle** [comment]
is  this fixed?

**Comment by vladimir-8** [comment]
It happens way less often, but still occurs sometimes (9 orders per month)

**Comment by vladimir-8** [comment]
Duplicate; #3929
