### ISSUE TITLE
inputting username is buggy

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4131]
![password](https://github.com/coopcycle/coopcycle-web/assets/77277854/d29ed03a-b157-47c0-91e1-4d627137a4eb)

every letter responds with a query when making a username, during which time you cant type, and after querying you have to click on the box again. this is horrible for new users and leads to dropped clients.

**Comment by lucasferraro** [comment]
@Paul-Eraman-CoopCycle I pushed a fix for this forcing a focus in the username input after each query for username suggestions. This is how it works now:

https://github.com/coopcycle/coopcycle-web/assets/4819244/02e102b0-8471-4163-9a52-09a21e83f0f1

I feel like the "disable" action in that input is a bit annoying for the user but in terms of the implementation for the suggestions search is a useful hack.

**Comment by Paul-Eraman-CoopCycle** [comment]
can we make the pause that triggers a query longer?

**Comment by lucasferraro** [comment]
> can we make the pause that triggers a query longer?

Here it's a bit longer and also I added a condition for query suggestions only when username is bigger or equal than 3 characters.


https://github.com/coopcycle/coopcycle-web/assets/4819244/8d89f396-5575-49c8-be5b-8b7be9d9ba77

Let me know if it's ok and then I'll push this change.

**Comment by Paul-Eraman-CoopCycle** [comment]
Its hard to tell without tying but lets go with this for now put in the demo and i can try it? Then after testing we push to main?

**Comment by lucasferraro** [comment]
> Its hard to tell without tying but lets go with this for now put in the demo and i can try it? Then after testing we push to main?

Ready to test it in demo https://demo.coopcycle.org/register/

**Comment by Paul-Eraman-CoopCycle** [comment]
Tested :) 

Im on mobile atm but a lot of accounts are made this way

Timing of the query seems good, but can we avoid the keyboard disappearing?

**Comment by Paul-Eraman-CoopCycle** [comment]
laptop is good
![usrnm](https://github.com/coopcycle/coopcycle-web/assets/77277854/96e00407-5c13-4541-bfe2-464a193092e2)

**Comment by Paul-Eraman-CoopCycle** [comment]
Sorry forgot the phone videohttps://github.com/coopcycle/coopcycle-web/assets/77277854/58e549b2-4584-4171-bcd5-578769517f89

**Comment by Paul-Eraman-CoopCycle** [comment]
Can we make it so that after the query, i am still "inside" the username field? so that if after the query I keep typing with the keyboard it will continue to type?

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/e6a4afed-1bfc-4dd0-be26-a9f35ef5aab7)

**Comment by Paul-Eraman-CoopCycle** [comment]
wait it does do this in the demo, sorry
that was a test on eraman

**Comment by Paul-Eraman-CoopCycle** [comment]
https://github.com/coopcycle/coopcycle-web/assets/77277854/6a319d0f-728e-4d73-9077-85c70ae31743

ios 
here it doesnt do any check, is that how we want it to work? i remember before it checked, and the keyboard disappeared after the check

**Comment by Paul-Eraman-CoopCycle** [comment]
so maybe we need to make a new issue for what i described above because thats app and not web (if we dont want it running checks in the field thats fine for me)

but right now doing it in browser with a phone, the keyboard disappears when it checks the username, would be better if it didnt

is that possible?

**Comment by lucasferraro** [comment]
sorry, I couldn't check yet the issue with the keyboard in phone's browser. 

Maybe that issue is happening because we disabled/enabled the input before/after the request for username suggestions. I'm wondering if disabling/enabling username input is needed, maybe we can avoid that because also if we don't disable the username input I think is a better experience for the user.

**Comment by Paul-Eraman-CoopCycle** [comment]
for an old person trying to do this and remember what is the next letter, this is still fast to "check". if the keyboard could be maintained open, it would be fine though. video finally, sorry it took a while

https://github.com/coopcycle/coopcycle-web/assets/77277854/caef0f23-c85f-4b63-8a00-8996930fbd7a

**Comment by Paul-Eraman-CoopCycle** [comment]
fixed 🦾
