### ISSUE TITLE
Dispatch pannel : An order is not in chronological order

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-web#4153]
**Describe the bug**
I am at the dispatch pannel like the screen. I received two orders. The 1st one was checked by the restauarnt Ichigo. And the second, from Bong, was accepted 1 min after.
But Bong order is after Ichigo in the panel while it should be the opposite.

**To Reproduce**
1. Go to Dispatch Panel
2. Wait for orders to drop
3. See the bug IF THE BUG APPEAR

**Expected behavior**
Whatever the accepted orders from the restaurants, the orders should always be in chronological order in the Dispatch Panel. 

**Screenshots**
![Capture (1)](https://github.com/coopcycle/coopcycle-web/assets/144671333/5f55be7c-8453-4759-9d0c-df0c7e379e9e)

**Desktop (please complete the following information):**
 - Browser : chrome

**Comment by Atala** [comment]
Fixed
