### ISSUE TITLE
nothing happening for business accounts when creating a new restaurant group

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4154]
**Describe the bug**
I go to https://demo.coopcycle.org/admin/restaurants/business-restaurant-groups and try to save a group in the Naofood instance. clicking save does not make a response. The page does not load, nothing changes. 

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/6eb89fca-2c7a-48d6-b3b9-caa118c55031)

**Comment by lucasferraro** [comment]
Check "Fulfillment" and/or "Settlemen" sections, for sure there are errors there that are note displayed in "General" section. It's a bit annoying behaviour but the same thing happens for all other settings pague like the restaurant one..

**Comment by lucasferraro** [comment]
For this kind of configuration screens (with multiple sections) may happen that a section is invalid or incomplete and the whole configuration can not been saved:

https://github.com/coopcycle/coopcycle-web/assets/4819244/f1e50d89-5266-4e6e-b754-e21103be43e7

I pushed a quick fix to show a general error message when this happens to alert user for checking all the sections before submit.

https://github.com/coopcycle/coopcycle-web/assets/4819244/c6b320ec-58ba-4927-9935-de3274d39a70

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok, could we put a text at the top above "name" that says "please fill out all three settings pages"? because my first reaction seeing that error would be to add a restaurant, not to realise that CC wants me to fill out the other two pages

**Comment by lucasferraro** [comment]
Ok, I added a message as you suggested at the top of the screen. It should be available in next deploy to demo instance. 

![Image](https://github.com/coopcycle/coopcycle-web/assets/4819244/1da749fc-b502-4da7-b134-7d6558169597)

**Comment by Paul-Eraman-CoopCycle** [comment]
shouldnt this throw that error message?

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/cd7f11d8-f655-4dc0-b31f-0614d1756512)

**Comment by Paul-Eraman-CoopCycle** [comment]
wait just figured it out
you made that error for restaurant groups, i guess its an open question if we need it for business accounts

**Comment by Paul-Eraman-CoopCycle** [comment]
it the error already is thrown and i press save again, but it still is incomplete, it should do something. like to show me that i still need to finish stuff



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/496cc753-e1b2-4c81-b8d2-dfb2abad03bb)
