### ISSUE TITLE
Sorting unassigned tasks is broken in dashboard

### ISSUE THREAD

**Issue by Srywards** [coopcycle/coopcycle-web#4162]
**Describe the bug**
When i choose another sort for my tasks, nothing happen unless i hard refresh the page (F5 for newbies)

**To Reproduce**
1. Go to non assigned tasks
2. Click on upper right button to sort
3. Choose sort by ascending order or another
4. Nothing happen, the tasks are not sorted
5. If i hard refresh the page the sort works until i receive a new task

**Expected behavior**
Sort should be effective when i click on it and remain effective

**Screenshots**
![image](https://github.com/coopcycle/coopcycle-web/assets/15232456/947593c8-c930-4877-83c9-38ffd61196c8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Latest release on 17 April 2024

**Comment by Atala** [comment]
hello clement thanks for the report I actually broke this doing some other stuff, there is a discussion on going here https://github.com/orgs/coopcycle/discussions/29

which sorting did you want?

**Comment by Srywards** [comment]
@Atala
Thanks for the link

I would like dropoff asc :)

**Comment by Atala** [comment]
OK I see why. right now they are sorted by beginnng of delivery slot  which is kind of ok, but i guess what you really want is to group pickup+dropoff to have a clear view that is it? (which is kind of another stuff no?)

also dont worry if you dnd just the dropoff then it will be alright

**Comment by Srywards** [comment]
If it's possible i just want to get all pickup in asc order like before, don't mind if pickup and drop are grouped together

**Comment by Atala** [comment]
I temporiraly disabled the "manual sorting" until we finish the discussion. I will test on naofood instance tomorrow

**Comment by Srywards** [comment]
Okay thanks, for now i see no difference, the bug still remain :)

**Comment by Atala** [comment]
deployed on naofood now + tested OK on rennes
