### ISSUE TITLE
When reordering a tour in the tasklist by draNdrop the tour jumps at the end of the list not at the desired index

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4185]
See gif below - not sure it arrives 100% of the time

does not happen when moving the tour up in the list

![reordering-tour](https://github.com/coopcycle/coopcycle-web/assets/4426585/8dea19bd-6c6a-4660-b7a2-8583c886616a)

**Comment by Paul-Eraman-CoopCycle** [comment]
now its only skipping down 1! progress!
