### ISSUE TITLE
"Create order" should be ticked by default for stores

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4204]
When we create a store the option "create order" is unticked, but it seems that it should be the default

BUT

if you tick that and don't have pricing rules for the store  it will break stuff (maybe that is already the case)

**Comment by Paul-Eraman-CoopCycle** [comment]
See https://github.com/coopcycle/coopcycle/issues/110

**Comment by Paul-Eraman-CoopCycle** [comment]
Should we close this and keep track there?
