### ISSUE TITLE
In the admin, If you chose a different map provider than google maps the form stills validate the GoogleMap API Key

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4206]
blocks changing settings even if you dont have the google maps API key yet

**Comment by Paul-Eraman-CoopCycle** [comment]
not closed until its in the finished column! sorry 🙏

**Comment by Atala** [comment]
To be checked when creating new instance https://github.com/coopcycle/coopcycle-ops/issues/51
