### ISSUE TITLE
Business account problem: with existing user account doesnt work

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4218]
I made a business account and wanted to make an existing account an administrator. since the only option was to input the email of that existing account, i did that.

then i didnt recieve an email, and after exiting and entering my account, i did not have access to the business account.

naofood instance
user is pauljiano@protonmail.com
business account is businessbob2

**Comment by lucasferraro** [comment]
Changes introduced in this PR https://github.com/coopcycle/coopcycle-web/pull/4245

**Existing user clicks on invitation but is not logged in in the app**
Now we ask for login first, and then we skip the step 1 (personal account creation) and send the user to the 2nd step when should complete the info of the company.

https://github.com/coopcycle/coopcycle-web/assets/4819244/b3a1ada0-847c-4c25-99c7-868a0ff6eebb

**Existing user opens the invitation while is already logged in in the app **
After click in the invitation we skip the step 1 (personal account creation) and send the user to the 2nd step when should complete the info of the company.

https://github.com/coopcycle/coopcycle-web/assets/4819244/b6b7aa06-4d17-4cca-bec3-88dd143163c6

**Resend invitation email**
New resend invitation email action for cases when the invitation email is not received

https://github.com/coopcycle/coopcycle-web/assets/4819244/caaeeb64-a40c-4166-9f53-b19cf4c026cd
