### ISSUE TITLE
business account order history confusion

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4222]
when i am in my business account admin page, the "my orders" page should show orders i made as a client (so far so good)
but somewhere it should show separately the orders made in the business account by my employees. right now, i dont know where this information is shown

**Comment by lucasferraro** [comment]
I think is a duplicated issue of this https://github.com/coopcycle/coopcycle-web/issues/3758

**Comment by Paul-Eraman-CoopCycle** [comment]
yep. closing
