### ISSUE TITLE
pricing problem with TLOK

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4223]
https://tlok.coopcycle.org/admin/deliveries/pricing/10

this pricing rule always results in 140 pesos no matter the conditions using either https://tlok.coopcycle.org/es/forms/Wwk9BaABjy6x?data=RvzrPxqeBZO6 this forumulario or as a shop

if all the conditions besides the first
<img width="1582" alt="Screenshot 2024-04-27 at 00 32 23" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/83eec5ed-8cab-4a67-9933-fd971d8aea34">
are deleted, it works at 70 pesos, if not always 140

**Comment by Atala** [comment]
Findings round 1 :

**Comment by Atala** [comment]
also we should add some info log to know if we evaluate against tasks or deliveries. maybe some other logs showing the matching process more deeply

**Comment by Atala** [comment]
- also a task has no distance so "apply to all tasks" won't work with distance. https://github.com/coopcycle/coopcycle-web/blob/master/src/Entity/Task.php#L1097

**Comment by Atala** [comment]
- see for shops what happen when you enable multidropoff deliveries ?
