### ISSUE TITLE
cancelled task showing as not cancelled

### ISSUE THREAD

**Issue by Oscarpaccio** [coopcycle/coopcycle-web#4225]
**Describe the bug**
A cancelled task was showing while the filter was off, the only way i made it disappear was by cancelling it again via right click cancell the task

**Expected behavior**
Cancelled tasks should not appear in dispatch if the filter is off

**Screenshots**
![filters](https://github.com/coopcycle/coopcycle-web/assets/168424849/ad41ab06-c7cf-4c81-8c68-51f00e6cdf2a)
![ichizeappearingondispatch](https://github.com/coopcycle/coopcycle-web/assets/168424849/00070929-c4c4-46c8-9ad1-6396670a5af5)
![ichizencancelled](https://github.com/coopcycle/coopcycle-web/assets/168424849/7a410f26-4e59-4a25-9c90-3a380fc9884e)

**Device (please complete the following information):**
Google chrome

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
going to track in #4491 , closing here
