### ISSUE TITLE
Default selection of packages does not work anymore

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#4229]
Some time ago, it had been done a super useful small thing which was that when only one package was created in a package set, it was selected by default in the form when creating a delivery. 

This doesn't work anymore (it's been not working for a while now). I stopped saving multiple times 2 clicks a day!

![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/a0e04370-a48f-464e-b2d2-4bcd754813d7)

**Comment by Atala** [comment]
PHP code https://github.com/coopcycle/coopcycle-web/blob/076c6e7288d8b6d2e25ddab412daeaa547804e14/src/Form/TaskType.php#L254-L271

should be doable to automatically select package around here https://github.com/coopcycle/coopcycle-web/blob/076c6e7288d8b6d2e25ddab412daeaa547804e14/js/app/forms/delivery.js#L254 

in `createPackagesWidget` or `createPackageForm` but code is knd of hairy so it has to be well thought
