### ISSUE TITLE
As an admin I want a global platform setting to not send this notification: "Your rider is coming close..."

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#4247]
**In order to** 
have less useless notifications

**As a**
dispatch/admin

**I want** 
to be able to disable the notifications that tells me the bike courrier is close

**Whereas currently** 
I get several notifications a day telling me my courrier is coming close

**Additional context**
when I do dispatch and ride at the same times, i get several notifications a day to tell me my bike courrier is coming close
I am in a sens my own bike courrier so I am actually always very close...
![signal-2024-05-07-121612_004](https://github.com/coopcycle/coopcycle-web/assets/146206239/d3f629c4-7a02-4594-8fba-9cc4eb68ff96)

**Comment by Paul-Eraman-CoopCycle** [comment]
This should be a notification that can be toggled on or off here: https://demo.coopcycle.org/admin/settings

![Image](https://github.com/user-attachments/assets/cd732340-d92b-4bf5-8b8f-550be2159174)
