### ISSUE TITLE
When you use "only show these filters"  in the dispatch dashboard, they should be "erased" when modifying other filters afterwards

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4249]
Steps to reproduce
- go into the dispatch dashboard
- select "only show tasks with incidents"
- apply (it should work)
- open filters again
- select "show finished tasks" (or any other filter)
- apply
-> you still see only tasks with incidents

**Comment by r0xsh** [comment]
Fixed by: https://github.com/coopcycle/coopcycle-web/commit/8d177f79fbb281bd935ba8debbd36e23ff9a81f3
