### ISSUE TITLE
Send reminders to accept orders

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#425]
We need to send reminders for orders that need to be accepted shortly. 
The simplest solution is to make a script that is scheduled every minute, and send emails/notifications to restaurant owners. 
If an order is still not accepted after a reasonable delay, it should be cancelled.

**Comment by Paul-Eraman-CoopCycle** [comment]
In the new design its not a reminder, its a color change in the order visualisation, which is an issue is the new designs
