### ISSUE TITLE
When you select "HIDE finished tasks" + "SHOW tasks with incidents" in the web dispatch it only shows UNFINIShed tasks 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4250]
this only shows unfinished tasks, doest not show tasks with incidents

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/abb14abf-5d98-4b31-a138-d6db19c5e850)

**Comment by r0xsh** [comment]
There was a problem with how it was worded and with the user experience. If you hide completed tasks and show tasks with incidents, unfinished tasks and tasks with incidents will appear together.

When you select "Only show these," it will display incidents only, regardless of their status. To make this clearer, I've added a violet color and a specific label when the "Only show these" option is turned on.

![image](https://github.com/coopcycle/coopcycle-web/assets/5613584/6942a6e3-3d04-41e5-b15c-42e5451b9276)
