### ISSUE TITLE
Make client name search appear by default

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4258]
The new client search field is great, but we would like to have it open by default, not below a dropdown menu

photo:

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/6ffd197f-e912-4665-bc0a-e841ee8d8679)

instead of being behind that dropdown, just appearing

**Comment by lucasferraro** [comment]
Now the input for search saved address is always open and available. https://github.com/coopcycle/coopcycle-web/commit/173e5168bce5e25bc487dd86e559c0ef73aef3a3

![Captura de pantalla de 2024-05-14 14-57-19](https://github.com/coopcycle/coopcycle-web/assets/4819244/5114259c-a456-47ff-9501-a4a5b77fcc6c)
