### ISSUE TITLE
When an admin deletes a package set of which a package is linked to a task then it fails

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4259]
The task is linked to the package
The package set deletion cascades to the packages
Deletion of the package fails because it is is linked to a task

https://coopcycle.sentry.io/issues/5288895928/?project=5294179&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0

-> so when we delete package set it should SET_NULL on package but not delete PACKAGE

TO TEST with package set named 1 on eraman instance

**Comment by Atala** [comment]
linked to #4999

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
