### ISSUE TITLE
I want to be able to save a comment with an adress

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#4265]
**In order to**
communicate the specificities of adresses of regular client to the courrier

**As a** `role`
dispatch/admin

**I want** `
to be able to save comment with the address of my client

**Whereas currently** 
when i save an adress it saves theadress, names and phone number

**Additional context**
we have deliveries everyday for client and very often the same adresses, some adresses are not really clear (exemple, we only have number and street, where as the truth is you gotte to find a door hidden somewhere unbearably weird to get to their delivery service)
we would like to be able to put in a comment those info for the courrier, and that they get put automatically every time we have a delivery at this adress

**Comment by Atala** [comment]
there is actually a field to save extra infos for an adress so i guess if you were using the stores saved adress you could add a description (if available in the form for saved address) and then when you create an order it will work

however
 - i dont think you can add orders or use saved adress from the dispatch panel
 - i think there is no "description" field when you use the saved address form from the store "adresses" tab

cc @Paul-Eraman-CoopCycle
