### ISSUE TITLE
Crash when deleting a tour after doctrine update

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4272]
to reproduce : delete a tour in the dispatch panel

https://coopcycle.slack.com/archives/G01JR0YF5V3/p1715868226522649

https://coopcycle.sentry.io/issues/5354900216/?project=5294179&query=is%3Aunresolved+managed&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Comment by alexsegura** [comment]
Fixed in 499eb6e60cc10e6bd8cd6a92a1f6db8349ab47ab
