### ISSUE TITLE
Dropoff is created before Pickup when importing CSV when they have the same timeslot

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4273]
It causes problems in the workflow of some users, as when they export they want to be able to sort tasks by ID

The problem was detected in the case pickup and dropoff timeslot of delivery are the same. I guess in case of equality the pickup should be put first when sorting the tasks.

Ask Aloïs for example file

**Comment by alexsegura** [comment]
For me it's a WONTFIX. The auto-generated IDs should have no meaning.

**Comment by Paul-Eraman-CoopCycle** [comment]
Talked to the users, is not a big deal if the number remains wrong, especially since we are building internally the tools to do what they are doing now manually with excels (profitability analysis). wontfix ✅
