### ISSUE TITLE
ability to import saved clients/addresses

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4288]
with csv file

**Comment by Paul-Eraman-CoopCycle** [comment]
Could I get a time estimate @Atala @vladimir-8 @alexsegura ?

**Comment by alexsegura** [comment]
What is the requirement exactly? 

Adding addresses to a store via CSV upload?

**Comment by Paul-Eraman-CoopCycle** [comment]
yes, with related fields

business name
contact name
phone number
comments

**Comment by vladimir-8** [comment]
Duplicate: https://github.com/coopcycle/coopcycle-web/issues/4151
