### ISSUE TITLE
Improve the error notif when invited user (both group admin or group member) has already an account

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4294]
Currently
 - user enters an email (and other details, actually it would be better if we check the email directly)
 - if the email exists a yellow info message is shown to redirect to login + the error message "account already exists" is displayed. one of the message is on top of the input and the other one at the bottom of the input

What we would be better :
 - there is only ONE (yellow) message that states : "This email is already taken, do you want to login with it (with the link)? You can use an other email if you want to"

**Comment by lucasferraro** [comment]
[Commit](https://github.com/coopcycle/coopcycle-web/commit/106e188eee65b3d1b2b6c9eaefbf89debad4a249) already in master.

@Atala  This is how it looks now, let me know if there is something to improve or change.

https://github.com/coopcycle/coopcycle-web/assets/4819244/d9101524-125b-42b5-9ff6-3790d2a14702

**Comment by Atala** [comment]
cool thanks !
