### ISSUE TITLE
[Need investigation] Business restaurant  group admin is logged out when one user accepts the invitation (?) 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4295]
From Guillaume Naofood : "
Otherwise, I signed up for an already existing account, created my business with it, therefore in business account mode.
I invite Théo, and Théo creates his account and logs in. At that point it disconnected me. I try to log in again, and my account no longer exists.
I manage to recreate the account with the same email address.
"

I dont think the account is deleted and it is not clear what happened, but strange in any case

additional info :
"I sent the code / link to a colleague / non-existent account, an average guy who has never been on Naofood or coopcycle.
He clicks on the link, creates his account.
It delights me when he logs in.
And I can't recognize myself anymore. No error message from pk. I'm trying to recreate an account with the same email: communication@naofood.fr, and it doesn't tell me that this email is already used, it accepts and validates the account creation. I didn't understand. I suddenly told myself that it had deleted my previous account."

**Comment by lucasferraro** [comment]
I found the error. We sent the existing user as a parameter of the registration form and that is why the new registered user was overriding the existing one. https://github.com/coopcycle/coopcycle-web/commit/0cab6d81d096abc270a6e4a0285cb7b58aac0861
