### ISSUE TITLE
In business restaurant group invitation process; check if the user exists before the user enters all of his detail 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4296]
Now : the invited user enters his email, then all his details THEN we check the email

Better : the invited user enters his email and we check right away the email, so he doesn't waste time

**Comment by lucasferraro** [comment]
@Atala 
We are validating the email in the same way for all kind of new users registration. 
Do we want to change it to validate at the beginning for one of them, for some or for all?
- Business Account managers invitation
- Business Account employee invitation 
- Regular users with invitation link
- Public registration screen

**Comment by Paul-Eraman-CoopCycle** [comment]
THis would be best for all users in all situations. The same way we check if the username is taken once they have finished typing it, when they finish writing their email and click out of the box (not while they are writing) it should check if we already have an account made with that email

**Comment by Atala** [comment]
yes i think same as username is nice, maybe with a longer delay before checking i had the impression it was a little bit too short?

i dont know how it is done technically this check, i guess with an API endpoint ?

**Comment by lucasferraro** [comment]
Yes, for username we are using an API endpoint  `/register/suggest`. So I think we could have a new one like `/register/check-email` which can be called after a user type a valid email (I think does not make any sense check for the email while is not complete) in the input.
