### ISSUE TITLE
add address.name & tag fields to /delivery/new

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#431]

**Comment by couleurmate** [comment]
And phone

**Comment by alexsegura** [comment]
Quick'n'dirty. 

Can be improved in terms of UX.
For example, hide the "name" field by default, and add a "+ Add a name" button, etc...

<img width="568" alt="capture d ecran 2018-12-13 a 17 53 34" src="https://user-images.githubusercontent.com/1162230/49954264-5ff86f80-ff00-11e8-8850-dbd28c47ed5d.png">
