### ISSUE TITLE
For the admin of the business group : miss in the topbar a big button "ADMINISTRATE MY BUSINESS GROUP" to go to settings

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4316]

**Comment by lucasferraro** [comment]
@Atala 
The idea is to have a button like this for Business Account managers?

https://github.com/coopcycle/coopcycle-web/assets/4819244/f816402b-c998-46de-b5aa-84b74aa93bce

**Comment by Atala** [comment]
yes !

be aware of the text size, as a text that long would break on tablets display i think, check on every screen size
