### ISSUE TITLE
for the customer of the business group : miss in the topar a big button "ORDER WITH MY COMPANY" (account switch)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4317]

**Comment by lucasferraro** [comment]
@Atala 
Is this duplicate of https://github.com/coopcycle/coopcycle-web/issues/4315?

**Comment by Atala** [comment]
mmm not exactly, i think we need both :
- something that show the user he is ordering with his company (current state = business mode)
- a switch action that show the user he can go in/out business mode (not buried in the dropdown but clearly stated)

but i think a good design could do both in one go. we can ask vincent for this if needed

(also as i say in another issue be aware of the screen size tablet when putting things in the topbar)
