### ISSUE TITLE
There is no "ORDER NOW" button to go to restaurant page from the professional account page

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4318]

**Comment by lucasferraro** [comment]
@Atala 
In this screen should exists a button "Order now"?
<img width="600" src="https://github.com/coopcycle/coopcycle-web/assets/4819244/4ec1662b-5c24-47d8-8507-a67f1ee6454b" />

Where should it redirect? to homepage (list of restaurants) or a restaurant page? (which one of the restaurants?)

**Comment by Atala** [comment]
yes indeed! to homepage (list of restaurants) or maybe better list of all restaurants with all the filters aso; (it is another page if i am not mistaken)

**Comment by lucasferraro** [comment]
Pushed to master https://github.com/coopcycle/coopcycle-web/commit/7f6171b648a822cb9d30ff491f03ce56b6e8f6fd

New button for Business Account managers which redirects to shops (restaurants) and turns on the "busines account" mode.

https://github.com/coopcycle/coopcycle-web/assets/4819244/f330289d-5d63-4049-9a7b-1ff09719c7b9
