### ISSUE TITLE
Add recurrent rules for orders

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4327]
Add recurrent rules options to right side hand of local commerce web page orders

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/230d0b9c-9347-4584-a448-b20658b8a70a)

Should support both pricing rules and manually set price (`arbitraryPrice`)

**Comment by vladimir-8** [comment]
Some cleanup and testing is still needed
