### ISSUE TITLE
Introduce Saved orders page

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4331]
1. Dispatch; 'Delivery' page: Add a button: `Duplicate an order`: opens "Create a new order" page while coping/pasting data from the current order 

PR: https://github.com/coopcycle/coopcycle-web/pull/4474

2. Dispatch; 'Delivery' page: Add `save order` option to right side hand of local commerce web page orders (only for Dispatch)

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/230d0b9c-9347-4584-a448-b20658b8a70a)

PR: https://github.com/coopcycle/coopcycle-web/pull/4489

3. Dispatch; 'Store' page: Add a page with the list of saved orders

![Screenshot 2024-06-27 at 15 35 01](https://github.com/coopcycle/coopcycle-web/assets/70273239/a097618b-0bcd-44f2-be38-c8cebf95b056)

PR: https://github.com/coopcycle/coopcycle-web/pull/4489

**Comment by Paul-Eraman-CoopCycle** [comment]
as discussed, this is more like "favorites" since everything is in practice saved
