### ISSUE TITLE
cash deliveries should have amount of money in the task info for the messenger

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4337]
when doing cash delivery the messenger must request money from the customer. These deliveries should have the amount of money in the pickup and dropoff task to facilitate this.

![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/68700a88-2678-4200-8708-4d7bab46c73a)

**Comment by vladimir-8** [comment]
It works only for food tech orders at the moment. It will not work for orders coming from a Delivery form (B2C customers) until https://github.com/coopcycle/coopcycle-web/issues/4746 is fixed.
