### ISSUE TITLE
Double refund requests

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4341]
**Describe the bug**

Sometimes, when creating a refund, double refund requests are created (both on the platform and on Stripe)

**Additional context**

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1716060037373999

Look at the timestamps (1s interval between reimbursement requests)

Problematic orders:

112048 on 10/07/2023 (lcr)
140049 on 2024-03-04 (lcr)
147745 on 2024-04-13 (lcr)

**Comment by vladimir-8** [comment]
Could somehow caused by this loop? https://github.com/coopcycle/coopcycle-web/blob/master/src/Controller/AdminController.php#L326

**Comment by Atala** [comment]
Duplicate of #4608
