### ISSUE TITLE
Incident report failed

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-web#4346]
**Describe the bug**
<img width="1580" alt="Capture d’écran 2024-05-29 à 13 03 26" src="https://github.com/coopcycle/coopcycle-web/assets/134289346/f260bdc9-6fda-4e24-b535-19d306c96e75">
When reporting an incident by right clicking a task on the dispatch dashboard, the report is not made and it seems to be stuck on loading...

**To Reproduce**
1. report an incident
2. fill the form
3. wait

**Comment by r0xsh** [comment]
Could you provide more details about the issue? Is it reproducible 100% of the time, or does it occur intermittently? Does it only happen with this particular task, or have you noticed it in other scenarios as well?

**Comment by Atala** [comment]
@0bi0ne1312 tell me if you have an issue with it

**Comment by 0bi0ne1312** [comment]
Works perfectly now !
