### ISSUE TITLE
Schedulable temporary closure for the whole platform

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#4357]
Add a temporary closure for the whole platform that can be scheduled ahead of time. Just like you can do with a single restaurant, but for the whole platform. It would prevent situations where a customer pre-order during a previous service and would make platform management more comfortable.
For instance, our service is going to be exceptionally closed tonight, but a customer pre-ordered during lunch shift for tonight. We have no way to efficiently prevent that from happening. Now we’re going to have to call the customer to inform him and apologize for the inconvenience.. which doesn't make us look good and shouldn't have to happen in the first place!
Thanks !

**Comment by vladimir-8** [comment]
Sounds the same as this one: https://github.com/coopcycle/coopcycle-web/issues/3627
