### ISSUE TITLE
Add the option to associate a weight to a package on top of the volume

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#4359]
Add the possibility to associate a weight to a package. This could be optional as sometimes the weight is not always fixed or known for a package type. But it could be useful to configure packages thoroughly. Weight and volume are the two most important information to have for a package (along with optional special care).

For instance we're going to work with a wine shop. The package weight is constant. A bottle of wine is on average 1.3 kg.

Additionally, could it be possible to change the data input from integer to decimal numbers ?

<img width="966" alt="Capture d’écran 2024-06-01 à 17 18 44" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/0fd7638e-d270-41da-9b36-461f98578afa">

<img width="966" alt="Capture d’écran 2024-06-01 à 17 18 44 copie" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/e85a99d7-f711-45bb-80fc-fc6ffefc14dc">

**Comment by Paul-Eraman-CoopCycle** [comment]
done!
