### ISSUE TITLE
Installation : make install lead to runtime exception error on Linux

### ISSUE THREAD

**Issue by freelibre** [coopcycle/coopcycle-web#436]
**System information**
Fedora 28
Linux 4.18.7-200.fc28.x86_64 

**Steps to reproduce**
`git clone https://github.com/coopcycle/coopcycle-web`
`cd coopcycle-web/`
`make install`

**Expected result:**
No error

**Actual result:**
[RuntimeException]                                              
  /srv/coopcycle/vendor does not exist and could not be created. 

**Detail logs:**
[MakeInstall.log](https://github.com/coopcycle/coopcycle-web/files/2386887/MakeInstall.log)

**Comment by Atala** [comment]
We have this workaround for now on (if you find the proper fix it will be better!)
```
Hi @florent_k I had the same exact issue on Debian 7 and had to change the Dockerfile to use uid 82 instead of www-data as well as chmodding var/cache and vendor to 777 (unsafe but I guess it is ok for testing)
```

**Comment by Atala** [comment]
Could you try this workaround? (or even find a proper fix?)
`had to change the Dockerfile to use uid 82 instead of www-data as well as chmodding var/cache and vendor to 777 (unsafe but I guess it is ok for testing)`

**Comment by freelibre** [comment]
Thank you for your feedback. Sorry I don't understand yet what you mean by "to change the Dockerfile to use uid 82 instead of www-data" also I don't see any vendor directory or file in the repository.
I have tried to change permission of var/cache to 777 before running a make install but it still through the same error message output in red.
`[RuntimeException]                                              
  /srv/coopcycle/vendor does not exist and could not be created.  `
I've also tried to create manually  /srv/coopcycle/vendor but I'm still getting the same error message.
I will investigate further and will let you know.

**Comment by freelibre** [comment]
May be a fix could be to add user 82 to www-data group with:
usermod -u 82 www-data

**Comment by Senzaki** [comment]
Or simply:

```
sudo chown -R $(id -u):82 coopcycle-web
sudo chmod -R g+w coopcycle-web
```

A bit of a hack but it works.

**Comment by freelibre** [comment]
Thank you, yes this hack works for me too so I could continue further in the make process but then I get a DB error (see attached logs). By the way yesterday (without the new merge) I was asked my API GCP and today with a clean install no key is asked...I will keep looking if I can find something to help you with.

**Comment by alexsegura** [comment]
@freelibre Looking at your log file, it says the database _already exists_, which explains why you weren't asked for GCP API key

When you say a clean install, are you sure you actually erased the containers?

**Comment by freelibre** [comment]
I tried again and this time I delete all docker images and containers see commands below:
`sudo docker ps -a -q | xargs sudo docker rm -f`
`docker images -q | xargs sudo docker rmi`
` sudo \rm -rf coopcycle-web/`
`git clone https://github.com/coopcycle/coopcycle-web `
`sudo chown -R $(id -u):82 coopcycle-web`
`sudo chmod -R g+w coopcycle-web`
`cd coopcycle-web/`
`make install`

I'm still getting a DB error message and no API GCP is requested. I guess it's still valid once set-up as it says:
`Database "coopcycle" for connection named default already exists. Skipped.`

In attachment you will find all the commands and logs
[logs-make-install-linux.txt](https://github.com/coopcycle/coopcycle-web/files/2430562/logs-make-install-linux.txt)

**Comment by Senzaki** [comment]
You should also remove the associated volumes (`docker volume rm $(docker volume list -aq)` if you only have CoopCycle-related volumes). Hope that solves it :)

**Comment by freelibre** [comment]
yes removing the volumes make it works :+1: 
(`docker volume rm $(docker volume list)` as the `-aq` parameters don't work for me.
So I could see it in the web app in my browser but there is another problem now regarding page layout see snapshot: 
![capture d ecran de 2018-09-29 13-41-10](https://user-images.githubusercontent.com/1781304/46245435-da2f5280-c3ed-11e8-9886-49685b81438f.png)

**Comment by alexsegura** [comment]
@freelibre try this:

```
docker-compose exec webpack npm rebuild node-sass
```

**Comment by freelibre** [comment]
I've just tried put it stops right away and get this error message:
`
ERROR: No container found for webpack_1
`

**Comment by alexsegura** [comment]
You need to have docker-compose already running somewhere else

**Comment by freelibre** [comment]
In fact I've just made it worked by adding one line to the webpack Dockerfile:
`RUN npm rebuild node-sass`
and then
`docker-compose up` works !

**Comment by freelibre** [comment]
I've played around but couldn't add any item to a restaurant order. I guess it's due to an installation issue as I don't find any existing issue on this subject.
See a snapshot / error:
![capture d ecran de 2018-09-30 08-46-04](https://user-images.githubusercontent.com/1781304/46254302-90964480-c48d-11e8-825b-170ad07b70d5.png)
![capture d ecran de 2018-09-30 08-47-31](https://user-images.githubusercontent.com/1781304/46254303-94c26200-c48d-11e8-8c33-1eadf07e8cc7.png)
![capture d ecran de 2018-09-30 08-47-37](https://user-images.githubusercontent.com/1781304/46254304-98ee7f80-c48d-11e8-9044-7a8a01096f4c.png)
![capture d ecran de 2018-09-30 08-47-48](https://user-images.githubusercontent.com/1781304/46254305-9ab84300-c48d-11e8-96e7-f7ff05cf7306.png)

**Comment by freelibre** [comment]
Thank you for these useful information, I will work on this rates issue and let you know if I can find something or at least may be help you on the user install documentation/manual may be adding something like may be the free [ReadtheDoc](https://read-the-docs.readthedocs.io/en/latest/getting_started.html) to your project.  
Anyway I could go further in the ordering process but then I'm getting stuck now when I want to pay. I guess it's related to the strip account as I don't have a stripe key set-up yet. Do you know if anybody could get a Stripe Test key for free ?

**Comment by alexsegura** [comment]
For the docs, there is a [coopcycle-docs](https://github.com/coopcycle/coopcycle-docs) repo. 
It is a Jekyll website deployed with GitHub pages. 
We have tested ReadTheDocs, but it is based on Sphinx/reStructuredText, we prefer Markdown. 

For Stripe, you can create an account for free.

**Comment by alexsegura** [comment]
The docs are far from perfect & exhaustive 😓

@freelibre for the taxes stuff, let me create an Issue so that I can give some details on what needs to be done. It's quite clear in my mind, but this may help you get started more quickly.

--- 

@Senzaki @freelibre now that this Issue is "fixed", may I ask you what you are doing here? 😅
Are you riders, geeks, both? Do you plan to create a co-op? How did you end up here?
We have a Slack (no IRC sorry, we're hipsters), drop us an email at dev@coopcycle.org if you want to get invited. 

If you are located in Paris, maybe we can have a coffee? We love to meet people in person.
And even if you are somewhere else, we travel around from time to time, so we may come to your town some day.

**Comment by freelibre** [comment]
I couldn't run behat test properly on Linux because of permission issue. To fix the issue I've changed the group of the private key generated during the installation and located in var/jwt to 82: `sudo chgrp 82 private.pem` and then allowed read access to group to the key: `chmod 640 private.pem`  I'm not sure it's the best solution security wise but at least it fix the issue.

**Comment by freelibre** [comment]
I've fetched the latest commits but now `make install` lead to a sylius_order table duplicate error see:
[make-install.log](https://github.com/coopcycle/coopcycle-web/files/2568155/make-install.log)

**Comment by alexsegura** [comment]
@freelibre 

Yep, `make install` is just for the first time. 

When updating, you should: 
- Run the database migrations `make migrations-migrate`
- Rebuild the Docker containers if they have changed `docker-compose build <container>`

There was #141 about providing a `make update` command, would you like to take care of it? 🙂

**Comment by freelibre** [comment]
Thank you, my bad. I will look into  https://github.com/coopcycle/coopcycle-web/issues/141 if I can do something during next update.
Here is a script I will use in the meantime to make sure I start from scratch with a fresh install, it's very brutal but at least I will be sure the environment is clean and conform to the original repo:
`docker ps -a -q | xargs docker stop`
`docker ps -a -q | xargs docker rm`
`docker rmi $(docker images -q)`
`docker volume rm $(docker volume list)`
`docker network rm $(docker network list)`
`sudo \rm -rf coopcycle-web`

**Comment by airsay** [comment]
Safe enough to resurrect this? I'm having similar issues with the most recent (February 2021) repo. Installed Docker and Docker-compose on a 18.04 Ubuntu Cloud Server. Cloned the Coopcycle-web repo and changed into that directory. Copied .env.dist to .env and edited the necessary variables (Algolia and LocationIQ). Left Algolia as default. Updated the blank variables in docker-compose.yml. Ran docker-compose up and then make install.

All seemed to run well. However it looks like the stylesheets and JS didn't install properly.

My current interface looks like 
![F972F0EA-5731-4A18-A640-85347C55C44E](https://user-images.githubusercontent.com/7488892/107983521-3ea2da80-6fc6-11eb-83fa-971df4268192.jpeg)
![A99F2B5D-2BC1-4590-97B5-9CDB9D400CDD](https://user-images.githubusercontent.com/7488892/107983531-42cef800-6fc6-11eb-994e-fd9f7e9a4f13.png)


Please advise
