### ISSUE TITLE
"Weight" field on tasks import (from dispatch panel) does not seem to be taken into account

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4362]
- instance : sandbox-fr
- file : example import file with a dropoff at 50kg weight

Result : no weight is displayed on the task

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/de71740e-ef56-4496-be2f-e00f3b82bc76)

**Comment by Paul-Eraman-CoopCycle** [comment]
is it not shown or is it not associated with the task at all?

**Comment by Paul-Eraman-CoopCycle** [comment]
appears related to #4360 , can we combine?

**Comment by Atala** [comment]
no it is not the same, there is a column in the csv for this but it is not taken into account

but i think we would like to forbid task imports to force users to use delivery import? so in this case we dont need to fix this, just block the import

**Comment by Paul-Eraman-CoopCycle** [comment]
right, there is an existing issue to remove this and implement an order creation button/modal which would make this irrelevant. closing as not planned.
