### ISSUE TITLE
As a dispatcher/admin, I want to be able to (automatically) create a new order when resolving an incident

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4367]
Example case :
 - customer was not there at dropoff
 - I need to do again the dropoff

Currently people have to create a new delivery manually, but they can't add stuff to the existing delivery.

**Comment by Paul-Eraman-CoopCycle** [comment]
this would be a reschedule, not create a new delivery, based on our current workflow

going to close for the moment

**Comment by Paul-Eraman-CoopCycle** [comment]
This was due to lack of info about how incidents work. By using not not using the "validate task" the incident can reflect if the package was delivered or not, with an incident marked
