### ISSUE TITLE
In the foodtech order dispatch the delay bar should change the pickup time not the dropoff (bad name)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4373]
As told by users : "In the foodtech order dispatch the delay bar should change the pickup time not the dropoff"

I don't think I understand all of this and the behaviour that the dispatcher expects. Especially from which orders/deliveries are we speaking about? orders that are not done yet, orders that are waiting for acceptance or orders that have already been accepted.

in the code the following happens (I think I dont know a lot about this part of the code):
- we propose DROPOFF time choices on the restaurant to the user, the global delay is taken into account
- we save this DROPOFF time in the database
- this DROPOFF doesn't change except if the dispatcher delays the order from the interface
- when the order is ACCEPTED by the restaurant/dispatcher then we create the delivery with :

PICKUP TIME:
        1. take the time the user chose (it includes the global delay, average shipping time and some fixed preparation time) = the time the user expects his order
        2. substract riding time (calculated from the distance between restaurant and the customer's home)
        3. substract 5min (time for the rider to get the bag)
    
DROPOFF TIME:
        1. take the time the user chose (it includes the global delay, average shipping time and some fixed preparation time)
        2. set the dropoff to this time

**Comment by vladimir-8** [comment]
Additional info: https://coopcycle.slack.com/archives/CQDUL440P/p1722340609040379

**Comment by HugoLCR** [comment]
### here is the current situation with a practical case :

**Prerequisites** 

- the restaurant has a preparation time of 15 minutes set
- the travel time between pick-up and drop-off is estimated by coopcycle at 15 min (we consider that the customers are all at the same distance).

**Process of operations**

1. the dispatcher puts a 15 minute “delay” on the gauge
2. a new order arrives -> _the pick-up is scheduled in 15 minutes ; the drop-off is scheduled in 30 minutes_
3. the dispatcher puts a 30 minute “delay” on the gauge
4. a new order arrives -> _the pick-up is scheduled in 15 minutes ;  the drop-off is scheduled in 30 minutes_
5.  the dispatcher puts a 45 minute “delay” on the gauge
6.  a new order arrives -> _the pick-up is scheduled in 30 minutes ; the drop-off is scheduled in 45 minutes_
 

### what we want in the future

**same prerequisites** 

**Process of operations**

1. the dispatcher puts a 15 minute “delay” on the gauge
2. a new order arrives -> __the pick-up is scheduled in 30 minutes ; the drop-off is scheduled in 45 minutes_
3. the dispatcher puts a 30 minute “delay” on the gauge
4. a new order arrives -> __the pick-up is scheduled in 45 minutes ; the drop-off is scheduled in 60 minutes_
5.  the dispatcher puts a 45 minute “delay” on the gauge
6.  a new order arrives -> __the pick-up is scheduled in 60 minutes ; the drop-off is scheduled in 75 minutes_


-
