### ISSUE TITLE
Order cancellation option post rider's tasks completion

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#4399]
Could it be possible to add the option to force the cancellation of an order post rider’s tasks completion, so the order is deleted from the .csv export from admin/orders ? For accounting and data analysis reasons, I want my .csv export to be the most accurate possible, and to be able to clean it prior to the export.

See attached screenshots for an example.
Thanks.
<img width="1280" alt="Capture d’écran 2024-06-05 à 16 59 42" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/5339d199-1fae-4905-96b1-e932758742c8">
<img width="1280" alt="Capture d’écran 2024-06-05 à 17 00 28" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/b29d131c-b834-4dbe-921e-3fad9078f040">
<img width="1280" alt="Capture d’écran 2024-06-05 à 17 00 35" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/97649853-8341-4b44-85eb-2696326658df">
<img width="1280" alt="Capture d’écran 2024-06-05 à 17 00 55" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/502bae9a-8e79-47e6-a142-5672a447c393">
<img width="1280" alt="Capture d’écran 2024-06-05 à 17 01 02" src="https://github.com/coopcycle/coopcycle-web/assets/101735534/6028427f-1b43-4027-8a83-e6d8fed445bb">

**Comment by Paul-Eraman-CoopCycle** [comment]
Here you should be switching to the universal excel (dispatch map page) where it not only shows the price, but also the status (cancelled)

Also, soon you won't need to be done this 😉
