### ISSUE TITLE
As a dispatcher, I want to see the order number on the task, not the task ID 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4458]
Change also in the modal

current display
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/f8fc03f9-6c3a-4f5b-9924-c2fd2327b81f)

**Comment by Paul-Eraman-CoopCycle** [comment]
So here in the photo the task ID is first and then the order code is next and kind of greyed out

We would like to delete the task number and make the order code first, and more bold than greyed out

**Comment by Atala** [comment]
ok no problem
