### ISSUE TITLE
Remove  "Hub categories" on the homepage, this feature is not supported anymore

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4463]
Example on Naofood instance, I think "restaurant entreprise midi is a hub. Also i see it as business account employee and i should not. Actually nobody should see it

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/7758bcbf-9e3e-4b83-9aa7-4e89d0ed3662)

**Comment by vladimir-8** [comment]
Duplicates https://github.com/coopcycle/coopcycle-web/issues/4409
