### ISSUE TITLE
In the dispatch change the display of deliveries that are for a shop/restaurant

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4468]
from @AdrienSICKLO 

here in the screenshot we have the shop name in bold. however we may better put the emphasize on the adress to deliver, i.e. address name.

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/d282c076-c383-4889-99e2-091929bfe1ae)

**Comment by AdrienSICKLO** [comment]
In this specific case, this might not be relevant cuz a final customer is not really an important element. But for a lot of our deliveries, we deliver businesses, bars, restaurants, and a bold name in the dispatch could lead to a quicker apprehension of the delivery

**Comment by Paul-Eraman-CoopCycle** [comment]
yeah, this was actually made this way on purpose haha

rider needs the address, dispatch more wants the client

Closing for the moment
