### ISSUE TITLE
In the dispatch panel, on a task, I want to see packages shortcode on the task "draggable item"

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4484]
Change the total of volume units to a list of package on a task

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/62100295-4b2e-4b41-8fa3-cbd1c75c27dc)

**Comment by Paul-Eraman-CoopCycle** [comment]
needs design to have 2 letter codes for packages to make the visualization work

**Comment by Paul-Eraman-CoopCycle** [comment]
field should auto generate unquei 2 letter codes if the user doesnt make them, but user should probably make them

**Comment by Paul-Eraman-CoopCycle** [comment]
Package set page design: https://www.figma.com/design/VDySM7Yj8qQ0shoBRA4DvC/Package-set-page-design?node-id=0-1&t=PRE5IfA35XbY8518-0



![Image](https://github.com/user-attachments/assets/3ec2f455-095b-4f6a-b6b7-f54ca9865611)

**Comment by Paul-Eraman-CoopCycle** [comment]
Whether you see package set icons, or volume, or weight, or all three, or some combination, should be a toggleable thing in the filter bar

**Comment by Atala** [comment]
I created an issue for the setting thing so not to forget it https://github.com/coopcycle/coopcycle-web/issues/4581
