### ISSUE TITLE
Fix Cypress tests crashing randomly with 500 error

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4496]
**In order to**  `have reliable tests`

**I want** `fix random crashes in Cypress tests`

**Whereas currently** `Cypress tests often fail with 500 error`

**Additional context**

![Address search -- search address with useless address details (failed)](https://github.com/coopcycle/coopcycle-web/assets/70273239/8ec8443f-b48f-429d-b219-525a942dfb23)

**Comment by Atala** [comment]
May be fixed by 44ba2838b305e53b776789d97492da57e8a94c71 , let's see
