### ISSUE TITLE
[question] [bug] Miss a vendor myclabs ?

### ISSUE THREAD

**Issue by clementtalleu** [coopcycle/coopcycle-web#45]
The RestrictedDiet use a vendor called : `MyCLabs\Enum\Enum `  which use the library :  https://github.com/myclabs/php-enum   but this library is not  install by the composer install command, indeed it's not present in the composer.json file.

**Comment by alexsegura** [comment]
Fixed in 6438e97ed3ea9175d42ede9f26153fea0c4a2fea
