### ISSUE TITLE
address field clears when making a saved address and pressing "enter" in name, phone # or business contact

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4507]
store -> saved addresses -> create new

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/3442745b-df97-4f44-955e-b346ed7b21d0)

**Comment by Atala** [comment]
duplicate of #3509

**Comment by Atala** [comment]
should be fixed actually
