### ISSUE TITLE
As a dispatcher; i am unable to select a task with incidents from the columns on the right

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4514]
I think the "incident overlay" (yellow stripes), catches the click event

![incident-no-select](https://github.com/user-attachments/assets/f952130c-6172-45c2-9f73-222f9d757673)

**Comment by Paul-Eraman-CoopCycle** [comment]
This would be good to fix before the GA if possible 

Is it a quick fix?

**Comment by Atala** [comment]
yes

**Comment by Atala** [comment]
actually it was working, it is just the background color of the tasks was not set correctly (it has the incident stripes not "selected gold")
