### ISSUE TITLE
In the "create incident modal" of the dashboard, task can be undefined and then the modal crashes on incident creation

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4516]
I think it is due to the the use of `selectSelectedTasks(state).shift()`

Steps to reproduce :
- right click 1 task
- open create incident modal
- wait for 1 redux event to happen, as "SCAN_POSITIONS" 
- the modal crashes on incident creation

**Comment by r0xsh** [comment]
Can't reproduce it
