### ISSUE TITLE
Customer needs to be told in clear way [ticket restaurant system] cannot be used to pay delivery fees

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#4517]
The legal context makes it impossible to pay delivery fees with ticket restaurants. That means we need to enforce the customer to pay the complement part with credit card. 

Right now, with the Edenred system, it leads to an error in the credit card payment stage without customer being told either prior or after having tried.

**Comment by alexsegura** [comment]
Should be improved in aceba70915f5c92a09cc2dfe931bbdd09651cb97

<img width="899" alt="Capture d’écran 2024-07-31 à 17 16 50" src="https://github.com/user-attachments/assets/282a3f39-5f2a-492b-b21f-a7fd2d2247be">
