### ISSUE TITLE
Display packages for deliveries create via a Delivery form 

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4522]
For deliveries create via a Delivery form packages are not displayed:

![Screenshot 2024-07-22 at 14 37 18](https://github.com/user-attachments/assets/4fcf5ecc-1bd7-4b49-babd-321198b423ab)

Whereas, for deliveries created by stores and admins they are displayed

![Screenshot 2024-07-22 at 14 37 26](https://github.com/user-attachments/assets/e947616b-7692-4a9c-b15f-f93b6fb86e8c)

**Comment by Paul-Eraman-CoopCycle** [comment]
i believe it does now, though im not 100% sure how you got to this page honestly, so maybe there is something im missing
