### ISSUE TITLE
Admin should be able to delete users

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#453]

**Comment by couleurmate** [comment]
Users can be deactivate but not deleted
https://github.com/coopcycle/coopcycle-web/issues/288

**Comment by alexsegura** [comment]
Basically, the goal is to do what is done in [AnonymizeCommand](https://github.com/coopcycle/coopcycle-web/blob/71b15e122cd992066edfa42a546986621b4db46f/src/Command/AnonymizeCommand.php), but via the web interface.
