### ISSUE TITLE
The order of a list of linked tasks generated by recurring rules changes when they are assigned.

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#4550]
**Describe the bug**
All is in the title :-)

**To reproduce**
How to reproduce the behavior :
1. Go to the Rayon9 dashboard
2. Click on "View reccurrent rules".
3. Generate "Proximus (tout sauf Rocourt)".
4. See the tasks, they are generated in the "right" order (this means that the task numbers (#152XXX) follow the same order as defined in the rule).
5. Add a courier
6. Assign tasks to this courier (drag and drop one of the tasks from the unassigned column to the courier's window).

**Expected behavior**
Not changing order

![task order](https://github.com/user-attachments/assets/4e82e2b7-7e03-4bee-98f8-1c4557ec571b)

**Comment by rayon9coop** [comment]
This also happens when I assign tasks that are generated automatically via the new feature (https://github.com/coopcycle/coopcycle-web/pull/4511)

**Comment by Paul-Eraman-CoopCycle** [comment]
@Atala

**Comment by rayon9coop** [comment]
![Capture d'écran 2024-09-12 111219](https://github.com/user-attachments/assets/6f0e3d88-f3e3-406a-8c15-2155c852c713)
![Capture d'écran 2024-09-12 111112](https://github.com/user-attachments/assets/f8d02a6e-d6a1-4765-818c-b68fbbb0ce21)
![Orderofthereccurent tasks](https://github.com/user-attachments/assets/85a69f3a-cf50-40b6-b796-a4778d056e11)

With the modification, there is no possibilities to change the order of the task and they are not in the right order.

**Comment by rayon9coop** [comment]
![image](https://github.com/user-attachments/assets/bacd30da-4f32-4492-9ffb-0ef5b2ec90f6)
I don't know if something have been done but know the tasks are in the right order

**Comment by Paul-Eraman-CoopCycle** [comment]
Yup! We fixed it, forgot to close the issue

**Comment by Atala** [comment]
no sorry there is indeed a problem, we put all the dropoffS first. I didnt know one could create multi-dropoff deliveries there.

correcting
