### ISSUE TITLE
Wrong information from wrapped unassigned tour panel

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-web#4582]
When wrapping up the "unassigned tour" panel, the number of created tours in it goes back to zero !
<img width="195" alt="Capture d’écran 2024-08-20 à 13 49 56" src="https://github.com/user-attachments/assets/33b52f78-b360-41a3-abfc-b6da61166f36">
<img width="1582" alt="Capture d’écran 2024-08-20 à 13 49 59" src="https://github.com/user-attachments/assets/27dcbb42-a86d-454f-9b3d-5e7d115969a2">

**Comment by Atala** [comment]
problem is for groups count ;) 

they jump from tour columns to unassigned tasks when you wrap (to respect the old way of doing things were group where in the left column)

will stay like this for now
