### ISSUE TITLE
when ordering with a restaurant that has automatic validation, it show a "waiting validation" on client ends

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-web#4598]
**Describe the bug**
when ordering with a restaurant that has automatic validation, it show a "waiting validation" on client ends even though it's did validate on the restaurant end

**To Reproduce**
1. order from restaurant with automatic validation
2. pay
3. check on restaurant account, the order has been accepted
4. See message that says waiting for validation

**Expected behavior**
client should see an accepted order straight away when ordering

**Screenshots**

**Device (please complete the following information):**
 - Device: pc chrome and pritom tab android
 - OS: [e.g. iOS 7]
 - Browser or App Version [e.g. chrome, safari]

**Additional context**
I am doing tests to see how the app looks on restaurant's end and it happened that while doing a test order it never showed me that my order had been accepted

https://github.com/user-attachments/assets/9baed408-3fea-4991-bfe3-f3c5967522a7

**Comment by Paul-Eraman-CoopCycle** [comment]
We are going to wait until we see this with details in the logs, and then make a new issue, thanks for pointing it out!
