### ISSUE TITLE
supplements

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#460]
Not possible to choose supplements, nothing answer and not possible to command the product without supplement too.
The is the same problem on the app
![capture3](https://user-images.githubusercontent.com/43618873/46148288-03be7180-c268-11e8-9f9f-6de7bb2035a9.PNG)

**Comment by alexsegura** [comment]
This is normal, you didn't specify any value for the options. 

Needs #368

<img width="735" alt="capture d ecran 2018-09-28 a 17 39 46" src="https://user-images.githubusercontent.com/1162230/46218708-a13ba300-c345-11e8-8413-544d3f93e8d6.png">
