### ISSUE TITLE
BUSINESS ACCOUNT: ask for LEGAL business name and tax ID number when manager makes account

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4618]
![makingbusinessaccount](https://github.com/user-attachments/assets/707dfd57-8b1b-4bac-bd63-6f52f7740b03)

In this page at the end of the GIF above:

under "name of the society" there should be

**public nom de la societe**
______________

**fiscal name of the society** 
________________

**Tax ID number**
_______________

all should be mandatory, and if they are not filled out, user cannot continue and an error should alert the user to the field that needs filling out

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle I fixed it on demo instance. It was due the old test business accounts missing an address, which is checked more strictly now

**Comment by Paul-Eraman-CoopCycle** [comment]
Awesome, thanks!
