### ISSUE TITLE
BUSINESS ACCOUNTS: breaks completely when ordering from more than 1 restaurant

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4620]
![makingbusinessaccount](https://github.com/user-attachments/assets/4ee99fa0-de7c-41f3-af35-dc358350d9de)

![orderingafternotshowingnewproductinsecondrestaurantbusinessaccount](https://github.com/user-attachments/assets/a347d12b-fc0b-4066-b66d-0631d5d68946)

When making a multi-restaurant order. when adding a product from the second restaurant:

1. it loads, then stops loading (indicating all is well) BUT it does not appear on the menu on the right
OR
2. it loads and never stops
AND
3. if situation #1, clicking on the "order" button breaks everything

**Comment by vladimir-8** [comment]
For now we will not allow ordering from more than one restaurant from the same cart
