### ISSUE TITLE
BUSINESS ACCOUNTS: Cart list format is not made for multiple restaurant items

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4621]
![image](https://github.com/user-attachments/assets/d52c7588-c3cf-4482-b954-d19b9767399a)

Format should be 

#### product 1 name - price
- [quantity] +
#### product 2 name - price
- [quantity] +
#### product 2 name - price
- [quantity] +

**Comment by vladimir-8** [comment]
We will only support one restaurant per order for now
