### ISSUE TITLE
Add a Shop column in order panel for non-food structures

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-web#4627]
In order to match an order with a delivery from the order panel

I would like to have a column for the shop name to know what the order is about !

The Client column is for instance a User column and should also be renamed.

 
<img width="1582" alt="Capture d’écran 2024-09-16 à 11 50 45" src="https://github.com/user-attachments/assets/53557eee-d7bc-4ead-bf98-508b0dfc0425">

**Comment by Paul-Eraman-CoopCycle** [comment]
https://www.figma.com/design/MOAqusOtLKGstcDcTpPIRw/3-I-Locals-commerces?node-id=882-45375&node-type=frame&t=H1X2fjOBRqpM6QTm-0
