### ISSUE TITLE
Restaurants within Naofood can't change or add products on their catalog

### ISSUE THREAD

**Issue by Srywards** [coopcycle/coopcycle-web#4644]
**Describe the bug**
Restaurants within Naofood can't change or add products on their catalog

**To Reproduce**
1. Go to a catalog of a restaurant like "l'éthiquete"
2. Click on modify a product or create a new product and save
3. See error like screenshot below

**Expected behavior**
Should save without error

**Screenshots**
![image](https://github.com/user-attachments/assets/f8b8fed0-7e38-44a5-8998-35cc052d9409)

**Device (please complete the following information):**
 - Device: Computer, tested with phone too, same problem

**Additional context**
Zed restaurant have the same problem

**Comment by vladimir-8** [comment]
For developers: it's this issue: https://coopcycle.sentry.io/issues/5516801079/

**Comment by Srywards** [comment]
Thanks !
