### ISSUE TITLE
Improve tasks exports performance

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-web#4673]
Should rewrite tasks export mechanism _à la_ [RestaurantStat::class](https://github.com/coopcycle/coopcycle-web/blob/master/src/Utils/RestaurantStats.php)

Current implementation take ~ 15 minutes to export a single month for a single coop

**Comment by alexsegura** [comment]
IMHO the way to go is #3177

If exports are managed asynchronously, they can be dead simple and just load all entities in memory.
