### ISSUE TITLE
Add a docker manager UI so that it would be easier to understand docker stack behavior

### ISSUE THREAD

**Issue by freelibre** [coopcycle/coopcycle-web#468]
I think you could add a manager UI so that, for new comers at least, it would be easier to understand and check docker stack status. You can easily add [portainer.io ](https://portainer.io/)for example.
See below a snasphot of portainer to manager coopcycle docker stack:
![capture d ecran de 2018-09-30 08-52-17](https://user-images.githubusercontent.com/1781304/46254371-8c1e5b80-c48e-11e8-95b7-143e007b10bd.png)

**Comment by alexsegura** [comment]
Fixed in #472
