### ISSUE TITLE
Add no maximal interval value for store timeslots so an order can be placed for one month from now

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-web#4682]
would it be possible to have the option to choose no maximal interval value for the the timeslot ? I want my client to be able to order a delivery 1 month from now.

**Comment by Atala** [comment]
thanks thomas i moved the part about the date picker in #4320

**Comment by Paul-Eraman-CoopCycle** [comment]
closing this issue, will track in #4320
