### ISSUE TITLE
The GoogleDirectionsApi class must implement some methods

### ISSUE THREAD

**Issue by clementtalleu** [coopcycle/coopcycle-web#47]
The `GoogleDirectionsApi` class implements the `RoutingInterface` so they need to implements this two methods : 

``` 
    public function getRawResponse(GeoCoordinates $origin, GeoCoordinates $destination)
    {
        // TODO: Implement getRawResponse() method.
    }

    public function getDistance(GeoCoordinates $origin, GeoCoordinates $destination)
    {
        // TODO: Implement getDistance() method.
    }
```  

Without theses 2 methods php will crash

**Comment by alexsegura** [comment]
Yep. Actually, this class is not used. 
At the beginning, we were using Google APIs to get routing data, but the quotas were reached very quickly. Now we use an [OSRM](http://project-osrm.org/) server. 

Of course, the idea is to implement the most common routing services and make it configurable through the admin. If someone wants to pay for Google APIs, and avoid the hassle of compiling the routing network from OSM data, no problem. 

To make the feature complete, this would imply at least:
- Storing the configuration in database
- Adding a panel in the admin area to configure the routing service (API key, etc)

If you want to do that, go for it 🙂
But this is not a high priority right now, you can also delete the class 😄
