### ISSUE TITLE
wrong minimum shopping cart amount

### ISSUE THREAD

**Issue by HugoLCR** [coopcycle/coopcycle-web#4702]
**Describe the bug**
the display of the minimum shopping cart amount is bad; the amount is that of the previous restaurant of the previous order

**To Reproduce**
1. create a shopping cart in one restaurant
2. create a new shopping cart in new restaurant
3. go to step 2 of the shopping cart

**Expected behavior**
I want the correct minimum shopping cart amount when I go to a restaurant profile

**Screenshots**
https://github.com/user-attachments/assets/1040cb6d-1b08-44f1-8b33-40d7d3bd7b8e

**Device (please complete the following information):**
 Windows 11
Chrome

**Additional context**
I am connected with a customer account

**Comment by vladimir-8** [comment]
Thanks for reporting! We track this issue here: https://github.com/coopcycle/coopcycle-web/issues/4095
