### ISSUE TITLE
Have human-readable filename for file imports (both for store owners and admins)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4723]

**Comment by vladimir-8** [comment]
FYI, there is a similar issue: https://github.com/coopcycle/coopcycle-web/issues/3990

**Comment by Atala** [comment]
thanks i was suspecting but i did not find it

@vladimir-8 can you review it?

the main challenge is securing the uploaded filename to avoid like '../../etc/password' paths but i think slugify does the trick (remove slash, antislash, points, ...)
