### ISSUE TITLE
Inconsistent data between recurrent rules and courier's tasks

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#4736]
Here is are 2 screenshots, one is the dispatcher's dashboard and the second is the courier's task. The comment doesn't appear. 

![Image](https://github.com/user-attachments/assets/0d8e88fc-5c83-4e2d-a476-632d32cabeb8)
![Image](https://github.com/user-attachments/assets/a8cc59c5-a1ff-4310-aec5-d35b09efa4eb)

**Comment by vladimir-8** [comment]
Closing as we are going to deprecate (and at some point remove) this interface on the Dispatch dashboard in favour of Recurrence rules in the Delivery form
