### ISSUE TITLE
address writting problems

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#488]
If I write my delivery address and click to the guess below, it's alright.  If I click anywhere, my words disapear.

Another problem. Look at the address in this picture
![capture](https://user-images.githubusercontent.com/43618873/47270829-b638da00-d571-11e8-8069-82a2f0318bae.PNG)

After I made my restaurant's choice, look at the address now
![capture 2](https://user-images.githubusercontent.com/43618873/47270843-e97b6900-d571-11e8-852c-1d5f9e5aff9e.PNG)
The address has changed. In fact it's an address of a preview test

**Comment by alexsegura** [comment]
> If I write my delivery address and click to the guess below, it's alright. If I click anywhere, my words disapear.

This is expected behavior.

The rest has been fixed I believe.
