### ISSUE TITLE
Composer 1.7.3 breaks installation

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#492]
It took me hours to understand the issue... 

See composer/composer#7764

It is because we are using `symfony/serializer:^4.1`, which should not be installed alongside Symfony 3.4. 

This is why a branch that was green in Travis went red when merged, with no additional changes...

**QUICK FIX**

Downgrade Composer to 1.7.2

**LONG TERM FIX**

Upgrade Symfony to 4.x 

#178

**Comment by alexsegura** [comment]
Workaround for Travis in 9e352e761c932a07a744f6652d2c58317332e8f7

**Comment by mesayuda** [comment]
hi. please you can help me, this is the error
Step 25/26 : RUN composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest     && composer clear-cache
 ---> Running in 7612c1198701
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/serializer v4.1.6 -> satisfiable by symfony/serializer[v4.1.6].
    - don't install symfony/symfony v3.4.17|don't install symfony/serializer v4.1.6
    - Installation request for symfony/symfony v3.4.17 -> satisfiable by symfony/symfony[v3.4.17].

ERROR: Service 'php' failed to build: The command '/bin/sh -c composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest     && composer clear-cache' returned a non-zero code: 2
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1

any idea? thanks for you help

**Comment by freelibre** [comment]
This workaround works for me.

**Comment by alexsegura** [comment]
Fixed in 050252170e452dbc2784863f356b50c698d2d5db
