### ISSUE TITLE
npm ERR! code ENOGIT no git found in your path

### ISSUE THREAD

**Issue by mesayuda** [coopcycle/coopcycle-web#493]
hi, please i need you help, i try to install the software but it crash and show this error:

alejandro@mesayuda:~/coopcycle-web$ docker-compose -f docker-compose.yml -f docker-compose-portainer.yml up

Creating volume "coopcycle-web_portainer_data" with default driver
Pulling smtp (namshi/smtp:)...
latest: Pulling from namshi/smtp
f189db1b88b3: Pull complete
eb1612d440dc: Pull complete
e65d3d397268: Pull complete
82d124bf3cdf: Pull complete
44f3200ac7ea: Pull complete
Building webpack
Step 1/7 : FROM node:8.12-alpine
 ---> df48b68da02a
Step 2/7 : WORKDIR /srv/coopcycle
 ---> Using cache
 ---> a36c3198b0e9
Step 3/7 : COPY package.json /srv/coopcycle
 ---> Using cache
 ---> bb049464dd37
Step 4/7 : COPY package-lock.json /srv/coopcycle
 ---> Using cache
 ---> ceb515da49f0
Step 5/7 : RUN npm install
 ---> Running in 0bdae2948184
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://git@github.com/coopcycle/coopcycle-js.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-02T21_57_13_203Z-debug.log
ERROR: Service 'webpack' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

i have installed git and works fine, 

alejandro@mesayuda:~$ git --version
git version 2.17.1
alejandro@mesayuda:~$ type git
git está asociado (/usr/bin/git)
alejandro@mesayuda:~$ 

thanks for you help.

**Comment by freelibre** [comment]
Hello,

Did you follow the prerequistes depanding on your plateform and then install the application before running it ?

**Comment by mesayuda** [comment]
> Hello,
> 
> What is your plateform ? Did you follow the prerequistes depending on your plateform and then install the application before running it ?

hi and thanks for you help

my platform is ubuntu mate 18.04 and yes i follow all the prerequisites.

**Comment by mesayuda** [comment]
> I've reproduced it on linux manjaro. May be it's due to npm profile as per [common error](https://docs.npmjs.com/troubleshooting/common-errors) a solution may be to [update npm profile](https://docs.npmjs.com/getting-started/modifying_your_profile_from_command_line).

i got this error in log.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'apk',
1 verbose cli   'add',
1 verbose cli   '--no-cache',
1 verbose cli   'git' ]
2 info using npm@6.4.1
3 info using node@v8.10.0
4 verbose stack Error: missing script: apk
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /home/alejandro/coopcycle-web
6 verbose Linux 4.15.0-38-generic
7 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "apk" "add" "--no-cache" "git"
8 verbose node v8.10.0
9 verbose npm  v6.4.1
10 error missing script: apk
11 verbose exit [ 1, true ]

**Comment by freelibre** [comment]
@mesayuda it's because alpine container doesn't have git. 
if you update the Dockerfile in coopcycle-web/docker/webpack with the following line it should work:
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
I've just push [this solution](https://github.com/coopcycle/coopcycle-web/tree/fix-issue-493)

**Comment by mesayuda** [comment]
> @mesayuda it's because alpine container doesn't have git.
> if you update the Dockerfile in coopcycle-web/docker/webpack with the following line it should work:
> RUN apk update && apk upgrade && 
> apk add --no-cache bash git openssh
> I've just push [this solution](https://github.com/coopcycle/coopcycle-web/tree/fix-issue-493)

tanks for response

i got this error
ERROR: Dockerfile parse error line 4: unknown instruction: APK

**Comment by mesayuda** [comment]
> @mesayuda it's because alpine container doesn't have git.
> if you update the Dockerfile in coopcycle-web/docker/webpack with the following line it should work:
> RUN apk update && apk upgrade && 
> apk add --no-cache bash git openssh
> I've just push [this solution](https://github.com/coopcycle/coopcycle-web/tree/fix-issue-493)

tanks for response

i got this error
ERROR: Dockerfile parse error line 4: unknown instruction: APK

**Comment by freelibre** [comment]
Could you share your Dockerfile ?
Does it have the "/" like in the commit proposed:
`RUN apk update && apk upgrade && \`
  `apk add --no-cache bash git openssh`
