### ISSUE TITLE
how to use the software?

### ISSUE THREAD

**Issue by mesayuda** [coopcycle/coopcycle-web#494]
hi everyone, 

please your said me hoy to use the app before install? i succefully install the software but i cant login with admin, or there are any other step that i must follow?

how deploy the software in production?
what are the data of admin user to login?
exist some manual "how to"?
thanks so much foy your help

**Comment by freelibre** [comment]
Hello @mesayuda ,
So I guess you can then close the issue 493 you have opened yesterday.
The doc is available there:
https://github.com/coopcycle/coopcycle-docs
If you would like to create a coop you need to check this website:
https://coopcycle.org/en/#about
you will find contacts and also how to contribute.

**Comment by mesayuda** [comment]
> Hello @mesayuda ,
> So I guess you can then close the issue 493 you have opened yesterday.
> The doc is available there:
> https://github.com/coopcycle/coopcycle-docs
> If you would like to create a coop you need to check this website:
> https://coopcycle.org/en/#about
> you will find contacts and also how to contribute.

yes thanks for you help, but i cant install the docs, i install ruby, and blunder y jekyll and it show the following error: bundle: command no found,

**Comment by mesayuda** [comment]
thanks i solve the problem.

**Comment by mesayuda** [comment]
> Hello @mesayuda you don't need to build the docs they are available [here](https://docs.coopcycle.org/fr/)
> 
> May I ask you what type of project you have?
> Are you creating a co-op? If yes, we can help on the technical side.


Hello and thanks for replying
in the documents does not appear how to start using the software, which is the user and password of the admin to start working, the steps to follow after the installation.
and answering your question, yes, my project is to form a group of messengers to provide different services.

**Comment by alexsegura** [comment]
> my project is to form a group of messengers to provide different services.

Cool, is this a co-operative? 
Our license only allows worker co-operatives / non-profit orgs to use the software. 
If yes, we happily provide hosting for your project, so that you can concentrate on building your business. 

Where are you located? 
Drop us a line on contact@coopcycle.org, and let's talk 🙂

**Comment by mesayuda** [comment]
That means that you can only use the software on your servers? and yes, it is a project that I intend to make with messenger friends. We are startup and want to use a free software like this. But if only run in your server it is a disappoint. Im alocate in colombia

**Comment by mesayuda** [comment]
> > my project is to form a group of messengers to provide different services.
> 
> Cool, is this a co-operative?
> Our license only allows worker co-operatives / non-profit orgs to use the software.
> If yes, we happily provide hosting for your project, so that you can concentrate on building your business.
> 
> Where are you located?
> Drop us a line on [contact@coopcycle.org](mailto:contact@coopcycle.org), and let's talk

hat means that you can only use the software on your servers? and yes, it is a project that I intend to make with messenger friends. We are startup and want to use a free software like this. But if only run in your server it is a disappoint. Im alocate in colombia

**Comment by almereyda** [comment]
It was left out here to distinguish, whether the bike messenger startup would be legally implemented in a columbian legal form that allows to build a cooperative model, eventually similar to the

* [Rochdale Principles - Wikipedia](https://en.wikipedia.org/wiki/Rochdale_Principles) respectively
* [Cooperative identity, values & principles | ICA](https://www.ica.coop/en/cooperatives/cooperative-identity)

This could have helped reducing the misunderstanding, or eventually even given an impulse to consider it that way, if the concept was unknown before.
