### ISSUE TITLE
To get a standard and common environment for OSX,Windows, Linux 

### ISSUE THREAD

**Issue by freelibre** [coopcycle/coopcycle-web#500]
Current dev environment installation can lead to OS specific issues and require different installation methods:
https://github.com/coopcycle/coopcycle-web/issues/392
https://github.com/coopcycle/coopcycle-web/issues/92
https://github.com/coopcycle/coopcycle-web/issues/436
...
It could be great to have a common and standard env set up and valid for all plateform, it would be easier for new members to contribute. 
May be a project like this [devilbox]( http://devilbox.org/) could be usefull as it contains lot of standard packages.

**Comment by alexsegura** [comment]
Fixed in #508
