### ISSUE TITLE
Localized address formatting

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#506]
[Addresses formats](https://en.wikipedia.org/wiki/Address#Format_by_country_and_area) are different for each country, and it's important to display addresses in a localized way. 

For example, in the `Geocoder` class, we don't care about this.

https://github.com/coopcycle/coopcycle-web/blob/f1f29bd4fd5274b9b17ec48cd9fd70ad65f59b1c/src/AppBundle/Service/Geocoder.php#L54-L58

And this can lead to some problems: for example, in Berlin, there are sometimes several streets with the same name, so it's mandatory for the courier to also know the postal code. 

There is [predicthq/address-formatter-php](https://github.com/predicthq/address-formatter-php) to achieve that.

**Comment by ERAMANrepartos** [comment]
Specific issue that seems to no longer be a problem, closing for now, but can be reopened if it pops up again
