### ISSUE TITLE
Make fonts work in Selenium

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#509]
<img width="455" alt="capture d ecran 2018-12-01 a 11 03 06" src="https://user-images.githubusercontent.com/1162230/49326857-c7094200-f558-11e8-8319-2c167884b95e.png">

**Comment by fedegos** [comment]
These webpack and webpack-encore issues may be related to this problem:

https://github.com/webpack/webpack/issues/4111
https://github.com/symfony/webpack-encore/issues/88
https://github.com/symfony/webpack-encore/issues/26

**Comment by alexsegura** [comment]
This should be fixed in db2de1f87aa0a91e73d5fcefdc4552068614c678

**Comment by alexsegura** [comment]
@fedegos I think you also had the problem on your installation (some assets pointing to `http://0.0.0.0`)? This should fix it.

Just re-build the webpack container, and relaunch.

```
docker-compose build webpack
```

**Comment by alexsegura** [comment]
Well, actually I had to revert the commit in 1a61b3ecb49e01576b337aafd13add109f1917be ☹️

It needs #516 to be merged first, almost good, just having an issue on Travis

**Comment by alexsegura** [comment]
#516 has been merged 🚀
