### ISSUE TITLE
Speed up the PHP-container response

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#51]
On my machine (OSX Yosemite), the PHP container is damn slow to responds when developing in the browser.

Do you have the same issue?

**Comment by alexsegura** [comment]
Nope. Maybe try to build the containers again? 

```
docker build
```

**Comment by Atala** [comment]
I solved it by adding the [`cached` option](https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-for-mac) to the volume for PHP. Let's see if it's suitable for dev.

**Comment by clementtalleu** [comment]
do you use d4m ? install https://github.com/IFSight/d4m-nfs  before `docker-compose up -d` it's pretty much faster

**Comment by Atala** [comment]
I will give it a try - I used to have [docker-osx-dev](https://github.com/brikis98/docker-osx-dev) when I was using Docker + Virtualbox.

**Comment by Atala** [comment]
@clementtalleu do you use it with webpack - it is very nice and webpack get notified of FS events, but there is an issue (permissions maybe?):
`Module build failed: Error: EIO: i/o error, open '/srv/coopcycle/js/app/cart/Cart.jsx'`

**Comment by Atala** [comment]
Use of [docker-sync](https://github.com/coopcycle/coopcycle-web#prerequisites) helps for this. 

What helped a lot on my machine : allow more CPUs for docker.
