### ISSUE TITLE
Tag selection popover could be closed by clicking outside

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#511]
Now : clicking on cog for opening/closing
Then : clicking also outside of the div

**Comment by alexsegura** [comment]
What about using something like [this](http://prakhar1989.github.io/react-tags/example/) instead?

![React Tags](https://github.com/saranshbansal/react-tags-autocomplete/raw/master/demo.gif)

**Comment by alexsegura** [comment]
Ok, I think the best is [React Select](https://react-select.com/home) in "Multi" mode

<img width="568" alt="capture d ecran 2018-12-13 a 15 06 18" src="https://user-images.githubusercontent.com/1162230/49943695-de491780-fee8-11e8-8b56-488d3e392c44.png">
