### ISSUE TITLE
minimum ammount bug

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#514]
I've started a new order on a Poitiers restaurant and the minimum ammount was alright. I've decided to come back and change restaurant to my order. Sometimes it's alright but sometimes the minimum ammount stays the minimum ammount from my first choice restaurant. And sometimes, this request appears
![capture](https://user-images.githubusercontent.com/43618873/49932991-d1b5c680-feca-11e8-97a7-72a3557e0dbd.PNG)
when I change restaurant to my order and it's not true.

**Comment by alexsegura** [comment]
Fixed in 03f1cc02cc4627ee4a1943772b8e3a387ed31e7f
