### ISSUE TITLE
new bug on product price

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#524]

**Comment by damienlapoitavelo** [comment]
In grand ours restaurant ( Poitiers ), if I choose this meal

![capture](https://user-images.githubusercontent.com/43618873/51088195-f36dcc00-175c-11e9-8b1a-85541da773bb.PNG)
with this option
![capture 2](https://user-images.githubusercontent.com/43618873/51088200-f7015300-175c-11e9-86ce-a0f8993e1cd1.PNG)
the price is false ( 2 options are free )

![capture3](https://user-images.githubusercontent.com/43618873/51088213-15ffe500-175d-11e9-9b9e-59d6d1315e79.PNG)

With the other option, no problem. In fact, the wrong price ( 9,00€ ) is the old price of this product.

**Comment by alexsegura** [comment]
Fixed in a5a069da03b7e4b5f01bc1b14d57bef05896a672
