### ISSUE TITLE
Docker issue : "Session data file is not created by your uid"

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#56]
When launching the website locally I have to remove the sessions file each time. I think it's because of the difference between the local user ID and the docker user ID.

[This fix on SO](https://stackoverflow.com/questions/39980171/symfony-3-1-5-warning-sessionhandlerread-session-data-file-is-not-created?answertab=votes#tab-top) should work.

Can I apply it @alexsegura ?

**Comment by alexsegura** [comment]
Good!
