### ISSUE TITLE
Import data from Google Sheets

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#568]
It should be possible to expose directly a Google Sheet to customers, that allows them to create tasks/deliveries. 

The platform should then use the Google Drive API to retrieve new items/changes happening in the sheet, and synchronize the database accordingly

- https://developers.google.com/sheets/api/quickstart/php
- https://www.twilio.com/blog/2017/03/google-spreadsheets-and-php.html
- https://github.com/gsuitedevs/php-samples/blob/master/drive/quickstart/quickstart.php

**Comment by Paul-Eraman-CoopCycle** [comment]
Not currently planned
