### ISSUE TITLE
Simplify data structure by removing Entity\Menu and Entity\MenuItem

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#57]
Do we need to keep Entity\MenuSection and Entity\MenuItem ? AFAIK we only use Entity\Menu\MenuSection and Entity\Menu\MenuItem

**Comment by alexsegura** [comment]
« It's complicated ». 
I don't remember exactly why, but this is useful. Let me check...

**Comment by Atala** [comment]
If you don't mind I will investigate and try to clean this, it is very error-prone.
