### ISSUE TITLE
delete pictures

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#578]
Restaurants have generally a problem with the pictures. Sometime they change just a meat or one vegetable or a garnish in a product but generally, the new product is ready on tuesday 12:00. And they don't have time to take a new picture and change it on coopcycle. So they prefer delete the picture the day before and put another picture later ( when they have time to make it ) but it's not possible.
When picture appeared on Coopcycle, I thought restaurants should be happy to discover this new feature but I received more reproaches than compliments. So I think it's important for us to delete pictures if they want. Actually I suggest us to substitute the old pictures with a white screen but they look at me with desperate faces in front of my improvise crafts.

**Comment by alexsegura** [comment]
Fixed in #1954
