### ISSUE TITLE
Allow geometry type LineString in zone import

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#581]
If we use a geojson with LineString instead of Polygon in zone import the server returned a "500 Internal Server Error"

**Comment by alexsegura** [comment]
Problem is we need polygons, because we want to be able to check if a Point is contained in a Polygon.
With a LineString, you can't check if it's contained in a Polygon, because it doesn't necessarily mean it's a **closed** area. 

I think it's a WONTFIX 😕
