### ISSUE TITLE
Firefox hang

### ISSUE THREAD

**Issue by antoineschmitt** [coopcycle/coopcycle-web#60]
Sur Firefox (v48.0.2), MacOS10.8.5, l'ouverture de la page https://coopcycle.org/fr/ bloque le navigateur. Qui tourne à +100% CPU. Un script dans une boucle infinie ?

**Comment by Atala** [comment]
Le site s'ouvre chez moi sous Firefox (OSX 10.11.1 et Firefox 54.0).

A priori il n'y a pas de scripts "lourds" qui tournent sur cette page (simple site statique généré par Hugo).

Pouvez vous copier-coller le contenu de la console (cmd + alt + i) ?

**Comment by Atala** [comment]
Le site s'ouvre chez moi sous Firefox (OSX 10.11.1 et Firefox 54.0).

A priori il n'y a pas de scripts "lourds" qui tournent sur cette page (simple site statique généré par Hugo).

Pouvez vous copier-coller le contenu de la console (cmd + alt + i) ?

**Comment by antoineschmitt** [comment]
Désolé, ça ne le fait plus. Mais hier, ça l'a fait plusieurs fois, après redémarrage de Firefox à chaque fois. Mais l'appli de simulation avait beaucoup plus d'événements qu'aujourd'hui..

**Comment by Atala** [comment]
Ok, nous avons eu un problème avec la DB hier, c'est surement lié à cela.

Merci pour le rapport d'erreur!
