### ISSUE TITLE
Safari cannot open

### ISSUE THREAD

**Issue by antoineschmitt** [coopcycle/coopcycle-web#61]
Sur Safari 6.2.8, MacOS10.8.5, l'ouverture de la page https://coopcycle.org/fr/ échoue car "Safari ne peut pas ouvrir une connexion sécurisée vers coopcycle.org"

**Comment by Atala** [comment]
Le site s'ouvre chez moi sous Safari (OSX 10.11.1 et Safari 9.0.1).

Pouvez vous copier-coller le contenu de la console (cmd + alt + i) ?

**Comment by antoineschmitt** [comment]
Il n'y a rien dans la console. Safari affiche cette page car il n'arrive pas à se connecter au site.
Voici le source de la page affichée : 



<HTML>

<HEAD>
    <LINK rel=stylesheet type="text/css" href="page-load-errors.css">
    
    <STYLE>
        BODY {font-family:'Helvetica Neue';}
    </STYLE>

    
    <TITLE>Ouverture de la page impossible</TITLE>
</HEAD>

<BODY>
<div class="error-container">
<div class="icon" alt="Safari Icon" role="img"></div>
<div class="text-container">

<P aria-hidden="true" class="error-title error-text-engraving">Safari ne parvient pas à ouvrir la page <A id="help-button"></a></P>
<P aria-hidden="true" class="error-title error-text">Safari ne parvient pas à ouvrir la page <A id="help-button"></a></P>
<P class="error-title error-text-inner-shadow">Safari ne parvient pas à ouvrir la page <A aria-label="Help" role="button" id="help-button" class="" HREF='open-help-anchor:ibrw1071'></a></P>
</div>
<div class="text-container">

<P class="error-message error-text-engraving">Safari ne parvient pas à ouvrir la page « https://coopcycle.org/fr/ » car Safari ne peut pas établir une connexion sécurisée au serveur « coopcycle.org ».</P>
<P aria-hidden="true" class="error-message error-text">Safari ne parvient pas à ouvrir la page « https://coopcycle.org/fr/ » car Safari ne peut pas établir une connexion sécurisée au serveur « coopcycle.org ».</P>
<P aria-hidden="true" class="error-message error-text-inner-shadow">Safari ne parvient pas à ouvrir la page « https://coopcycle.org/fr/ » car Safari ne peut pas établir une connexion sécurisée au serveur « coopcycle.org ».</P>
</div>
</div>
</BODY>

</HTML>

**Comment by Atala** [comment]
Effectivement [le test SSLabs](https://www.ssllabs.com/ssltest/analyze.html?d=coopcycle.org) indique que (1) le setup SSL est ok et (2) le handshake ne passe pas pour Safari 6 et OSX 10.8.5. 

Je vous conseille d'updater Safari pour résoudre le problème, en cherchant on trouve plusieurs utilisateurs qui ont eu des soucis ([ici](https://forums.macrumors.com/threads/safari-6-os-10-8-cant-establish-a-secure-connection.1413942/) par exemple).
