### ISSUE TITLE
address with ter

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#617]
We found a problem with number with "ter" as "150ter Boulevard Damien Dedieu 86000 Poitiers". It can't be understand by address finder.

**Comment by alexsegura** [comment]
This is something we can't fix on our side. If an address with "ter" is listed in Google Maps, it appears. 

<img width="408" alt="Capture d’écran 2020-07-24 à 11 13 58" src="https://user-images.githubusercontent.com/1162230/88377067-e5abf480-cd9e-11ea-89f6-0ac1e2ed5f00.png">
