### ISSUE TITLE
Improve dispatching of imported grouped tasks

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#619]
Now : a group of task can only be assigned to one courier. The group should be split beforehand or dispatcher needs to unassign/reassign  

After : group selecting inside a group of task

**Comment by alexsegura** [comment]
Maybe it's not clear, but you can already do that. 
If you click on "Afficher tout", the tasks in the group will be displayed individually. 

<img width="214" alt="Capture d’écran 2019-07-17 à 15 36 23" src="https://user-images.githubusercontent.com/1162230/61379976-d69b8800-a8a8-11e9-91f4-b924dc48dc60.png">

**Comment by Atala** [comment]
Not clear from a newbie standpoint.

**Comment by alexsegura** [comment]
Should be fixed in #3223
