### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#621]
A client said me he couldn't choose his schedule and he must be choose 13h15 instead of 13h ( command 1HW ).

And for this command, restaurant couldn't validate it. She was at home and she wanted to valide it with her PC
![Capture](https://user-images.githubusercontent.com/43618873/61366097-3124ec00-a889-11e9-808a-986f3784ab3e.PNG)

and i just find a tranlation problem :   
![Capture1](https://user-images.githubusercontent.com/43618873/61366145-4e59ba80-a889-11e9-8393-571229d318e0.PNG)

**Comment by alexsegura** [comment]
Missing translation fixed in a7caa56f56f88a2ede29b41d964201e96875be88

**Comment by alexsegura** [comment]
403 Forbidden error fixed in 1cdf8100832f87191a3e8e2cd04dc645ddebdea3
