### ISSUE TITLE
pas possible d'enregistrer

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#623]
Excusez-moi mais comme je ne suis pas sur que des non francophones liront ce message je ne vais pas perdre mon temps à écrire en anglais. Parce que vous m'en avez déjà fait perdre beaucoup cette semaine. Donc voilà on m'a demandé un devis pour une tournée en me donnant les adresses et quand j'ai voulu commencer en rentrant la première adresse sur coopcycle le chargement devant le bouton enregistrer ne s'est pas arrêté et je ne peux donc pas enregistrer et aller plus loin. J'ai essayé trois fois
![Capture](https://user-images.githubusercontent.com/43618873/61382704-8ecb2f80-a8ad-11e9-95de-08a7fb0b81fa.PNG)
J'ai l'impression qu'à chaque fois que vous rajouter des fonctions, le logiciel craquelle de partout.

**Comment by alexsegura** [comment]
Problème uniquement dans Firefox, lié à babel/babel#8297

**Comment by alexsegura** [comment]
Hotfix dans e1619a0b6eba05d9506558f9b5efed85da348b89

Remplacé par #624, sur un aspect purement technique.
