### ISSUE TITLE
french tax

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#637]
I think french taxation is difficult for no-french people so I found an excuse to write in french.

Prenons cette capture : 
![Capture](https://user-images.githubusercontent.com/43618873/62086680-6e14b980-b25f-11e9-8b79-7940fce0078d.PNG)

L'expression "revenu net" n'est à mon sens pas juste parce que la tva est dans le montant, donc ce n'est pas net pour le restaurant. Je sens que ça ne va pas être simple mais il faudrait pouvoir différencier le revenu sans tva et avec tva. Parce qu'en plus le restaurant en question a 3 tva différentes ( conso immédiate, différée et alcool ( d'ailleurs la tva alcool n'est pas dans les choix, du coup je dis aux restos de mettre la tva livraison sur leurs bières ( 20% comme l'alcool ))), donc quand il donne ses chiffres à l'urssaf, s'il doit faire tous ces calculs manuellement, il va s'arracher les cheveux. Les caisses enregistreuses ont ces options donc je pense qu'il serait pro de les avoir.
Pour les frais plateforme je souhaiterais qu'ils apparaissent en ht et en ttc afin que les restaurants puissent récupérer la tva et n'est pas de calcul à faire

**Comment by vladimir-8** [comment]
linked to #1542
