### ISSUE TITLE
Price should not be calculated when store has no pricing rule set

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#639]
When a store has no pricing rule set, the price is calculated anyway. 

Moreover, when there are no pricing rules sets defined, we should show a better error message inviting to create one, instead of a blank dropdown.

**Comment by ERAMANrepartos** [comment]
For a new cooperative admin user who has a fresh new instance, when they are making their first store. When they make the store, we want a message of some kind that immediately says "great! now make a price rule over here [link]"
