### ISSUE TITLE
client phone number problem

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#645]
When people create an account with their facebook account, the first number of their phone number ( a 0 in France ) doesn't appear. So when you want to call their, you need to correct manually before calling.

**Comment by arnomasson** [comment]
Précisions : 

Une personne s'est créée un compte via facebook vendredi 2 août et à commander aussitôt. Son nom d'utilisateur c'est antilia_saumont_ragot. Si j'édite son profil je m'aperçois que son numéro de tel est 00 7 7* * * * * * *. Si je vais voir la commande sur le site dans admin/order il n'y a que les 9 derniers chiffres de son numéro. Par contre si je vais voir la commande dans la barre de tâches du resto concerné un 0 a été rajouté au début ce qui donne un numéro à 10 chiffres commençant par 07 ( ce qui est normal en France ).
Sur l'app en tant que coursier il a été rajouté +7 au début du numéro à 9 chiffres donc on me propose d'appeler le +77 ** ** ** **. Je n'ai pas essayé d'appeler mais à mon avis ça ne marche pas
