### ISSUE TITLE
Structured filename when exporting picture/signature

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-web#684]
Exempli gratia : `ID_address.name_date.jpg`

**Comment by alexsegura** [comment]
It's done here

https://github.com/coopcycle/coopcycle-web/blob/47a0f82104d3107a10658847b441f1858a56d775/src/AppBundle/Controller/Utils/AdminDashboardTrait.php#L302-L327

**Comment by KaiCMueller** [comment]
@alexsegura please assign me :) What name schema would you suggest?

**Comment by alexsegura** [comment]
Well like @couleurmate is suggesting, he's one of our power users and knows best 😎

**Comment by alexsegura** [comment]
Fixed in #749
