### ISSUE TITLE
Allow inserting another linked stop through dashboard

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#690]
When there are 2 linked tasks on the dashboard, it should be possible to add another stop (in the middle, at the end...). 

There are several possibilities for the UI/UX: right-click & context menu, drag'n'drop...

**Comment by alexsegura** [comment]
We could use [combining items](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/combining.md)

**Comment by ERAMANrepartos** [comment]
This seems like its part of mult-dropoff deliveries and / or routes, but either way, is being dealt with elsewjhere
