### ISSUE TITLE
Display together recipient name as well as address in the list of tasks (dispatch panel)

### ISSUE THREAD

**Issue by vdegove** [coopcycle/coopcycle-web#691]
![Sélection_606](https://user-images.githubusercontent.com/15861435/65164119-8c678c00-da3c-11e9-95ce-c446d75ae405.png)

In this view, it is useful to have together both:
- Customer name
- Recipient company + name
- Address + postal code + city

To understand where is a delivery you're assigning.

**Comment by ERAMANrepartos** [comment]
@alexsegura This is finished right?
