### ISSUE TITLE
[bug] Where is my task? Did I delete it by mistake?

### ISSUE THREAD

**Issue by vdegove** [coopcycle/coopcycle-web#692]
![Sélection_607](https://user-images.githubusercontent.com/15861435/65164468-3e06bd00-da3d-11e9-977b-c8baae625d66.png)
In this task, I had a dropoff that disapeared. Have I deleted it without seeing it?

**Comment by couleurmate** [comment]
Could it have been hided with filters ?

**Comment by alexsegura** [comment]
Also, there was a confusion with the "Cancel" button.
It cancels a task, but people clicked on it to close the modal.
There is now a confirmation message.

Closing since there is no further information.
