### ISSUE TITLE
Allow specifying an arbitrary shipping date

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#698]
Currently, visitors are only proposed 2 date choices, i.e the next 2 available days. 

<img width="525" alt="Capture d’écran 2019-09-20 à 16 15 18" src="https://user-images.githubusercontent.com/1162230/65334049-f0678d00-dbc1-11e9-8b30-e6f3ea400e0f.png">

But it is too limiting in certain use cases. 
For example, for restaurants offering catering services, i.e with orders on quotation, customers should be allowed to choose an arbitrary shipping date. 

In terms of UI/UX, a possible solution would be to add a button/link "More choices", which opens a calendar/date picker.

**Comment by PasLoin** [comment]
Is there a maximum ?

**Comment by alexsegura** [comment]
Take care with #1388, an arbitrary shipping date can't be more than 7 days in any case.

**Comment by ERAMANrepartos** [comment]
This is now maximum of 6 days, which is limited by stripe authorization issues, so I am closing this
