### ISSUE TITLE
docker-compose error during make install: did not find require(/srv/coopcycle/app/../vendor/autoload.php)

### ISSUE THREAD

**Issue by Ledoux** [coopcycle/coopcycle-web#72]
@Atala 
tx for having done a clear onboarding. I just fall into this breaking error during the install.

```
Step 23/23 : CMD docker-app-start
 ---> Running in 27c7c197a1c0
 ---> ca90af961e4a
Removing intermediate container 27c7c197a1c0
Successfully built ca90af961e4a
Successfully tagged coopcycleweb_php:latest
WARNING: Image for service php was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

Warning: require(/srv/coopcycle/app/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/coopcycle/app/autoload.php on line 7

Fatal error: require(): Failed opening required '/srv/coopcycle/app/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /srv/coopcycle/app/autoload.php on line 7
make: *** [install] Error 255
```

**Comment by Atala** [comment]
Looks like the composer deps weren't installed as they [should be](https://github.com/coopcycle/coopcycle-web/blob/master/docker/php/start.sh#L7-L11).

Can you give me the output of `ls -lah vendor` in the coopcycle-web dir?

**Comment by Ledoux** [comment]
no such file or directory, but note that /vendor/ is gitignored

**Comment by Atala** [comment]
The vendors are installed in the `/start.sh` script but the Makefile launch a custom command first..

Quickfix : Run `docker-compose run php composer install --prefer-dist --no-progress --no-suggest`  and rerun `make install`

I am going to fix the install script.
