### ISSUE TITLE
Add a warning when Stripe is in test mode

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#720]
Now, when Stripe is in test mode, users are not aware. At we have this kind of message: 

![71782394_552085708930601_8313664621730856960_n](https://user-images.githubusercontent.com/1162230/66267532-39f6df80-e832-11e9-8d34-95dad5dbed91.jpg)

On the payment page, when Stripe is in test mode, a warning should be added to indicate that only test cards are supported.

**Comment by Craig115** [comment]
I'd like to take a crack at this :slightly_smiling_face:

**Comment by alexsegura** [comment]
@Craig115 Nice 👏

Don't hesitate if you have questions. 

The warning should probably be added somewhere here

https://github.com/coopcycle/coopcycle-web/blob/4bacf1c3e5795787de5851103779af93848aa91b/src/AppBundle/Resources/views/order/payment.html.twig#L39-L73

**Comment by ERAMANrepartos** [comment]
I think this is fixed, correct?
@alexsegura

**Comment by Paul-Eraman-CoopCycle** [comment]
now i understand. this would be a quality of life issue, so not going to prioritize for the moment. closing
