### ISSUE TITLE
Support semicolons in CSV import

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#734]
Excporting .CSV from Excel in Europe only provides ";" 

We have a lot of recurring tasks and imports are essential to manage them.

**Comment by KaiCMueller** [comment]
I'll look into this

**Comment by KaiCMueller** [comment]
I already see the issue and have an idea how to solve it.

Unfortunately I don't get the docker image to run. All I get is a bunch of SQL errors. I can not do anything without testing the changes. Maybe you can help me out with that. Please find the console output attached.

[console.log](https://github.com/coopcycle/coopcycle-web/files/3711615/console.log)

**Comment by alexsegura** [comment]
@KaiCMueller sorry for this, it's a known issue

Are you on a Mac or Linux?

You shouldn't care too much about the `Some commands could not be registered` errors, it doesn't cause problems. 

Actually, the web platform runs on http://localhost, on http://localhost:8080, it's Webpack Dev Server. So make sure to go to http://localhost. From what I see in the logs, the PHP container has started, so you should see a nice Symfony error page. 

Try to create manually the following folders: 

```
mkdir -p web/images/products
mkdir -p web/images/restaurants
mkdir -p web/images/tasks
```

And relaunch `docker-compose up`

**Comment by KaiCMueller** [comment]
I'm using a Mac. After creating the folders and using http://localhost it works perfectly fine :) Thanks a lot!
