### ISSUE TITLE
Icon with activities should be a link to the activity page

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#739]
![grafik](https://user-images.githubusercontent.com/56302059/66469842-f0ec9880-ea88-11e9-88c5-efbbce487c3c.png)

e.g. link: https://tricargo.coopcycle.org/admin/activity?date=2019-10-08

**Comment by ERAMANrepartos** [comment]
@GuidoHaagen 
can you explain this better plz?

**Comment by GuidoHaagen** [comment]
@ERAMANrepartos 
oh thats an old one. I dont really remember it. I think I would have loved to have tasks in the aktivity page as a clickable link to the actual tasks. Just the number helps very little. 
At the moment we are not using that page

**Comment by ERAMANrepartos** [comment]
Ok, closing
