### ISSUE TITLE
Allow to download proofs of delivery as PDF

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#764]
Now, the only method to give a proof of delivery to a customer is to download the images through the dashboard, and send them to the customer. 

It should be possible to download a PDF, that contains the images, with additional information.
From the profile area, the customer should be allowed to download those PDFs.
Even better, they should be sent via email once the delivery is completed.

**Comment by couleurmate** [comment]
https://printjs.crabbly.com/

**Comment by alexsegura** [comment]
Example PDF by @CCCC-Jorrit

[View PDF](https://github.com/coopcycle/coopcycle-web/files/4248968/POD.Sketch.pdf)
