### ISSUE TITLE
Add filter for unassigned tasks

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#772]

**Comment by PasLoin** [comment]
Also a filter for untagged task

**Comment by joel-shiftdelivery** [comment]
It would be helpful to have a filter to show/hide unassigned tasks. 

This could be used:
- In combination with other filters to view unassigned tasks with only 1 or 2 couriers you are assigning the tasks to
- With hiding all couriers to view just unassigned tasks on the map.

**Comment by alexsegura** [comment]
Does it fix the problem? I closed #1390 

<img width="429" alt="Capture d’écran 2020-06-22 à 16 40 18" src="https://user-images.githubusercontent.com/1162230/85300879-6b3e3b00-b4a7-11ea-96fb-ad38c63a76a3.png">

**Comment by rayon9coop** [comment]
Also a filter for failed tasks / to do tasks
(in the morning, we check all the failed tasks of the day before, so we can duplicate and move them to today)

**Comment by ERAMANrepartos** [comment]
@rayon9coop 
your comment is a new feature, even though it is related to this one
. if you still think is necessary, please make a new issue
