### ISSUE TITLE
Allow moving a task to top/bottom with right click

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#773]
Additionally click right option with "move to top / bottom" would be nice.

**Comment by alexsegura** [comment]
Scroll should work since 4fac82e588bf88a92e88c627b2aeb63f4cf3bef6

I changed the scope of the issue, because right-click + move to top/bottom is a nice idea

**Comment by alexsegura** [comment]
Fixed in c1e5afaf6e983d5ada5cafd823b30dd3a9d7f6ef
