### ISSUE TITLE
Docker compose - php container exited with code 1

### ISSUE THREAD

**Issue by nodesoccoop** [coopcycle/coopcycle-web#789]
Hi,
when i start my instance i got this error:
```
php_1          | ocramius/package-versions:  Generating version class...
php_1          | ocramius/package-versions: ...done generating version class
php_1          | > Incenteev\ParameterHandler\ScriptHandler::buildParameters
php_1          | Updating the "app/config/parameters.yml" file
php_1          | > @php bin/console cache:clear --no-warmup
php_1          |
php_1          |  // Clearing the cache for the dev environment with debug
php_1          |  // true
php_1          |
php_1          |  [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
php_1          |
php_1          | > @php bin/console assets:install --symlink --relative web
php_1          |
php_1          |  Trying to install assets as relative symbolic links.
php_1          |
php_1          |  --- ----------------------------- ------------------
php_1          |       Bundle                        Method / Error
php_1          |  --- ----------------------------- ------------------
php_1          |   ✔   ApiPlatformBundle             relative symlink
php_1          |   ✔   CraueConfigBundle             relative symlink
php_1          |   ✔   FOSJsRoutingBundle            relative symlink
php_1          |   ✔   JMoseCommandSchedulerBundle   relative symlink
php_1          |  --- ----------------------------- ------------------
php_1          |
php_1          |  [OK] All assets were successfully installed.
php_1          |
php_1          | + php bin/console doctrine:database:create --if-not-exists '--env=dev'
php_1          | Database "coopcycle" for connection named default already exists. Skipped.
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis' '--env=dev'
php_1          | int(0)
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis_topology' '--env=dev'
php_1          | int(0)
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS pg_trgm' '--env=dev'
php_1          | int(0)
php_1          | + php bin/console doctrine:database:create --if-not-exists '--env=test'
php_1          | Database "coopcycle_test" for connection named default already exists. Skipped.
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis' '--env=test'
php_1          | int(0)
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis_topology' '--env=test'
php_1          | int(0)
php_1          | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS pg_trgm' '--env=test'
php_1          | int(0)
php_1          | + chmod -R 777 CONTRIBUTING.md LICENSE Makefile README.md app assets behat.yml bin composer.json composer.lock cypress cypress.json docker docker-compose-dev.yml docker-compose-portainer.yml docker-compose.yml docker-sync.yml docs features jest.config.js js node_modules package-lock.json package.json phpunit.xml.dist pm2.config.js postcss.config.js src stats.json templates tests var vendor web webpack.config.js
php_1          | chmod: CONTRIBUTING.md: Operation not permitted
php_1          | chmod: LICENSE: Operation not permitted
php_1          | chmod: Makefile: Operation not permitted
php_1          | chmod: README.md: Operation not permitted
php_1          | chmod: app: Operation not permitted
php_1          | chmod: app: Operation not permitted
php_1          | chmod: assets: Operation not permitted
php_1          | chmod: assets: Operation not permitted
php_1          | chmod: behat.yml: Operation not permitted
php_1          | chmod: bin: Operation not permitted
php_1          | chmod: bin: Operation not permitted
php_1          | chmod: composer.json: Operation not permitted
php_1          | chmod: composer.lock: Operation not permitted
php_1          | chmod: cypress: Operation not permitted
php_1          | chmod: cypress: Operation not permitted
php_1          | chmod: cypress.json: Operation not permitted
php_1          | chmod: docker: Operation not permitted
php_1          | chmod: docker: Operation not permitted
php_1          | chmod: docker-compose-dev.yml: Operation not permitted
php_1          | chmod: docker-compose-portainer.yml: Operation not permitted
php_1          | chmod: docker-compose.yml: Operation not permitted
php_1          | chmod: docker-sync.yml: Operation not permitted
php_1          | chmod: docs: Operation not permitted
php_1          | chmod: docs: Operation not permitted
php_1          | chmod: features: Operation not permitted
php_1          | chmod: features: Operation not permitted
php_1          | chmod: jest.config.js: Operation not permitted
php_1          | chmod: js: Operation not permitted
php_1          | chmod: js: Operation not permitted
php_1          | chmod: node_modules: Operation not permitted
php_1          | chmod: node_modules: Operation not permitted
php_1          | chmod: package-lock.json: Operation not permitted
php_1          | chmod: package.json: Operation not permitted
php_1          | chmod: phpunit.xml.dist: Operation not permitted
php_1          | chmod: pm2.config.js: Operation not permitted
php_1          | chmod: postcss.config.js: Operation not permitted
php_1          | chmod: src: Operation not permitted
php_1          | chmod: src: Operation not permitted
php_1          | chmod: stats.json: Operation not permitted
php_1          | chmod: templates: Operation not permitted
php_1          | chmod: templates: Operation not permitted
php_1          | chmod: tests: Operation not permitted
php_1          | chmod: tests: Operation not permitted
php_1          | chmod: var: Operation not permitted
php_1          | chmod: var: Operation not permitted
php_1          | chmod: vendor: Operation not permitted
php_1          | chmod: vendor: Operation not permitted
php_1          | chmod: web: Operation not permitted
php_1          | chmod: web: Operation not permitted
php_1          | chmod: webpack.config.js: Operation not permitted
**coopcycle-web_php_1 exited with code 1**
```

Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

uname -a:
```
Linux srvriders 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

How can i fix it? All the other containers start well.

Thank you.

**Comment by alexsegura** [comment]
Hi. 

It looks like you are on Linux. 
Did you follow Linux-specific instructions in the README?

**Comment by nodesoccoop** [comment]
Yes,
i follow the Linux instructions. I don't understand where is the command "_chmod 777 -R ..._" on scripts. I can't find it. I simply added an "echo" on _docker/php/start.sh_ but seems don't execute it.

Thank you

**Comment by nodesoccoop** [comment]
I rebuild php container and now it works!
Now visiting the website i see:
![image](https://user-images.githubusercontent.com/52574840/67563016-28617300-f720-11e9-9751-84a0fbe72cab.png)
on port 9080 (nginx-test). I attach a log file from Developer Tools Inspector of Chrome.
[10.101.100.26-1571998223842.log](https://github.com/coopcycle/coopcycle-web/files/3771531/10.101.100.26-1571998223842.log)



and on port 80 (nginx) i see:
![image](https://user-images.githubusercontent.com/52574840/67563090-4a5af580-f720-11e9-8932-1659e3294529.png)

Any suggestion about these problems?
Thank you so much.

**Comment by nodesoccoop** [comment]
Now it give to me this error:
![image](https://user-images.githubusercontent.com/52574840/67575576-25c14680-f73d-11e9-9827-14c5b7169842.png)

Another question: how do i create at least one admin user that allows me to manage the platform?

Thank you.

**Comment by alexsegura** [comment]
The Nginx server running on port 9080 is only for functional tests.
You should try to make it work on port 80 first.

Is `10.101.100.26` the IP address of you Docker host?

**Comment by nodesoccoop** [comment]
Yes, it is.

**Comment by alexsegura** [comment]
Ok. Still a 404 on port 80? 
Try `10.101.100.26/fr/`, maybe (it's the default language in dev mode). 
But you should be redirected there when language is missing 🤔

**Comment by nodesoccoop** [comment]
Unfortunately it doesn't work:
![image](https://user-images.githubusercontent.com/52574840/67578420-b3536500-f742-11e9-9a31-65ad7ed0402c.png)

**Comment by alexsegura** [comment]
Hmmm ok. So it means Nginx is running, at least.

You can see how Nginx is configured here:

https://github.com/coopcycle/coopcycle-web/blob/7b3c46b306e8ab565d6f3d52ddc0365304a5a349/docker/nginx/conf.d/default.conf#L33-L61

From my understanding it means that the `try_file` / reverse proxy stuff is not matching, and it goes to the last rule. 

Is everything running in `docker-compose up` logs?

**Comment by nodesoccoop** [comment]
As attached file the `docker-compose logs`.
[docker-compose.logs.txt](https://github.com/coopcycle/coopcycle-web/files/3772522/docker-compose.logs.txt)

I found a block into `default.conf` file that i commented trying to fix this issue. 
Now it works on port 80 but it doesn't find any JS/CSS/assets files.
Log file:
[webpage inspector.log.txt](https://github.com/coopcycle/coopcycle-web/files/3772526/webpage.inspector.log.txt)

**Comment by alexsegura** [comment]
Assets should be served from the `webpack` container, it runs on port 8080. 
A special Symfony bundle takes care of this, don't understand why you have wrong URLs 🤔

**Comment by nodesoccoop** [comment]
I added a parameter to generate relative URLs instead of absolutes because it put the host 0.0.0.0:8080 into `manifest.json` and `entrypoints.json` into `web` folder.

The added parameter is `--keep-public-path` into `coopcycle-web/docker/webpack/start.sh` file.

**Comment by alexsegura** [comment]
@nodesoccoop I think all the problems are now fixed thanks to #801 #803 #816

Can you pull the latest changes, and try again?

Make sure to start fresh:
```
rm -rf vendor
rm -rf var/jwt
docker-compose down -v
docker-compose build php osrm
docker-compose up
```

**Comment by alexsegura** [comment]
The problem reported in https://github.com/coopcycle/coopcycle-web/issues/789#issuecomment-546389780 is fixed by commit 5972bf0491ced22440471b55b99c9c5e0131e407 😉

**Comment by alexsegura** [comment]
Hmmm I'm afraid 5972bf0491ced22440471b55b99c9c5e0131e407 won't actually fix your problem because your Docker host is `10.101.100.26`, not `localhost`. 

I'm not a Docker specialist, but on most installations I have seen, it runs on `localhost`.
Why is it running on `10.101.100.26` for you? Are you using [Docker machine](https://docs.docker.com/machine/overview/)? It is now in maintenance mode (docker/machine#4537)

**Comment by nodesoccoop** [comment]
Hello again :)
I'm not using Docker Machine but i want to deploy an instance of this Compose Project on a Linux Server linked with my office's network that it can be available for my colleagues too.

To change the `entrypoints.json` and `manifest.json` i edited `/docker/webpack/start.sh` at line 7 on _public_ parameter:
```
node_modules/.bin/encore dev-server --watch-poll --host 0.0.0.0 --port 8080 --public 10.101.100.26:8080 --content-base=web/ --disable-host-check --keep-public-path
```

and into `webpack.config.js` i added this lines:
```
+ Encore.setPublicPath('http://10.101.100.26:8080');
+ Encore.setManifestKeyPrefix('web/');

let webpackConfig = Encore.getWebpackConfig()
```
I download from GitHub repo your new commits but i had to make some changes to resolve some issue in addition to those already mentioned:

- added a copy of the file `.env.dist` with the name `.dev.env` because Symfony (i think but i'm not sure) it was looking for them;

- into `/docker/nodejs/Dockerfile` i had this line
```
+ RUN npm config set unsafe-perm true

RUN npm install -g pm2
```
to fix [this issue](https://stackoverflow.com/q/52196518) with the comment wrote by _Nick Roz_.

- on `/app/config/parameters.yml` changed the param **mjml_server_base_uri** with the value: `'http://10.101.100.26:8889'` 

- if i want to move the geo context from Paris to Rome (for example), i took the new OSM file from Geofabrik repo [here](http://download.geofabrik.de/europe/italy/centro.html) and put into `Makefile` instead of Paris at line 10.

I tried to change the environment from **dev** to **prod** but i got this issue when php container starts:

> Populating schema..
> 
> 
>  [WARNING] Some commands could not be registered:
> 
> 
> In FileSystemLocator.php line 124:
> 
>   Root image path not resolvable "/var/www/html/../../shared/web"
> 
> 
> 
> 
>  [WARNING] Some commands could not be registe
[prod-2019-11-07.log](https://github.com/coopcycle/coopcycle-web/files/3820193/prod-2019-11-07.log)
red:
> 
> 
> In FileSystemLocator.php line 124:
> 
>   Root image path not resolvable "/var/www/html/../../shared/web"
> 
> 
> 
>  !
>  ! [CAUTION] This operation should not be executed in a production environment!
>  !
> 
>  Creating database schema...
> 
> 14:48:09 ERROR     [console] Error thrown while running command "doctrine:schema:create --env=prod". Message: "Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))':
> 
> SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists' while executing DDL: CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))" ["exception" => Doctrine\ORM\Tools\ToolsException^ { …},"command" => "doctrine:schema:create --env=prod","message" => """  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))':\n  \n  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists' while executing DDL: CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))  """]
> 
> In ToolsException.php line 34:
> 
>   Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE craue_config_setting (name VA
>   RCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))':
> 
>   SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists' while executing DDL:
>    CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR
>   (255) DEFAULT NULL, PRIMARY KEY(name))
> 
> 
> In AbstractPostgreSQLDriver.php line 66:
> 
>   An exception occurred while executing 'CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VA
>   RCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))':
> 
>   SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists
> 
> 
> In PDOConnection.php line 90:
> 
>   SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists
> 
> 
> In PDOConnection.php line 88:
> 
>   SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "craue_config_setting" already exists
> 
> 
> doctrine:schema:create [--dump-sql] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
> 
> make: *** [Makefile:5: install] Error 1

As attachment, the log file.

[prod-2019-11-07.log](https://github.com/coopcycle/coopcycle-web/files/3820252/prod-2019-11-07.log)

Could i suggest a new paragraph on README.md where explain better where and how set up the Compose App (.env, parameters.yml, etc ...) or maybe create a single configuration file to centralize all parameters that all the various tools will use?

Thank you so much.

**Comment by alexsegura** [comment]
Hi, sorry to answer only now. 

From what I understand, you kind of want to run a production instance. The Docker environment is not intended for production, but for development. 
In production the assets shouldn't be served through Webpack Dev Server, but compiled. 

Sorry, but we don't provide support for running the software in production given the state of our human resources. It _should_ work with Docker, but you will have to figure it out by yourself. It's pretty standard stuff, and there are plenty of resources out there. 

Btw, Docker images have changed in c2bb67aa06be3219712f24f09a34d527ec43861e & dee1d22b7d8e8a1da83814b16869c85d6fcd2935, make sure to build them again.

> Could i suggest a new paragraph on README.md where explain better where and how set up the Compose App (.env, parameters.yml, etc ...) or maybe create a single configuration file to centralize all parameters that all the various tools will use?

Actually we're using a mostly deprecated technique with `parameters.yml` (see #925).
There are some mechanisms/best practices in Symfony for managing everything via `.env` that we need to migrate to. I'm slowly transitioning towards this.
