### ISSUE TITLE
Modify link in confirmation mail

### ISSUE THREAD

**Issue by zouglou** [coopcycle/coopcycle-web#79]
The link sent in the subscription confirmation mail isn't clickable.

**Comment by Atala** [comment]
Hey,

Can you give more informations as : 
 - mail client (Gmail, Outlook, etc.)
 - browser (Safari, Firefox, etc.)

And possibly a screenshot or HTML content of the mail.

Best,

**Comment by zouglou** [comment]
Yes, of course, sorry I could have thought about it myself!

I don't think it depends of clients because there's simply no < a > in the content, but I use Gmail on Chrome.

Here's the content, it's the one about _demo.coopcycle.org_ sent by _transactional@coopcycle.org_  (I had forgotten I've received two mails, I can't remember at what moment I've received the first from _services@coopcycle.org_  ..?): 

```
<div id=":31a" class="a3s aXjCH m15ecf152420efdd2">Bonjour Zou !<br>
<br>
Pour valider votre compte utilisateur, merci de vous rendre sur https://demo.coopcycle.org/<wbr>register/confirm/<wbr>xxxxxxxxxxxxxxxxxxxxx-<wbr>xxxxxxxxxxxxxxxxxxxxx<br>
<br>
Ce lien ne peut être utilisé qu'une seule fois pour valider votre compte.<br>
<br>
Cordialement,<br>
L'équipe<div class="yj6qo"></div><div class="adL"><br>
</div></div>
```

**Comment by Atala** [comment]
I am quite surprised, it works nice by me on Gmail + Chrome (see below). Could you try to open your inbox in private session (i.e. with no extensions enabled) and see if it works ?

```html
<div id=":12s" class="a3s aXjCH m15edc3df441a711f">Bonjour Alois !<br>
<br>
Pour valider votre compte utilisateur, merci de vous rendre sur <a href="https://demo.coopcycle.org/register/confirm/SSO_UXJoztzhUSg2NHBzys0ttSB1nCNv_s7B1oSY0MU" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://demo.coopcycle.org/register/confirm/SSO_UXJoztzhUSg2NHBzys0ttSB1nCNv_s7B1oSY0MU&amp;source=gmail&amp;ust=1507020056570000&amp;usg=AFQjCNHD5xAz4NnGNihUwz6M_B4E5vVQXA" rel="noreferrer" target="_blank">https://demo.coopcycle.org/<wbr>register/confirm/SSO_<wbr>UXJoztzhUSg2NHBzys0ttSB1nCNv_<wbr>s7B1oSY0MU</a><br>
<br>
Ce lien ne peut être utilisé qu'une seule fois pour valider votre compte.<br>
<br>
Cordialement,<br>
L'équipe<div class="yj6qo"></div><div class="adL"><br>
</div></div>
```

**Comment by zouglou** [comment]
I tried in a private session, and even with Firefox, the content is still the same, and I don't really imagine how the html content sent by Gmail could change with browser ..?

**Comment by Atala** [comment]
@alexsegura any idea?

**Comment by Atala** [comment]
Problem met by another user (in Gmail)

```html
<br>Bonjour Ol !<br>
<br>
Pour valider votre compte utilisateur, merci de vous rendre sur <a href="https://demo.coopcycle.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://demo.coopcycle.org/&amp;source=gmail&amp;ust=1508753663663000&amp;usg=AFQjCNHWL5RoN2AnrMl7KO_JVodBQK-00Q">https://demo.coopcycle.org/</a>reg<wbr>ister/confirm/656pBIndLPGhW0ZU<wbr>SfHeATp-YJRVoQHNKnu7yiXwb58<br>
<br>
Ce lien ne peut être utilisé qu'une seule fois pour valider votre compte.<br>
<br>
Cordialement,<br>
L'équipe<div class="yj6qo"></div><div class="adL"><br>
</div></div>

**Comment by Atala** [comment]
@zouglou it may be fix by now (by adding mailjet), if you have time to test it again that would be nice

**Comment by zouglou** [comment]
It works fine!
I hope the dev is going as fine as that, good job!

**Comment by Atala** [comment]
Dev is going fine, a lot of work ahead of us!
