### ISSUE TITLE
More options for a Store

### ISSUE THREAD

**Issue by CCCC-Jorrit** [coopcycle/coopcycle-web#793]
When creating a store now you can only add one phone number. Sometimes there are more phone numbers. Land line and Mobile for example. But some clients only contact via email. Would be super to have this there

**Comment by CCCC-Jorrit** [comment]
- Field for Client Number
- More phone numbers
- E-mail address

**Comment by ERAMANrepartos** [comment]
This is a pretty specific use case, and there is a comments field. I´m going to close the issue, but make another issue if you still feel that this is important
