### ISSUE TITLE
Contact Book

### ISSUE THREAD

**Issue by CCCC-Jorrit** [coopcycle/coopcycle-web#796]
Have your clients in a contact book with the option to add notes so you don't have to enter reoccurring addresses and also have the option to add something like, "5th floor, the elevator is in the back".

**Comment by CCCC-Jorrit** [comment]
This is the Store section

**Comment by rayon9coop** [comment]
Hi, would there be a way to have some sort of address book for the tasks that are created manually via the dashboard ? 
Type in the name of a place and it would automatically fill in the adress and other details if it's been previously saved.
