### ISSUE TITLE
Pick up and Delivery notification by mail

### ISSUE THREAD

**Issue by CCCC-Jorrit** [coopcycle/coopcycle-web#797]
For the client and the courier company. With the signature included

**Comment by PasLoin** [comment]
For store owner will also great to have the detail of the delivery.
- Client Name
- Comments (with the number from woocomerce)

**Comment by ERAMANrepartos** [comment]
This is something some clients want, some super do not want. UI/UX issue

**Comment by Paul-Eraman-CoopCycle** [comment]
We need to redesign notifications from the ground up. closing as not planned, but we will write an epic with this feature included
