### ISSUE TITLE
[UI/UX] Add an interval after opening and before closing for accepting orders

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#81]
Which time should we leave?

**Comment by taniki** [comment]
Let the choice to the restaurants?

**Comment by Atala** [comment]
Easily doable, I will hardcode on the restaurant for now on, but if needed we will add a choicefield to the restaurant dashboard.

**Comment by alexsegura** [comment]
This Issue is obsolete, since there is now a "smart" calculation of preparation time, & restaurants can always refuse orders.
