### ISSUE TITLE
Allow configuring intra-community VAT number

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#835]
Prerequisite for #785 

If the instance is located in Europe, administrators should be allowed to specify the VAT number, to be used in invoices. We can use [ibericode/vat](https://github.com/ibericode/vat) to check if the instance is running in a European country, and [ddeboer/vatin](https://github.com/ddeboer/vatin) to validate the user input.

**Comment by ERAMANrepartos** [comment]
This seems not to currently be an issue...
If not true, reopen
