### ISSUE TITLE
Re assign several task from a courier to another with one click

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#836]
Move multiple tasks at once from a couriers to another couriers and keep the order chosen (right click option)

**Comment by alexsegura** [comment]
Related to #775

**Comment by joel-shiftdelivery** [comment]
This would be helpful as well for us, especially if it keeps the task order that was set, so you can easily move a partial or whole route between couriers. This is helpful if someone is sick or unable to work and another courier is taking their shift.

It could be a drag and drop or a right click, move to other courier.

Along with this, it would be helpful if shift+click to select and range of deliveries worked as well as crtl+click to select multiple.

**Comment by rayon9coop** [comment]
Related to this: https://github.com/coopcycle/coopcycle-web/issues/1356

**Comment by ERAMANrepartos** [comment]
This is a route, which is currently being implemented. I´m going to close the issue since it should be dealt with by this new feature

**Comment by rayon9coop** [comment]
Perhaps this feature is not fully resolved by the route concept. When assignment is made to a courier (mixed tasks and orders) and he is sick or unable to work, another courier has to take his job. The route concept is not useful in this case, because I cannot create a route with assigned tasks/orders. In daily use, it is not possible to create a route for all tasks because some are added to an assigned route (express or last minute orders).

Translated with www.DeepL.com/Translator (free version)

**Comment by ERAMANrepartos** [comment]
The use case you are worried about is
1. you have created a series of tasks (pickups and dropoffs) in a specific order and assigned them to a messenger
2. the messenger has called in sick today
3. you want to move all the tasks, in their order, from one messenger to another

I don´t totally understand your last sentence sorry

**Comment by rayon9coop** [comment]
Yes, the use case i'm worried about is the 3 points you re formulated

For the last sentence, sorry for my still-beginner-english :-)

What this sentence means : i think creating routes is not the solution for all the tasks because some are not predictable/are added after creating routes. For exemple, our last minutes orders and express deliveries will probably never be included in routes.

**Comment by ERAMANrepartos** [comment]
The way routes will have to work is that urgent things can be added into them, this is super important since mixing high volume low value clients with low volume high value clients is key to making money in a lot of places, so rather i think that the route concept will have to be designed in a way that allows for this
