### ISSUE TITLE
Allow validation of group of tasks in one swipe

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#837]
For dispatch: allow grouping some tasks (eg. pickup of several packages from the same place) 
For courriers: allow validation of this group of tasks by validating just one of the grouped tasks

**Comment by GuidoHaagen** [comment]
We would use that option as well.

**Comment by ERAMANrepartos** [comment]
This has been done, though it still needs some UI/UX improvements, so I´m going to close

**Comment by ERAMANrepartos** [comment]
@lucasferraro Is this deployed to all instances?
