### ISSUE TITLE
Unassigning tasks while a filter is active has side effect

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#852]
I did the following:
1 uploading tours with different tags
2 assigning tasks to driver
3 activate filter on one tag
4 unassigning tasks by clicking on the x
5 deactivating filter -> Then I noticed that tasks with other tags were unassigned as well

**Comment by alexsegura** [comment]
Can't reproduce, please reopen if you still face the issue

![unassign_with_tags](https://user-images.githubusercontent.com/1162230/75553420-a5875680-5a38-11ea-946c-a3d21dfc285a.gif)
