### ISSUE TITLE
Possibilty to change password if a user only has driver rights is missing

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#865]
When you are logged in as a driver there is no way in getting to the change password page. 
For now its only possible by an external link.

**Comment by ERAMANrepartos** [comment]
@GuidoHaagen 
Is this in the app, a browser, or both?

**Comment by GuidoHaagen** [comment]
@ERAMANrepartos 
I only noticed it in the browser. But its some time ago and have not checked it since then.

**Comment by ERAMANrepartos** [comment]
Maybe this is a dumb question, but if I am logged in, why would i need to change the password? I just tried to check if this was still true and realized...why would this happen in real life?

**Comment by GuidoHaagen** [comment]
@ERAMANrepartos 
I think the change comes from the times when you had to set a password for the new users. 
Change pw should be a general function but is not very important

**Comment by ERAMANrepartos** [comment]
There are workarounds so i think this is ok, closing
