### ISSUE TITLE
Unassigning tasks while a search is active

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#886]
I must split tasks beetween some courrier ; i use the search form to find some points speeder , but it is not possible to unasign with X. 
It will be also great to do that with the modal  popup task detail.
And also "dreaming" of selecting a lot of task with drawing polygon in the map and unasing them in one click ;-)

**Comment by PasLoin** [comment]
Ok it's work with right click ; just not refreshing on dashboard. You can close this issue.

**Comment by Paul-Eraman-CoopCycle** [comment]
Done!
🥳
