### ISSUE TITLE
enhancement : sorting task list (in right) with criteria

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#887]
Actualy Tasks in the right of the screen are sorting by id-number or by re-assigned order ; It will be a great enhancement if we could sort by (up-down) : alpha ; id ; before and after (group) ; comments instructions, tag. And vroom order (cerise sur le gâteau)

**Comment by Paul-Eraman-CoopCycle** [comment]
@Atala check this out

**Comment by Atala** [comment]
should be rephrase so we all agree on what it means

"tasks on the right side of the screen": he is speaking of assigned tasks I guess? or unassigned tasks?

I think they are for now sorted by "end of slot for delivery"

**Comment by Paul-Eraman-CoopCycle** [comment]
My idea is they were talking about unassigned

**Comment by Atala** [comment]
OK

we need design here, because we have an existing "sort" so either we add an option on this old design or do a revamp of this menu.

existing menu:
**
![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/42352c0f-cefe-40cb-8c57-9dcd3c07d53b)
**

**Comment by Paul-Eraman-CoopCycle** [comment]
yeah i wanted you to see this (im just throwing things at you that you should know about) 

but i totally agree that we need a different way to organize this stuff because it doesnt make any sense how it is
