### ISSUE TITLE
opening date restaurants bug

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#893]
974 saveurs will be exceptionnaly close tomorrow ( wednesday ). In their own page, no problem, the first date is thursday 11:45.

![image](https://user-images.githubusercontent.com/43618873/69157027-a0834480-0ae4-11ea-8158-fdcd960a8bea.png)

But in restaurants page it's announced open for tomorrow 11:45

![image](https://user-images.githubusercontent.com/43618873/69157447-34551080-0ae5-11ea-9fa1-35dbe07bc223.png)

**Comment by alexsegura** [comment]
Not relevant anymore since 307469a0aeda34cde4f87160203a3663fdf1bb61
