### ISSUE TITLE
restaurants order

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#913]
In webpage coopcycle for customers, three restaurants appears randomly. I propose to break it and choose restaurants order according to their opening hours. For example in Poitiers, there is only one restaurant open on monday. If a customer happen on the website to command a lunch, it's better if it sees opened restaurant before. Because if it sees three closed restaurants, maybe it  won't want to go further.
If a customer happen at x o'clock, I propose restaurants next opening come before restaurants last opening

**Comment by PasLoin** [comment]
Agreed for opening hour and day ; it will be also great to configure custom order (priority level) for marketing action for exemple. (or contractual highlighting)
