### ISSUE TITLE
Store owner : view detail of the delivery (courrier feedback)

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#941]
Store Owner need more information display here : profile/deliveries/174x

- Status of the task (Todo, done , failled) and comments
- Name of courier
- Proof of delivery

**Comment by alexsegura** [comment]
Since b764cb1125d57ea7878f13fde53bf9455f44789d, store owners can download proofs of delivery as ZIP

**Comment by ERAMANrepartos** [comment]
I believe this is all complete, closing
