### ISSUE TITLE
Create a task based on an other

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#947]
For now, a cloned task is a task using the same object in database than the original (same name and adress). 
It could  be interresting to have possibility to create a new task duplicated from another even the newone doesn’t have all similar particularities than the original. So in this use case, you can save time by duplicating two tasks with for eg same tag and timeslot but not same adress.

**Comment by alexsegura** [comment]
In terms of user interface, what do you think of this?
When the user clicks on "Duplicate", it opens a window with checkboxes, asking what needs to be copied. By default, the address is checked.

**Comment by rayon9coop** [comment]
Yes it's good. Can we insert and / or change (in the same windows) other informations in the duplicated task

**Comment by alexsegura** [comment]
Hmmm, I think we can just open the duplicated task popup after it has been duplicated successfully.

**Comment by ERAMANrepartos** [comment]
I believe this is now a feature, closing
