### ISSUE TITLE
Ask for confirmation when beginning shopping in a new restaurant

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#95]
Use case is the following : 
 - shop in restaurant 1 (add some products)
 - go back to restaurant page
 - go to restaurant 2 page
 - click item

We should : 
 - ask the customer if he wants to shop in restaurant 2, telling him he started in restaurant 1
 - if yes, clear the basket and add the item to the basket
 - if no, do nothing

**Comment by Atala** [comment]
The code which is triggered when a user add an item to the cart is [here](https://github.com/coopcycle/coopcycle-web/blob/master/js/app/cart/index.jsx#L32). So at the beginning of the handler we need to check if the id of the current restaurant is the same as the id of the restaurant of the cart. To access this data from javascript we need to pass the variables thanks to the PHP templating [here](https://github.com/coopcycle/coopcycle-web/blob/master/src/AppBundle/Resources/views/Restaurant/index.html.twig#L93-L105). One is `restaurant.id` (current restaurant), other one is `cart.restaurant.id` .
If the ids don't match, open a [bootstrap modal](https://getbootstrap.com/docs/3.3/javascript/#modals) with a warning.
The modal has two buttons : 
 - one that add the items as attended (means you need to save the menu item id that was clicked / handle the case when it should open a modifiers modal) (no need to clear the cart, it will clear itself)
 - one that does nothing (easy :) )

**Comment by Ladias-Elie** [comment]
I am struggling a bit with this issue, here is how I would proceed, do you think it's a good way of doing ? 

1. Create a cartTotal components:  it will be stored in cartTotal.jsx and will render the session.cartTotal for non restaurant pages and the current cartTotal for pages where we can add items to the basket

2. Call the cartTotal components: Here I am not sure how, should we create a new js script that would be call in the menu.html.twig file ? If not should we use the index.js file ? But if so how do we handle the case when we are prompting something not in a restaurant page ?

3. When a new item is added: For the first one, prompt a bootstrap message box:  
	a) if the customer want to buy in this new restaurant: 	erase the old basket, add the new item and update the cartTotal componment
	b) if not do nothing

**Comment by Atala** [comment]
Let's start with the (1). It is actually quite complicated.

What you want to do is to have two React components which are storing the same state (the same `cartItems`, the same `total`). So you would like that the `Cart` component render at two places when an element is added at the same time : in the right-column and in the header.

Happily this feature was added in React 1.16 : https://reactjs.org/docs/portals.html ([example](https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202))

However we are in React 15.3.2 for now on. I could do the migration to 1.16 and let you try to do a portal. I think it's quite challenging but interesting. Would like to continue on this issue?

PS: all templates inherit of [base.html.twig](https://github.com/coopcycle/coopcycle-web/blob/master/src/AppBundle/Resources/views/base.html.twig). So if you wanted to run javascript on all pages you could for example create a new JS script include it at [the bottom of this page](https://github.com/coopcycle/coopcycle-web/blob/master/src/AppBundle/Resources/views/base.html.twig#L44-L59)

**Comment by Ladias-Elie** [comment]
Great feature ! 

Actually I would be happy to continue with that issue, but I guess I would need some support from you and I don't want to waste to much of your time as you have got much to do.

So it's up to you =)

**Comment by Atala** [comment]
Part of the project is to have a fun & to learn !

I will be able to migrate to React 1.16 this Sunday I think, I'll let you know (I think I need to do it myself (?)).

**Comment by Ladias-Elie** [comment]
Cool ! yes, if you don't mind, I have no idea how to do it... Thanks a lot

**Comment by Atala** [comment]
Done bb0e06e1aa430605d6f46810dd7cce132dfd119a
