### ISSUE TITLE
Ordering a delivery from a store with an incomplete address should be impossible

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#964]
This bug is back. The store owner has successfully encoded a delivery request with an incomplete address. See task 4154  order 37E

**Comment by alexsegura** [comment]
We can't fix this, we rely on what is considered "precise" from Google's point of view. 

https://github.com/coopcycle/coopcycle-web/blob/1cd3b311d7b806d6911571061121a803b47eca4e/js/app/utils/GoogleMaps.js#L32
