### ISSUE TITLE
Bug with the interval of days when the advanced time slot mode is enabled

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#966]
When I select advanced mode for configuring the time slot and 3 days of interval, the app show me 7 days of interval instead of 3

**Comment by ERAMANrepartos** [comment]
@rayon9coop 
what is "advanced mode"?
why is 7 days a problem?

if the case, please comment telling me to close the issue

**Comment by Paul-Eraman-CoopCycle** [comment]
Need more info! @rayon9coop

**Comment by rayon9coop** [comment]
Yes I understand you need info... But difficult for me 4 years after... I don't understand (or at least remember) why i open this issue

**Comment by Paul-Eraman-CoopCycle** [comment]
Ok, well...closing haha. if you remember or see it again, let me know
