### ISSUE TITLE
misleading hour

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#991]
I don't know why I've never seen that but when I make that :
![Capture](https://user-images.githubusercontent.com/43618873/71009192-209fc880-20ea-11ea-8819-c1073c122afa.PNG)
 Next page I see that :
![Capture 1](https://user-images.githubusercontent.com/43618873/71009369-6361a080-20ea-11ea-9ac8-c5fc05f28c13.PNG)
And it's not logic for me. Normally customers must see delivery hour they chose or at least : livraison aujourd'hui à partir de 19h

**Comment by damienlapoitavelo** [comment]
![Capture](https://user-images.githubusercontent.com/43618873/71265206-08c48080-2346-11ea-9715-76c3fc1f08b6.PNG)

**Comment by alexsegura** [comment]
Fixed in 3606dfbbf8effb995ded3bd920ad863dcb4d117c
